### ISSUE TITLE
支持数学公式显示

### ISSUE THREAD

**Issue by Asymp** [tamlok/vnote#1]
请考虑通过Mathjax等方式支持显示数学公式 。非常感谢。

**Comment by tamlok** [comment]
Hi! 现在VNote已经支持通过MathJax显示数学公式了 (commit a9b34955ee935153d6027c97dec9d194f4430567)。目前在Hoedown或Markdown-it下基本没有啥问题，所以更新后请选择Markdown-it作为渲染引擎！

另外，由于我用到公式的机会暂时不多，所以使用过程中有任何问题，欢迎反馈！
