### ISSUE TITLE
导出、分享功能完善

### ISSUE THREAD

**Issue by wjingyuan** [tamlok/vnote#10]
# 1. 导出
希望允许导出为PDF、Word格式文档以及PNG或者JPG长图；
# 2. 分享
希望笔记文档能够通过VNote直接分享给其他人；
# 3. 打印
有时候写好的稿子想直接打印出来，所以希望VNote能够支持打印。

**Comment by tamlok** [comment]
已支持导出为PDF文件：0131569c02e0c1c64cadd41d92960b5da6b6b0d9

**Comment by fengzhizi715** [comment]
hi @tamlok ,希望能支持将整个文件夹中的.md文件导出成pdf文件

**Comment by tamlok** [comment]
@fengzhizi715 Hi, 这个只是初步的功能，后面肯定会加上文件夹导出的功能的。而且目前导出的PDF没有Outline，后面也会继续完善。谢谢使用！

**Comment by cxy0105** [comment]
@tamlok ，希望能直接导出html格式，导出的pdf格式有时体积很大

**Comment by tamlok** [comment]
@cxy0105 Hi, 后面完善这块的时候肯定会支持HTML导出的，只不过目前还在忙编辑功能的实现，所以还得等等。谢谢使用和反馈！

**Comment by sinnerliu** [comment]
@tamlok 导出的pdf希望增加大纲，也就是pdf中的书签目录

**Comment by tamlok** [comment]
@sinnerliu 正在做，下一个版本应该可以带上

**Comment by skysinger** [comment]
导出的PDF书签目录能否显示在PDF阅读器的书签目录窗口中，而不是只在第一页显示

**Comment by tamlok** [comment]
@skysinger 请使用wkhtml2pdf工具（需要下载安装）进行导出：

![image](https://user-images.githubusercontent.com/5763157/59272692-23c48280-8c89-11e9-8d6f-af4293b5535f.png)

**Comment by longzekai** [comment]
现在能导出word了吗？

**Comment by tamlok** [comment]
> 现在能导出word了吗？

请使用wkhtml2pdf导出任意格式
