### ISSUE TITLE
VNote v2.7.2 在 macOS Catalina 10.15 系统中，浏览器目录中，上下左右滑动时，特别卡顿。

### ISSUE THREAD

**Issue by feeltens** [tamlok/vnote#1002]
OS Version (操作系统):  macOS Catalina 10.15

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

Symptoms (表现): 在文件浏览器目录中，上下左右滑动时，特别卡顿。

How to Repro (如何复现): 在文件浏览器目录中上下左右滑动时，特别卡顿。

**Comment by feeltens** [comment]
实测，升级到最新 qt，使用最新版 VNote 源码编译一下，就解决问题了。

**Comment by tamlok** [comment]
最新版qt编译可能会出现阅读模式出错的问题。qt的版本向后兼容比较差~~
