### ISSUE TITLE
win下能不能保存布局位置

### ISSUE THREAD

**Issue by blowsnowit** [tamlok/vnote#1005]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

win下能不能保存布局位置

每次重新打开后 布局位置都会还原初始化，很不方便操作

**Comment by tamlok** [comment]
Hi，

您指的是什么布局呢？默认应该是保存的，可以尝试调整布局后，文件菜单，退出，然后重新打开VNote看看。

如果可以，可以截图说明一下。

**Comment by blowsnowit** [comment]
> 嗨，
> 
> 您指的是什么布局呢？或者应该是保存的，可以尝试调整布局后，文件菜单，退出，然后重新打开VNote看。
> 
> 如果可以，可以截图说明一下。

操作后 重新打开无法还原布局呢

**Comment by blowsnowit** [comment]
![image](https://user-images.githubusercontent.com/34737801/66816037-f73cb200-ef6b-11e9-922e-a755bd49ce5a.png)
比如我布局是这样的  我关闭软件后 重新打开
![image](https://user-images.githubusercontent.com/34737801/66816080-07549180-ef6c-11e9-8774-ef6ec9fcad57.png)
窗口大小修改了

**Comment by blowsnowit** [comment]
@tamlok

**Comment by blowsnowit** [comment]
现在又没有问题了 懵逼....
