### ISSUE TITLE
请问如何迁移已有md文件到笔记本中

### ISSUE THREAD

**Issue by lyolve** [tamlok/vnote#1008]
直接移动文件到Notebook Root Folder发现在软件内不能确取到这些.md文件，刷新了也还是没有，有没有办法能够让软件自动写入json？

**Comment by tamlok** [comment]
1. 可以自己写脚本修改json文件；
2. 文件菜单，从外部文件新建笔记，可以导入多个文件到当前文件夹（非递归）；
3. 暂时使用浏览器功能（左侧第三个按钮）来浏览编辑外部文件；

**Comment by lyolve** [comment]
如果支持自动检测并读取指定文件夹内文件就更好了，一些用户更喜欢用其他软件写笔记，然后用vnote做管理，希望能够支持这样的需求
