### ISSUE TITLE
希望能够方便对笔记本顺序进行更改

### ISSUE THREAD

**Issue by fanglypro** [tamlok/vnote#1020]
现在修改笔记本顺序只能把笔记本全部删除，然后按顺序添加，希望能够方便地直接更改笔记本的顺序。

**Comment by tamlok** [comment]
Hi,

VNote设计里面考虑的是笔记本的数量比较少，所以没有提供排序。你可以在文件菜单打开配置文件夹，找到`session.ini`文件，修改里面的笔记本顺序来达到笔记本排序的目的（注意先关闭VNote）。后面会优化。

**Comment by tamlok** [comment]
Hi,

2.8已经支持笔记本排序了。在笔记本列表右键可见。
