### ISSUE TITLE
[Mac OS Catalina] Github Release 版本无法安装

### ISSUE THREAD

**Issue by ShadowDevourer** [tamlok/vnote#1021]
OS Version (操作系统): macOS 10.15 Catalina

VNote Version Release 2.7.2

Symptoms (表现):从网络下载的dmg镜像包无法执行安装流程，被GateKeeper拦截。

How to Repro (如何复现):从网络上下载Release 2.7.2 dmg镜像文件，双击安装，会弹出无法验证开发者告警对话框并阻止安装。

Suggestion：可以通过Developer Application ID certification公证应用包解决。

**Comment by tamlok** [comment]
我还不是认证的苹果开发者，所以这个应该是无解了？

好像可以添加例外运行非认证的dmg文件的，具体您搜一下。

**Comment by ShadowDevourer** [comment]
好的，我这就去试试。感谢您提供的建议！

**Comment by ShadowDevourer** [comment]
> 我还不是认证的苹果开发者，所以这个应该是无解了？
> 
> 好像可以添加例外运行非认证的dmg文件的，具体您搜一下。

好的，谢谢您的建议，我去试试。

**Comment by ShadowDevourer** [comment]
找到解决方法了，打开dmg文件，右击应用图标选择打开，在弹出的警告对话框中点击打开即可。希望这个方法能帮到有相关问题的使用者。

**Comment by downtown12** [comment]
先尝试打开，报错后执行以下操作
设置 -- 安全性与隐私 -- 通用 -- “允许从以下位置下载的 App” 选择允许
