### ISSUE TITLE
需求: 增加交换文件路径配置

### ISSUE THREAD

**Issue by yuexiahu** [tamlok/vnote#1022]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

问题:
- 当前交换文件直接生成在笔记文件夹内，如果使用了同步软件，会造成交换文件的频繁上传下载

需求:
- 请参考vim，增加交换文件路径的配置，将交换文件生成在其他目录

**Comment by tamlok** [comment]
Hi,

在vnote.ini里面添加一行即可：

https://github.com/tamlok/vnote/blob/fccf6863d7b08ca8491213b3e4f09f8194b31436/src/resources/vnote.ini#L177

**Comment by yuexiahu** [comment]
谢谢，linux上测试可以使用，但是必须是提前创建好这个文件夹，否则不会自动创建。
windows上好像没有效果，比如 `backup_directory=D:\`

**Comment by tamlok** [comment]
试试`D:\\`或者`D:/`，或者`D:/tmp`，或者`D:\\tmp`?

**Comment by yuexiahu** [comment]
上面4种都试了下，包括 `D:` 也不行。

**Comment by yuexiahu** [comment]
抱歉，windows下面`D:\\`和`D:/`都是可以的，是因为我没有在托盘把程序退出重启的缘故
