### ISSUE TITLE
Auto heading sequence doesn't work anymore?

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#1026]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

Symptoms (表现): Auto Heading Sequence do nothing at all. I don't recall since when.

How to Repro (如何复现): Setting it in Settings|Markdown or clicking on the toolbar button, nothing worked.

**Comment by tamlok** [comment]
Try creating a new note for a test? And would you mind paste your contents here?

**Comment by seaspeak** [comment]
I notice that Settings/Markdown/Heading sequence is disabled so that heading_sequence_base_level is grayed out, but base_level still effective. It's a little misleading.

My previous setting:
heading_sequence_type=0
heading_sequence_base_level=6
