### ISSUE TITLE
Especific media folders for each note

### ISSUE THREAD

**Issue by Agrotsa** [tamlok/vnote#1027]
OS Version (操作系统): Windows, Linux, macOS
Linux

VNote Version
2.7.2

Symptoms (表现):
Not a bug but a feature suggestion

I've just known Vnote and I'm enchanted with the existence of an almost totally WYSIWYG (I'll make another sugestion about making if completely WYSIWYG) note taking app native for Linux. There are a few nice WYSIWYG editors based on Electron, like Typora, Uncolored, etc, but none that I knew of was Linux native and really well integrated in the KDE desktop. There are many natives with the typical two panels, code and real views, in which you have to edit in MD code and then look to the other panel to see what's what you have really done. This is absurd for the majority of users, who just want to take down notes maybe with some photos, voice comments or short videos inserted. Go tell my uncle, Art professor, that he has to learn MD code to compose the lesson schemes and commentaries that he prepares for their students... Nonsense.
So, many many thanks for your work. Vnote was really a needed program since obsolete Kjots is abandoned since 10 years ago or so.

Now I'd like to make a suggestion.
Seems that Vnote copies the inserted media files in notes to a single folder called "_v_atachemnts" or  "_v_images" by default. This may end being a mess if you have a lot of notes and media files in said folder since all them are stored there together no matter to which note they belong. It wouldnt be too problematic if one only has local notes, the problem comes when one wants to share notes with media inserted.
Id like to suggest you to consider the method used by Typora, and Markor (a nice notes app for Android) which is the same that web browsers use when you save a web page: creating a new subfolder for each note with the name of said note, and then store in said subfolder all the inserted files corresponding to that single document. Firefox creates a folder called NameOfTheHTMLFile_files, Typora creates TitleOfTheNote.assets, but in esence is the same, the extension name doesnt have much importance.
For example, if I'm using Typora to write a note titled Vacations_itinerary.md and want to insert some photos and videos of places that I've visited in my vacations I would end with a .md file and a .assets folder with only the media that I inserted in said MD file, not all the medias that I have in all my notes collection; and I could easily upload/sinchronize both the .md and the .assets folder to my cloud and share it to people or open it in my mobile or tablet, etc.
I think this is more efficient than having a folder with like 35 notes and, lets say, 150 images. Sure I could upload the MD file to my cloud and search, select and upload by hand the images atached but is very time consuming and probably most users would end getting tired of the process.

Thanks for reading. Cheers

**Comment by tamlok** [comment]
Hi,

If you want to share a note, you could export that note in MD format. VNote will fetch related images and attachments and put them in a separated folder.

The reason why VNote does not use a separare folder for each note in the same directory is it will make the directory a mess if you use other editors to browse VNote's notebook folder.

I might consider using a separate folder in the ` v_images` folder. But it may make the image link longer in the markdown text.

Thank you!

**Comment by Agrotsa** [comment]
Ah, ok. I hadn't tried the export function. Thanks for the tip. I'm not going to annoy you more until I don't know the program better and know its real limits, not those I believe to see because of mi ignorance. xD
