### ISSUE TITLE
无法正常使用了

### ISSUE THREAD

**Issue by blowsnowit** [tamlok/vnote#1030]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
重装系统后，设置原来的笔记路径，
现在进入编辑后完全无法点击了
动都不能动，只能右击退出编辑

How to Repro (如何复现):

**Comment by blowsnowit** [comment]
把时间删除 重新安装也没有反应

**Comment by tamlok** [comment]
请参考置顶issue： https://github.com/tamlok/vnote/issues/853

**Comment by blowsnowit** [comment]
更换opengl设置就好了
