### ISSUE TITLE
mac深色主题

### ISSUE THREAD

**Issue by sqlkrad** [tamlok/vnote#1033]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

Symptoms (表现): 现有的vnote主题没有一个可以很好地适配MacOS的深色模式。

How to Repro (如何复现): 适配比较好的就是simple那个主题了，但是还是偏亮，如果能再暗一点就好了。

**Comment by sqlkrad** [comment]
https://github.com/tamlok/vnote/issues/1035

**Comment by tamlok** [comment]
moonlight主题很暗

**Comment by sqlkrad** [comment]
嗯……但是美观度上感觉不是太好，所以把#1035那个issue贴上了，感觉跟那个是一个问题
