### ISSUE TITLE
Anchor

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1037]
OS Version (操作系统): macOS

VNote Version: 2.7.2

Symptoms (表现): to place an anchor in your document use
`<a name="my-anchor-name></a>`
This allows you to then reference that anchor with `[text](#my-anchor-name)`. VNote supports that. It would be useful if the anchor point would be displayed with an anchor symbol like ⚓. Here's how that could be done in a CSS sheet:
```
/* hide the anchor HTML */
a[name]:empty + .md-raw-inline {
  display:none;
}
a[name]:empty {
  text-decoration: none;
}
a[name]:empty:before {
 content:"⚓";
}
/* show the anchor HTML when cursor is inside */
.md-expand .md-raw-inline {
    display: inline !important;
}
```
Is that a possibility?

How to Repro (如何复现):

**Comment by tamlok** [comment]
You could add that CSS snippet to the CSS file of your chosen theme.

**Comment by DutchPete** [comment]
@tamlok : yes that works. Thank you.
