### ISSUE TITLE
Referencing an image file

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1042]
OS Version (操作系统): macOS

VNote Version: 2.7.2

Symptoms (表现): I have image files (.png), which I always give a verbal name. When I reference such a file that resides in the "images" folder outside the VNote root folder, the reference is shown as
`[name](path/to/the/file/filename.png)`

But when I reference an image in the "images" subfolder of the VNote root folder, the reference is shown as
`[name](images/number.png)`

Why does the 2<sup>nd</sup> reference not have a similar format to the 1<sup>st</sup> one? Is it possible to set this somewhere?

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

When you insert an image file into VNote's editor, it will prompt you for how to insert this file. You could select insert absolute path link.

**Comment by DutchPete** [comment]
@tamlok : yep, that works. As an additional comment: one should go to the file in Finder, drag & drop to the location in VNote where the image is to be inserted, choose "insert as image link".
