### ISSUE TITLE
New notebook

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1044]
OS Version (操作系统): macOS 10.14.6 Mojave

VNote Version: 2.7.2

Symptoms (表现): I have been using VNote for at least 1 year now, and am still confused by its notebook system.
I created a new notebook by referencing an existing folder with .md files and some subfolder. I thought VNote would import all of it, but instead it shows on 1 .md file from 1 subfolder. When I want to delete that file it tells me it will delete the file in the original folder.

How can I handle this?
Why does this have to be so complex? Why not just allow a simple copy/paste of an external  folder to VNote? I tried dragging an existing external folder to the VNote dock icon but that does not work. I am lost and frustrated. I have not come across such a convoluted system before, yet I love VNote.

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi, this will be refactored in the future. Hope it will come soon.

**Comment by DutchPete** [comment]
Halleluyah !! I too hope it will come soon, in fact, it cannot come soon enough, as far as I am concerned.

**Comment by DutchPete** [comment]
BTW, check your Gmail inbox.

**Comment by DutchPete** [comment]
Please tell me how to delete a notebook with 1 folder and 1 file, both of which reside outside VNote and neither of which I want to lose.

**Comment by DutchPete** [comment]
@tamlok : when you have time I would appreciate advice on deleting a notebook as desv=cribed in my previous comment.

**Comment by tamlok** [comment]
In the pop-up list of the notebooks, right click an item and you could delete any notebook.
