### ISSUE TITLE
ToC and wkhtmltopdf

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1047]
OS Version (操作系统): macOS 10.14.6 Mojave

VNote Version: 2.7.2

Symptoms (表现): when I export a document to PDF ("enable Table of Contents" is checked) without using `wkhtmltopdf` the output file contains a ToC.

But when I do the same via `wkhtmltopdf` the output file does not contain a ToC.

How to Repro (如何复现):

**Comment by tamlok** [comment]
When using `wkhtmltopdf`, the TOC will be the outline of the PDF. Just find a PDF reader that could show the outline to read it.

**Comment by DutchPete** [comment]
@tamlok : not sure what you mean by outline, is that the list of thumbnails of each page? I use Mac's native *Preview* app, which shows those thumbnails.

It also shows a proper ToC when the file is exported without `wkhtmltopdf`.

**Comment by tamlok** [comment]
There should be a outline panel in a normal PDF reader

**Comment by DutchPete** [comment]
@tamlok : OK, got it. Checked it in a normal PDF reader and saw what you meant.
Is there a way to have a ToC in the document itself and in the outline panel, or does one have to make a choice between either of those 2 options?

**Comment by tamlok** [comment]
You could add `[toc]` at the front of your article before export.

**Comment by DutchPete** [comment]
@tamlok : ah yes, of course. Thanks for that. I'll close this issue.
