### ISSUE TITLE
菜鸟一枚，请问编辑器模式能否进行中英文字体的分别设置？

### ISSUE THREAD

**Issue by NovaNemesis** [tamlok/vnote#1048]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
想分别设置中英文字体为华文楷体+calibri，修改css后阅读器模式成功。但利用同样方式修改mdhl文件时，若华文楷体在前，则结果中英文都是华文楷体；若calibri在前，则英文为calibri，中文为默认字体无变化（因为calibri应用到中文字体上无效）。所以请问编辑器模式中能否分别设置中英文字体？谢谢
修改的css：
![css](https://user-images.githubusercontent.com/34089802/68525070-b0db3880-0308-11ea-90c7-eccb19a8333a.jpg)
修改的mdhl：
![mdhl](https://user-images.githubusercontent.com/34089802/68525085-d9633280-0308-11ea-9882-edb2b64f620c.jpg)

**Comment by tamlok** [comment]
Hi，

目前暂时不行。后面看看能不能设置Calibri的字体的Fallback字体是华文楷体。

**Comment by NovaNemesis** [comment]
好的了解了，thx
