### ISSUE TITLE
Nested markup doesn't work

### ISSUE THREAD

**Issue by MichalMichalak** [tamlok/vnote#105]
I may be wrong, but shouldn't nested markup work as below? In edit mode only. I read mode works OK.

Version: 1.11.1 Windows x64
Text:
```
aaa _bbb **ccc** ddd_ eee
```
Output: ccc is bold, but not italic
Expected output: ccc is bold and italic

**Comment by tamlok** [comment]
Hi, in read mode, `ccc` should be both bold and italic. In edit mode, `ccc` is bold which is a bug need to fix. In detail, VNote sets `bbb ccc ddd` to italic, and then it sets `ccc` to bold which overwrite the italic format. We need to merge the format. I will consider to fix it.

By the way, VNote use *PEG Markdown Highlighter* to parse the Markdown in edit mode while use different renderer to render the read mode. So there might be some differences between the edit and read mode.

Thanks for your feedback!

**Comment by MichalMichalak** [comment]
Thanks for prompt answer. 👍
If you have it on road map, I guess I'll just close the ticket.

**Comment by tamlok** [comment]
It has been fixed in (217eafd) which will be carried in next version.

![image](https://user-images.githubusercontent.com/5763157/35042429-9dd908c8-fbc3-11e7-923c-b1f067e6fd0b.png)

Thanks!
