### ISSUE TITLE
希望能有个开关可以禁用复制粘贴链接的时候的弹框提示选择

### ISSUE THREAD

**Issue by athom** [tamlok/vnote#1050]
OS Version (操作系统):  macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.1

Symptoms (表现):
复制粘贴链接时候, 它总是弹框选择,很影响效率

How to Repro (如何复现):
1. 复制任意链接
2. 在笔记中粘贴

![image](https://user-images.githubusercontent.com/85204/68537978-5e515900-03a8-11ea-9630-b7ebadbd2f1f.png)

期望有个记忆选项, 不要每次都询问了,非常影响效率

**Comment by tamlok** [comment]
直接回车确认即可，ctel-j/k上下移动，ctrl-shift-v是粘贴纯文本。

如果记忆而不提示，那想不同的粘贴应该怎么提示呢？

**Comment by HgyHgyHgy** [comment]
他是说有一个开关，可以调整默认的选项。这样只需调整一次，就不用每次都调整了。

如果想要不同的选项，可以去那个开关调整呀。

自然开关中，也可以保持原来的功能，就是每次都询问。

感觉没矛盾。

**Comment by athom** [comment]
对头, 高频操作, 每次弹框...
体会一下你写代码, 编辑器每次复制粘贴都弹出来问候一下的心情..

**Comment by athom** [comment]
如果记忆而不提示，那想不同的粘贴应该怎么提示呢？
---
默认纯文本就行了, 不要破坏大众预期习惯, 
有特殊偏好的, 可以去重新开启这个开关
