### ISSUE TITLE
Link text chopped up

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1051]
OS Version (操作系统): macOS 10.14.6 Mojave

VNote Version: 2.7.2

Symptoms (表现): sometimes a link that occurs near the end of a line in the Read mode is chopped up in the middle of word, with the rest of the word pushed to the next line. In the Edit mode the link does not necessarily appear near the end of the line, so it is not apparent that the chop will happen until one switched to Read mode.

This, by the way, also happens in the Linux and Windows versions.

My question is how to deal with this, to avoid this.

How to Repro (如何复现):

**Comment by tamlok** [comment]
Could you please show a concrete example, please?

**Comment by DutchPete** [comment]
Couple of screenshots:

![Edit mode](https://user-images.githubusercontent.com/10794265/68575018-18a59680-0463-11ea-9591-9de177e8bafb.png)
![Read mode](https://user-images.githubusercontent.com/10794265/68575020-19d6c380-0463-11ea-86eb-24dcd659c762.png)

**Comment by tamlok** [comment]
Hi,

The blue part works as expected.

The problem is the `(file)[xxxx]` part. URL should not contain any space. Spaces should be replaced by `%20`.

![image](https://user-images.githubusercontent.com/5763157/68589853-fdb93d80-04c7-11ea-9fa7-5d7cd3da7f41.png)

You could just drag and drop your file into VNote's editor. VNote will handle the link path automatically.

**Comment by DutchPete** [comment]
@tamlok : I am sorry but I have to disagree. The `(file)[xxxx]` part that you refer to is not part of the link. If you look at the Read mode screenshot you will see it is not included. The actual link part starts at `[misrepresentation of the Agreement]`.

**Comment by tamlok** [comment]
1. First, the `(file)[]` part should be the first link, and its syntax is wrong.
2. Second, What do you expect the second link to be in read mode? I think it is now correct.

**Comment by tamlok** [comment]
Could you please paste the text here? I will show you the syntax.

**Comment by DutchPete** [comment]
@tamlok 

[misrepresentation of the Agreement](USA--US-IMAGINARY_ENEMIES_-_assorted--US-Imag-NORTH_KOREA_-_assorted--US-Imag-NK-DIPLOMACY.html#pluturan)

**Comment by tamlok** [comment]
All of the paragraph, please!

**Comment by tamlok** [comment]
The whole paragaph, please?

**Comment by DutchPete** [comment]
@tamlok:

On 2005-11-29 the U.S. government decides to finally terminate the KEDO project to build two light water reactors claiming “the North Koreans were covertly developing a uranium enrichment program which was contrary to the Agreed Framework”. This a blatant [misrepresentation of the Agreement](USA--US-IMAGINARY_ENEMIES_-_assorted--US-Imag-NORTH_KOREA_-_assorted--US-Imag-NK-DIPLOMACY.html#pluturan).

**Comment by tamlok** [comment]
Indeed, I need the `[file](xxx)` part. Any way I will type it myself.

![image](https://user-images.githubusercontent.com/5763157/68629876-59171a00-0520-11ea-9ff1-ba0c64ac09af.png)


I think it should be like this:

```
uranium enrichment program which was contrary to the Agreed Framework". ([file](file://Q:/US/US%20attachments/north20%korea%20nuclear%20chron%201989-2005.pdf), p.66). This is blatant [misrepresentation of the Agreement](USA--US-IMAGINARY_ENEMIES_-_assorted--US-Imag-NORTH_KOREA_-_assorted--US-Imag-NK-DIPLOMACY.html#pluturan)
```

If you put it directly in GitHub issue, it will be rendered as:

uranium enrichment program which was contrary to the Agreed Framework". ([file](file://Q:/US/US%20attachments/north20%korea%20nuclear%20chron%201989-2005.pdf), p.66). This is blatant [misrepresentation of the Agreement](USA--US-IMAGINARY_ENEMIES_-_assorted--US-Imag-NORTH_KOREA_-_assorted--US-Imag-NK-DIPLOMACY.html#pluturan)

This is the same as VNote does (except that the `file` will be in blue color in VNote, which is also a link).

About link syntax, for your information [Link](https://www.markdownguide.org/basic-syntax#links)

**Comment by DutchPete** [comment]
@tamlok : no, you're on the wrong track. The bit that I left out has nothing to do with the chopped up link that I am talking about, that bit is just a piece of text. I am fully aware and conversant with the syntax for links since I am writing it on an almost daily basis.

Here is another example of a chopped up link, and there should not be any confusion there.
This is the full paragraph in Edit mode:
`In order to consolidate this polity and make it irreversible, Israel adopted the so-called [Jewish Nation State bill](https://en.wikipedia.org/wiki/Basic_Law:_Israel_as_the_Nation-State_of_the_Jewish_People) on 2018-07-19, as part of its constitution, the Basic Laws.`

And this is what is looks like when it is rendered in Read mode:
<img width="757" alt="Screenshot 2019-11-12 at 11 04 27" src="https://user-images.githubusercontent.com/10794265/68657384-85846380-052b-11ea-8ebe-35ede99a1e82.png">

Notice the word "State" is chopped. This happens regularly with links in Read mode in VNote.

**Comment by tamlok** [comment]
Got it. Just need to modify the css file by replacing break-all to break-word.

**Comment by DutchPete** [comment]
@tamlok : yep, that works. Thanks very much. Oh, and .... don't forget to go to sleep ;-))
