### ISSUE TITLE
Font has changed after Tab

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1054]
OS Version (操作系统): macOS 10.14.6 Mojave

VNote Version: 2.7.2

Symptoms (表现): in Edit mode a normal <kbd>tab</kbd> jump is 4 spaces and the font remains unchanged. In some places in my document something has changed meaning that when I hit <kbd>tab</kbd> the text is like that for a code block.

Normal situation: `...Since when` : the text starting on the 4<sup>th</sup> position and the font normal.
Abnormal: the font has changed into one of coding (looks like Comic Sans font)

How can I correct this?

How to Repro (如何复现): ?

**Comment by tamlok** [comment]
https://www.markdownguide.org/basic-syntax#code-blocks

**Comment by DutchPete** [comment]
@tamlok : I do not want a code block. Look at the 2 screenshots below. The 1<sup>st</sup> is indented (4 spaces) with a normal text, whereas the 2<sup>nd</sup> is also indented with 4 spaces but the font is different.

<img width="155" alt="Screenshot 2019-11-13 at 11 56 43" src="https://user-images.githubusercontent.com/10794265/68753256-9a7cf780-05fc-11ea-8447-e6d0ea4192d0.png">

<img width="178" alt="Screenshot 2019-11-13 at 11 57 46" src="https://user-images.githubusercontent.com/10794265/68753271-a1a40580-05fc-11ea-8960-8b442528f4a3.png">

The 2<sup>nd</sup> in Read mode looks like:

<img width="134" alt="Screenshot 2019-11-13 at 12 00 59" src="https://user-images.githubusercontent.com/10794265/68753344-c0a29780-05fc-11ea-80bc-554c19de4903.png">

which is a code block, right?
I do NOT want a code block, I want regular text. I don't know how the change in Edit mode happened, but I want it to go back to regular.

**Comment by tamlok** [comment]
Could you paste the line before the target line?

Again, whether you want it or not, 4 spaces indented lines will be treated as code block in MD. This is the standard syntax.

If you want 4 spaces at the front of a line, search Google to find out how to achieve that in md. Lots of solutions.

**Comment by DutchPete** [comment]
No, 4 indents are rendered as normal text in VNote.

Regarding pasting the target line, I have sent it by email to you.

**Comment by tamlok** [comment]
VNote uses markdown-it to render md. There is an official md-it demo website. You could test your text in it first.

**Comment by DutchPete** [comment]
I just checked it, and the 4-space indent renders as a code block. Nevertheless, I can assure you I have text in my VNote document where the 4-space indent is rendered as regular text, and a quote indented 4 spaces also renders as a regular quote.

When I put copy/paste such a piece of text into the demo website, it is rendered as a code block.

So, somehow VNote seems to be inconsistent, or there is something else going on. I would have to send you the document so you could see for yourself, but I won't do that because of the content.

I shall close this issue and live with 3-space indent where 4-space indents give me code blocks.

**Comment by tamlok** [comment]
If the indented line is under a list, then it is parsed as a nested element in the list.

**Comment by DutchPete** [comment]
The indented text line is under this line
`<span style='font-size:0.75em'>Source: [Title](website)</span>`

and from the end of that line I may have done an <kbd>Enter</kbd>. Could that be the reason for the change in indent behaviour?

If so, how can I correct it?

**Comment by tamlok** [comment]
Without a more clear context, I could conclude nothing more.

**Comment by DutchPete** [comment]
OK, then let's leave it at that.
