### ISSUE TITLE
期待增加一个“展开所有子目录”的功能

### ISSUE THREAD

**Issue by Fxiao1** [tamlok/vnote#1058]
OS Version (操作系统): Windows 10

VNote Version：2.7.2

Symptoms (表现):
期待增加一个功能，在目录上右键可以增加一个选项“展开所有子目录”，否则层级比较多的情况下一级一级展开比较麻烦

How to Repro (如何复现):

**Comment by tamlok** [comment]
按*键即可(非数字键盘)

**Comment by Fxiao1** [comment]
感谢
