### ISSUE TITLE
Failure making package

### ISSUE THREAD

**Issue by zzzzasd** [tamlok/vnote#106]
Downloading as Arch Linux.
When run `makepkg -sic `error message: PKGBUILD does not exist.

```
-fno-plt -fPIC -w -D_REENTRANT -DQT_NO_DEBUG -I../../peg-highlight -I. -I/usr/lib/qt/mkspecs/linux-g++ -o pmh_styleparser.o ../../peg-highlight/pmh_styleparser.c
rm -f libpeg-highlight.a
ar cqs libpeg-highlight.a pmh_parser.o pmh_styleparser.o
make[1]: Leaving directory '/home/shern/Development/vnote-git/src/vnote/build/peg-highlight'
cd src/ && ( test -e Makefile || /usr/bin/qmake-qt5 -o Makefile /home/shern/Development/vnote-git/src/vnote/src/src.pro ) && make -f Makefile 
Project MESSAGE: VNote will be installed in prefix /usr
Project ERROR: Unknown module(s) in QT: svg
make: *** [Makefile:98: sub-src-make_first] Error 3
==> ERROR: A failure occurred in package().
```

**Comment by Sasasu** [comment]
Erk- maybe forget to add dependency `qt5-svg`

```
depends=('qt5-base' 'qt5-webengine')
depends=('qt5-base' 'qt5-webengine' 'qt5-svg')
```

**Comment by tamlok** [comment]
@Sasasu How about these packages: `qt59webchannel qt59svg qt59location qt59tools qt59translations`? Thanks!

**Comment by Sasasu** [comment]
`qt5-webengine` depends on `qt5-webchannel` and `qt5-location`, install webengine will install webchannel and qt5-location. 
`qt59tools` is included in `qt5-base`, which provides moc rcc uic and qmake and .h and runtime libs.
`qt5-translations` should install manually. It contains all translation, not all user need translation.

package | arch name | ubuntu name
--- | --- | ---
qtbase|qt5-base|qt59base
webengine| qt5-webengine |qt59webengine
webchannel| qt5-webchannel | qt59webchannel
svg| qt5-svg | qt59svg
location | qt5-location | qt59location
tools | contain in qt5-base | qt59tools
translations | qt5-translations |qt59translations

**Comment by tamlok** [comment]
@Sasasu Thanks! How about openSSL? VNote needs openSSL for networking.

**Comment by Sasasu** [comment]
you consider too much, `pacman (the package manager like apt)` depends on curl, curl depend on OpenSSL. so every archlinux have installed OpenSSL.

**Comment by tamlok** [comment]
@Sasasu Thanks! I use Manjaro and download standalone Qt SDK from Qt for development. In this case, I need to copy the openSSL 1.0 lib to Qt's lib folder manually.

**Comment by Erk-** [comment]
Must already had it installed I will add the dependencies later today.

**Comment by Erk-** [comment]
The missing dependency have been added, so I think this can be closed.

**Comment by tamlok** [comment]
@Erk- Thanks a lot!

@zzzzasd Could you please try it again. If there is anything wrong, please re-open this issue. Thanks!
