### ISSUE TITLE
能不能方便的切换预览-编辑模式？

### ISSUE THREAD

**Issue by Fxiao1** [tamlok/vnote#1060]
OS Version (操作系统): Windows 10
VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.1
Symptoms (表现):
在编辑的过程中总想反复的查看最终效果。但是现在“保存-右键-阅读模式-右键-编辑模式”的切换方式太不方便了。能否增加一个按钮（或者快捷键）可以一键循环切换编辑和预览模式。并且不需要保存当前的文档，预览的是当前编辑区的最新状态。
How to Repro (如何复现):

**Comment by tamlok** [comment]
ctrl-t 就是切换模式，不过是会保存的。更多快捷键可以悬停鼠标在按钮上查看，或者帮助菜单快捷键说明。

熟悉语法习惯后，基本很少需要切换回到阅读模式。

**Comment by Fxiao1** [comment]
首先感谢百忙中的回复，^_^
其次提一点个人的小小愚见：对于老鸟来说，确实不需要频繁的切换阅读模式，但是对于新用户（不是太熟悉Markdown）来说，频繁的切换编辑、阅读模式，还是一个难以跳过的阶段。如果明显的在快捷键帮助里面标明快速切换功能就是“ctrl+t”的话，对于刚接接触到vnote的新用户会比较友好。所以感觉将“ctrl+t”的描述改为“快速预览”会更好点

**Comment by tamlok** [comment]
后面弄个每日一贴吧😁

**Comment by HgyHgyHgy** [comment]
我是把快捷键设为Esc.那样按一个键就可以了。在那个快捷键设置里设置。

感觉好多功能，都没能在快捷键设置里设置。
这个是否比较困难？

**Comment by xb12369** [comment]
> ctrl-t 就是切换模式，不过是会保存的。更多快捷键可以悬停鼠标在按钮上查看，或者帮助菜单快捷键说明。
> 
> 熟悉语法习惯后，基本很少需要切换回到阅读模式。

谢谢  get到正确的姿势~
