### ISSUE TITLE
警告提示不生效，

### ISSUE THREAD

**Issue by goodZhaoliu** [tamlok/vnote#1064]
:::alert-info

123123

:::

是不是没实现，？不生效

**Comment by tamlok** [comment]
- alert前加一个空格试试;
- 确保md菜单里面渲染器是markdown-it，然后重新打开当前笔记;
- 上下记得和其他文本空一行;

**Comment by goodZhaoliu** [comment]
没切到渲染器是markdown-it所致！谢谢了！
