### ISSUE TITLE
如何添加主题？我看了文档但是还是没有成功

### ISSUE THREAD

**Issue by Fxiao1** [tamlok/vnote#1065]
OS Version (操作系统): Windows, Linux, macOS
windows10
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.7.2
Symptoms (表现):
现在的需求是，图片如果和背景色一样（都是灰色）在阅读模式的时候会很容易被误认为成文字，所以我想为我的图片增加一圈细细的边框。

于是我从“C:\Users\**\AppData\Roaming\vnote\themes\v_pure”复制了一份默认主题。
重命名文件夹以后并重启vnote,但是发现并没有扫描到该主题，于是我查看文档之后，将其复制倒了“C:\Users\**\AppData\Roaming\vnote\styles\codeblock_styles\v_abc”这个位置，失败
然后又将里面的“v_pure.css”这个文件放置在了“C:\Users\**\AppData\Roaming\vnote\styles\codeblock_styles”这里，仍然不能被发现，请问究竟要怎么样做才能增加一个主题呢

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

复制`v_pure`文件夹后，重命名文件夹，然后进到文件夹，将所有`v_pure`命名的文件都相应改名，然后打开`xxx.palette`文件，将里面的`[metadata]`部分改为对应文件即可。

重启vnote应该就可以发现了。

这里的设计有一点蹩脚。
