### ISSUE TITLE
Inline footnotes

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1066]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

Symptoms (表现): This is not a problem issue, merely a feature I discovered.
VNote supports inline footnotes. The syntax is `text^[an aside here]`. The advantage is that you don't have to pick a footnote number and move down to type the note; instead, the text between the square brackets is automatically replaced with a sequential number and transferred down to the list of footnotes.

This not mentioned in the VNote markdown guide that comes with VNote, nor in the Documentation on the VNote website.

Note: in inline footnotes there can only be 1 line of text, whereas with the traditional ones there can be more, even paragraphs.

@tamlok : this is certainly worth mentioning in the guide and the documentation because it is a lot more efficient to do footnotes this way.

How to Repro (如何复现):

**Comment by Fxiao1** [comment]
Hello, because I am not good at English, so the English here is machine translated, maybe some is not smooth, sorry.

After my test, vnote supports multiple lines of footnotes, examples are as follows:
Abc\^[123]
Bcd\^[
789
10216
]

**Comment by DutchPete** [comment]
@Fxiao1 : OK, good to know, thank you for the tip.

**Comment by watson387** [comment]
Yes, this has been supported for quite a while. It is a feature not an issue...

**Comment by DutchPete** [comment]
@watson387 : it may have been a feature for quite a while, I was not aware of it, and it is not mentioned anywhere, in the VNote markdown guide only the traditional footnotes are, i.e. 
in body text: `text[^1]`
in footnote: `[^1]: footnote text`
The 1st line in my original comment was an acknowledgement that this is a feature, not an issue.
