### ISSUE TITLE
Cursor sometimes won't turn into ibeam while entering intert mode

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#107]
In this video, I repetitively press `<i>` and `<esc>`. Sometimes the block cursor won't disappear when vim goes into edit mode (at 9 seconds, 21, )

version 1.11.1 on Windows 10
[Video_2018-01-18_191044.zip](https://github.com/tamlok/vnote/files/1642629/Video_2018-01-18_191044.zip)

**Comment by tamlok** [comment]
Hi, thank you for the feedback!

- Could you repro it exactly every time?
- Do you have a dev environment to compile VNote? That will be convenient to test whether we have fixed it.

**Comment by seaspeak** [comment]
- Yes. I can reproduce it every time.
- No. I am sorry. I can't compile _vnote_.

**Comment by tamlok** [comment]
Em ... so could you help me to repro it? :)

**Comment by seaspeak** [comment]
I would love to help. But I don't know how. :-) Just tell me how.

**Comment by seaspeak** [comment]
If my memory is correct, 1.10 has no such issue. Where can I retrieve 1.10, and test it again?

**Comment by seaspeak** [comment]
I can't use v.1.11 to reproduce this issue. Maybe it's related to this [fix](https://github.com/tamlok/vnote/issues/71)?

**Comment by tamlok** [comment]
That fix takes effect only when user click mouse. I have some ideas. I will make a private build for you to test later.

**Comment by seaspeak** [comment]
Did you fix the problem in version v1.12? I can't reproduce it on my site now. If you did, maybe we can close this issue.

**Comment by tamlok** [comment]
Yes, I did some change in 1.12. That is great!
