### ISSUE TITLE
Global zoom setting

### ISSUE THREAD

**Issue by raelb** [tamlok/vnote#1072]
OS Version (操作系统): Windows 10 Scaling 150%
VNote Version: 2.7.2

The default editor text display (size) turns out to be quite large on my display. I can adjust this with zoom. However, as far as I can tell, it does not save between sessions, and it also does not apply to all notes. (i.e. applies to each note individually)

It would be very helpful to have a global zoom setting that will apply to all notes by default.

Thanks
Great app!

**Comment by tamlok** [comment]
Hi,

There is already setting in the Settings dialog Read/Edit tab to control the zoom factor of both edit and read mode.

![image](https://user-images.githubusercontent.com/5763157/69007278-ec17e000-0976-11ea-87dd-46fc3cbf3614.png)

**Comment by raelb** [comment]
Ok thanks. Took me a while to figure out how that works, especially since it only applies after restart.
