### ISSUE TITLE
Linking errors when building using CMake

### ISSUE THREAD

**Issue by jimbo1qaz** [tamlok/vnote#1073]
OS Version (操作系统): Windows

When I try to clone vnote master (fbdc5a54067ba524b268a7347539ba396e8de179) and build using CMake and MSVC 2017, I get:

vmdtab.cpp.obj : error LNK2019: unresolved external symbol "public: __cdecl VGithubImageHosting::VGithubImageHosting(class VFile *,class QWidget *)" (??0VGithubImageHosting@@QEAA@PEAVVFile@@PEAVQWidget@@@Z) referenced in function "private: void __cdecl VMdTab::setupUI(void)" (?setupUI@VMdTab@@AEAAXXZ)
...

VGithubImageHosting is defined in src\vimagehosting.cpp, which is found in src\src.pro but not in src/CMakeLists.txt.

--------

Do you have build instructions? Is the official build system CMake or QMake?

------

I ran CMake in Qt Creator with a kit set up. But I was unable to make CMake find Qt until I removed `set(Qt5_DIR ...)` and `NO_DEFAULT_PATH`. Do you want to remove the hard-coded paths from the public repo?

**Comment by tamlok** [comment]
Hi,

The default way is QMAKE. CMAKE is added by a user. I will try to fix the CMAKE build later.

Please use QMAKE and qt 5.9 to build VNote. Qt 5.12 and above will not work.

**Comment by miurahr** [comment]
@jimbo1qaz Now it is fixed.
Could you try to open with MSVC2017 and give me feedback?
