### ISSUE TITLE
Modify inline keyboard shortcuts

### ISSUE THREAD

**Issue by vezzalinistefano** [tamlok/vnote#1074]
OS Version (操作系统):Linux, macOS

VNote Version (Version: )(VNote版本): 2.7.2

In which part of the code can I modify inline keyboard shortcuts?

**Comment by tamlok** [comment]
887468

**Comment by tamlok** [comment]
https://github.com/tamlok/vnote/blob/master/src/vmdeditoperations.cpp#L428

**Comment by vezzalinistefano** [comment]
Thanks
