### ISSUE TITLE
导出

### ISSUE THREAD

**Issue by ice-doom** [tamlok/vnote#108]
vnote现在是还未支持导出带样式的html功能是么

**Comment by tamlok** [comment]
是的，目前正在开发。 :)

**Comment by tamlok** [comment]
已经支持啦！欢迎下载v1.12

**Comment by DerekTso** [comment]
请问, 将来会支持导出为图片的功能吗? 谢谢

**Comment by tamlok** [comment]
@DerekTso Hi, 请参考[文档](http://vnote.readthedocs.io/en/latest/user_docs/export.html)，使用`wkhtmltoimage`和`pandoc`进行转换，VNote支持自定义转换，会对选定的文件调用对应的命令进行转换，还支持多合一。实在不行，也可以写一个脚本，让VNote来调用，然后脚本再对参数进行进一步的处理。

谢谢！

**Comment by DerekTso** [comment]
@tamlok 
我在文档里面没有看到 `wkhtmltoimage` 啊，只找到 `wkhtmltopdf` 
如何安装第三方的插件进行转换呢？
`pandoc` 应该不可以转换成图片吧？
可以像 `wkhtmltopdf` 一样弄一个内置的转换接口吗？ 谢谢

**Comment by tamlok** [comment]
@DerekTso `wkhtmltopdf`官网就有介绍`wkhtmltoimage`。pandoc应该是可以的。内置转换接口就懒得弄了啦～～

**Comment by DerekTso** [comment]
@tamlok 文档里面说的，它会将MD文件转换成HTML后再转其它格式，如果用 `wkhtmltoimage` 的话，那个HTML文件如何找到呢，试了%0 %1 %3都是下面的结果

```
>>> 导出到 D:/我的文档/vnote_exports 。
>>> 非法的自定义导出配置。
```

命令为：
`D:\wkhtmltopdf\bin\wkhtmltoimage.exe --javascript-delay 10000 "%0" "D:\我的文档\vnote_exports\test.jpg"`

**Comment by DerekTso** [comment]
@tamlok 好吧。折腾了一下还是成功了。谢谢~
