### ISSUE TITLE
Linking to headers

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1081]
OS Version (操作系统): macOS 10.14.6 Mojave

VNote Version: 2.7.2

Symptoms (表现): I thought this would work in VNote:
```
[text](#my-multi-word-header)

### My Multi Word Header
```
with [text] being the clickable link.
But it does not work in VNote, or am I doing something wrong?

How to Repro (如何复现):

**Comment by DutchPete** [comment]
Whether the header is multiword or not, the link does not work.

**Comment by tamlok** [comment]
The hearder anchor should be like toc_1 in vnote.

**Comment by DutchPete** [comment]
@tamlok : OK. The only trouble is that if you insert another header afterwards then the anchor points to the wrong header. Anyhow, that's the way VNote is set up now, so I'll use the
`<a name="abcd"></a>` and `[text](#abcd)` method, it's failsafe.
