### ISSUE TITLE
[QUESTION]: Footers with auto page numbering

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1082]
OS Version (操作系统): macOS 10.14.6 Mojave

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

Symptoms (表现): is it possible to add a footer that is repeated at the bottom of every page when exported to e.g. PDF?

Is it possible to have automatic page numbering in that footer?

How to Repro (如何复现):

**Comment by tamlok** [comment]
You could do that via wkhtmltopdf in the export dialog. Just explore it deeper.

**Comment by DutchPete** [comment]
@tamlok : OK, clear. Thanks for the tip.
