### ISSUE TITLE
一个建议，关于代码复制按钮

### ISSUE THREAD

**Issue by yousifun** [tamlok/vnote#1083]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
一个建议，关于代码复制按钮，复制按钮能不能设置在代码框右边。
![Cwu3xif79m_看图王.png](https://gitee.com/yousifun/images/raw/master/99ea4056cf201dc131291caaeb547fe4.png)

How to Repro (如何复现):

**Comment by tamlok** [comment]
去到配置文件夹，把common文件夹删除了，重启vnote

**Comment by yousifun** [comment]
谢谢，已经完成。
