### ISSUE TITLE
插入公式不能正常显示 

### ISSUE THREAD

**Issue by terry-fjp** [tamlok/vnote#1087]
OS Version (操作系统): Windows 10

VNote Version :2.7.2

Symptoms (表现):Markdown-it、启用MathJax后重启VNote

插入公式 $\sum$            $$\sum$ $，```mathjax  \sum  ```均不能正常显示公式，请问是我设置有问题么？

How to Repro (如何复现):如上

**Comment by tamlok** [comment]
1. 请确认VNote的确重启了（而不是驻留系统托盘）；
2. 需要联网；
3. 单独新建一个笔记，输入`$\sum$`看看；

**Comment by terry-fjp** [comment]
谢谢，以解决，是联网问题
