### ISSUE TITLE
[QUESTION]: open an existing folder

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1088]
OS Version (操作系统): macOS 10.14.6 Mojave

VNote Version: 2.7.2

Symptoms (表现): is it possible to open an existing folder with .md files in VNote. I know @tamlok is working on refactoring and folders will be part of it. But isn't there a possibility to open such a folder with the present VNote version?

If so, can you tell me what steps to take? I find the instructions in the documentation confusing.
 I would be OK with having the folder I want to open put in my only existing VNote notebook.

How to Repro (如何复现):

**Comment by tamlok** [comment]
In the top left corner, there is a Browser tab, which is the only one widget to open an external folder.

**Comment by DutchPete** [comment]
@tamlok : OK, got it, thanks a lot. It would be nice to be able to have various folders open in the notebook view without having to go through acrobatics; I hope that will be possible when the refactoring is complete.
