### ISSUE TITLE
[QUESTION]: VNote as default app

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1089]
OS Version (操作系统): macOS 10.14.6 Mojave

VNote Version: 2.7.2

Symptoms (表现): is it possible to make VNote my default app for .md files? If so, when I open an .md file that is not part of a VNote notebook, will that work?

If it is not currently possible, will it be possible after the refactoring exercise?

How to Repro (如何复现):

**Comment by tamlok** [comment]
That will wok now. Just do it as what your os suggests.

**Comment by DutchPete** [comment]
@tamlok : no, it does not. I tried to open an .md file with VNote from Finder (Apple's explorer) by right-clicking on it, then click "open with", and select VNote. Nothing happens.

**Comment by tamlok** [comment]
I am not familiar with macOS, so you need to work it out yourself.

In general, VNote accepts the file path as the start argument like this:

```
./VNote "/home/tamlok/mynote.md"
```

**Comment by DutchPete** [comment]
OK, thanks, I'll leave it at that because having to jump through hoops is not the way a default setting should work, at least IMO.
