### ISSUE TITLE
V2.8版本代码复制代码按钮消失，主题被覆盖

### ISSUE THREAD

**Issue by yousifun** [tamlok/vnote#1092]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8,  d78e892d5cc  etc..

Symptoms (表现):
看到有图床功能，感觉软件越来越好了，马上就更新到了2.8，可以等我更完，启动后发现，之前修改的主题样式都被新的覆盖了（还好有备份），而且之前的代码复制功能好像也没有了。不知道是不是我一个人这样。
如果不是的话，我建议，更新软件后，可以不要覆盖已经修改的主题。

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

1. 复制按钮因为在复制HTML的时候，会带上，所以暂时默认先关闭，可以修改`vnote.ini`打开，参考 https://github.com/tamlok/vnote/issues/944
2. 如果需要修改主题，建议复制一份，重命名并修改`palette`文件中相关文件信息。默认主题在升级的时候是会自动更新覆盖的（这样才能升级，不然后面想要修改主题，但用户的却一直不更新）。

谢谢！

**Comment by Fxiao1** [comment]
# 复制按钮消失
我今天也发现了这个问题。首先说一下解决办法：
1. 在软件中打开`文件`菜单
2. 在里面选择`打开配置文件夹`
3. 在.打开的文件夹里面修改`vnote.ini`这个文件。
4. 在其中搜索`enable_code_block_copy_button`这个关键字，如果能搜到，将它的值改成`true`，如果搜不到，在末尾追加以下代码
```
[web]
enable_code_block_copy_button=true
```
5. 删除刚才那个配置文件夹里面的“resources”文件夹，待会重启后会重新创建。
6. 重启vnote
# 主题文件被覆盖

**Comment by tamlok** [comment]
@Fxiao1 非常感谢！我会在设置里面添加一个配置选项暴露出来。

**Comment by tamlok** [comment]
2.8.1已经在设置里面的Markdown标签页加了一个勾选开关。
