### ISSUE TITLE
puml 无法进行渲染

### ISSUE THREAD

**Issue by silva6** [tamlok/vnote#1095]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8, 2.7.2

Symptoms (表现):
使用在线服务，不能渲染出图片

How to Repro (如何复现):
必现

**Comment by tamlok** [comment]
hi，

我这里没问题。设置里面开启后，vnote重启了吗？能否贴出文本？

**Comment by silva6** [comment]
重启、重装都试过，任何文本都不行。现在怀疑和系统有关，最近通过brew升级了一些系统库，如果是这样的话，是否有方法帮助定位呢

**Comment by tamlok** [comment]
能否贴出一个示例文本呢？只要能联网应该就可以。是官网下载的dmg吗？

**Comment by silva6** [comment]
- 示例文本

![image](https://user-images.githubusercontent.com/2333255/70105702-93d22500-167c-11ea-84d3-37545f4bf105.png)

- 预览

![image](https://user-images.githubusercontent.com/2333255/70105796-cda32b80-167c-11ea-85c0-a8a9760a79e6.png)

- 设置

![image](https://user-images.githubusercontent.com/2333255/70105815-e27fbf00-167c-11ea-8bd2-3f0467cb23b8.png)

**Comment by tamlok** [comment]
是自己编译的还是下载DMG的？

**Comment by silva6** [comment]
从release页下载的dmg，网络是正常的

- 帮助页
![image](https://user-images.githubusercontent.com/2333255/70105954-59b55300-167d-11ea-9b3c-e3f54c8524d5.png)

**Comment by silva6** [comment]
抓包看了下，在编辑puml时，没有发网络请求

**Comment by silva6** [comment]
发现很多错误日志

![image](https://user-images.githubusercontent.com/2333255/70112635-e9183180-1690-11ea-99a7-c7077de12833.png)

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/70113351-d2bfa500-1693-11ea-90ed-cfdc3e11aa61.png)

plantuml.com的这个资源没有了~~

**Comment by silva6** [comment]
这类依赖资源放本地会不会更好些？

另外，为啥只有我的不能使用，理论上所有人都会受影响吧

**Comment by tamlok** [comment]
我的也不能用。你可以用local plantuml jar。我联系一下plantuml.com，下个版本改为本地。

**Comment by silva6** [comment]
本地版本用过了，实时预览非常卡，会启动N个jar，打字都不流畅，渲染还慢，体验差特别多

**Comment by silva6** [comment]
> 我的也不能用。你可以用local plantuml jar。我联系一下plantuml.com，下个版本改为本地。

试试这个
https://github.com/imaya/zopfli.js/blob/master/bin/zopfli.raw.min.js

**Comment by tamlok** [comment]
已经修复 https://github.com/tamlok/vnote/pull/1097

**Comment by tamlok** [comment]
可以下载最新构建版本： https://bintray.com/tamlok/vnote/vnote/2.8#files

**Comment by silva6** [comment]
多谢~
好像有点问题，编辑模式没有原地预览了

![image](https://user-images.githubusercontent.com/2333255/70369999-b2465380-18fc-11ea-939a-ca52e1c1141d.png)

**Comment by jt6562** [comment]
感觉没完全修好，阅读模式是好的，但是编辑模式下的实时预览还在请求`zopfli`

**Comment by tamlok** [comment]
ok，有可能，我再改一下，这个简单

**Comment by tamlok** [comment]
已经修复，请更新2.8.1版本
