### ISSUE TITLE
“VNote.app” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by zhangwei** [tamlok/vnote#1096]
OS Version (操作系统): macOS

VNote Version:  https://github.com/tamlok/vnote/releases/download/v2.8/VNote-2.8-x64.dmg

Symptoms (表现):
打开时出现错误提示：“VNote.app” cannot be opened because the developer cannot be verified.

How to Repro (如何复现):
在Mac上安装安装 https://github.com/tamlok/vnote/releases/download/v2.8/VNote-2.8-x64.dmg 后，打开VNote.app

**Comment by tamlok** [comment]
是的，暂时没钱认证苹果开发者。你可以右键菜单，打开，这样可以在弹出的窗口选择是否仍然要固执地打开。具体可以搜一下。

**Comment by zhangwei** [comment]
谢谢回答！
