### ISSUE TITLE
表格下面加分隔符，表格和分隔符会连在一起

### ISSUE THREAD

**Issue by wuscloud** [tamlok/vnote#11]
#### 表格
|姓名|年龄|住址|
|-----|-----|----|
|张三 |5     |北京|
|李四 |6     |南京|

---

**Comment by tamlok** [comment]
谢谢反馈！确实有这个问题，应该是CSS样式的设置。

谢谢使用！

**Comment by tamlok** [comment]
已经修复了(1b59afbdf2e96ba79afbcf9b8e6799f8427278a0)，会在下一个版本中生效。

您也可以自行修改样式里面的`default.css`，或者直接下载覆盖。https://github.com/tamlok/vnote/commit/1b59afbdf2e96ba79afbcf9b8e6799f8427278a0

**Comment by wuscloud** [comment]
big thanks
