### ISSUE TITLE
系统默认程序、外部程序快捷键无效 Both Open Via Default Program's and external editors's shortcuts are invalid

### ISSUE THREAD

**Issue by MaiTestarossa** [tamlok/vnote#110]
默认.md编辑器是Typora，
`OpenViaDefaultProgram=F12`按`F12`无任何反应，
修改`OpenViaDefaultProgram=F1`、修改`OpenViaDefaultProgram=Alt+Q`均无效

添加外部程序，
```
[external_editors]
Typora=C:\\\"Program Files\"\\Typora\\Typora.exe \"%0\", F1
```

按`F1`效果同上
同时鼠标右键菜单点击均有效

另外自定义外部程序的快捷键变量，在舰长模式快捷键设置内，这样写是否可以生效？
```
[captain_mode_shortcuts]
Typora=Z
```

**Comment by tamlok** [comment]
Hi，谢谢使用！

快捷键无效的原因应该是你单击一个笔记后，输入焦点就跳转到编辑区域了。尝试一下按住Ctrl来点击？后面我会改一下这段逻辑。

舰长模式的快捷键功能是固定的，暂不支持这样自定义。您可以使用`Ctrl+E W`来定位到某个笔记，然后`F1`来打开Typora编辑。（另：真的不试试VNote的编辑模式吗？） :)

谢谢！

**Comment by tamlok** [comment]
已经修复了点击以后快捷键无效的问题 (d630ff7bf24ab07c9f43a8a247f35bcf1) 。谢谢！
