### ISSUE TITLE
请问片段中可以动态的解析幻词吗?

### ISSUE THREAD

**Issue by x-demo** [tamlok/vnote#1101]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8

Symptoms (表现):
请问: 在片段中可以动态的解析幻词吗? 比如说 我有2个幻词a 和 b;  分别对应abc 和 def; 我想在片段中根据选中的幻词名称 a 或者 b, 动态的解析成abc 或 def; 是不是现在没办法实现? (我知道目前片段中是可以解析固定的幻词的, 我只是想要动态的解析幻词而已)  先谢过大佬告知详情 :)

How to Repro (如何复现):

**Comment by tamlok** [comment]
选中的文字是否会扩展幻词这个你恐怕得自己试一下了。印象中好像是不行的，因为一段文字中可能有正常的词刚好是幻词的形式。

**Comment by x-demo** [comment]
> 选中的文字是否会扩展幻词这个你恐怕得自己试一下了。印象中好像是不行的，因为一段文字中可能有正常的词刚好是幻词的形式。

谢谢, 知道了 :)
