### ISSUE TITLE
原地预览数学公式时\会被转义，需要四个\\\\才能在原地预览中看到换行效果

### ISSUE THREAD

**Issue by cang-ming** [tamlok/vnote#1105]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8

Symptoms (表现):

比如用这个代码测试

$$\begin{cases}
a_1x+b_1y+c_1z=d_1\\
a_2x+b_2y+c_2z=d_2\\
a_3x+b_3y+c_3z=d_3\\
\end{cases}
$$

原地预览会长条式的列在下面，ctrl T渲染后就没问题了
这个问题怎么解决呢？应该是原地预览时\被转义了？挠头

**Comment by tamlok** [comment]
检查一下渲染器是不是md-it.

应该是三个斜杠即可。我这里编辑和阅读模式都得转义。

这个没办法，md 里面某些特殊字符得转义。

一个避免转以的方法是把公式定义写在代码块里面(语言是mathjax)，具体可以参考帮助菜单的语法帮助。

**Comment by cang-ming** [comment]
> 检查一下渲染器是不是md-it.
> 
> 应该是三个斜杠即可。我这里编辑和阅读模式都得转义。
> 
> 这个没办法，md 里面某些特殊字符得转义。
> 
> 一个避免转以的方法是把公式定义写在代码块里面(语言是mathjax)，具体可以参考帮助菜单的语法帮助。

换渲染器确实解决了，谢谢啦
