### ISSUE TITLE
关于自动添加“标题序列”功能的一点小建议

### ISSUE THREAD

**Issue by Creling** [tamlok/vnote#1108]
目前（v2.8），使用自动添加标题序列这一功能后，会产生如下的效果
![图片](https://user-images.githubusercontent.com/43109504/70497125-06477700-1b4d-11ea-8828-78bd01c21451.png)

希望可以将标题统一升一级，也就是将效果修改为
```
# Lab1实验报告
## 1. 项目及成果概要
## 2. 重要数据结构及说明
```

一般而言，h1都是作为文章标题使用的，在文章标题前加上一个序号显得有些奇怪

**Comment by tamlok** [comment]
设置一下就好了：

![image](https://user-images.githubusercontent.com/5763157/70497660-cd100680-1b4e-11ea-8818-171a2b3f035b.png)

**Comment by Creling** [comment]
感谢回复
