### ISSUE TITLE
shortcut keys in MacOS

### ISSUE THREAD

**Issue by txchen** [tamlok/vnote#111]
Currently all the ctrl + ? is mapped to cmd + ? in MacOS, is it possible to make an option to disable this behavior?

I personally use both windows and mac, having the same shortcut keys would be much better experience IMO. Thanks!

**Comment by tamlok** [comment]
This is the default behavior of Qt. I think it is `cmd+c` in macOS to copy, so Qt tries to make it consistent. I will add an option later. For now you could just custom the shortcuts in macOS by using `Meta+?`.

**Comment by txchen** [comment]
@tamlok Nice! I changed the `Ctrl` to `Meta` and got what I want. Thank you so much!
