### ISSUE TITLE
Windows10平台上以阅读模式打开较大体积的Markdown文档时程序无法响应.

### ISSUE THREAD

**Issue by PrimaryFantasty** [tamlok/vnote#1111]
OS Version (操作系统): Windows
Windows 10 专业版 版本号 1909 操作系统版本 18365.476
硬件: 处理器 Intel(R) Core(TM) i7-8550U 已安装的RAM 16.0GB 系统类型 64位操作系统 

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8
使用的是release下的VNote_win_X64_portable_2.8.zip 

Symptoms (表现):
1. 从外部复制了一份纯文本的markdown文档(体积为45Kb的markdown文件)的内容到新的空白笔记中;
2. 此时编辑模式下还是正常的,但一旦点击"保存更改并阅读",就会出现下述情况:
当点击相应笔记()时,无法显示内容,同时,整个程序无法响应,此时vnote.exe进程的CPU占比一直稳定在25%,内存占用超过300M.
3. 尝试了文档[(https://vnote.readthedocs.io/zh_CN/latest/user_docs/faqs.html)]中提供的方案,但该问题在我的环境下仍旧100%重现.

How to Repro (如何复现):
 如上.

**Comment by tamlok** [comment]
其他内容的文档有这个问题吗？如果没有问题的话，可以怀疑是文档内容有特殊字符。如果可以，可以把该文档发我邮箱。

**Comment by PrimaryFantasty** [comment]
另外测试了一份更大的文档（4.5MB左右），发现除了速度较慢外，没有卡死的问题，应该是我的文档有字符问题吧（这份文档原本是用Typora编写的），文档已发到您的Gmail邮箱，谢谢！

**Comment by tamlok** [comment]
Hi,

把`^H`这个特殊字符删除即可：

![image](https://user-images.githubusercontent.com/5763157/70848704-62ddc580-1eb0-11ea-9ac8-26847dc28c27.png)

**Comment by PrimaryFantasty** [comment]
谢谢!确实如此,问题已解决.
