### ISSUE TITLE
yaml metadata block support

### ISSUE THREAD

**Issue by yuuuxt** [tamlok/vnote#1116]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.1

Symptoms (表现):
markdown not working correctly when a yaml block is added at top

How to Repro (如何复现):
add a yaml metadata block at top (see [here](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block))

because of the need to use pandoc to export pdf using [template](https://github.com/Wandmalfarbe/pandoc-latex-template), a yaml metadata block is required. but currently vnote doesn't support adding such a block to function as expected (cannot render properly). could you consider adding yaml metadata block support? Thank you!

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/71056620-e9d2bc80-2194-11ea-8a75-60b7d82c7fe2.png)

Turn it on and re-open your tabs.

**Comment by yuuuxt** [comment]
just found the real issue: currently metadata that ends with "..." is not supported.
I already opened that on, but I used "..." to mark the end of metadata, which is the default in the template I use and is acceptable for pandoc.  Changing it to "---" fixes the issue.

So it's just an edge case, but worth noting. Thank you for your reply!
