### ISSUE TITLE
自定义导出错误: QProcess错误 0 

### ISSUE THREAD

**Issue by yuuuxt** [tamlok/vnote#1118]
OS Version (操作系统): Windows 10 19037.1

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.1

Symptoms (表现): failure when running pandoc command: QProcess错误 0

How to Repro (如何复现):
1. get pandoc and miktex working; tried runnning identical pdf export task and succeeded;
1. get vnote working, tried exporting pdf and succeeded but failed running custom pandoc task, getting error message QProcess错误 0.

p.s. 怀疑与系统版本有关, 同样的miktex + pandoc环境, 同样操作, 在较早版本win10上运行成功.

**Comment by tamlok** [comment]
写命令的时候，尝试写`pandoc.exe`的绝对路径。

**Comment by yuuuxt** [comment]
成功, 谢谢帮助
