### ISSUE TITLE
Feature request: reset layout.

### ISSUE THREAD

**Issue by txchen** [tamlok/vnote#112]
I can drag the layout and mess it up: e.g. make the folder pane invisible. And the thing is: it cannot be restored easily.

Now I have to close VNote, open `session.ini`, clean up the geometry setting, and reopen vnote. It would be nice if you could add a `reset layout` function, IMHO.

**Comment by tamlok** [comment]
Sure! You could use the `Expand` toolbar button to change the layout. `Ctrl+E E` to toggle expand mode if you need to hide the folder panel.

Thanks!

**Comment by txchen** [comment]
Actually I couldn't use Ctrl+E E to solve the problem:

Firstly, I use 'two panels' layout:
![image](https://user-images.githubusercontent.com/713074/35257936-2ef9a664-ffb1-11e7-9e12-59d46782ec7a.png)

Then, I expand the file list panel to the left most:
![image](https://user-images.githubusercontent.com/713074/35257965-61c2bfe0-ffb1-11e7-8c88-4335e0844082.png)

As you can see, the folder panel disappeared, and I cannot restore it since I cannot reach the splitter. Also, ctrl+E E does not help, it just toggle the file panel and folder panel, but I could not make folder panel to appear again. Hope this explains my issue.

**Comment by tamlok** [comment]
Added (bc9dd643fc141c671c11d4a815aa1940a9440c30). Will be carried on next version.

Thanks!
