### ISSUE TITLE
VNOTE的开屏文档是怎么个选择机理？数学公式似乎没有语法高亮?

### ISSUE THREAD

**Issue by cang-ming** [tamlok/vnote#1120]
win10+2.8.2
每次新打开vnote时都会自动打开一个我很久不编辑、已经彻底终结的文档，这个开屏文档怎么设置呢……
（其实这个问题应该在群里问问，可是vnote交流群只有那么一个500人群还满人了QAQ）
同时我看latex语法中并没有语法高亮是吗？全程就绿油油的样子，这个能设置吗？

**Comment by tamlok** [comment]
设置里面设置一下启动页面：

![image](https://user-images.githubusercontent.com/5763157/71315274-b002fe00-2493-11ea-8ca1-495e3ccca1d3.png)

可以文件菜单里面的退出来确认VNote没有驻留系统托盘。

**Comment by cang-ming** [comment]
> 设置里面设置一下启动页面：
> 
> ![image](https://user-images.githubusercontent.com/5763157/71315274-b002fe00-2493-11ea-8ca1-495e3ccca1d3.png)
> 
> 可以文件菜单里面的退出来确认VNote没有驻留系统托盘。
> 
> 高亮latex语法是一个好想法，后面可以实现一下。

辛苦hhh
