### ISSUE TITLE
左边的笔记本窗口关闭后，没有可以重新打开的地方

### ISSUE THREAD

**Issue by CDtoo** [tamlok/vnote#1122]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.1

Symptoms (表现):关闭左边的笔记本窗口，没有地方可以重新打开

How to Repro (如何复现):关闭左边的笔记本窗口

**Comment by tamlok** [comment]
左边的笔记本窗口是无法关闭的。

如果是用鼠标拉小的，把鼠标放在窗口边缘拉回来。
如果是工具栏扩展编辑区域的，重新点一遍那个按钮。

实在不行，就设置，重置布局，重启vnote。

**Comment by CDtoo** [comment]
> 左边的笔记本窗口是无法关闭的。
> 如果是用鼠标拉小的，把鼠标放在窗口边缘拉回来。
> 如果是工具栏扩展编辑区域的，重新点一遍那个按钮。
> 实在不行，就设置，重置布局，重启vnote。

在边缘处的确很隐蔽，拉不出来，重置布局可以解决。
