### ISSUE TITLE
自定义图片文件夹--无效

### ISSUE THREAD

**Issue by duansheli** [tamlok/vnote#1124]
OS Version (操作系统): Windows 10
VNote 2.8.1 

Symptoms (表现):
自定义图片文件夹不生效

How to Repro (如何复现):
设置 -》 笔记管理 -》 
外部文件---- 自定义图片文件夹
设置为 F:/zz/
编辑md文档时，粘贴图片时， 图片还是被保存在md同目录下 
不是应该会保存到 F:/zz/ 么

**Comment by tamlok** [comment]
重启vnote试一下？确认是编辑外部文件。

**Comment by duansheli** [comment]
外部文件是啥意思 
编辑的是笔记中 

![image](https://user-images.githubusercontent.com/8579595/71319656-1c095480-24dc-11ea-9234-d7c4b75d8ab7.png)

图片粘贴后变成这样

![image](https://user-images.githubusercontent.com/8579595/71319663-304d5180-24dc-11ea-8dfc-1dff485cb594.png)


有重启过 
笔记 ---- 自定义图片文件夹
这个选项改文件夹名字是正常的

**Comment by duansheli** [comment]
另外用了下 typora  
在粘贴图片时， 除了 图片会保存到一个全局文件夹 
还可以右键 自定义文件保存名与路径 
![image](https://user-images.githubusercontent.com/8579595/71319743-3db70b80-24dd-11ea-99f1-cbf1c9919221.png)

**Comment by tamlok** [comment]
外部文件就是相对笔记本里面的笔记而言的文件。vnote区分笔记文件和外部文件。
