### ISSUE TITLE
Bullets in the TOC

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1134]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

Symptoms (表现): In the edit mode I have added `[toc` to the top of the page. When I change to Read mode the TOC is there, but each (sub)heading has a bullet point next to it. Is there a way to avoid getting those?

How to Repro (如何复现):

**Comment by tamlok** [comment]
You need to modify the CSS style.

**Comment by DutchPete** [comment]
I look through the CSS sheet of v_pure (the one I am using) but there is nothing about TOC or table of contents in there.
Please tell what I should look for and which element to change.

**Comment by tamlok** [comment]
You could export one toc note as html. Open that html in chrome and press F12 to debug all the elements. Google how to change the style of an unordered list.

**Comment by DutchPete** [comment]
@tamlok : I have never seen a TOC, whether in a paper book or in an electronic one, with bullet points. Surely that is a bug in VNote to be solved by the dev?

**Comment by tamlok** [comment]
Add the following to the end of `[configuration folder]/resources/common.css`:

```css
.vnote-toc ul {
    list-style-type: none
}
```

**Comment by DutchPete** [comment]
@tamlok : yes, that did the trick.
Many thanks, once again, for your help. I know this is not the Chinese New Year yet, nevertheless I wish you and your loved ones a happy, successful, and healthy year, both 2020 and the coming Chinese New Year.

**Comment by tamlok** [comment]
@DutchPete My pleasure! Thank you! Happy new year 2020!
