### ISSUE TITLE
无法输入公式

### ISSUE THREAD

**Issue by joechenrh** [tamlok/vnote#1135]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现):

无法输入公式

How to Repro (如何复现):

菜单里已经启用mathjax，也已经重启软件和tab，

![Screenshot from 2020-01-01 13-07-31](https://user-images.githubusercontent.com/18008525/71638352-81a5cf80-2c98-11ea-992c-2df469b2fe8b.png)

**Comment by tamlok** [comment]
默认需要联网哦，帮助菜单检查更新是否正常？是自己编译的还是appimage？

**Comment by joechenrh** [comment]
编译版，检查更新确实不行，应该是全局代理没设置好，我再检查一下

**Comment by tamlok** [comment]
如果是自己编译的，也需要检查一下openssl是否正常。可以下载一个appimage来测试一下是否是代理问题。或者下载mathjax到本地然后指定使用本地版本也可以。
