### ISSUE TITLE
请问自定义主题可以替换全部图标吗？

### ISSUE THREAD

**Issue by boyan0108** [tamlok/vnote#1138]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8

Symptoms (表现):

你好，我在修改一个自定义主题，想替换图标，但是主题目录里面似乎只有一小部分图标；
有些图标我找不到，请问那些找不到的图标放在哪里？
如果不能全部替换，请问有没有办法修改默认图标的颜色？
感谢！

**Comment by tamlok** [comment]
暂时不可以。图标颜色可以修改palette文件的icon_fg那几个参数即可。
