### ISSUE TITLE
疑问：有的笔记偶然会出现“不被索引”的问题，这是怎么回事？

### ISSUE THREAD

**Issue by zhahuya** [tamlok/vnote#1139]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8,1 

Symptoms (表现): 
在Onedrive同步的情况下，昨天还写的笔记，今天在list里就看不到了。
在文件夹里还有，打开以后显示“独立文件”，这是怎么回事呢？
这是偶然会发生的问题。

How to Repro (如何复现):无

**Comment by tamlok** [comment]
不知道这个和onedrive有没有关系。vnote是通过_vnote.json文件来索引的，你可以看一下这个文件的修改历史。可以通过文件菜单的从外部文件新建笔记来把丢掉的笔记重新导入到当前文件夹。

**Comment by zhahuya** [comment]
> 不知道这个和onedrive有没有关系。vnote是通过_vnote.json文件来索引的，你可以看一下这个文件的修改历史。可以通过文件菜单的从外部文件新建笔记来把丢掉的笔记重新导入到当前文件夹。

感谢您的回复，为我提供了一个线索(･ω･)ﾉ
