### ISSUE TITLE
How to donate to this project?

### ISSUE THREAD

**Issue by ikelaiah** [tamlok/vnote#114]
Hi,

How to donate to this project?

Regards,
Iwan

**Comment by tamlok** [comment]
Hi,

Thank you for your attention! I will consider adding info about the donation in near future. For now, please feel free to use VNote, and advertise it to more people if you enjoy it, which will surely also drive me to further development!

Thanks!

**Comment by tamlok** [comment]
Already added donate info in the homepage of Github project. https://github.com/tamlok/vnote#donate

Thanks!

**Comment by ikelaiah** [comment]
Thank you!
