### ISSUE TITLE
编辑时一行显示的长度大于编辑器的宽度,导致有一个字符显示不完全

### ISSUE THREAD

**Issue by jiujiii** [tamlok/vnote#1141]
OS Version (操作系统): macOS
VNote Version (Help - About VNote - Version: )(VNote版本): 2.8
Symptoms (表现):
![Image of Yaktocat](https://s2.ax1x.com/2020/01/03/lU0Qoj.jpg)
How to Repro (如何复现):
正常编辑就行

**Comment by tamlok** [comment]
https://github.com/tamlok/vnote/issues/454
