### ISSUE TITLE
"Constrain Width of Images" does not work in Edit mode

### ISSUE THREAD

**Issue by louwers** [tamlok/vnote#1144]
OS Version (操作系统): Linux

VNote Version: 2.8.2

Symptoms (表现):

When I include a large image, the image is bigger (horizontally) than the viewport. The "Constrain Width of Images" should also work for images shown in "Edit mode". I tried adding

```
max-width: 100%
```
to the custom style, but that also does not work.

**Comment by tamlok** [comment]
Hi,

`Constrain Width of Images` should work in both read and edit mode. Could you please paste a screenshot here?

CSS styles are used only in read mode.

**Comment by louwers** [comment]
![image](https://user-images.githubusercontent.com/649392/71781394-b4b8cd80-2fce-11ea-85c1-66eb806b6a3e.png)

**Comment by tamlok** [comment]
You need to enable this one:

![image](https://user-images.githubusercontent.com/5763157/71790758-14fe4c80-306d-11ea-9a9d-e23929f2b651.png)

**Comment by louwers** [comment]
Not quite sure why it wasn't working (I had that option checked), but it does now! Thanks.
