### ISSUE TITLE
Is there a text-search function?

### ISSUE THREAD

**Issue by ikelaiah** [tamlok/vnote#115]
Hi,

Thanks for the app.
Is there a text-search function?

Regards,
ikel

**Comment by tamlok** [comment]
Hi,

Currently you could search your notes using external tools like `grep` and `ag`. Full-text search will be supported soon (within next two versions).

Thanks for your attention!

Regards,
Le

**Comment by ikelaiah** [comment]
I didn't think of `grep`, well, yes, that would work for now. Thank you for this project.

**Comment by tamlok** [comment]
Already added in 1.13 version. :)
