### ISSUE TITLE
Mouse is always in 'drag' mode when opening note in edit mode

### ISSUE THREAD

**Issue by louwers** [tamlok/vnote#1150]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现):

When opening a note in edit mode, it always 'drags'.

See video (the flickering is a problem with the recording).

![bug](https://user-images.githubusercontent.com/649392/71851475-f339af80-30d6-11ea-8b21-2208b233cb94.gif)

How to Repro (如何复现):

Not sure! For me it happens every time I open a note. I'll try to downgrade Qt.

**Comment by tamlok** [comment]
Are you building VNote from Qt with version above 5.9? VNote now works well only with Qt 5.9. You could try the AppImage directly or install Qt 5.9 privately (via the *.run file from Qt website) into your home dir (which won't affect your system's newer one).

**Comment by louwers** [comment]
Thanks for the advice. I'm using a binary compiled with Qt 5.9 now and that works. Thank you.
