### ISSUE TITLE
可否自助设置图片默认宽度？

### ISSUE THREAD

**Issue by cang-ming** [tamlok/vnote#1155]
插入图片默认大小是2880px的宽度，太大了，这个能手动设置吗？如果能，怎么修改呢？
以及能不能设置文档所有图片“一键统一宽度”？

我把vnote当整理笔记本用的，会有很多截图，如果能实现这俩就太好了

**Comment by tamlok** [comment]
Hi,

插入图片的时候，对话框里面有滑块可以滑动缩放图片。一键设置这个功能感觉不太具有普遍性，毕竟不同图片有不同要求。

**Comment by cang-ming** [comment]
> Hi,
> 
> 插入图片的时候，对话框里面有滑块可以滑动缩放图片。一键设置这个功能感觉不太具有普遍性，毕竟不同图片有不同要求。

那修改默认宽度可以实现吗，直接去配置参数里搜索修改嘛

**Comment by tamlok** [comment]
修改默认宽度是什么意思呢? markdown菜单下面有一个 限制图片宽度，打开后，所有大图片都会被限制大小。

**Comment by cang-ming** [comment]
> 修改默认宽度是什么意思呢? markdown菜单下面有一个 限制图片宽度，打开后，所有大图片都会被限制大小。

大概是这个意思：
![1](https://github.com/cang-ming/picture_vnote/blob/master/Snipaste_2020-01-08_14-58-26.png?raw=true)

**Comment by tamlok** [comment]
这个暂时没有设置，默认就是不缩放，图片原大小。你试试markdown菜单下面的限制图片宽度吧。

**Comment by cang-ming** [comment]
> 这个暂时没有设置，默认就是不缩放，图片原大小。你试试markdown菜单下面的限制图片宽度吧。

噢噢噢噢，是原大小啊，那我明白了，谢谢啦
