### ISSUE TITLE
Shortcuts Help & Markdown Guide

### ISSUE THREAD

**Issue by vmexia** [tamlok/vnote#116]
Hello, I've been trying out VNote and I noticed that when I open Shortcuts Help or Markdown Guide in the Help menu the .md that appears is empty for both of them. Is this not implemented yet? If so, where can I check them out? Best regards and awesome job so far.

Edit: I know that a few shortcuts are mapped on the shortcut bar like Bold (ctrl + B) etc, but the switch between edit/read mode doesn't show any, and that would be really helpful.

**Comment by tamlok** [comment]
Hi,

What do you mean by "the .md that appears is empty"? These two files are embedded into the EXE file via Qt's resource system, so they are tagged "System" and are read-only. You could edit them to see the contents or check [this](https://github.com/tamlok/vnote/blob/master/src/resources/docs/shortcuts_en.md).

Yeah, I have added the shortcuts in the tooltip of other buttons.

Thanks for your attention and feedback!

**Comment by vmexia** [comment]
Ok so that may explain it, when I click **Shortcuts Help** it opens a shortcuts_pt.md file whereas the link you mentioned shows a shortcuts_en.md file. My **guess** is that vnote is trying to open the shortcuts file based on the language that the system is using, which in my case is pt_PT, that doesn't exist yet.

**Comment by tamlok** [comment]
Oh, thanks for the bug report! I will fix it later! Thank you so much!

**Comment by tamlok** [comment]
By the way, for now you could change language from `System` to `English` in the `Settings`.

**Comment by tamlok** [comment]
Already fixed in (97721f3e9263d1b78b0cfc790319be664542dbc9). Thanks!
