### ISSUE TITLE
Update replaces settings

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1160]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现): I have to configuration files that I added some code to, as per #1037 and #1134.
When I updated from VNote 2.7.2 to 2.8.2 the two files were overwritten by the original files. Is there a way to avoid this?

How to Repro (如何复现):

**Comment by tamlok** [comment]
2 ways:

1. copy default theme and rename it as a new theme;
2. just copy the css style file and rename it. in vnote's markdown menu, you could specify your own style to use.

**Comment by DutchPete** [comment]
@tamlok 
I copied v_pure.css, renamed the copy to v_purePB.css, put it in the v_pure sub folder in the themes folder.
Then closed VNote, reopened VNote, but v_purePB is not listed in the Rendering Style list under Markdown.

Next effort:
I copied the whole v_pure folder, renamed it to v_purePB, closed VNote, put the v_purePB folder in the themes folder - see screenshot below. After opening VNote, v_purePB is still not listed.
<img width="567" alt="theme" src="https://user-images.githubusercontent.com/10794265/72091039-f40d5400-3317-11ea-8dab-6adb6ecf8fba.png">

I renamed the v_pure.css file in the v_purePB folder to v_purePB.css. Closed and reopened VNote, still no luck.

It is strange because when I added a theme folder before (can't remember which one, long time ago) it was listed immediately.

**Comment by tamlok** [comment]
Try: `Markdown menu` -> `Rendering Style` -> `Add Style` -> `Add Style` in the bottom right  corner, it should open the folder where you should put your style.

**Comment by DutchPete** [comment]
When I click on the `Add Style` button in the lower *left* corner, it open the `Styles` folder, which has nothing than an empty `codeblock_styles` subfolder. Anyway, I tried it, closed VNote and reopened, but my `v_purePB` style is still not listed.

**Comment by tamlok** [comment]
That style folder is only for `*.css` file, not a theme folder. Please read the documentation (theme and style are two different things).

https://tamlok.gitee.io/vnote/en_us/#!docs/Users/Themes%20and%20Styles.md

**Comment by DutchPete** [comment]
Yes that works.
What I still don't understand is that, having now selected `v_purePB`, it shows the anchors as per #1037 because that is the code I had added to it.

But in the TOC the bullets do not appear, which I am happy about but that code is not in `v_purePB`. Huh?

**Comment by tamlok** [comment]
I remember you put that in the `common.css`. Check it out.

**Comment by DutchPete** [comment]
Yes, you are right. But will that code be preserved in `common.css` if I do an update?

**Comment by tamlok** [comment]
I think so due to an update big.

**Comment by DutchPete** [comment]
OK, thanks a lot for your help :-))
