### ISSUE TITLE
非链接被强制识别为链接

### ISSUE THREAD

**Issue by rihalvnium76** [tamlok/vnote#1161]
OS Version (操作系统): Windows 10 1803 x64

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2 x64
MD代码：
```
- The library files (Library.lib for windows or libLibrary.a for \*nix)
- The binary files (Library.dll for windows or Library.so for \*nix)
```
阅读界面如下：
- The library files (Library.lib for windows or libLibrary.a for \*nix)
- The binary files (Library.dll for windows or ![Library.so](http://Library.so) for \*nix)

即Library.so被强制识别为超链接`http://Library.so`还无法解除
VNote似乎是缺乏严格语法模式

**Comment by tamlok** [comment]
这不是VNote的错。

library.so 也有可能是链接，所以就自动被识别为链接了。

你可以把下面菜单中的`linkify`去掉：

![image](https://user-images.githubusercontent.com/5763157/72198945-ebc82c80-346f-11ea-8a34-7f9dbd3efb65.png)

或者，对于这种特殊的文件名，最规范的就是用行内代码把它括起来，既省心又好看：

```
`library.so`
```

**Comment by rihalvnium76** [comment]
> 
> 
> 这不是VNote的错。
> 
> 首先，Markdown就没有严格的语法模式。
> 
> 其次，`library.so` 也有可能是链接（比如`github.cc`，你说是C++源文件还是一个域名），所以就自动被识别为链接了。
> 
> 你可以把下面菜单中的`linkify`去掉：
> 
> ![image](https://user-images.githubusercontent.com/5763157/72198945-ebc82c80-346f-11ea-8a34-7f9dbd3efb65.png)
> 
> 或者，对于这种特殊的文件名，最规范的就是用行内代码把它括起来，既省心又好看：
> 
> ```
> `library.so`
> ```

谢谢，你的回答解决了我的问题
