### ISSUE TITLE
cmake 编译错误，提示找不到 Qt5WebChannel

### ISSUE THREAD

**Issue by irreallich** [tamlok/vnote#1166]
OS Version (操作系统): Windows, Linux, macOS
ubuntu 18
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
last version of github
Symptoms (表现):

cmake version:
cmake version 3.16.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).

使用下面命令编译
```cmake  -DQt5_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5/ ../```
**log:**
>src/vnote/build$ cmake  -DQt5_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5/ ../
>CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
>  Could not find a package configuration file provided by "Qt5WebChannel"
>  with any of the following names:
>
>    Qt5WebChannelConfig.cmake
>    qt5webchannel-config.cmake
>
>  Add the installation prefix of "Qt5WebChannel" to CMAKE_PREFIX_PATH or set
>  "Qt5WebChannel_DIR" to a directory containing one of the above files.  If
>  "Qt5WebChannel" provides a separate development package or SDK, be sure it
>  has been installed.
>Call Stack (most recent call first):
>  CMakeLists.txt:15 (find_package)
>
>
> -- Configuring incomplete, errors occurred!

How to Repro (如何复现):

**Comment by tamlok** [comment]
@miurahr Could you help to take a look, please? Thanks!

**Comment by miurahr** [comment]
`sudo apt install    libqt5webchannel5-dev  `

**Comment by irreallich** [comment]
非常感谢

**Comment by miurahr** [comment]
Fix fixed please close here.

**Comment by irreallich** [comment]
又遇到新的问题
报告缺少
    Qt5WebEngineConfig.cmake
    qt5webengine-config.cmake

我尝试安装了sudo apt search libqt5web 给出的部分，都没有效果，同时我并没有找到类似libqt5webengine5-dev之类的库，如何将qt这些库装全？


$ sudo apt search libqt5web
Sorting... Done
Full Text Search... Done
libqt5webchannel5/bionic,now 5.9.5-0ubuntu1 amd64 [installed,automatic]
  Web communication library for Qt

libqt5webchannel5-dev/bionic,now 5.9.5-0ubuntu1 amd64 [installed]
  Web communication library for Qt - development files

libqt5webengine-data/bionic,bionic,now 5.9.5+dfsg-0ubuntu2 all [installed]
  Web content engine library for Qt - Data

libqt5webengine5/bionic,now 5.9.5+dfsg-0ubuntu2 amd64 [installed]
  Web content engine library for Qt

libqt5webenginecore5/bionic,now 5.9.5+dfsg-0ubuntu2 amd64 [installed]
  Web content engine library for Qt - Core

libqt5webenginewidgets5/bionic 5.9.5+dfsg-0ubuntu2 amd64
  Web content engine library for Qt - Widget

libqt5webkit5/bionic,now 5.212.0~alpha2-7ubuntu1 amd64 [installed,automatic]
  Web content engine library for Qt

libqt5webkit5-dev/bionic,now 5.212.0~alpha2-7ubuntu1 amd64 [installed]
  Web content engine library for Qt - development files

libqt5websockets5/bionic,now 5.9.5-0ubuntu1 amd64 [installed,automatic]
  Qt 5 Web Sockets module

libqt5websockets5-dev/bionic,now 5.9.5-0ubuntu1 amd64 [installed]
  Qt 5 Web Sockets module - development files

libqt5webview5/bionic 5.9.5-0ubuntu1 amd64
  display web content in a QML application - Library

libqt5webview5-dev/bionic 5.9.5-0ubuntu1 amd64
  display web content in a QML application - Development Files

hjwang@hjwang-home-ubuntu:~/work/download/tools/src/vnote/build$

**Comment by miurahr** [comment]
why don't you 
```
$ dpkg -S Qt5WebEngineConfig.cmake
qtwebengine5-dev:amd64: /usr/lib/x86_64-linux-gnu/cmake/Qt5WebEngine/Qt5WebEngineConfig.cmake

```

**Comment by irreallich** [comment]
又遇到新的问题
报告缺少
    Qt5WebEngineConfig.cmake
    qt5webengine-config.cmake

我尝试安装了sudo apt search libqt5web 给出的部分，都没有效果，同时我并没有找到类似libqt5webengine5-dev之类的库，如何将qt这些库装全


$ sudo apt search libqt5web
Sorting... Done
Full Text Search... Done
libqt5webchannel5/bionic,now 5.9.5-0ubuntu1 amd64 [installed,automatic]
  Web communication library for Qt

libqt5webchannel5-dev/bionic,now 5.9.5-0ubuntu1 amd64 [installed]
  Web communication library for Qt - development files

libqt5webengine-data/bionic,bionic,now 5.9.5+dfsg-0ubuntu2 all [installed]
  Web content engine library for Qt - Data

libqt5webengine5/bionic,now 5.9.5+dfsg-0ubuntu2 amd64 [installed]
  Web content engine library for Qt

libqt5webenginecore5/bionic,now 5.9.5+dfsg-0ubuntu2 amd64 [installed]
  Web content engine library for Qt - Core

libqt5webenginewidgets5/bionic 5.9.5+dfsg-0ubuntu2 amd64
  Web content engine library for Qt - Widget

libqt5webkit5/bionic,now 5.212.0~alpha2-7ubuntu1 amd64 [installed,automatic]
  Web content engine library for Qt

libqt5webkit5-dev/bionic,now 5.212.0~alpha2-7ubuntu1 amd64 [installed]
  Web content engine library for Qt - development files

libqt5websockets5/bionic,now 5.9.5-0ubuntu1 amd64 [installed,automatic]
  Qt 5 Web Sockets module

libqt5websockets5-dev/bionic,now 5.9.5-0ubuntu1 amd64 [installed]
  Qt 5 Web Sockets module - development files

libqt5webview5/bionic 5.9.5-0ubuntu1 amd64
  display web content in a QML application - Library

libqt5webview5-dev/bionic 5.9.5-0ubuntu1 amd64
  display web content in a QML application - Development Files

hjwang@hjwang-home-ubuntu:~/work/download/tools/src/vnote/build$
