### ISSUE TITLE
failed to create OpenGL context for format QsurfaceFormat

### ISSUE THREAD

**Issue by oceanlvr** [tamlok/vnote#1168]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2
Symptoms (表现):
* `OpenGL` 出现错误警告。
* 笔记本编辑模块加载速度变慢。

How to Repro (如何复现):

在 X64 版本下无法打开 `markdown` 文件，因此在尝试 #853 中的解决方案，将 `OpenGL` 选项修改为 `DesktopOpenGL`。该版本无效果，依然秒退。参考 #1068 后尝试下载 2.8.2 X86 版本，尝试以下步骤，出现了：

下载X86版本，依然无法正常显示编辑界面。尝试上述步骤，重置整个笔记本，并且修改 `OpenGL` 选项为非默认的选项后：

<div align=center><img src="https://user-images.githubusercontent.com/36698124/72326548-57b5c980-36ea-11ea-9832-dda3bb8a562e.png" width="50%" height="50%" >
</div>

出现以下错误：

<div align=center><img src="https://user-images.githubusercontent.com/36698124/72326089-75366380-36e9-11ea-97d7-f41332f7f2d5.png" width="50%" height="50%" >
</div>

问题：
能够正常打开笔记本界面。该问题需要解决吗？

**Comment by tamlok** [comment]
把所有值都尝试一遍看看。

**Comment by oceanlvr** [comment]
修改为 `OpenGLES` 后报错和卡顿消失，应该是硬件驱动问题。谢谢大佬。
