### ISSUE TITLE
为啥我macOS系统的，一打开VNote就直接闪退？

### ISSUE THREAD

**Issue by coder-zjh** [tamlok/vnote#1169]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现):一打开就闪退

How to Repro (如何复现):

**Comment by coder-zjh** [comment]
相同issue

**Comment by tamlok** [comment]
尝试`-m`看看。

**Comment by coder-zjh** [comment]
重启了就能打开了，如果还有相同问题，会尝试-m
