### ISSUE TITLE
请求添加新功能pandoc

### ISSUE THREAD

**Issue by youmoxiaozi** [tamlok/vnote#1175]
pandoc 是一个功能强大的格式转换工具希望能添加上，谢谢O(∩_∩)O

**Comment by tamlok** [comment]
请参考官方文档关于导出的部分说明，可以在自定义导出里面调用任意工具进行导出转换。

**Comment by ekoski1** [comment]
It would be especially useful to have the ability to use pandoc with a default command-line to process a selected note (or notebook?), and to be able to edit the pandoc command-line to provide different parameter-settings etc., and save the customized command-line. You seem to be pretty close to having this functionality already. (btw I wouldn't be commenting if I didn't already like VNote a lot.)
