### ISSUE TITLE
求助：想用正则表达式在每行头添加文字

### ISSUE THREAD

**Issue by youmoxiaozi** [tamlok/vnote#1187]
A干姜片200G
V花椒180G
A小茴香120G
H草果，桂皮各100G
F胡椒90G
D沙姜，肉蔻各50G

在行首添加 文字

1，正则 “^” 没起作用 ,我应该怎样写？

2，“ ^[a-z]  ” 能匹配到行首字母。

**Comment by tamlok** [comment]
在每一行前面添加一个`B`：

![image](https://user-images.githubusercontent.com/5763157/73627437-b0440b00-4687-11ea-92e5-985a634a51c3.png)
