### ISSUE TITLE
建议增加全文检索功能

### ISSUE THREAD

**Issue by fanrongqitiancai** [tamlok/vnote#119]
当笔记达到一定数量后，通过全文检索来搜索笔记是一个十分实用的功能，希望作者能够采纳。谢谢。

**Comment by hongbin0908** [comment]
同样建议

**Comment by tamlok** [comment]
@fanrongqitiancai @hongbin0908 Hi, 全文查找会在下两个版本之内实现。谢谢！

**Comment by tamlok** [comment]
1.13已经实现了！
