### ISSUE TITLE
Folder and file not shown

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1192]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现): I created a new root folder, and into that I copied existing files and subfolders from a folder that is external to VNote.

All the files are shown in the root folder and are accessible, but only 1 out of 2 subfolders is shown, and in that 1 visible subfolder only 1 file out of many is shown.

When I use macOS's file explorer (called "Finder") both subfolders and all the files in them are present.

How can I make everything visible?

How to Repro (如何复现):

**Comment by DutchPete** [comment]
Am I missing something or is this a bug?

**Comment by tamlok** [comment]
VNote uses `_vnote.json` file to track subfolders and files. You need to add it to the json file manually after adding external files and folders.

**Comment by DutchPete** [comment]
@tamlok : OK, I understand. That is a long-winded way of doing it, which basically tells me that I should not do a manual copying of files and folders.

So, I deleted those things and started from scratch. I created a root folder, then, from the menu, did File > New Notes From Files, then you can select external files that will then be copied over to VNote. Similarly, I created subfolders, and did the same steps from the menu.

1 question I still have: I also created an "attachments" and an "images" files, then did the same menu steps. That worked well. But the files in those 2 folders are non-markdown files, they are png, pdf, docx, and such like. The question I have is: is there any advantage to have the 2 folders with non-markdown files in VNote, or could I just have those  folders sitting somewhere on my hard drive outside VNote?

**Comment by tamlok** [comment]
VNote has its own way to add attachments to a note. Why not use it? And VNote will also manage the images files when you insert them. You could new a test note and insert some images and check the file structure to know how VNote works.

**Comment by DutchPete** [comment]
I understand VNote has its own way, but is there an advantage to use the VNote way?

Furthermore, I am in a situation where I already have a large number of images and attachments related to the .md files I imported into VNote. Is there a method to add them to the .md files imported into VNote? Or would I have to do that 1 by 1?

**Comment by tamlok** [comment]
For attachments, you could add files by the toolbar:

![image](https://user-images.githubusercontent.com/5763157/73989623-673ed000-4981-11ea-8e1c-6ca4b6425c2f.png)

Since VNote uses plain text to track all data, you could always do anything on your own way if you know VNote's way well. Otherwise, you should just obey to VNote's way and use what VNote has provided.

**Comment by DutchPete** [comment]
OK, thanks.
