### ISSUE TITLE
Image Preview Size

### ISSUE THREAD

**Issue by vmexia** [tamlok/vnote#120]
This is more of a request, bare with me. I'm a heavy user of print screens for contextualization within text notes, and to be able to show them directly on the note its awesome in terms of productivity. The problem, for me, its the size taken by the image inside the note. I find that it occupies too much space, more than necessary most of the time. I guess that the preview is being set based on the image resolution. It would be awesome if we could choose the size of the preview or even have it as a link that we could just hover/click  it to get the full picture. Thanks for your time

**Comment by tamlok** [comment]
Hi, you could now constrain the width of the image to the edit area in both read and edit mode. In the `Markdown` menu, click `Constrain The Width Of Images` and `Constrain The Width Of Previewed Images` to enable it. It only affect the view of the images and won't compress them.

To support resizing images needs lots of code changes. We will look back to it in near future. :)

Thanks!

**Comment by wyhhh** [comment]
supply image:
![image](https://user-images.githubusercontent.com/28824519/38404621-e938b85a-399d-11e8-9f1b-0786c8e20839.png)

**Comment by tamlok** [comment]
Hi,

After checking the following two options, the image size will be constrained to the width of the edit window.

![image](https://user-images.githubusercontent.com/5763157/38414685-c3fd77dc-39c1-11e8-9e45-9808acb38e9f.png)

Thanks!

**Comment by tamlok** [comment]
Support specifying image size now (https://github.com/tamlok/vnote/issues/222).

Thanks!
