### ISSUE TITLE
一行的末尾，会有半个文字被遮挡

### ISSUE THREAD

**Issue by shangleixun** [tamlok/vnote#1201]
OS Version (操作系统): macOS Catalina 10.15.3

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现): 编辑时，一行文字的末尾，会有半个文字被下拉的指示条所在的底部视图遮挡。

How to Repro (如何复现): 打一行或者复制一行文字，超过一行的宽度，就能复现了。
<img width="121" alt="截屏2020-02-13上午9 17 33" src="https://user-images.githubusercontent.com/20725011/74392314-acf80e80-4e41-11ea-8e96-f7df49b81a37.png">

**Comment by tamlok** [comment]
搜一下已经关闭的issue中，关键字: mac 滚动条

设置一下即可
