### ISSUE TITLE
Feature Requests: 增加图片操作功能

### ISSUE THREAD

**Issue by heyizhang** [tamlok/vnote#1207]
OS Version (操作系统): Windows10
VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Feature Requests:
右键菜单上增加图片操作功能：打开图片本地位置

例如：![ imga](_v_images/20200215164526078_20648.png)， 当光标在改行，或者选中_v_images/20200215164526078_20648.png   时，右键菜单上希望可以增加：
1. 打开图片的本地位置功能（ Typora 已经有了，可以参考emm）

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/74585291-0ca71300-5016-11ea-8c35-f27391aa9ed3.png)

**Comment by heyizhang** [comment]
好的，好的。多谢老大。
