### ISSUE TITLE
一个排序的bug，排序无效果

### ISSUE THREAD

**Issue by ma3252788** [tamlok/vnote#1212]
OS Version (操作系统): Windows, Linux, macOS 
Win10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.8.2

Symptoms (表现):
排序无效果

How to Repro (如何复现):
直接进行排序，没有效果，设置过很多次，不行。并且，重启也不行。见下图：

![](https://ypyssl.machunjie.com/machunjie/20200218154012.png)

**Comment by tamlok** [comment]
Hi,

大眼睛那里请勾选`View By Configuration File`.

![image](https://user-images.githubusercontent.com/5763157/74716428-81be5680-5269-11ea-9164-33765a55bb04.png)

**Comment by ma3252788** [comment]
> Hi,
> 
> 大眼睛那里请勾选`View By Configuration File`.
> 
> ![image](https://user-images.githubusercontent.com/5763157/74716428-81be5680-5269-11ea-9164-33765a55bb04.png)

解决了，谢谢~
