### ISSUE TITLE
Ubuntu18下卡死

### ISSUE THREAD

**Issue by platinhom** [tamlok/vnote#1213]
OS Version (操作系统): Ubuntu 18.04, Unity系桌面

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8, 二进制文件

This program uses Qt version 5.9.7.

Symptoms (表现):

经常性出现卡死. 主要表现是编辑模式时(如图) 无法动弹, 也不进行Markdown渲染了.. 

![image](https://user-images.githubusercontent.com/3596077/74725964-a1f61180-5279-11ea-8b39-b8b508b28b27.png)

请问怎么能看到Vnote的错误日志啥的或者如何排查这种问题?

How to Repro (如何复现):

- 有时候我在搜索到的文件上双击打开, 就会出现卡死, Vnote菜单那些都有反应, 就是界面上无法编辑, 无法动弹. 只能关闭掉VNote再打开就好了. 
- 怀疑时搜狗拼音的锅, 这货在ubuntu经常各种问题, 但暂无证据..

**Comment by tamlok** [comment]
Hi,

1. 同一篇笔记会总是卡死吗？还是概率性？
2. 阅读模式打开，不会发生卡死?如果只有编辑模式会卡死，那很大概率是输入法的问题。
3. 用的是官网下载的AppImage吗？

**Comment by platinhom** [comment]
@tamlok 跟笔记无关, 会卡死的时候就算重开也会经常卡. 有时又会一段时间都不出现. 现在设置了阅读模式打开貌似没有问题了, 好像是编辑模式打开时才会莫名其妙卡住. 我怀疑是搜狗输入法的锅, 有一次搜狗也同时崩了, 重新打开搜狗后一段时间就不出现卡死.  github release下的appimage二进制文件.

**Comment by tamlok** [comment]
那只能换输入法测试一下了。

**Comment by platinhom** [comment]
@tamlok 使用阅读模式还是会卡死. 改用sunpinyin (fcitx的) 还是会卡死. 让人崩溃啊啊啊...

**Comment by tamlok** [comment]
是NVIDIA显卡吗？

**Comment by platinhom** [comment]
@tamlok 是的, QuadroP2200, 显卡版本440.44

**Comment by tamlok** [comment]
参考一下以下issue？可能是显卡驱动问题。

https://github.com/tamlok/vnote/issues?q=is%3Aissue+is%3Aclosed+nvidia


可以在帮助菜单里面查看日志文件。

**Comment by platinhom** [comment]
```
Warning:(:0) QXcbClipboard: SelectionRequest too old
```

不断出现这个, 再往上的时就就太早了

**Comment by platinhom** [comment]
@tamlok 解决不了, 为了vnote我卸了unity改用了KDE. 问题消失了. :man_facepalming:
