### ISSUE TITLE
How about supporting Vim e command (提供Vim的e命令)

### ISSUE THREAD

**Issue by MrHate** [tamlok/vnote#1217]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

--------

Vim mode without `:e` command seems to be strange and a less convenient.

既然vnote支持vim模式，那常用的`:e`命令的缺失在某种程度上会使得vim模式下的操作有些别扭

**Comment by tamlok** [comment]
e 对应的当前工作目录是什么呢？如果是当前文件夹或者当前笔记本的话，其实ctrl-g 就可以做到呀。

**Comment by MrHate** [comment]
主要是若是在文档里都注明了要实现vim模式的话，光是普通的插入替换和hjkl大概是无法满足vim使用者的需求的，还是需要尽可能的实现vim中的大部分快捷键这样，当然也不是要一定完全按照vim的做，因为不同的环境有更适合的解决方案。

**Comment by tamlok** [comment]
https://github.com/tamlok/vnote/pull/1218
