### ISSUE TITLE
图片文件夹的路径中包含空格时，图片无法显示

### ISSUE THREAD

**Issue by undermyowwnmoon** [tamlok/vnote#1219]
OS Version (操作系统): Windows
VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现):
图片文件夹的路径中包含空格时，图片无法显示；删除掉空格后就能正确显示图片

How to Repro (如何复现):

**Comment by tamlok** [comment]
url标准里面空格需要使用`20%`进行替代，可以直接在vnote里面插入图片，vnote会自动处理好，无需手工干预。

**Comment by undermyowwnmoon** [comment]
不是url了，是本地图片的链接，比如图片都放在 `SpyGlass  教程.assets` 这个文件夹中，如果插入这个文件夹中的图片，例如`![](SpyGlass  教程.assets/image-20200206130011525.png)`，就不能正常显示。
当删除文件夹名和图片链接中的空格后，比如 `SpyGlass教程.assets`，图片就能正常显示。

**Comment by tamlok** [comment]
图片链接括号里面的就是url，试试替换成20%即可

**Comment by undermyowwnmoon** [comment]
解决了，谢谢~ 加上`%20`后在Vnote和Typora都能正常显示图片。
作为一个FPGA工程师，一直把URL当做网络资源的链接，惭愧中。。。。
