### ISSUE TITLE
PDF Export margin = 0

### ISSUE THREAD

**Issue by ikelaiah** [tamlok/vnote#122]
Export to PDF works well. But the margin defaults to 0 and I was unable to change it.
Could you help?

Thanks!

**Comment by tamlok** [comment]
Thanks for feedback! I am working on refractoring the export module. I will look into it.

**Comment by tamlok** [comment]
It is a bug. Already fixed in dev branch. BTW, VNote will support exporting PDF via wkhtmltopdf tool, which enable rich options.

Thanks!
