### ISSUE TITLE
有自动保存的功能不

### ISSUE THREAD

**Issue by nashera** [tamlok/vnote#124]
经常忘记保存，心塞。

**Comment by tamlok** [comment]
Hi, 您担心的是程序突然崩溃或者关机吗？VNote采用Vim类似的交换文件，会定期将文件的更改保存到一个临时文件中。如果打开一个文件的时候发现存在交换文件，会提示用户注意恢复。这基本能保障未保存的数据不会丢失。

**Comment by nashera** [comment]
在用两台电脑， 文件同步，忘记保存，而导致文件不同步，如果能自动保存，就很好了，而不是使用交换文件。
最好和vim一样，有这样的选项

**Comment by tamlok** [comment]
了解！后面有时间我把这个加上。

**Comment by tamlok** [comment]
已经加上了(4bcb60e90390ca81b61b9c08d3a1d1639a5fef67)，下一个版本带上。

**Comment by nashera** [comment]
非常非常感谢, 还有配置文件, 有可能和启动文件放在同一个目录吗? 这样重装系统后, 配置文件就不会被删除了

**Comment by tamlok** [comment]
Hi, VNote将会支持优先读取可执行文件所在目录的`vnote.ini`配置文件，所以只需要把`vnote.ini`和`session.ini`拷贝到`VNote.exe`所在目录，VNote就会使用当前目录作为配置文件夹。

但是，建议还是程序和数据分离比较好。
