### ISSUE TITLE
[Bug Report] 列表高亮必须有前置空行

### ISSUE THREAD

**Issue by laggardkernel** [tamlok/vnote#1242]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现):

与渲染无关，只是编辑时的高亮问题。列表语法必须在第一个列表前加空行，编辑框内才会有高亮。

```markdown
Paragraph. （此时下边的列表语法符 `-` 不会有高亮，需要在本行后加空行）
- abc
- def
```

**Comment by tamlok** [comment]
Hi,

VNote的编辑器部分采用的是比较严格的一个语法分析，要求列表元素之前得有一个空行或者是一个块元素（例如标题）。

为了兼容性，一般建议md得元素之间都用空行分隔一下。
