### ISSUE TITLE
编辑笔记时图片的出现时机

### ISSUE THREAD

**Issue by feloxx** [tamlok/vnote#1244]
OS Version (操作系统):

win7 sp1

VNote Version (Help - About VNote - Version: )(VNote版本):

2.8.2

---

在笔记编辑的时候,如果我添加了图片,在使用vim进行上下移动时

如果要经过图片,怎么不让`整个突然出现`,而是`逐步出现`就像鼠标滚轮那样滚动.

这样的目的是能让图片的出现时机比较柔和点,而不是突兀的一下闪现出来

**Comment by tamlok** [comment]
Hi,

因为Vim里面j/k就是挪动光标上下一行，类似于Vim里面移动到一行非常长的一行一样。可以尝试`Ctrl+J/K`。

**Comment by feloxx** [comment]
好的,谢谢老哥
明白意思了
