### ISSUE TITLE
编辑模式下代码块对markdown heading 语法也进行渲染

### ISSUE THREAD

**Issue by violetu** [tamlok/vnote#1245]
OS Version (操作系统): 
manjaro Linux

VNote Version (Help - About VNote - Version: )
(VNote版本): 2.8.2

Symptoms (表现):
在代码块中使用 `# `等会导致其在编辑模式下显示为标题，虽然预览模式下，完好，但是希望能改进一下。

How to Repro (如何复现):
比如：
```
# gitee and github
# 注意：多个Host公用一个公钥时，
# 对应的HostName和Port必须跟在Host后面
    Host gitee.com
```
![image](https://user-images.githubusercontent.com/33022132/76671906-12235900-65d4-11ea-9fd9-742a8c163921.png)

**Comment by tamlok** [comment]
Hi，

第8行，也就是代码块的开始标记那一行，请在前面添加一个空行即可，谢谢！

严格一点的Markdown语法要求如果前面不是块元素，需要使用空行分隔。

**Comment by violetu** [comment]
好的，谢谢大大
