### ISSUE TITLE
macOS 10.14 和10.15系统下无法打开

### ISSUE THREAD

**Issue by superleeyom** [tamlok/vnote#1249]
OS Version (操作系统): macOS 10.14.5 和 macOS 10.15.3

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现): 我公司的电脑是10.14，家里的电脑是10.15，刚开始的时候是能正常使用，但是隔了一段时间，无法点击打开 vonte，在dock栏上一直跳，一直跳，但是如果用命令：`/Applications/VNote.app/Contents/MacOS/VNote -m` 就可以打开，已经很影响使用了，不知道是什么问题，即使我重新卸载重装，也是一样，刚开始没问题，过段时间就出问题，我公司的电脑是黑苹果系统，家里的是白苹果，15款13寸的mbp，vnote是个好产品，但是这个问题让人很困扰，还希望作者能尽快查看下是什么问题，我可以帮忙配合；

How to Repro (如何复现):
点击vnote，无法打开，比如在终端使用：`/Applications/VNote.app/Contents/MacOS/VNote -m`打开；

**Comment by tamlok** [comment]
就是因为创建共享内存出现问题，VNote通过共享内存来检测多个实例。后面我尽快修复一下。

**Comment by superleeyom** [comment]
@tamlok 期待新版本发布

**Comment by tamlok** [comment]
应该修复了，可以下载这里的最新构建版本试一下： https://bintray.com/tamlok/vnote/vnote/2.8.2#files

**Comment by superleeyom** [comment]
@tamlok 好的，谢谢，先试试看，有问题再反馈给你
