### ISSUE TITLE
建议在arch aur里加个vnote-bin的版本

### ISSUE THREAD

**Issue by amitbha** [tamlok/vnote#125]
安装 vnote-git 时发现 qt5 的编译依赖体积挺大，如果能直接使用编译好的程序就更方便了。
可以直接下载 appimage，再加上 desktop integration 的一些文件即可。

**Comment by tamlok** [comment]
打包这块我不太熟悉，可能得向[ArchLinuxCN](https://github.com/archlinuxcn/repo)提Issue。

谢谢！

**Comment by amitbha** [comment]
好
