### ISSUE TITLE
显示其他格式的文件

### ISSUE THREAD

**Issue by feloxx** [tamlok/vnote#1256]
现在在 `笔记` 处,只能显示 `.md`格式的文件, 有什么办法做到 `仅显示` 其他格式的笔记吗?

比如 txt

vnote不好解析的话,可以先只是显示,然后调用其默认的`打开方式`

**Comment by tamlok** [comment]
后面新版会类似于代码编辑器一样，支持语法高亮编辑代码文件。效果图：

![image](https://user-images.githubusercontent.com/5763157/77245904-56120000-6c5d-11ea-805c-34958266c16d.png)

**Comment by feloxx** [comment]
嘿嘿,我也正有此意,vim智能模式太牛逼了
希望到时候,还能支持打开`脑图`和`图片`,可以就只是显示文件的列表,然后用默认的打开方式打开就行
