### ISSUE TITLE
Change Style of Markdown

### ISSUE THREAD

**Issue by barbedCoil** [tamlok/vnote#126]
Is there a way to alter the style of the Markdown?  For instance, the font size for the Code Block seems rather large.

I would like to be able to alter the font-size of some of the Markdown 'tags' so I can see more in the editing window.

Thoughts?

**Comment by tamlok** [comment]
Hi,

I just wrote the doc about [Themes and Styles](http://vnote.readthedocs.io/en/latest/user_docs/themes_and_styles.html#syntax-of-mdhl-file).

You need to copy the `mdhl` file from default theme and put it to the `styles` folder in the configuration folder. Add one line in the `VERBATIM` element:

```
font-size: -2
```

For now, there is a bug I need to fix to make it work. So please wait for next version. :)

**Comment by barbedCoil** [comment]
This is excellent. I'll look for the next build to give it a try.
Thanks!

**Comment by barbedCoil** [comment]
Great changes, excellent work!

**Comment by tamlok** [comment]
v1.12 has been released! Now VNote will ouput the built-in themes in the configuration folder. You could copy and tweak it easily. Enjoy!

**Comment by barbedCoil** [comment]
Perfect! Thanks much.
