### ISSUE TITLE
如果有网络剪辑就更好了

### ISSUE THREAD

**Issue by plus-zhang** [tamlok/vnote#1263]
如果能通过chrome插件, 把剪辑的文章或者博客保存到本地就太完美了

OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):

**Comment by tamlok** [comment]
现在可以直接复制网页内容，在VNote里面右键菜单，解析为Markdown并粘贴，即可。

**Comment by plus-zhang** [comment]
> 现在可以直接复制网页内容，在VNote里面右键菜单，解析为Markdown并粘贴，即可。

配合web clipping 还真不错, 谢谢~
