### ISSUE TITLE
希望新增引用按钮以及允许代码块自动换行

### ISSUE THREAD

**Issue by molkes** [tamlok/vnote#1268]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

请求:

1. 希望新增引用按钮
2. 希望允许代码块自动换行

目前进行块引用，必须在每一行前加`>`。或者使用HTML 的`<blockquote>`标签

```
<blockquote>
xxx
xxxx
</blockquote>
```

代码块不自动换行的话，浏览很不方便。

因为缺了这两项内容，所以只好用Typora来补足。

**Comment by tamlok** [comment]
Hi,

1. 剪切需要变成块引用的文本，然后右键菜单，粘贴为块引用；
2. 请自定义CSS样式文件里面关于`pre`和`code`的换行属性即可，具体请参考文档。

谢谢！

**Comment by molkes** [comment]
嗯，解决了。根据文档，复制原主题的渲染样式（比如`v_pure.css`）到`styles/codeblock_styles`并取消只读属性，将其中的`pre code`的`white-space: pre;`改为`white-space: pre-wrap;`
