### ISSUE TITLE
渲染流程图失败

### ISSUE THREAD

**Issue by murphys1989** [tamlok/vnote#127]
勾选了 flowchart.js，关闭标签页重新打开进入阅读，仍然没有流程图。
版本：window1.11.1x64

**Comment by tamlok** [comment]
hi，代码块标明语言`flowchart`了吗？

**Comment by murphys1989** [comment]
因为之前用的是cmd markdown，代码块标明语言都是用flow。现在改成flowchart，就可以了。谢谢啦，软件很不错。
