### ISSUE TITLE
winx64版本 vim 模式下打中文界面卡死

### ISSUE THREAD

**Issue by ifnk** [tamlok/vnote#1275]
OS Version (操作系统): Windows10 1909
VNote Version (Help - About VNote - Version: )(VNote版本): VNote_win_X64_portable_2.9

Symptoms (表现): 在 开启vim 模式下，打 开md 文件，切换输入法到中文(我是用的小鹤双拼) 界面 就卡死未响应……
![dwm_dXuIXW8hMY](https://user-images.githubusercontent.com/39295458/77839387-d29d6500-71ae-11ea-9ecf-7b87052fb09e.png)

How to Repro (如何复现):每次都这样 ，作者可以尝试下……

**Comment by tamlok** [comment]
是什么输入法呢？

可以参考置顶Issue看一下是不是显卡驱动的问题。

https://github.com/tamlok/vnote/issues/853

**Comment by ifnk** [comment]
> 是什么输入法呢？
> 
> 可以参考置顶Issue看一下是不是显卡驱动的问题。
> 
> #853

谢谢 作者 ， 我 在设置里面 把openGl 更换 成 OpenGLES 选项 就行了， 我是 i3 8100 的cpu Amd hd6700 的显卡 ,那应该是 显卡驱动 的问题了！
