### ISSUE TITLE
已经插入后的图片如何再修改其大小（并且该图片已经在github上同步）

### ISSUE THREAD

**Issue by One010101** [tamlok/vnote#1276]
OS Version (操作系统): Windows,

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):

**Comment by tamlok** [comment]
按照帮助菜单里面的Markdown语法指南通过语法修改呈现大小即可：

![image](https://user-images.githubusercontent.com/5763157/77839810-efd43280-71b2-11ea-91d4-d979f1ac9b23.png)

**Comment by One010101** [comment]
比如说这个
![示例图片](https://raw.githubusercontent.com/用户名/仓库名/master/示例图片.png)
我该怎么添加限制宽高代码

**Comment by tamlok** [comment]
```
![示例图片](https://raw.githubusercontent.com/用户名/仓库名/master/示例图片.png =800x600)
```

**Comment by One010101** [comment]
谢谢，学到了！

**Comment by tamlok** [comment]
多看看帮助菜单的语法帮助，都写得很详细。
