### ISSUE TITLE
VNote使用ibus中文输入法光标错误

### ISSUE THREAD

**Issue by leemeans** [tamlok/vnote#128]
### 问题描述
我使用Ubuntu 16.04和Gnome界面，在使用VNote时非常舒服，好评。

但是我现在发现了在使用ibus的Rime输入法进行输入的时候会发生一些让人恼火的事情：

在我输入一两个词语之后，发现拼音是错误的，然后我删除了所有输入的拼音，然后我的光标突然就不见了，而变成了我最后删除的拼音对应的候选文字。同时我用backspace键也会把这个文字当作光标，直到我再次输入另一个文字（这时代表光标的文字会被覆盖）或者切换程序窗口（这时代表光标的文字会变成已经输入的文字，可以被删除）。

**Comment by tamlok** [comment]
Hi, 请问您是下载AppImage的吗？其他基于Qt5的程序有没有这个问题呢？我这边Fcitx测试没有问题，我会尝试重现这个问题。

谢谢！

**Comment by leemeans** [comment]
我用源码编译的

**Comment by leemeans** [comment]
```
cd vnote.git
mkdir build
cd build
qmake ../VNote.pro
make
sudo make install
```
我是像上面这样按照文档编译的,我的qt版本如下：
```
QMake version 3.1
Using Qt version 5.9.1 in /home/lee/Qt5.9.1/5.9.1/gcc_64/lib
```
另外，我用的是ibus，所以Fcitx就没管了。

**Comment by tamlok** [comment]
OK，了解了。我后面找个虚拟机试试。

谢谢！

**Comment by leemeans** [comment]
:smile:

**Comment by tamlok** [comment]
Hi，已经知道问题了，设置一下ibus即可。

通过命令`ibus-setup`打开ibus设置界面，将`Embed preedit text in application window`去掉勾选即可。

![image](https://user-images.githubusercontent.com/5763157/37769950-be816828-2e0d-11e8-93a6-3d69d1235e07.png)

谢谢！

**Comment by leemeans** [comment]
了解，谢谢

**Comment by piedgogo** [comment]
Win7 64 位下面，使用 Google 拼音，出现类似问题。下载的官方二进制文件。

在中文输入时，我发现我输错了拼音，使用 backspace 删除，再输入正确拼音，然后选择要输入的字，结束输入。
结束输入后，光标就不见了。
使用鼠标选择编辑位置，可以正确的在选中位置插入文字，但是仍然没有光标。
关闭文档再打开，又恢复了。

**Comment by tamlok** [comment]
Hi, @piedgogo 请参考这个issue https://github.com/tamlok/vnote/issues/133
