### ISSUE TITLE
38KB大小的md文件打开出现无响应

### ISSUE THREAD

**Issue by yeylcode** [tamlok/vnote#1287]
OS Version (操作系统): Windows 10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现):打开一笔记文档，大小在38KB，vnote无响应，内存占用大概上升到200M以上，CPU占用率升高

![image](https://user-images.githubusercontent.com/29844001/78010128-9582cf80-7374-11ea-9fa9-06a6fd190be6.png)

以右键编辑模式打开，能显示文字，但也是程序无响应，无法编辑
![image](https://user-images.githubusercontent.com/29844001/78010823-64ef6580-7375-11ea-935d-d12d1a8948ca.png)

文件字数2.4万字
![image](https://user-images.githubusercontent.com/29844001/78010948-8ea88c80-7375-11ea-810d-2fbdc485cf30.png)

How to Repro (如何复现):

**Comment by tamlok** [comment]
32K大小的文件VNote还是能够轻松处理的。如果该文件不是VNote编辑生成的，出现无响应的原因，有可能是因为md里面某些元素不符合语法规定或者有特殊不可见字符。

1. 正常文件是否能正常打开？如果不正常，可以考虑置顶issue的显卡问题；
2. 用Vim等打开看一下是否有不可见字符（特别是VSCode编辑过来的）；
3. 二分排查一下语法问题；

**Comment by yeylcode** [comment]
ok，多谢。问题已经解决，文档中混入了不可见字符导致的
![image](https://user-images.githubusercontent.com/29844001/78027449-f5d33a80-738f-11ea-8364-fa4ad9e0aa9e.png)
![image](https://user-images.githubusercontent.com/29844001/78027472-fe2b7580-738f-11ea-8716-3a7272eb9fdc.png)
