### ISSUE TITLE
希望第二次ctrl+b能取消粗体

### ISSUE THREAD

**Issue by pisces312** [tamlok/vnote#129]

**Comment by tamlok** [comment]
Hi, 目前是`Ctrl+B`会添加4个`*`，然后如果没有任何输入，再按`Ctrl+B`，则会删除这4个`*`；如果有其他输入，则`Ctrl+B`会跳过后面的两个`*`，表示结束加粗输入。因为加粗的符号标记是可以跨行的，所以目前检测当前光标是否在一个加粗标记之内还有点难度，后面有时间会看一下当光标位于加粗标记之内，且不是临近结束标记的时候，再按一次`Ctrl+B`取消加粗。

谢谢！

**Comment by pisces312** [comment]
谢谢及时回复。还有两个小建议：
- 允许方便的设置图片的缩放大小，如通过扩展语法等方式。
- 编辑模式下也能用鼠标滚轮调整字体。

**Comment by tamlok** [comment]
- 图片缩放后面会看一下，主要是不太想引入过多的扩展语法，将Markdown弄得太复杂；
- 编辑模式下调整字体大小已经实现了，v1.12会带上。

谢谢！

**Comment by amitbha** [comment]
pandoc 支持图片缩放语法，可以参考一下
