### ISSUE TITLE
有的时候在编辑模式下预览公式和图片是正确的，但是阅读模式下却不能正常显示

### ISSUE THREAD

**Issue by Ce1este** [tamlok/vnote#1295]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
编辑模式：
![image](https://user-images.githubusercontent.com/51806751/78454207-3f41c380-76c9-11ea-8d44-352f2a03a248.png)
阅读模式：
![image](https://user-images.githubusercontent.com/51806751/78454216-48329500-76c9-11ea-930a-4b50f7e69a70.png)

编辑模式：
![image](https://user-images.githubusercontent.com/51806751/78454224-54b6ed80-76c9-11ea-9b59-5cc515d68e04.png)
阅读模式：
![image](https://user-images.githubusercontent.com/51806751/78454229-5b456500-76c9-11ea-848a-c75440c9cb84.png)

How to Repro (如何复现):
在别的编辑器写好的Markdown文档直接复制到Vnote中或者选择“从文件新建笔记“发生这种情况的几率比较大

**Comment by Ce1este** [comment]
我在反复尝试发现了一些规律：
有的时候`$a<b$`这种写法不被识别，而却会牵连到它之前的公式
改成`$a < b$`就好了

**Comment by tamlok** [comment]
因为其他编辑器的语法不标准？图片那个，url可能不符合规范，试试/而不是\。

**Comment by Ce1este** [comment]
今天试了一下，图片的问题确实是斜杠的问题，谢谢作者大大啦=）
