### ISSUE TITLE
macos无法打开2.9版本

### ISSUE THREAD

**Issue by dongxurr123** [tamlok/vnote#1298]
OS Version (操作系统): macOS Mojave 10.14.6

VNote Version : 2.9-x64

Symptoms (表现):
打不开，双击启动后，图标一直在launchbar上跳动，过大概一分钟后停止。一直无界面弹出。
不知道是否因为macos加入了公司域的原因。

How to Repro (如何复现):
启动必现

**Comment by dongxurr123** [comment]
今天下载了 2.7.1 版本，可以使用。

**Comment by tamlok** [comment]
请下载2.9.1试一下，应该修复了。

**Comment by dongxurr123** [comment]
> 请下载2.9.1试一下，应该修复了。

赞赞赞~ 已经可用了，修复真快！
