### ISSUE TITLE
可以增加对markdown preview enhanced支持吗？

### ISSUE THREAD

**Issue by ToughLife** [tamlok/vnote#1299]
作者你好，非常感谢你的辛苦付出。
我是Latex的重度使用者，经常会使用tikz来进行绘图。
请问，在markdown的渲染结果中，是否可以考虑增加
[Markdown Preview Enhanced](https://github.com/shd101wyy/markdown-preview-enhanced)中提出的 [Code Chunk](https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/code-chunk)功能？这样可以方便地使用诸如latex、gnuplot等工具来增强markdown渲染结果。谢谢。

**Comment by RyanGreenup** [comment]
TikZ is really good but it's a shame it's only really implemented through <b>L</b><sup>a</sup><b>T</b><sub>e</sub><b>X</b>.

[Here's a good post](https://castel.dev/post/lecture-notes-1/) on using [InkScape](https://inkscape.org/) with Vim, maybe you could find it helpful.

**Comment by ToughLife** [comment]
@RyanGreenup Thanks for the valuable comment. Very useful.
