### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [tamlok/vnote#131]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [VInsertImageDialog](https://github.com/tamlok/vnote/blob/c9b1801a5a47e360109f973b63fc9f0ff5e40e54/src/dialog/vinsertimagedialog.cpp#L55 "Destructor for VInsertImageDialog")
- [VTextEdit](https://github.com/tamlok/vnote/blob/b1f7760ea24a8e45dafbe1f9e7107fd812df23d7/src/vtextedit.cpp#L37 "Destructor for VTextEdit")

**Comment by tamlok** [comment]
Thanks! I need to refresh my C++ knowledge since coding with C for years. Pull Requests are welcome if you have interest in VNote. :)

I will fix this later.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/tamlok/vnote/commit/6d24f7e92bb2554d3ad2ae9b1a9b68714a64b5ac "Remove unnecessary NULL check before delete").
