### ISSUE TITLE
大纲显示的问题

### ISSUE THREAD

**Issue by jackydi** [tamlok/vnote#1318]
OS Version (操作系统): Windows 10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现):

看下面的图片，这是大纲中显示的，标题字体大小不一样，因为标题的长短不一样。短标题字体大，长标题字体小，看起来很不舒服，能不能显示成一样的字体？不行就加个滚动条呗，也比现在这样的好看。

<img width="134" alt="2020-04-16_08-54-57" src="https://user-images.githubusercontent.com/50565266/79402988-233efb80-7fc0-11ea-9357-8211f6d81a8e.png">

How to Repro (如何复现):

**Comment by tamlok** [comment]
什么系统？什么主题？是否是字体问题？

我的效果：

![image](https://user-images.githubusercontent.com/5763157/79403647-102d2b00-7fc2-11ea-9ebf-5e5406278e47.png)

**Comment by jackydi** [comment]
主题：v_pure，win10系统。

笔记本外接一个显示器作为主显示器用。笔记本自带显示器为150%模式显示，外接显示器为100%模式显示，二者最大分辨率相同，都是1920x1080。这是在外接显示器上出的这个问题，编辑模式下。

应该不是字体问题，**如果向左拖动边框的话，超过一定距离（差不多长标题也能以大字体完整显示的时候）长标题就变成大字体了，向右拖动边框的时候，超过一定距离，本来是大字体的标题也变成小字体了。**

刚刚把vnote拖到笔记本显示器上，发现问题没有了，再拖回到外接显示器上，问题也没有重新出现。不知道咋回事儿？

期间没有其他操作，感觉还是软件显示的问题。

**Comment by jackydi** [comment]
主题从来没改过，应该就是默认的。

**Comment by tamlok** [comment]
如果两个缩放系数不一样，那vnote可能有点问题，qt的通病。最好用哪个显示器，就在那个显示器上启动vnote。

**Comment by jackydi** [comment]
好的，只是看起来不好看而已，不耽误使用
