### ISSUE TITLE
数学Latex公式换不了行

### ISSUE THREAD

**Issue by dcoi** [tamlok/vnote#1324]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):

数学Latex公式换不了行，用`\\`没有效果

How to Repro (如何复现):

$$
\sum_{i=1}^A (i-p_i)(B-i+1)+\sum_{i=1}^A (i-p_i)(A-i+1)\\
=(A+B+2)\sum (i-p_i)-\sum 2i(i-p_i)
$$

编辑器上公式渲染就一行。

**Comment by tamlok** [comment]
试试转义，4条斜杠

**Comment by dcoi** [comment]
> 试试转义，4条斜杠

我试过了，也不行

**Comment by tamlok** [comment]
`\\`可以呀：

![image](https://user-images.githubusercontent.com/5763157/79702741-a2427580-82d9-11ea-8e8b-026e0e1eca97.png)

**Comment by dcoi** [comment]
不行啊，我试试重装

**Comment by tamlok** [comment]
哦哦，那可能是新版本升级了MathJax 3.0，不知道有什么变化。
