### ISSUE TITLE
提个打开笔记的方式的小建议

### ISSUE THREAD

**Issue by Omiga3721** [tamlok/vnote#1326]
现在的打开笔记的方式是单击笔记就会新建一个tab页面，有很多时候并不希望这个tab保持打开，只是看一眼，特别是在查找资料的时候（已经知道要找的资料分散在好几个笔记，用不到搜索时），tab栏一不小心就占满了。

其实就是建议参考了一下 vscode 单击所有的文件只是共用一个tab页面预览，修改过这个预览，需要保存才保持打开。双击才打开笔记到tab页面。

可以在设置弄个双击打开笔记的开关，来切换是否需要这种打开方式。

**Comment by tamlok** [comment]
看一下设置里面，打开个选项即可

**Comment by Omiga3721** [comment]
我更新到2.9.1 Mac版，没有找到这样的选项，只有阅读模式与编辑模式。

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/79834034-f5522080-83de-11ea-94ac-b9f156e3bf6a.png)

**Comment by Omiga3721** [comment]
找到了，谢谢。
