### ISSUE TITLE
反饋:VIM正常模式下的光標經常會出現無光標,只有行顯示.

### ISSUE THREAD

**Issue by 904897560** [tamlok/vnote#133]
![vnote_bug](https://user-images.githubusercontent.com/17105125/36173095-da78de86-1142-11e8-8332-9ce906baaaca.jpg)

**Comment by tamlok** [comment]
您好！

- 是一直不显示光标吗？还是光标在闪烁，所以有时候会看不见光标？
- 哪个操作系统？
- 这个问题能精确复现吗？

谢谢！

**Comment by 904897560** [comment]
您好！
主要就是輸入中文後光標就會消失,輸入英文就暫時沒發現這個問題,只要出現了光標消失,就很難恢復光標,出發重啟編輯器.
系統是:Win7_x86_64,VNote_win_X64_portable_1.11.1.zip
問題能即時復現,需要的話可以加QQ演示給你看,名字就是QQ號碼.
谢谢！

**Comment by tamlok** [comment]
请问用的是什么输入法呢？谢谢！

**Comment by 904897560** [comment]
Google
![image](https://user-images.githubusercontent.com/17105125/36212557-2b53ca68-11df-11e8-8168-7aa43d1cc30d.png)

**Comment by tamlok** [comment]
好的，我这边看能否重现。谢谢！

**Comment by 904897560** [comment]
不客氣,祝你早日修復BUG,第一眼就喜歡的APP,正考慮作為長期使用.

**Comment by tamlok** [comment]
我这边做了一些修改，不知道能否解决这个问题，过几天会发布1.12，到时候您试一下。

谢谢！

**Comment by 904897560** [comment]
ok,發布後我會測試,並反饋.

**Comment by 904897560** [comment]
你好,這邊測試過新版,問題依舊.

**Comment by tamlok** [comment]
换一个输入法呢？谢谢！

**Comment by 904897560** [comment]
尷尬,用搜狗沒問題誒,看來谷歌不知道是不兼容還是太老了.

**Comment by 904897560** [comment]
這個應該不關係自动禁用输入法。
因為這個情況是出現在敲完拼音後按空格把字符串輸入進去就會把光標覆蓋掉.

**Comment by tamlok** [comment]
OK

**Comment by tamlok** [comment]
Hi，有用户反映说把谷歌输入法换成嵌入式模式就能正常使用，您可以试试！

**Comment by 904897560** [comment]
謝謝,不過測試不可以....

**Comment by mizegit** [comment]
我也遇到了谷歌拼音2.7.25.128光标消失的问题（win7 64位），更新到了谷歌拼音的3.0.1.98的测试版本，就没有光标消失的问题了。

**Comment by tamlok** [comment]
@mizegit 谢谢反馈！

**Comment by 904897560** [comment]
> 我也遇到了谷歌拼音2.7.25.128光标消失的问题（win7 64位），更新到了谷歌拼音的3.0.1.98的测试版本，就没有光标消失的问题了。

你好,谷歌拼音有3.0的测试版吗,请问在哪里可以下载到.

**Comment by mizegit** [comment]
> 
> 
> > 我也遇到了谷歌拼音2.7.25.128光标消失的问题（win7 64位），更新到了谷歌拼音的3.0.1.98的测试版本，就没有光标消失的问题了。
> 
> 你好,谷歌拼音有3.0的测试版吗,请问在哪里可以下载到.

有的。新浪上还可以下载：http://down.tech.sina.com.cn/page/42066.html

**Comment by 904897560** [comment]
> > > 我也遇到了谷歌拼音2.7.25.128光标消失的问题（win7 64位），更新到了谷歌拼音的3.0.1.98的测试版本，就没有光标消失的问题了。
> > 
> > 
> > 你好,谷歌拼音有3.0的测试版吗,请问在哪里可以下载到.
> 
> 有的。新浪上还可以下载：http://down.tech.sina.com.cn/page/42066.html

3Q

**Comment by wendouzi** [comment]
linux  4.15.0-39-generic ubuntu 18.04 版本 安装完 vim-gtk 必现，卸载后恢复
