### ISSUE TITLE
亲，提个小小的建议哈 0^0

### ISSUE THREAD

**Issue by cainb** [tamlok/vnote#1334]
OS Version (操作系统): Windows 10

VNote Version: 2.9.1

亲，提个小小的建议哈 0^0

我在使用过程中，发现搜索栏和大纲工具栏只能在界面的上下左右边缘移动固定（上下方的固定，呈现效果个人觉得不是很舒服，可能是没习惯..

所以是否能考虑让它们也可以移动固定到“笔记本”一栏的右边（处于“笔记本”和编辑预览窗口中间那里

如：
![image](https://user-images.githubusercontent.com/48700331/80187161-ba9bf280-8641-11ea-958c-cc4a88f9fd10.png)

截图里的工具栏只能移到那个地方，再上去一点点就上固定了...（但是应该不影响我想表达的建议吧

**Comment by tamlok** [comment]
明白，后面笔记本这一栏也是和工具一栏一样，都可以随便移动。

另外，搜索可以通过 通用入口 来实现，一般不用搜索栏。
