### ISSUE TITLE
窗口标题栏下方有一个黑条

### ISSUE THREAD

**Issue by chenyangvk** [tamlok/vnote#1335]
OS Version (操作系统): Windows 10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
窗口最大化后标题栏下方有一个黑条，窗口底部内容显示不完整，好像窗口内容整体下移了。
在笔记本外接显示器有此现象，笔记本主显示屏没有这个问题。

How to Repro (如何复现):
……

如下是一个全屏截图
链接: https://pan.baidu.com/s/1PDddCc0i7QRQb_F7zkIhfg 提取码: qvf3

**Comment by tamlok** [comment]
Hi,

请尝试： https://github.com/tamlok/vnote/issues/853

另外，两个显示器的缩放设置是否一样，如果不一样，VNote需要在使用的那个显示器上面启动。

**Comment by chenyangvk** [comment]
将opengl选项选择SoftwareOpenGL，然后每次启动在指定的一个显示器启动，没有再出现问题
