### ISSUE TITLE
反馈bug：代码块中添加宏定义导致代码高亮消失

### ISSUE THREAD

**Issue by chason0528** [tamlok/vnote#134]
例如   
 #define PACKED(x) __attribute__ ((__aligned__(x), __packed__))
    template<typename T>
    class PACKED(sizeof(T)) Atomic : public std::atomic<T> {
                    ......
    };

**Comment by chason0528** [comment]
PS:这个编辑器做得很好我很喜欢感谢作者：）

**Comment by tamlok** [comment]
Hi，这个似乎是Highlight.js的问题。把语言标记为`cpp`没有高亮，标记为`cs`则有高亮，说明Highlight.js对cpp的语法高亮有问题，某些关键词可能没有。后面我会反馈一下。

谢谢！

**Comment by tamlok** [comment]
Hi，已经修复了(faff0cd8f6fa46864a6f14dd7766ed84bae8f97e)，谢谢反馈！

**Comment by rothleer** [comment]
所以是heightlight.js 的问题？

**Comment by tamlok** [comment]
不是😂调用highlightjs的时候用错了一个参数。
