### ISSUE TITLE
同步到github后md文件中图片不能显示

### ISSUE THREAD

**Issue by BingHuaCheng** [tamlok/vnote#1341]
在root目录将笔记git init...，然后push到github，md文件中图片不能显示，图片路径似乎是以当前目录为root目录

**Comment by tamlok** [comment]
能详细说一下吗？

1. md文本是怎么写的；
2. 文件结构是怎么样的；

**Comment by BingHuaCheng** [comment]
---原始邮件---
发件人: "Le Tan"<notifications@github.com&gt;
发送时间: 2020年4月30日(周四) 下午3:25
收件人: "tamlok/vnote"<vnote@noreply.github.com&gt;;
抄送: "BingHuaCheng"<3246729538@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [tamlok/vnote] 同步到github后md文件中图片不能显示 (#1341)




 
能详细说一下吗？
  
md文本是怎么写的； 

文件结构是怎么样的；

**Comment by BingHuaCheng** [comment]
github查看情况





---原始邮件---
发件人: "Le Tan"<notifications@github.com&gt;
发送时间: 2020年4月30日(周四) 下午3:25
收件人: "tamlok/vnote"<vnote@noreply.github.com&gt;;
抄送: "BingHuaCheng"<3246729538@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [tamlok/vnote] 同步到github后md文件中图片不能显示 (#1341)




 
能详细说一下吗？
  
md文本是怎么写的； 

文件结构是怎么样的；
