### ISSUE TITLE
笔记与文件夹之间的随意拖动

### ISSUE THREAD

**Issue by cainb** [tamlok/vnote#1342]
OS Version : Windows 10
VNote Version : 2.9.1

emmmm，笔记和笔记，文件夹和文件夹，笔记和文件夹之间似乎不能进行拖动以进行快速的二次分类和调整（类似 OneNote ？

后面会考虑支持这种操作嘛亲？

**Comment by tamlok** [comment]
可以右键复制粘贴，后面会实现拖拽。

**Comment by tianyalang** [comment]
可以移动，但是图片接入的链接不能是绝对路径

**Comment by tamlok** [comment]
@tianyalang 什么意思？有具体例子嘛？

**Comment by hello-sea** [comment]
弱弱问下，“笔记和笔记，文件夹和文件夹，笔记和文件夹之间拖动”这个相对比不好实现吗？(看到之前好像有描述可以 https://github.com/vnotex/vnote/issues/440#issuecomment-429315345)
但是貌似暂无法继续使用了

**Comment by tamlok** [comment]
还是只能右键复制粘贴
