### ISSUE TITLE
 从磁盘重加加载无效

### ISSUE THREAD

**Issue by qianshen88** [tamlok/vnote#1354]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

从磁盘重加加载无效。
How to Repro (如何复现):

从本地磁盘新建MD文件，使用VNote 查看目录没有此文件显示，当点击从磁盘重加加载，一样无法加载新建的MD文件。

**Comment by qianshen88** [comment]
> OS Version (操作系统): Windows
> 
> VNote Version (Help - About VNote - Version: )(VNote版本): 2.2, [d78e892](https://github.com/tamlok/vnote/commit/d78e892d5ccfcb1a096cec678adb556d5d2a4fb8) etc..
> 
> Symptoms (表现):
> 
> 从磁盘重加加载无效。
> How to Repro (如何复现):
> 
> 从本地磁盘新建MD文件，使用VNote 查看目录没有此文件显示，当点击从磁盘重加加载，一样无法加载新建的MD文件。

**Comment by tamlok** [comment]
外部新建md文件需要修改该文件夹下的json索引文件，然后重新加载。
