### ISSUE TITLE
提一个关于[打开笔记]的需求

### ISSUE THREAD

**Issue by feloxx** [tamlok/vnote#1359]
希望可以像vscode或者sublime text那样的类似打开笔记的效果;

在打开笔记的时候,`单击A笔记`直接显示A笔记内容;

此时再`单击B笔记`则会`关闭`A笔记后再显示B笔记;

只有`双击A笔记`的时候,此笔记才会常驻,不会因为单击其他笔记而关闭.必须手动才能进行关闭;

这样的目的是因为当打开特别多的笔记时,标签栏特别多会分不清哪些是临时打开,哪些是确定要打开的;

减少笔记的`无效`打开;

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/81467867-24092d00-920e-11ea-9f3e-cf0af4e8cbdf.png)

设置里面把这个勾上即可。

**Comment by feloxx** [comment]
好的,找到了,谢谢

**Comment by Mojicode** [comment]
好像有点区别吧，跟VScode，我尝试了下，双击A文档应该是单独打开，而这时我单击B文档，应该独立打开B文档，但是实际上却把我刚才双击打开的A文档给关了，只保留了B文档。

期望：
双击A文档是固定永久打开，除非主动关闭，单击A文档是临时打开，只有单击另一个文档B，才会把目前临时打开的A文档关闭。
