### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by jtortoise** [tamlok/vnote#137]
在阅读模式下按Ctrl+W进入编辑模式，Ctrl+T保存退出编辑模式，希望能改成按Ctrl+W进入编辑，再次按Ctrl+W退出编辑。觉得这两个功能是一对的，一方面使用相同的快捷键来切换使用起来会更加顺心，另一方面能够更加方便Markdown小白(比如我)在前期能够快速切换到预览模式查看语法的正确性，用户体验会更好。

**Comment by tamlok** [comment]
Hi, 下一个版本会支持`Ctrl+T`切换编辑和阅读模式。

谢谢！

**Comment by jtortoise** [comment]
感谢作者及时回复。
既然决定使用`Ctrl+T`做为切换编辑和阅读模式的快捷键，而对于`Ctrl+W`的处置有个建议：在大部分浏览器上`Ctrl+W`是用来关闭当前标签或窗口的，在windows或linux的文件管理器也是如此，这是一个习惯来的。如果可以的话，请将`Ctrl+W`设置成关闭当前的标签，毕竟一个一个标签拿鼠标去关闭实在有些蛋疼。

**Comment by tamlok** [comment]
Hi, `Ctrl+W`在Linux中用作向前删除一个单词，VNote也是采用该惯例，在几乎所有能输入的框中都可以通过`Ctrl+W`来删除一个单词。不过，您也可以自定义快捷键`Ctrl+W`为关闭当前标签页。默认的关闭当前标签页的快捷键是`Ctrl+E X`。

谢谢！

**Comment by jtortoise** [comment]
谢谢回复，好久没用vim，忘记Ctrl+W的功能。删除当前的单词的惯例要更好用些。
