### ISSUE TITLE
对vnote的小建议

### ISSUE THREAD

**Issue by wanghuijz** [tamlok/vnote#1376]
希望可以在代码块右上角加一个`一键复制`的按钮. 类似于这样:

![image](https://user-images.githubusercontent.com/25444996/82288405-ff167600-99d4-11ea-9ce7-63b811738b23.png)
<br/>
感谢作者的软件!

**Comment by tamlok** [comment]
Hi,

设置里面打开即可。

![image](https://user-images.githubusercontent.com/5763157/82288972-46e9cd00-99d6-11ea-974c-397934faa2b8.png)

**Comment by wanghuijz** [comment]
> Hi,
> 
> 设置里面打开即可。
> 
> ![image](https://user-images.githubusercontent.com/5763157/82288972-46e9cd00-99d6-11ea-974c-397934faa2b8.png)

非常感谢!
