### ISSUE TITLE
VNote font size

### ISSUE THREAD

**Issue by avernan** [tamlok/vnote#138]
Is there any clean way to resize (maybe as a scaling factor) the interface font? From a first glance at the documentation, it looks like the only option is to tweak a theme and change the font size of the elements.

**Comment by tamlok** [comment]
Yes, I don't have time to expose these configs to a GUI interface, so we need to modify the config directly. 1.12 version will be released within next few days. It will output the default themes to the disk. We could just copy them and modify it easily.

Thanks!
