### ISSUE TITLE
Copying in visual mode (vim) does not copy to system clipboard

### ISSUE THREAD

**Issue by xuesoso** [tamlok/vnote#1384]
OS Version (操作系统): Linux (Manjaro i3 distro)

VNote Version (Help - About VNote - Version: )(VNote版本): 2.71

Symptoms (表现): Copying in visual mode (vim) does not copy to system clipboard. 

How to Repro (如何复现): Try highlight in visual and copy. Cannot paste from the system clipboard onto an external program (say firefox).

**Comment by tamlok** [comment]
Hi,

https://github.com/tamlok/vnote/issues/1316

**Comment by xuesoso** [comment]
Thanks for re-directing me there! That solved my problem. Thanks for writing and sharing this tool!
