### ISSUE TITLE
mathjax矩阵上/下方大括号渲染问题

### ISSUE THREAD

**Issue by zhyma** [tamlok/vnote#1385]
OS Version (操作系统): Windows
VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
使用```\underbrace```的时候部分括号不显示，使用的Mathjax版本是配置在本地的3.0.5
（```\overbrace```也存在类似的问题，）

Vnote 渲染结果
![vnote显示结果](https://user-images.githubusercontent.com/2032749/82614755-9971e780-9b96-11ea-9023-4581c07dbacd.png)

Mathjax网站demo渲染结果
![Mathjax网站demo效果](https://user-images.githubusercontent.com/2032749/82614786-a8f13080-9b96-11ea-9962-2b7f68ebbc15.png)

How to Repro (如何复现):
Try this
```
$$J(z,x_0)=x'_0Qx_0+\begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_N\end{bmatrix}'
\underbrace{
\begin{bmatrix}
1 & 0 \\
&& 1 & 0 \\
&&&& \ddots \\
&&&&& 1 & 0
\end{bmatrix}}_{T}$$
```

**Comment by tamlok** [comment]
Hi,

![image](https://user-images.githubusercontent.com/5763157/82616079-c4902180-9bfe-11ea-8e41-e8f12b510282.png)

配置在本地的话是不是字体原因呢？可以本地弄一个简单的http server来部署mathjax，看看这样能不能解决。

**Comment by zhyma** [comment]
我把配置文件改成了[https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.0.5/es5/tex-mml-chtml.js](https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.0.5/es5/tex-mml-chtml.js)，然后打开原地预览，还是有同样的问题
原地预览效果（阅读模式显示效果一样）：
![vnote](https://user-images.githubusercontent.com/2032749/82620556-cc23dc00-9ba6-11ea-829a-5f2f928243fd.png)
导出HTML（显示正常）：
![html](https://user-images.githubusercontent.com/2032749/82620611-ecec3180-9ba6-11ea-8e2a-908853b9a7c6.png)
导出PDF（也不太正常）：
![pdf](https://user-images.githubusercontent.com/2032749/82620618-f2497c00-9ba6-11ea-992e-e769f4e59f31.png)

我尝试了右键改渲染为SVG，也没有效果

**Comment by tamlok** [comment]
感觉是网络问题，你尝试多等一会看看？我这边也是一两秒左右才正常。

**Comment by zhyma** [comment]
试了等了一段时间，没有变化，换了另外一台电脑(Windows10+Vnote 2.9.1)，以及切换到Ubuntu16.04+Vnote 2.9.1，都有同样的问题。两个在预览模式显示的不太一样，在阅读模式显示的和上面是一样的问题。这两台电脑用的是默认的在线的3.0.1的Mathjax
两者的的log里都有```Critical:(markdown-it.js:198) Uncaught TypeError: MathJax.texReset is not a function```
Windows的log里有```Warning:(vutils.cpp:1258) fail to delete file"C:/Users/*******/AppData/Roaming/vnote/resources/common.css"```

Win10 预览模式
![win10](https://user-images.githubusercontent.com/2032749/82631628-f6d05d80-9bc3-11ea-871e-cd515bffa8b3.png)

Linux 预览模式
![linux](https://user-images.githubusercontent.com/2032749/82631716-297a5600-9bc4-11ea-9a92-63c4b458c000.png)

log文件
```

```

**Comment by zhyma** [comment]
用MacOS（Catalina, 10.15.4）测试了一下（版本也是2.9.1），如果用3.0的mathjax源的话，效果和上面一样（缺少两边的长臂）。如果在配置中改成[2.7](https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML)，关闭标签之后重新打开标签，可以正确显示。完全退出后再打开，就不能解析公式了（应该是因为现在的版本已经不支持2.7了吧？）。在Windows下用同样的步骤没有效果，直接不解析公式。

**Comment by zhyma** [comment]
我发现把Mathjax版本配置为3.0.1，js文件选择tex-svg.js，渲染配置为SVG可以正常显示，具体方法为
matjax配置为：```file:///.\plugin\MathJax-3.0.1\es5\tex-svg.js```
公式上点右键 math setting-> math renderer->SVG

tex-mml-chtml.js，tex-chtml.js都不行。如果配置成3.0.5的tex-svg.js也不能正确渲染。

**Comment by hlyang1992** [comment]
这应该是mathjax的问题，跟vnote无关。 [overbrace broken in SVG output](https://github.com/mathjax/MathJax/issues/2402)

**Comment by zhyma** [comment]
@hlyang1992 多谢
