### ISSUE TITLE
不能自动列出目录下文件

### ISSUE THREAD

**Issue by fcwys** [tamlok/vnote#139]
第一眼就喜欢上了，打算长期使用，我把云笔记md文档搬下来，放进Vnote文档目录下不能自发现文件夹及目录，感觉很不方便，希望改进，谢谢！
改进建议：支持自动发现文档目录及目录下MD文件。

**Comment by tamlok** [comment]
Hi, 谢谢使用！

VNote每个文件夹下面都使用一个`_vnote.json`文件来跟踪记录所有文件夹和笔记。目前有几个解决方案：

1. 写脚本修改JSON文件，将相应文件加入到VNote的结构中；
2. 将复制过去的文件先删除，然后使用VNote的“文件”菜单中的“从外部文件新建笔记”功能批量复制导入笔记；
3. 将VNote作为一个编辑器使用，设置VNote为MD文件的默认打开方式；后面会加入一个导航栏，用以浏览文件系统；

之所以不自动发现文件是因为VNote对支持的笔记类型不作限制，可以是任意文件。

谢谢！

**Comment by fcwys** [comment]
好的，希望vnote做得更好

**Comment by tamlok** [comment]
1.17支持直接浏览外部文件，欢迎更新！
