### ISSUE TITLE
笔记本的回收垃圾桶似乎在工具栏中没有按钮实现？

### ISSUE THREAD

**Issue by cainb** [tamlok/vnote#1404]
OS Version (操作系统): Windows 10 1903

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Iaaues:

亲，笔记本的回收垃圾桶似乎在工具栏中没有按钮实现？

VNote X 是否会考虑加个回收垃圾桶管理按钮？

以此实现便捷的进行回收管理和清理垃圾？

**Comment by tamlok** [comment]
后面会这样统一管理：

![image](https://user-images.githubusercontent.com/5763157/83348022-c030da80-a35b-11ea-99a2-015651cff312.png)
