### ISSUE TITLE
Portable Mode

### ISSUE THREAD

**Issue by smaragdus** [tamlok/vnote#141]
Currently [VNote](https://github.com/tamlok/vnote) saves data and settings to AppData:

`C:\Users\UserName\AppData\Local\VNote`

containing the following sub-folders:

- _cache_
- _QtWebEngine_

`C:\Users\UserName\AppData\Roaming\vnote`

containing the following sub-folders:

- _styles_
- _templates_
- _themes_

and the following files:

- _flash_page.md_
- _session.ini_
- _vnote.ini_
- _vnote.log_

so according to my definition of "**Portable**" **VNote** is not portable since a truly portable program does not write outside its program folder.

I would like to suggest an option for saving all data and settings in program folder (where is **VNote.exe**). I suppose this can be implemented in different ways:

- **command-line argument** - for example if **VNote** is started with "**VNote.exe -portable**" parameter it saves all data and settings in program folder;
- **portable flag** - on program start **VNote** checks it program folder for "**Portable**" flag and if it exists it saves data and settings in program folder;
- **portable option** - in "**Settings**" there is a check-box "**Portable mode**", which, if it is selected, **VNote** is forced to save data and settings to program folder;

There must be a way all data and settings to be saved in program folder- thus the users would be able to carry **VNote** on external drives and run it on other machines with all its data and settings and without leaving any traces behind.

**Comment by tamlok** [comment]
Hi, please reference [here](http://vnote.readthedocs.io/en/latest/user_docs/faqs.html#how-to-make-vnote-more-portable) for how to put files in VNote's configuration folder along with VNote's executable.

`cache` and `QtWebEngine` are generated by `QWebEngineProcess`, not VNote specific.

One thing to mention is currently VNote store the absolute path of notebooks in `session.ini`, which may be a problem after you moving VNote to another PC.

Thanks!

**Comment by smaragdus** [comment]
@tamlok 

Hello and thank you for the explanation and for the link to [FAQ](http://vnote.readthedocs.io/en/latest/user_docs/faqs.html#how-to-make-vnote-more-portable).

In short- do you mean that if I copy all the stuff from 'C:\Users\UserName\AppData\Roaming\vnote" ('styles', 'templates' and 'themes' sub-folders and 'flash_page.md', 'session.ini', 'vnote.ini' and 'vnote.log' files) to VNote folder, VNote will use these and ignore AppData?

Wouldn't it be better if VNote uses relative paths in stead of absolute paths?

**Comment by tamlok** [comment]
Yes, VNote will treat the folder containing `vnote.ini` as the configuration folder and read other stuffs there.

It is designed to separate VNote from data. User could use any editors to edit their notes without VNote. So we use absolute paths here. Do you want to put all data with VNote in a usb stick?

**Comment by smaragdus** [comment]
@tamlok 

Hello and excuse me for the late reply.

> It is recommended to separate the data and application.

You know- different users have different preferences. I prefer truly portable software for several different reasons- they are easy to back-up, they can be easily transferred to other devices, different versions can be used with different settings (this is very useful for testing).

> It is designed to separate VNote from data.

I understand your philosophy, I accept it and I respect the choice of any developer who releases free and open-source software, So I am not trying to impose my preferences upon your program.

I opened this issue because I discovered somewhat similar program- [QOwnNotes](https://github.com/pbek/QOwnNotes), which can be easily run in portable mode via a command-line parameter ([Installation](http://www.qownnotes.org/installation)):

`QOwnNotes.exe --portable`

And I supposed that similar behaviour may be added to [VNote](https://github.com/tamlok/vnote).

> Do you want to put all data with VNote in a usb stick?

Yes, for me this would be convenient.

Since you provide an option to make [VNote](https://tamlok.github.io/vnote/) more portable ([How to make VNote more "portable"?](http://vnote.readthedocs.io/en/latest/user_docs/faqs.html#how-to-make-vnote-more-portable)) please feel free to close this issue- I am not closing it myself because you may have some plans for the future about portability.

Regards

**Comment by tamlok** [comment]
Hi, I will add an option to choose whether use relative path or not when creating a notebook. I think we need to wait before implementing some more critical features. Thanks!

**Comment by smaragdus** [comment]
I appreciate your work! Take your time. Thanks

**Comment by tamlok** [comment]
Already fixed!

**Comment by smaragdus** [comment]
@tamlok 

Thanks!

I will download the latest version ([1.20](https://github.com/tamlok/vnote/releases/tag/v1.20)) and check it.

Regards
