### ISSUE TITLE
图片链接中含有空格，则图片无法显示。

### ISSUE THREAD

**Issue by X-hood** [tamlok/vnote#1416]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
图片链接中含有空格，则图片无法显示

How to Repro (如何复现):空格

**Comment by tamlok** [comment]
URL规定空格得用`%20`来表示，VNote一般会自动处理。

**Comment by X-hood** [comment]
我是设置的原本的笔记文件夹，里面有的md笔记中图片链接用的相对路径，其中有些有空格，在Vnote中并没有自动处理，只是不展示。

**Comment by X-hood** [comment]
> URL规定空格得用`%20`来表示，VNote一般会自动处理。

我是设置的原本的笔记文件夹，里面有的md笔记中图片链接用的相对路径，其中有些有空格，在Vnote中并没有自动处理，只是不展示。

**Comment by tamlok** [comment]
自动处理是指当你插入新图片的时候，如果有空格，vnote会转换成20%。vnote一般不会擅自改动用户的笔记，所以现在的笔记内容是不会自动处理的。
