### ISSUE TITLE
关于“从磁盘重新加载”的疑问。

### ISSUE THREAD

**Issue by X-hood** [tamlok/vnote#1417]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
不知道这个到底有什么用，我以为是重新递归扫描这个文件夹，结果好像什么反应也没有。
这就涉及到一个问题：直接在资源管理器中操作笔记本文件夹中文件，如新增或删除文件，在笔记软件中没法更新这种变化，如果这个“从磁盘重新加载”是重新扫描文件夹的话，应该能满足这个需求。

How to Repro (如何复现):
点击“从磁盘重新加载”，笔记列表没有任何变化。

**Comment by tamlok** [comment]
vnote使用索引文件`_vnote.json`来跟踪所有笔记，从磁盘重新加载只是重新加载这个json文件。如果绕开vnote新增或者删除笔记，需要自行手动修改json文件。

如果频繁有这种需求，可以使用笔记本旁边的那个`浏览器`功能来浏览编辑外部文件，将vnote单纯当作一个编辑器使用。

后面会改进。

**Comment by X-hood** [comment]
> vnote使用索引文件`_vnote.json`来跟踪所有笔记，从磁盘重新加载只是重新加载这个json文件。如果绕开vnote新增或者删除笔记，需要自行手动修改json文件。
> 
> 如果频繁有这种需求，可以使用笔记本旁边的那个`浏览器`功能来浏览编辑外部文件，将vnote单纯当作一个编辑器使用。
> 
> 后面会改进。

这样说可能很不友好，希望你不要介意。我觉得vnote作为一个笔记软件还是很好的，期待后续的功能完善。作为一个编辑器，还是有较大的进步空间的。所以我想能否添加设置点击一下默认打开方式是外部程序（要求好像有点过分，还有更过分的：) ），我对QT完全不了解，所以下面这个建议您就当一乐吧：能否默认打开方式是外部程序，然后把它的界面在软件内展示。。。（想想这种建议确实太过分，希望您不要生气）
