### ISSUE TITLE
笔记无法自动排序

### ISSUE THREAD

**Issue by JiasenLee** [tamlok/vnote#1427]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):笔记工作区无法自动排序

How to Repro (如何复现):能不能加入按照字典顺序或者文件大小等方式进行自动排序

**Comment by tamlok** [comment]
右键排序，笔记列表的话按那个小眼睛

**Comment by JiasenLee** [comment]
> 右键排序，笔记列表的话按那个小眼睛

嗯嗯，找到了，谢谢你
