### ISSUE TITLE
shell代码贴进去显示有问题

### ISSUE THREAD

**Issue by cuijianzhe** [tamlok/vnote#1429]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
编辑模式中铁如shell命令行代码，保存后代码显示错误……
![image](https://user-images.githubusercontent.com/48144475/85919445-aec8e880-b89d-11ea-9f8e-f4e71209afce.png)
编辑模式原本代码：for i in `ls -la | awk '{print $9}'` ;do du -sh $i;done  （行内代码有问题）

How to Repro (如何复现):
行内代码贴进去：
for i in `ls -la | awk '{print $9}'` ;do du -sh $i;done

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/85919644-c608d580-b89f-11ea-838e-84340e2645dd.png)

**Comment by cuijianzhe** [comment]
ok
