### ISSUE TITLE
Mermaid

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#1430]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):Does VNote support Mermaid?

How to Repro (如何复现):

**Comment by tamlok** [comment]
yes, it is written in the github README.

**Comment by DutchPete** [comment]
> yes, it is written in the github README.

The link on that page leads to a 404.

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/85945143-43028080-b96e-11ea-982d-5fd2441a3bae.png)

**Comment by DutchPete** [comment]
Thank you, it works.
