### ISSUE TITLE
增加一个小功能吧

### ISSUE THREAD

**Issue by WsxIkm** [tamlok/vnote#1438]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本):2.91

Symptoms (表现):
在代码块中添加注释，且在注释中使用到了 `` 符号即行内代码，会导致在md编写界面 代码块的显示异常 ，可能会导致右侧的大纲结构显示异常，在预览界面显示正常。
这只是一个小功能，我已经避免在注释中使用这种符号。

此外，能不能增加一个小功能，当按键盘上的向下 ⬇ 方向键时，会向下跳行，希望光标移至 最后一行时继续按 ⬇ 会将光标移至行末。

**Comment by Fxiao1** [comment]
首先第一点：
> 在代码块中添加注释，且在注释中使用到了 `` 符号即行内代码。

没有你这样玩的，单行代码就单行代码，代码块就代码块，代码代码块里面的都是代码，都要符合代码规范，而“``”又是个什么？这是markdown的标记符，不属于代码块里面的语法

第二点：
> 此外，能不能增加一个小功能，当按键盘上的向下 ⬇ 方向键时，会向下跳行，希望光标移至 最后一行时继续按 ⬇ 会将光标移至行末。

键盘上的`home`和`end`不就是这功能么？

**Comment by tamlok** [comment]
你得看一下代码块里面反引号怎么转义。或者通过缩进四个空格的代码块来输入带有反引号的代码块。

**Comment by WsxIkm** [comment]
> 首先第一点：
> 
> > 在代码块中添加注释，且在注释中使用到了 `` 符号即行内代码。
> 
> 没有你这样玩的，单行代码就单行代码，代码块就代码块，代码代码块里面的都是代码，都要符合代码规范，而“``”又是个什么？这是markdown的标记符，不属于代码块里面的语法
> 
> 第二点：
> 
> > 此外，能不能增加一个小功能，当按键盘上的向下 ⬇ 方向键时，会向下跳行，希望光标移至 最后一行时继续按 ⬇ 会将光标移至行末。
> 
> 键盘上的`home`和`end`不就是这功能么？

**Comment by WsxIkm** [comment]
> 首先第一点：
> 
> > 在代码块中添加注释，且在注释中使用到了 `` 符号即行内代码。
> 
> 没有你这样玩的，单行代码就单行代码，代码块就代码块，代码代码块里面的都是代码，都要符合代码规范，而“``”又是个什么？这是markdown的标记符，不属于代码块里面的语法
> 
> 第二点：
> 
> > 此外，能不能增加一个小功能，当按键盘上的向下 ⬇ 方向键时，会向下跳行，希望光标移至 最后一行时继续按 ⬇ 会将光标移至行末。
> 
> 键盘上的`home`和`end`不就是这功能么？

关于第一点 `` 这个符号是曾经编码时 在注释中引用某变量时 个人习惯 如 ```<!-- `max` 是在某某地方某某 -->``` 这样的 在做笔记的时候我复制粘贴了部分代码 在编辑界面的渲染出了点问题 才提出来的 发现问题所在之后我也没有再使用了 只是略微提及一下 个人觉得 写在 代码块 ``` ``` 里的代码不应该受到除了" ``` "的影响 当然Vnote在预览界面完全达到了这个需求 
第二点 至于Home和 end 很少使用到这个区域的宝藏按键 del 除外 😂 相对于方向键 这个在我键盘上的跨度有点大 而且使用方向键这个习惯已经养成了好久了😂

**Comment by tamlok** [comment]
第一点可能是bug，后面看看。向下这个实现也简单，后面也看看。
