### ISSUE TITLE
Generate single PDF for few Markdown files (for book creating) 

### ISSUE THREAD

**Issue by Symbian9** [tamlok/vnote#144]
Currently if try export to PDF "Current Folder" or "Current Notebook" it create many files (one pdf-file per one md-file).

Add option for export folder/notebook as single PDF file, aka book.

- Export
  - Target format:
    - [x] Markdown
    - [x] HTML
    - [x] PDF
    - [ ] PDF (book)

**Comment by tamlok** [comment]
Hi, I am working on exporting PDF via wkhtmltopdf tool. I think it is a good idea.

Thanks!

**Comment by Symbian9** [comment]
As test case try use this book example written in Markdown

- https://github.com/mikepan/GameEngineBook

**Comment by tamlok** [comment]
Already added (a331eee186ed91e49b67a099783c071e6dcbdfee).
