### ISSUE TITLE
Workflowy-like behaviour

### ISSUE THREAD

**Issue by ntqr** [tamlok/vnote#1443]
OS Version: Windows

VNote Version : 2.9.1

Is there a way to have workflowy-like behaviour in vnote?
I found this in the source:
```
// Html: rich text file;
// Markdown: Markdown text file;
// List: Infinite list file like WorkFlowy;
// Container: a composite file containing multiple files;
enum class DocType { Html = 0, Markdown, List, Container, Unknown };
```
But when I tried to make a note with a '.list' extension, the program crashes when I tried to open it.

**Comment by tamlok** [comment]
It is just a todo at the very beginning of VNote. Not inplemented yet till now.

**Comment by ntqr** [comment]
I see, I hope it will be implemented some day
