### ISSUE TITLE
如何默认展开所有子目录

### ISSUE THREAD

**Issue by sqlkrad** [tamlok/vnote#1448]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现): 笔记的目录组织成了树状结构，每次打开都要自己手动展开子目录，能否默认展开所有子目录呢？

**Comment by tamlok** [comment]
那样会很卡顿吧，试试在一个目录上面按`x`。

**Comment by sqlkrad** [comment]
按x出来的是查找对话框

**Comment by tamlok** [comment]
是 * ，说错了

**Comment by sqlkrad** [comment]
可以，谢谢！
