### ISSUE TITLE
Feature Request: Export Note as Picture (PNG) & One-page PDF / 特性需求: 导出笔记为图片 (PNG) 和一整页PDF

### ISSUE THREAD

**Issue by DanielW10001** [tamlok/vnote#1449]
PDF is good for print, but not as good for reading on screens because of the gaps between pages.
How about leting users to export note as a long pic (PNG format for quality concerns), and as one-page PDF?

PDF适用于打印，但由于页面之间存在间隙，因此不适用于在屏幕上阅读。
允许用户将笔记导出为长图片（出于质量考虑的PNG格式）和一整页的PDF怎么样？

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/86884140-b736e400-c125-11ea-817f-670d8c8b95a5.png)

**Comment by DanielW10001** [comment]
Can we integrate this into VNote? This can make it easier.

**Comment by tamlok** [comment]
You can now call this tool in customized export.

**Comment by DanielW10001** [comment]
Thanks! This works for me: `wkhtmltoimage --format png --quality 100 --width 1000 %0 %1`
