### ISSUE TITLE
Update screenshots and manual to show features of VNote v1.12

### ISSUE THREAD

**Issue by Symbian9** [tamlok/vnote#145]
Currently screenshots and docs look like outdated, so update it show current version of VNote

- http://vnote.readthedocs.io/
- https://tamlok.github.io/vnote/gallery.html

**VNote Version**: 1.12

P.S.: Here is my screenshot
![VNote v1.12](http://pasteall.org/pic/show.php?id=130100)

**Comment by tamlok** [comment]
VNote's development occupies almost all of my spare time, so I have little time for the documentation. You could send a PullRequest to upload your screenshots. Maybe we could create a separate page for users' screenshots. :)

BTW, I am more a fan of `v_pure`. :)

Thanks!

**Comment by tamlok** [comment]
Already updated. Thanks!
