### ISSUE TITLE
Sorting method for folders and notes

### ISSUE THREAD

**Issue by vmexia** [tamlok/vnote#146]
Hello,

Could you tell me if it is on the roadmap the implementation of a new sorting method? The current one feels kinda monolithic. It would be very helpful to be able to sort by name or creation/modified date.
Example: I have a notebook for work in which I have ALOT of individual notes, each one for a different task. The current method of individually moving each note to the ideal position is not very useful for this kind of use case :(

Best regards,
Vitor

**Comment by tamlok** [comment]
hi, the gui interface is ready but the logic is not implemented yet. Will add it within days. Thanks!

**Comment by tamlok** [comment]
Already added (d404360fee4844359bf4c4bda1257cd4814d51b3).
