### ISSUE TITLE
公式过多导致实时渲染 性能问题

### ISSUE THREAD

**Issue by MaiLunJiye** [tamlok/vnote#1462]
OS Version (操作系统): Linux archlinux 5.7.9-arch1-1

VNote Version (Help - About VNote - Version: )VNote 版本: 2.9.1

Symptoms (表现):

当编辑Markdown 里面有大量公式时候， 实时渲染公式将无法正确显示。
同时进程 QtWebEngineProcess 会占用大量的 CPU 和 内存。

How to Repro (如何复现):

保存下面的笔记， 然后重启vnote， 然后编辑这个笔记：

```
# lec1

## 简单count-min

使用 count-min 进行基数统计。Count-min 算法很简单，统计每个流元素最小的哈希值，通过最小的哈希值就可以推断大概有多少个不同的元素（即流基数）。

对于一个流 $x_1, x_2, x_3, \dots, x_k$ , 使用一个哈希函数使得其映射到 $[0,1]$ 之间,那么最小哈希值的期望为:

$$
E\left[ \min_{i = 1,\dots,k} h(x_i) \right] = \frac{1}{k+1}
$$

证明:

令 $Y = min(h(x_1), \dots, h(x_k))$。  $h(x_1), \dots, h(x_k)$ 互相独立，且随机均匀分布于$[0,1]$ 。 
那么 某一个 $h(x_i)$ 小于 $t$ 的概率为： $Pr\left[ Y \le t \right] = t$ ， 
由于$h(x_1), \dots, h(x_k)$ 互相独立，因此有 $Pr[Y>t] = (1-t)^k$，$Pr[Y \le t] = 1 - (1-t)^k$。
那么对前面那个式子求导有：$(Pr[Y \le t])' = Pr\left[Y \in [t, t+ dt] \right] = k(1-t)^{k-1}$。
近似可以认为 $Pr[ Y = t ] = k(1-t)^{k-1}$。

因此 $Y$ 的期望可以表示为：

\begin{align}
E[Y] &= \int_0^1 t \cdot Pr[ Y = t ] dt \\
    & = \int_0^1 t \cdot k(1-t)^{k-1} dt \\
    & = k \int_0^1 (1 - (1 - t))(1-t)^{k-1} dt \\
    & = k \left( \int_0^1 (1-t)^{k-1} dt - \int (1-t)^k dt \right) \\
    & = k \left(\frac{1}{k} - \frac{1}{k + 1} \right) \\
    & = \frac{1}{k+1}
\end{align}


$Y$ 的方差计算：

\begin{align}
Var[Y] &= E[Y^2] - E[Y]^2 \\
    & = \int_0^1 t^2 Pr[ Y = t ] dt  - \left(\frac{1}{k+1} \right) ^ 2 \\
    & = \int_0^1 t^2 \cdot k(1-t)^{k-1} dt - \left(\frac{1}{k+1} \right) ^ 2 \\
    & = k \int_0^1 (1 - (1-t))^2 \cdot (1-t)^{k-1} dt - \left(\frac{1}{k+1} \right) ^ 2 \\
    & = k \int_0^1 (1^2 + 2(1-t) + (1-t)^2) \cdot (1-t)^{k-1} dt - \left(\frac{1}{k+1} \right) ^ 2 \\
    & = k \left[ \int_0^1 (1-t)^{k-1} dt + 2 \int_0^1 (1-t)^{k} dt + \int_0^1 (1-t)^{k + 1} \right] - \left(\frac{1}{k+1} \right) ^ 2 \\
    & = k \left[ \frac{1}{k} - \frac{2}{k+1} + frac{1}{k + 2} \right] - \left(\frac{1}{k+1} \right) ^ 2 \\
    & = \frac{(k+1)^2(k+2) - 2k(k+1)(k+2) + k(k+1)^2) - (k+2)}{(k+1)^2(k+2)} \\
    & = \frac{k}{(k+1)^2(k+2)} \\
    & \le \frac{1}{(k+1)^2} \\
    & = E[Y]^2
\end{align}

通常会考虑使用切比雪夫不等式确定 Y 的一个边界。

$$Pr(|Y - E[Y]| > \epsilon E[Y] ) \le \frac{Var[Y]}{(\epsilon E[Y])^2}$$

但是 $\epsilon$ 没有任何意义。

# 多个count-min

上面讲的方法通常只维护一个最小哈希值，为了提高精度，
可以使用多个哈希函数，对流进行多次哈希计算，维护多个哈希值（每个哈希函数记录最小的哈希值），
并且计算其算术平均值，利用算术平均值估计流基数。各个哈希之间独立。设$Y_1 + Y_2 + \dots + Y_t$
分别为哈希函数$h_1, h_2 , \dots, h_t$ 保留的最小哈希值。可知 $Y_1 + Y_2 + \dots + Y_t$ 互相独立。

令 $Z := \frac{Y_1 + Y_2 + \dots + Y_t}{t}$，由于$Y_1 + Y_2 + \dots + Y_t$ 互相独立。
因此 $E[Z] = E[Y], Var[Z] = \frac{1}{t^2} \sum_1^t Var[Y_i] = \frac{Var[Y]}{t} \le \frac{E[Y]^2}{t}$

根据上式使用切比雪夫不等式就可以计算出误差界限：

$$
Pr(|Z-E[Z]| \ge \epsilon E[Z]) \le \frac{Var(Z)}{(\epsilon E[Z])^2} \le \frac{1}{\epsilon ^ 2 t}
$$

当 $t = \frac{4}{\epsilon ^ 2}$，我们可以得到误差界限为 $\frac{1}{4}$ 。

# Median of Means

上一章节可以看出 提高 t 可以提高准确度，提高统计结果处于 $[(1-\epsilon)E[Z], (1+\epsilon)E[Z]]$ 之间的概率。
但是过大的t消耗很多空间，因此可以用 `median of means` 方法，
让统计结果落在$[(1-\epsilon)E[Z], (1+\epsilon)E[Z]]$ 内的概率为  $1-\delta$。

1. 令 $Z_1, \dots, Z_s$ 表示 上一章节中$t = \frac{4}{\epsilon ^ 2}$下各个 $Z$ 独立重复实验的结果，因此其两两独立。
2. 使用 $median(Z_1, \dots, Z_s)$ 即 中值 用于估算。

那么需要多少个 $Z_i$ 即 s 的多大才能确保 其中值 落在误差范围  $[(1-\epsilon)E[Z], (1+\epsilon)E[Z]]$ 的概率至少为 $1-\delta$呢？

对于每个 $Z_i$ ，令 $A_i$ 为一个0, 1 状态量。如果 $Z_i$ 处于 $[(1-\epsilon)E[Z], (1+\epsilon)E[Z]]$  之间，
则 为 1, 反之为 0。因此有 $E[A_i] \le \frac{1}{4}$。 $E[A] = E[A_1 + \dots + A_s] = \sum_{i=1,\dots,s}A_i \le \frac{s}{4}$

只要 $Z_1, \dots, Z_s$ 中有一半以上处于误差范围外，那么其中值就必然处于误差范围外，反之毅然。因此有：


\begin{align}
Pr[median(Z_1, \dots, Z_s)\ is\ bad] & \le Pr[at\ lease\ half\ of\ z_1, z_2, \dots, z_i\ are\ bad] \\
    & = Pr(A \ge \frac{s}{2}) \\
    & \le e^{-(2 ln2 - 2 + 1)\frac{s}{4}} \\
    & \le e^{\frac{-s}{11}}
\end{align}

其中 第 3 行使用了 切诺夫边界（ Chernoff bound）。
根据上式有 $Pr[median(Z_1, \dots, Z_s)\ is\ bad] \le \delta$ ，得 $s = 11 ln \frac{1}{\delta}$


# 切诺夫边界

## 马尔可夫不等式

如果 $X$ 是一个非负随机变量且 $a > 0$， 那么 X 不小于 a 的概率为 $P(X \ge a) \le \frac{E(X)}{a}$。

令 $a = \tilde a \cdot E(X)， \tilde a > 0$ ，可得 $P(X \ge \tilde a \cdot E(X)) \le \frac{1}{\tilde a}$。
```

**Comment by Superkeyv** [comment]
你要不要考虑使用本地Mathjax3？

我这里打开该文档cpu占用只有打开瞬间比较高，后面就正常了。公式渲染不出来，有可能和网速有些关系。

设置方法:
文件->设置->Markdown->Mathjax配置=/usr/share/mathjax/tex-mml-chtml.js

**Comment by zhyma** [comment]
> OS Version (操作系统): Linux archlinux 5.7.9-arch1-1
> 
> VNote Version (Help - About VNote - Version: )VNote 版本: 2.9.1
> 
> Symptoms (表现):
> 
> 当编辑Markdown 里面有大量公式时候， 实时渲染公式将无法正确显示。
> 同时进程 QtWebEngineProcess 会占用大量的 CPU 和 内存。
> 
> How to Repro (如何复现):
> 
> 保存下面的笔记， 然后重启vnote， 然后编辑这个笔记：
> 
> ```
> # lec1
> 
> ## 简单count-min
> 
> 使用 count-min 进行基数统计。Count-min 算法很简单，统计每个流元素最小的哈希值，通过最小的哈希值就可以推断大概有多少个不同的元素（即流基数）。
> 
> 对于一个流 $x_1, x_2, x_3, \dots, x_k$ , 使用一个哈希函数使得其映射到 $[0,1]$ 之间,那么最小哈希值的期望为:
> 
> $$
> E\left[ \min_{i = 1,\dots,k} h(x_i) \right] = \frac{1}{k+1}
> $$
> 
> 证明:
> 
> 令 $Y = min(h(x_1), \dots, h(x_k))$。  $h(x_1), \dots, h(x_k)$ 互相独立，且随机均匀分布于$[0,1]$ 。 
> 那么 某一个 $h(x_i)$ 小于 $t$ 的概率为： $Pr\left[ Y \le t \right] = t$ ， 
> 由于$h(x_1), \dots, h(x_k)$ 互相独立，因此有 $Pr[Y>t] = (1-t)^k$，$Pr[Y \le t] = 1 - (1-t)^k$。
> 那么对前面那个式子求导有：$(Pr[Y \le t])' = Pr\left[Y \in [t, t+ dt] \right] = k(1-t)^{k-1}$。
> 近似可以认为 $Pr[ Y = t ] = k(1-t)^{k-1}$。
> 
> 因此 $Y$ 的期望可以表示为：
> 
> \begin{align}
> E[Y] &= \int_0^1 t \cdot Pr[ Y = t ] dt \\
>     & = \int_0^1 t \cdot k(1-t)^{k-1} dt \\
>     & = k \int_0^1 (1 - (1 - t))(1-t)^{k-1} dt \\
>     & = k \left( \int_0^1 (1-t)^{k-1} dt - \int (1-t)^k dt \right) \\
>     & = k \left(\frac{1}{k} - \frac{1}{k + 1} \right) \\
>     & = \frac{1}{k+1}
> \end{align}
> 
> 
> $Y$ 的方差计算：
> 
> \begin{align}
> Var[Y] &= E[Y^2] - E[Y]^2 \\
>     & = \int_0^1 t^2 Pr[ Y = t ] dt  - \left(\frac{1}{k+1} \right) ^ 2 \\
>     & = \int_0^1 t^2 \cdot k(1-t)^{k-1} dt - \left(\frac{1}{k+1} \right) ^ 2 \\
>     & = k \int_0^1 (1 - (1-t))^2 \cdot (1-t)^{k-1} dt - \left(\frac{1}{k+1} \right) ^ 2 \\
>     & = k \int_0^1 (1^2 + 2(1-t) + (1-t)^2) \cdot (1-t)^{k-1} dt - \left(\frac{1}{k+1} \right) ^ 2 \\
>     & = k \left[ \int_0^1 (1-t)^{k-1} dt + 2 \int_0^1 (1-t)^{k} dt + \int_0^1 (1-t)^{k + 1} \right] - \left(\frac{1}{k+1} \right) ^ 2 \\
>     & = k \left[ \frac{1}{k} - \frac{2}{k+1} + frac{1}{k + 2} \right] - \left(\frac{1}{k+1} \right) ^ 2 \\
>     & = \frac{(k+1)^2(k+2) - 2k(k+1)(k+2) + k(k+1)^2) - (k+2)}{(k+1)^2(k+2)} \\
>     & = \frac{k}{(k+1)^2(k+2)} \\
>     & \le \frac{1}{(k+1)^2} \\
>     & = E[Y]^2
> \end{align}
> 
> 通常会考虑使用切比雪夫不等式确定 Y 的一个边界。
> 
> $$Pr(|Y - E[Y]| > \epsilon E[Y] ) \le \frac{Var[Y]}{(\epsilon E[Y])^2}$$
> 
> 但是 $\epsilon$ 没有任何意义。
> 
> # 多个count-min
> 
> 上面讲的方法通常只维护一个最小哈希值，为了提高精度，
> 可以使用多个哈希函数，对流进行多次哈希计算，维护多个哈希值（每个哈希函数记录最小的哈希值），
> 并且计算其算术平均值，利用算术平均值估计流基数。各个哈希之间独立。设$Y_1 + Y_2 + \dots + Y_t$
> 分别为哈希函数$h_1, h_2 , \dots, h_t$ 保留的最小哈希值。可知 $Y_1 + Y_2 + \dots + Y_t$ 互相独立。
> 
> 令 $Z := \frac{Y_1 + Y_2 + \dots + Y_t}{t}$，由于$Y_1 + Y_2 + \dots + Y_t$ 互相独立。
> 因此 $E[Z] = E[Y], Var[Z] = \frac{1}{t^2} \sum_1^t Var[Y_i] = \frac{Var[Y]}{t} \le \frac{E[Y]^2}{t}$
> 
> 根据上式使用切比雪夫不等式就可以计算出误差界限：
> 
> $$
> Pr(|Z-E[Z]| \ge \epsilon E[Z]) \le \frac{Var(Z)}{(\epsilon E[Z])^2} \le \frac{1}{\epsilon ^ 2 t}
> $$
> 
> 当 $t = \frac{4}{\epsilon ^ 2}$，我们可以得到误差界限为 $\frac{1}{4}$ 。
> 
> # Median of Means
> 
> 上一章节可以看出 提高 t 可以提高准确度，提高统计结果处于 $[(1-\epsilon)E[Z], (1+\epsilon)E[Z]]$ 之间的概率。
> 但是过大的t消耗很多空间，因此可以用 `median of means` 方法，
> 让统计结果落在$[(1-\epsilon)E[Z], (1+\epsilon)E[Z]]$ 内的概率为  $1-\delta$。
> 
> 1. 令 $Z_1, \dots, Z_s$ 表示 上一章节中$t = \frac{4}{\epsilon ^ 2}$下各个 $Z$ 独立重复实验的结果，因此其两两独立。
> 2. 使用 $median(Z_1, \dots, Z_s)$ 即 中值 用于估算。
> 
> 那么需要多少个 $Z_i$ 即 s 的多大才能确保 其中值 落在误差范围  $[(1-\epsilon)E[Z], (1+\epsilon)E[Z]]$ 的概率至少为 $1-\delta$呢？
> 
> 对于每个 $Z_i$ ，令 $A_i$ 为一个0, 1 状态量。如果 $Z_i$ 处于 $[(1-\epsilon)E[Z], (1+\epsilon)E[Z]]$  之间，
> 则 为 1, 反之为 0。因此有 $E[A_i] \le \frac{1}{4}$。 $E[A] = E[A_1 + \dots + A_s] = \sum_{i=1,\dots,s}A_i \le \frac{s}{4}$
> 
> 只要 $Z_1, \dots, Z_s$ 中有一半以上处于误差范围外，那么其中值就必然处于误差范围外，反之毅然。因此有：
> 
> 
> \begin{align}
> Pr[median(Z_1, \dots, Z_s)\ is\ bad] & \le Pr[at\ lease\ half\ of\ z_1, z_2, \dots, z_i\ are\ bad] \\
>     & = Pr(A \ge \frac{s}{2}) \\
>     & \le e^{-(2 ln2 - 2 + 1)\frac{s}{4}} \\
>     & \le e^{\frac{-s}{11}}
> \end{align}
> 
> 其中 第 3 行使用了 切诺夫边界（ Chernoff bound）。
> 根据上式有 $Pr[median(Z_1, \dots, Z_s)\ is\ bad] \le \delta$ ，得 $s = 11 ln \frac{1}{\delta}$
> 
> 
> # 切诺夫边界
> 
> ## 马尔可夫不等式
> 
> 如果 $X$ 是一个非负随机变量且 $a > 0$， 那么 X 不小于 a 的概率为 $P(X \ge a) \le \frac{E(X)}{a}$。
> 
> 令 $a = \tilde a \cdot E(X)， \tilde a > 0$ ，可得 $P(X \ge \tilde a \cdot E(X)) \le \frac{1}{\tilde a}$。
> ```

建议在现版本关掉公式实时渲染，并且配置本地的mathjax解析

**Comment by MaiLunJiye** [comment]
谢谢解答，目前已经使用本地 mathjax 了，感觉情况有所改善。
如果公式不能实时渲染的话，那写复杂公式看得眼睛疼。

希望有个缓存机制，因为我发现对有大量公式的笔记（阅读模式已经正确渲染公式）， 点击编辑时候，
vnote会从头开始对每一个公式进行实时渲染。如果可以使用缓存机制，避免重新渲染整个公式环境可能
会有更好的使用体验。
