### ISSUE TITLE
marked标题中code编译问题

### ISSUE THREAD

**Issue by unihon** [tamlok/vnote#1463]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1..

Symptoms (表现):

marked编译问题，如图。

![image](https://user-images.githubusercontent.com/42078581/88014657-0df2e380-cb52-11ea-8547-7df4ee2b98c2.png)

![image](https://user-images.githubusercontent.com/42078581/88014682-177c4b80-cb52-11ea-8400-23c1d1f00036.png)

How to Repro (如何复现):

**Comment by tamlok** [comment]
用md-it吧，后面不会支持marked了，维护太多套有点耗精力啊

**Comment by unihon** [comment]
啊，我喜欢marked多点
