### ISSUE TITLE
Shortcuts for focus on docks

### ISSUE THREAD

**Issue by atehnix** [tamlok/vnote#1465]
Is it possible to assign keyboard shortcuts for focus to folder list, note list, main area (current tab with note), etc?
Ideally, without using the Captain Mode key.

Keyboard shortcuts would be more convenient than using the mouse or "Tab / Shift + Tab" for this.

For myself, I would set it up like this:

- `Alt + 1` - Folders
- `Alt + 2` - Files
- `Alt + 3` - Tools
- `Alt + 4` - Search
- `Esc` - Back to main area (tab with current note)

Someone might want different keys, so it's better to make them customizable.

**Comment by tamlok** [comment]
Is `ctrl-e w` suitable?

**Comment by atehnix** [comment]
Agree, "Ctrl-E W" is useful. (I also use this in Vimium browser extension)
But, in some cases, using explicit keyboard shortcuts would be more convenient and faster. Press - and immediately know what area I am in.

Switch focus to folders, select, press Enter, switch focus to notes, select, press Enter.

Instead of pressing a sequence of keyboard shortcuts, then look at which letters appear for the folders, and then press those letters. Then repeat all this again for the notes in the selected folder.

**Comment by tamlok** [comment]
Got it. Will consider it.
