### ISSUE TITLE
如何把VNote笔记部署到网站

### ISSUE THREAD

**Issue by luneice** [tamlok/vnote#1466]
OS Version (操作系统): ubuntu 20.04
VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1
Symptoms (表现):
VNote是一个非常出色的笔记管理软件，组织好的md文件如何去生成你静态网站呢？有没有可以提供的开源项目？比如node.js的

How to Repro (如何复现):

**Comment by tamlok** [comment]
参考viki，vnote的主页是通过viki来读取vnote笔记本生成的。

**Comment by luneice** [comment]
> 参考viki，vnote的主页是通过viki来读取vnote笔记本生成的。

好的，谢谢大佬。
