### ISSUE TITLE
国内下载太痛苦了 能不能多分享几个下载链接

### ISSUE THREAD

**Issue by wzmooo** [tamlok/vnote#1474]
百度  189 蓝奏云  GIT太坑了

**Comment by tamlok** [comment]
有百度云的，这几天刚好失效了。

修复了：链接: https://pan.baidu.com/s/1XO-upO2QVpj_kkZCS_ssPA 提取码: 3g5c

**Comment by tamlok** [comment]
好像还是不行：

![image](https://user-images.githubusercontent.com/5763157/88988021-4a6ccf00-d30a-11ea-83b8-d30b6a1e4e40.png)

**Comment by tamlok** [comment]
更换为189了，谢谢推荐！

https://cloud.189.cn/t/Av67NvmEJVBv
