### ISSUE TITLE
创建SSL上下文错误

### ISSUE THREAD

**Issue by LiuJiaBaiDing** [tamlok/vnote#1477]
系统是深度v20_

在使用码云 Gitee做为图床使用时,一上传图片就报这个错误
![ss](https://bbs.deepin.org/data/attachment/forum/202008/01/184824u7wnzk92p9yfnxl5.png)

**Comment by tamlok** [comment]
官网下载的appimage吗？openssl的问题。

**Comment by LiuJiaBaiDing** [comment]
对的  官网下载的。
我同时也在win10 用码云做图床，是可以成功的
在深度v20就报这个错误

**Comment by tamlok** [comment]
你可以安装一下openssl
