### ISSUE TITLE
Feature request: add theme with blank .qss file (to inherit the system theme style)

### ISSUE THREAD

**Issue by actionless** [tamlok/vnote#148]
I think for desktop applications most of the users prefer when they are following the common system appearance theme.

having blank .qss file in theme folder already solves the issue for me:

![2018-03-01--1519861658_2027x2116_scrot](https://user-images.githubusercontent.com/1655669/36819565-424207ce-1cea-11e8-87ba-d541895dd9d2.png)

**Comment by tamlok** [comment]
I think it should be kept as a user's custom theme rather than a built-in theme.

I have been playing a lot with the theme and look of VNote.

At first, it looks like this which was blamed by some users that it looks like an app from Windows 98 time.

![image](https://user-images.githubusercontent.com/5763157/36941773-3646a158-1f9e-11e8-9510-1f942fc911a1.png)

Then the `v_white` theme:

![image](https://user-images.githubusercontent.com/5763157/36941775-4309684e-1f9e-11e8-99e8-b04386202b8a.png)

And the `v_pure` theme:

![image](https://user-images.githubusercontent.com/5763157/36941778-4ca4966c-1f9e-11e8-8dbc-cbbd3b31068a.png)

And the `v_moonlight` theme:

![image](https://user-images.githubusercontent.com/5763157/36941782-574dcf48-1f9e-11e8-95fd-7168c361dfd5.png)

For a developer, it is really hard to design.

Thanks! :)

**Comment by actionless** [comment]
i think you can name it as new theme `v_system` or `v_native`

**Comment by tamlok** [comment]
It is so rude that just delete the `qss` file. I will reduce the `v_white` theme to inherit most of the system's style. Maintaining too many built-in themes is a heavy burden to me. :)

Thanks!

**Comment by actionless** [comment]
actually maintaining a blank qss file shouldn't take that much effort ;)

you should think of linux users -- almost each linux distro have slightly different visual look by default. so approach of having couple of themes with hardcoded colors could work well on windows but wouldn't work well if someone have, let's say, brown-and-pink or violet-and-yellow UI colors by default

especially important the 'temperature' of grays -- for example in your first two themes they gray temperature is neutral and in the last one it's slightly cold: that wouldn't work good with warm or completely cold temperature themes

**Comment by tamlok** [comment]
OK, I got what you mean. I will change `v_white` to that.

Thanks!

**Comment by tamlok** [comment]
BTW, your work [oomox](https://github.com/actionless/oomox) is amazing. I wonder if you could help to design a pallete for VNote, such as the background, foreground, selected foreground, disabled foreground, and so on. That would be really great! :)

**Comment by actionless** [comment]
feel free to pick any of oomox palettes if you want to -- they already have `background, foreground, selected foreground` but not `disabled foreground` (it's computed during theme generation, just mix of foreground and background)

btw oomox also exports palettes for `qt5ct` tool

**Comment by tamlok** [comment]
Replaced `v_white` with `v_native` (84df970e22749210bd6470a4db898e5108ebd41a).

![_1521364819_1039833868](https://user-images.githubusercontent.com/5763157/37564421-ab239d9a-2ad0-11e8-8f5b-5a97861a61a5.png)

**Comment by actionless** [comment]
thanks!

i've only noticed what titles of the sidebars and especially name of the notebook are still using too light colors:

![2018-03-18--1521379870_2175x1341_scrot](https://user-images.githubusercontent.com/1655669/37566416-0ceba3fa-2ab9-11e8-9894-fa2d8b13b054.png)

and with a dark theme there is a problem with the text color:

![2018-03-18--1521380026_2210x1063_scrot](https://user-images.githubusercontent.com/1655669/37566433-6942499c-2ab9-11e8-9575-51680c2392d0.png)

**Comment by tamlok** [comment]
So you mean the dark theme of you desktop env? I will empty all the hard-coded color in v_native.

**Comment by actionless** [comment]
i was using this qt5 palette:

```conf
#               FG              BTN_BG bright less brdark        less da     txt fg               br text              btn fg           txt bg     bg     shadow   sel bg     sel fg     link       visited           alt bg default          tooltip bg  tooltip_fg
[ColorScheme]
  active_colors=#d4d6d5,          #0d0e10, #0d0e10, #0d0e10, #0d0e10, #0d0e10, #aaad78,           #aaad78,           #d4d6d5,           #1d1f23, #0d0e10, #0d0e10, #886c95, #0d0e10, #886c95, #d4d6d5,            #0d0e10, #d4d6d5,           0d0e10,  #838882
disabled_colors=#a2a4a3, #0d0e10, #0d0e10, #0d0e10, #0d0e10, #0d0e10, #868962,  #868962,  #a2a4a3,  #1d1f23, #0d0e10, #0d0e10, #886c95, #0d0e10, #886c95, #a2a4a3,   #0d0e10, #a2a4a3,  #0d0e10, #656965
inactive_colors=#d4d6d5,          #0d0e10, #0d0e10, #0d0e10, #0d0e10, #0d0e10, #aaad78,           #aaad78,           #d4d6d5,           #1d1f23, #0d0e10, #0d0e10, #886c95, #0d0e10, #886c95, #d4d6d5,            #0d0e10, #d4d6d5,           #0d0e10, #838882

#               FG              BTN_BG     bright   less br  dark     less da  txt fg               br text  btn fg     txt bg     bg     shadow   sel bg     sel fg     link       visite alt bg default  tooltip bg  tooltip_fg
#  active_colors=#d4d6d5,          #aaad78, #0d0e10, #cbc7c4, #9f9d9a, #b8b5b2, #aaad78,           #ff0000, #19140e, #1d1f23, #0d0e10, #767472, #886c95, #0d0e10, #886c95, #d4d6d5,            #0d0e10, #d4d6d5,           0d0e10, #838882
#disabled_colors=#a2a4a3, #aaad78, #0d0e10, #cbc7c4, #9f9d9a, #b8b5b2, #868962,  #ffec17, #19140e, #1d1f23, #0d0e10, #767472, #886c95, #0d0e10, #886c95, #a2a4a3,   #0d0e10, #a2a4a3,  #0d0e10, #656965
#inactive_colors=#d4d6d5,          #aaad78, #0d0e10, #cbc7c4, #9f9d9a, #b8b5b2, #aaad78,           #ff9040, #19140e, #1d1f23, #0d0e10, #767472, #886c95, #0d0e10, #886c95, #d4d6d5,            #0d0e10, #d4d6d5,           #0d0e10, #838882
```

**Comment by tamlok** [comment]
For the dark theme, you need to tune it yourself. You could use v_moonlight as the base.

**Comment by actionless** [comment]
with blank qss it works except for toolbar icons color:
![2018-03-19--1521450378_1924x1066_scrot](https://user-images.githubusercontent.com/1655669/37586636-41cd54de-2b5d-11e8-8fda-836ba0887c10.png)

**Comment by tamlok** [comment]
Nope. You need to tune the mdhl file and other VNote-specific widgets.

**Comment by actionless** [comment]
yup, i left blank only qss style file, other files i took from one of the existing themes (otherwise as you said it was missing some stuff)
