### ISSUE TITLE
希望增强图片管理功能

### ISSUE THREAD

**Issue by uname2p** [tamlok/vnote#1484]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): v 2.9.1

Symptoms (表现):
以下功能遇到一个图片多出引用的时候会有逻辑问题，但是一般情况都是一个图片只出现在一个笔记内。

功能1：新增右键删除图片
现在有复制图片路径的功能，但是没有提供图片删除功能。
场景：写教程的时候会遇到需要变更图片的情况，我想要直接贴个新的截图，并直接删除老的图片。但是页面现在没有直接删除图片的功能，而需要去图片文件夹下手动删除，如果操作次数多，来回切换图片比较繁琐，而且图片文件夹内图片多的时候找图片变得很困难。

功能2：图片跟随笔记迁移
直接粘贴图片会默认放入笔记所属文件夹下的v_images目录下，但是我笔记日后从A迁移到B时，笔记关联图片不会从A下的v_images自动迁移到B目录下的v_images下，需要手动去迁移图片。
场景：刚开始我笔记内容不够多，所以笔记就分布在四五个文件夹内，后来笔记多了之后我需要做分类管理，此时迁移笔记时相关的图片归属变得头痛无比。

**Comment by tamlok** [comment]
Hi,

1. VNote会在保存的时候自动删除没有被引用的图片，无需手动管理。
2. 直接右键复制剪切笔记（是笔记文件，不是内容），然后粘贴到其他文件夹的时候，vnote会自动将图片复制或者移动到目标文件夹下面。

如果发现上面两点不工作，请贴详细md文本。

谢谢！

**Comment by uname2p** [comment]
@tamlok tamlok 解答了我的疑惑，感谢您的专业指点
