### ISSUE TITLE
最大化时高度尺寸不匹配

### ISSUE THREAD

**Issue by uname2p** [tamlok/vnote#1485]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
屏幕尺寸 1920x1080
竖向三列布局，每列都只占用了屏幕高度的一半，横向也没有满屏布局，需要点击右上角的“向下还原”按钮，然后再次点击“最大化”按钮”才能满屏布局

How to Repro (如何复现):
关闭软件前，将软件尺寸调整为“最大化”，然后关闭软件，再次打开软件，就会出现屏幕尺寸不匹配的情况，异常情况见附件
![2020-08-10_165702](https://user-images.githubusercontent.com/19523804/89766821-5850fa00-db2b-11ea-9ad5-dd21eaacf26f.png)

**Comment by tamlok** [comment]
Hi, 请参考置顶issue的关于显卡驱动或者OpenGL的问题进行解决即可。

**Comment by uname2p** [comment]
@tamlok 确实时OpenGL的问题，我进入设置项，将OpenGL由默认“修改”为“DeskOpenGL”就解决了。刚开始以为要更新驱动，实际上建议优先改一下设置项目。
