### ISSUE TITLE
字数统计

### ISSUE THREAD

**Issue by LeoXing1996** [tamlok/vnote#149]
首先感谢开发者，请问vnote有字数统计功能嘛，如果没有的话希望能够添加一下~

**Comment by tamlok** [comment]
暂时还没有，不过已经在计划中。

**Comment by LeoXing1996** [comment]
辛苦啦，谢谢开发者~

**Comment by tamlok** [comment]
Hi, 已经实现了(9710659a003ce4283065197a3af30e59014ceb85)，下一个版本会带上！

谢谢！
