### ISSUE TITLE
Windows 10 八月份更新之后，VNote打开笔记闪退

### ISSUE THREAD

**Issue by idweball** [tamlok/vnote#1497]
- OS Version (操作系统): Windows, Linux, macOS

  Microsoft Windows [版本 10.0.18363.959]

- VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

  2.9.1   67fd713820def1e434423acd981715ded10387c6 

- Symptoms (表现):
  
   VNote打开之后，然后点击一篇笔记打开，立马闪退。

- How to Repro (如何复现):

**Comment by idweball** [comment]
这是问题GIF图
![vnote-闪退](https://user-images.githubusercontent.com/18215336/90997069-08763680-e5f3-11ea-8372-d8c170718470.gif)

**Comment by tamlok** [comment]
Hi,

看一下置顶issue： https://github.com/tamlok/vnote/issues/853

显卡驱动或者opengl的问题，设置一下即可。

**Comment by idweball** [comment]
在设置里将OpenGL修改成如下恢复正常
![image](https://user-images.githubusercontent.com/18215336/90999197-94d72800-e5f8-11ea-84c3-8941ea5d9f6c.png)

**Comment by idweball** [comment]
@tamlok  已恢复正常，谢谢提示
