### ISSUE TITLE
数学公式不渲染

### ISSUE THREAD

**Issue by stweiyy** [tamlok/vnote#1500]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
数学公式，无论是inline 还是$$ .. $$都不渲染。

How to Repro (如何复现):
markdown设置里面已经设置了mathjax的网站（默认设置）

**Comment by tamlok** [comment]
md菜单，扩展，公式，开启

**Comment by stweiyy** [comment]
没有这个“公式开启”呀。
![Screen Shot 2020-08-27 at 10 41 27 AM](https://user-images.githubusercontent.com/8340784/91457145-0c53c400-e852-11ea-8547-f722a67398d4.png)

**Comment by stweiyy** [comment]
okay. 好了。谢谢！
