### ISSUE TITLE
formula edit experience need improvement

### ISSUE THREAD

**Issue by makefile** [tamlok/vnote#153]
Editing formula in plain text mode is very easy to have mistake, so add a instant preview for inserting formula just like `Typora` and `Yu writer` does is essential.

**Comment by tamlok** [comment]
Yeah, it is designed to be previewed in place just like what image does now. The road map is full text search, then formula preview, then chart preview, and then plantUML enabled.

Thanks!

**Comment by tamlok** [comment]
1.15 now support in-place preview of MathJax. Please give it a try!

Thanks!

**Comment by makefile** [comment]
That is really great! Thanks!
