### ISSUE TITLE
vnote 频繁卡死

### ISSUE THREAD

**Issue by wxknxxzj** [tamlok/vnote#1530]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.1,  d78e892d5cc  etc..

Symptoms (表现):
![图片](https://user-images.githubusercontent.com/69200664/94927720-3e151600-04f5-11eb-94df-6f4d8299c831.png)

How to Repro (如何复现):
打开后，使用vim模式，或者使用快速入口查找全部笔记等

**Comment by tamlok** [comment]
大佬，看一下置顶issue呀

**Comment by wxknxxzj** [comment]
> 
> 
> 大佬，看一下置顶issue呀

好的，看到了。这是什么原理啊？

**Comment by l00c00l** [comment]
不知是否graphviz的原因，VNote在浏览模式下，无法滚动页面--而且CPU发出一种负重的声音。
切换回编辑模式，立马好了。
没有安装graphviz之前，没有发现这个问题。

**Comment by tamlok** [comment]
如果是windows，可以看看置顶的openssl问题。
