### ISSUE TITLE
1.12-Single click in file list-Why open a new tab first?

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#154]
version 1.12's new feature: "Single click in file list to open file in current tab"

There is no bug here. 

I'm just curious why bother to open a new tab first and then close the old one. The whole process takes a little more time than before. Is that possible to directly switch the view to the new file, and buffer or delete the old file object?

**Comment by tamlok** [comment]
When we double click the item, Qt will emit two single click signals and one double click signal. The double click signal will be emitted after the first single click signal. Hence there is an interval used to judge whether two singla clicks will trigger a double click.

Thus we need to wait for that interval to decide whether we should open the note in current tab or a new tab. Opening the note in a new tab first indeed is a kind of acceleration: we do not need to wait for that interval before loading the content.
