### ISSUE TITLE
新版不支持上下标了吗？

### ISSUE THREAD

**Issue by heartnn** [tamlok/vnote#157]
就是比如^和~，像平方立方和角标这样的。用sup和sub太麻烦了

**Comment by tamlok** [comment]
是的，因为如果启用了上下标语法，MathJax公式的很多符号需要转义。后面，我加一个开关选项吧，默认关闭，可以按需启用。

**Comment by heartnn** [comment]
这个应该是可以识别$和$$的内外吧？如果在$内就不解析，这样做就完美了

**Comment by tamlok** [comment]
VNote使用以下两个插件来支持上下标：

[markdown-it-sup](https://github.com/markdown-it/markdown-it-sup)
[markdown-it-sub](https://github.com/markdown-it/markdown-it-sub)

我会向他们提交issue，或者你熟悉JS的话，也可以直接修改一下代码给VNote使用。

谢谢！

**Comment by tamlok** [comment]
添加开关了，在Markdown菜单下面。
