### ISSUE TITLE
High-resolution adapting.

### ISSUE THREAD

**Issue by wyhhh** [tamlok/vnote#159]
Hello,author,I want to say it's a good production for me,nowadays is the best.But,
I have been using 3840x...,four k resolution screen,so,some of widget of software don't work well,they are too small,such as scrolling bar.
I hope this will be better and better,the cost of this software is considered by me.

**Comment by wyhhh** [comment]
顺便问下,这是国人开发的还是外国的呀?我上面都写的英文

**Comment by tamlok** [comment]
Hi, I do not have a 4K display to test VNote. For my 2K display, it works fine. Qt has a good support for high resolution display. There are some custom configs which are hard-code pixel values. I need to find out widgets that do not work well and tune them. So could you please help to take some snapshots and point them out?

Thank you for the feedback!

P.S 中文英文都可以，英文的话可以供更多人参考。:)

**Comment by wyhhh** [comment]
![qq 20180310131334](https://user-images.githubusercontent.com/28824519/37238615-35990612-2465-11e8-8843-0f75990f59ad.png)
上图你对比下你的.
不知道是不是底层框架的支持问题,比如java9就全面支持高分屏了好像.这个是C类语言写的吧?响应就是快,而且有些idea不错.

**Comment by tamlok** [comment]
Fixed (49e2c7412284e2beecbbe1a9fb4831ae24cb774e). It should now be better. If you feel anything wrong, please report it, since I do not have a 4K display to test. Theme `v_native` should be better in theory. Please try it out in next version 1.13.

Thanks!

**Comment by wyhhh** [comment]
Thank you.I'll try it immediately until published.
