### ISSUE TITLE
大纲的问题

### ISSUE THREAD

**Issue by wyhhh** [tamlok/vnote#161]

**Comment by wyhhh** [comment]
上面无视.
编辑区东西一多右边大纲就只显示最大量了,大概4000行,可能还不到.求修复啊!

**Comment by tamlok** [comment]
有截图说明一下吗？下次发issue还是把前面的那段说明删了吧。谢谢！

**Comment by wyhhh** [comment]
![image](https://user-images.githubusercontent.com/28824519/37249603-a38d85d8-2525-11e8-96fc-1b66a640c4df.png)


如图,东西一多,就只剩下这点了

**Comment by tamlok** [comment]
还是不太明白。您说的是大纲有问题吗？这张图说明不了什么问题呀，大纲只会显示文章的所有标题，比如`# abc`或`### abc`这种，正文多长和这个没有关系。

谢谢！
