### ISSUE TITLE
Cannot scroll up/down in edit mode on Surface's touch screen

### ISSUE THREAD

**Issue by pisces312** [tamlok/vnote#162]
In 1.12 version, when the finger moves across lines in edit mode, it will only select the contents. 
Can we make the same behavior as OneNotes does?

**Comment by tamlok** [comment]
It seems that it is an old bug of Qt [here](https://bugreports.qt.io/browse/QTBUG-40461). Maybe two fingers touch will work? I don't have any idea about how to implement this.

Thanks!

**Comment by pisces312** [comment]
Two-finger touch works on Surface... Thanks.
Just build my Windows version today. Not get much time before due to family things... Hope I can commit something later.
