### ISSUE TITLE
Import existing file in place

### ISSUE THREAD

**Issue by pisces312** [tamlok/vnote#164]
My use case is that I pushed the whole note folder to git from PC.
Then I pulled it to my phone and added a new file to the existing VNote sub-folder.
On PC, I pulled the change and tried to import the new file, it will generate a new file because the file is already existed.
E.g.
    The folder "TODO" is created by VNote.
    My new file is TODO/test.txt
    After importing test.txt, it will create test_001.txt.

Can we just add meta data to _vnote.json in this scenario or refresh the folder on demand to manage the untraced file?

Maybe you can share some instruction about how to setup Windows environment. This is a simple feature.

**Comment by tamlok** [comment]
Since many users have been asking for auto-scanning of external files, I will add a feature to scan and import existing notes in place.

Thanks!

**Comment by tamlok** [comment]
Hi, 1.14 supports import external files in current folder in place without copying it. Please give it a try. :)
