### ISSUE TITLE
添加数学公式的快捷键

### ISSUE THREAD

**Issue by stanleywu111** [tamlok/vnote#166]
因为经常打数学公式，希望可以添加数学公式的快捷键

**Comment by tamlok** [comment]
Hi, 数学公式的快捷键是指插入`$ $`或`$$ $$`吗？如果是这个，可以尝试使用一下**片段**，通过分配一个快捷键字母，能够使用类似于`Ctrl+E S a`的按键序列插入相关符号。

谢谢！

**Comment by tamlok** [comment]
1.15已经支持公式原地预览，相信体验会好不少！谢谢！

**Comment by blackredscarf** [comment]
@tamlok 你好，公式原地预览可以选择关闭吗？虽然能实时看到是不错，但公式太多反而影响编辑文字。

**Comment by l0o0** [comment]
> 
> 
> @tamlok 你好，公式原地预览可以选择关闭吗？虽然能实时看到是不错，但公式太多反而影响编辑文字。
@tamlok 你好啊，我也发现有的时候公式预览真是会把格式打乱，希望可以有关闭公式预览的设置

**Comment by tamlok** [comment]
@blackredscarf @l0o0 后面会添加开关。谢谢！
