### ISSUE TITLE
建议拖动目录到vnote文件夹窗口

### ISSUE THREAD

**Issue by jerry011235** [tamlok/vnote#168]
建议可以手动从 资源管理器 拖动目录（文件夹）到 vnote文件夹窗口，并且可以新建，删除，编辑已有的md文件。
也可以设置一个 菜单栏- 文件-打开文件夹 。

有时需要编辑多个文件夹的多个md文件，所以需要这个需求，而不仅仅是设置一个总的my_vnotes 文件夹。
图片资源可以使用全局设置，也可以全部使用外部链接。

**Comment by tamlok** [comment]
1.17支持浏览器直接浏览外部文件。
