### ISSUE TITLE
 【需求】发布linux版本

### ISSUE THREAD

**Issue by hnyaoqingping** [tamlok/vnote#17]
能编译个linux下的发行版吗？

**Comment by tamlok** [comment]
Hi，Linux下的打包比较复杂，因为发行版实在太多了。后面会再研究一下怎么搞。您目前可以在Qt官网下载一个Qt，自行编译，步骤也比较简单。
您是什么发行版呢？
我尽快看看怎么打包吧。
谢谢关注！

**Comment by hnyaoqingping** [comment]
这么快就回应了，非常感谢。我是用Archlinux的，以前也没弄过打包。下午试着打了一下包，在我的电脑上是能安装了。如你能用得上，请参考一下。地址: https://github.com/hnyaoqingping/VNote-under-archlinux

**Comment by tamlok** [comment]
@hnyaoqingping 赞！谢谢使用！后面欢迎反馈！

**Comment by tamlok** [comment]
目前VNote编译有AppImage格式的执行文件，大多数发行版都支持！由于VNote使用的Qt 5.7很多发行版还没支持，所以后面会尝试在一些滚动发行版上发布打包。谢谢～～
