### ISSUE TITLE
配置文件位置

### ISSUE THREAD

**Issue by Merodi** [tamlok/vnote#172]
建议别把配置文件放在 C:\Users\<User>\AppData\Roaming\vnote 里，做个Protable的选项可以定义在应用程序的目录里，这样放u盘里用也不用担心换了电脑设置就没了

**Comment by wyhhh** [comment]
可以做成类似于IntelliJ IDEA,导出个XML或者JSON文件,后面配置越来越多.

**Comment by tamlok** [comment]
Hi, 请参考[文档](http://vnote.readthedocs.io/en/latest/user_docs/faqs.html#how-to-make-vnote-more-portable)，可以让VNote在可执行文件所在目录优先读取配置文件。

谢谢！

**Comment by tamlok** [comment]
可以参考 https://github.com/tamlok/vnote/issues/141
