### ISSUE TITLE
win10打开后，点击笔记后卡死

### ISSUE THREAD

**Issue by ice-doom** [tamlok/vnote#173]
打开vnote后，点击笔记卡死。
后来我打开vnote，点击别的笔记后，再点击之前卡死的那个笔记，弹出是否从备份中恢复还是放弃备份的弹窗。好像是因为那个弹窗导致卡死。

**Comment by tamlok** [comment]
谢谢反馈！后面会重新理一下这块逻辑！

**Comment by hirCodd** [comment]
点击备份的逻辑貌似是有问题的，点击取消备份卡死，可能导致卡死很多次...

**Comment by tamlok** [comment]
@hirCodd 请下载1.14看还能不能复现这个问题？谢谢！
