### ISSUE TITLE
UI的建议

### ISSUE THREAD

**Issue by wyhhh** [tamlok/vnote#174]
功能上还好,只是偶尔备份功能多个文件连续提示时会无响应.整体UI能不能更高大上点?感觉有点不好看

**Comment by wyhhh** [comment]
换点配色也成,毕竟我还年轻,希望火热点的配色

**Comment by tamlok** [comment]
Hi, 请参照[文档](http://vnote.readthedocs.io/en/latest/user_docs/themes_and_styles.html)进行自定义主题，目测可以修改下面几个颜色即可：

```ini
[phony]
; Abstract color attributes.
master_fg=#F5F5F5
master_bg=#00897B
master_light_bg=#80CBC4
master_dark_bg=#00796B
master_focus_bg=#009688
master_hover_bg=#009688
master_pressed_bg=#00796B
```

谢谢！

**Comment by hirCodd** [comment]
哈喽，左侧导航栏的笔记本能否向右移动一点，他离左边太近了，导致很可能看不见名字。一个目录下的笔记能加一个list？在左边做一下标号？如果文件太多，可能都不知道有多少。感谢作者！！目前用到最好用的markdown笔记。

**Comment by tamlok** [comment]
@hirCodd 第一个问题能上图说明一下吗？谢谢！

**Comment by hirCodd** [comment]
@tamlok 
![20184263](https://user-images.githubusercontent.com/20184263/37863654-7b47ca94-2f9c-11e8-82bb-e3262c95ac32.jpg)
只是我个人觉得是这样的，可能全桌面太靠左边了。
有错的话，请谅解。

**Comment by hirCodd** [comment]
![ss](https://user-images.githubusercontent.com/20184263/37863678-03052940-2f9d-11e8-9378-caf5dd688eda.png)
全屏幕的话我个人觉得是的确太偏左边了，可以稍微向右边一点？
如果有错的话，请谅解。

**Comment by tamlok** [comment]
@hirCodd OK，那我加点margin，谢谢！
