### ISSUE TITLE
左侧出现小红块

### ISSUE THREAD

**Issue by wyhhh** [tamlok/vnote#175]
![image](https://user-images.githubusercontent.com/28824519/37815706-e0e4e9d8-2eaa-11e8-94d6-555c75ec4ce6.png)

如图,

**Comment by tamlok** [comment]
Hi, 请确认下图的设置为`0`。

![image](https://user-images.githubusercontent.com/5763157/37824477-b384ff06-2ec7-11e8-8816-cddba1e4abfa.png)

**Comment by wyhhh** [comment]
这功能什么意思?

**Comment by tamlok** [comment]
高亮代码块第几列，来自Vim的[ColorColumn](https://vi.stackexchange.com/questions/356/how-can-i-set-up-a-ruler-at-a-specific-column)。
