### ISSUE TITLE
复制图片的问题

### ISSUE THREAD

**Issue by wyhhh** [tamlok/vnote#176]
为什么只有复制的内容中有图片和文字,只出图片,文字呢

**Comment by tamlok** [comment]
什么意思？具体说明一下？

**Comment by wyhhh** [comment]
比如有一段文字和一张图片被复制了,再ctrl+v时会弹出图片的提示框,确认后只会有图片上去

**Comment by tamlok** [comment]
能不能再具体一点？在哪里复制一段什么样的文字图片，粘贴的时候弹出什么对话框？

**Comment by wyhhh** [comment]
![image](https://user-images.githubusercontent.com/28824519/37872051-4660bb98-3031-11e8-8af6-3d422c25b817.png)
![image](https://user-images.githubusercontent.com/28824519/37872059-5dea5da0-3031-11e8-90ca-0787a88dcf00.png)

**Comment by tamlok** [comment]
明白了。当前还不支持将混排富文本解析为md，只能分开复制粘贴。

**Comment by tamlok** [comment]
1.22已经支持
