### ISSUE TITLE
java代码，部分代码无法高亮显示

### ISSUE THREAD

**Issue by zhangmeng001** [tamlok/vnote#177]
如图,java代码，部分代码无法高亮显示，不知道是bug还是我写的有问题，代码直接从api复制的应该没问题。

编辑模式下：
![123](https://user-images.githubusercontent.com/18597442/37871682-5c507994-3026-11e8-8a4a-b67d6512c4a0.png)

阅读模式下：
![456](https://user-images.githubusercontent.com/18597442/37871684-6f63673a-3026-11e8-98d7-ad9c0f07c316.png)

代码如下：
```java
public Constructor<T> getConstructor(Class<?>... parameterTypes);
public Constructor<?>[] getConstructors();
public Constructor<T> getDeclaredConstructor(Class<?>... parameterTypes);
public Constructor<?>[] getDeclaredConstructors();
```

**Comment by tamlok** [comment]
Hi, 非常感谢反馈！VNote是直接调用[highlight.js](https://highlightjs.org/)来进行语法高亮的。这个问题应该是highlight.js本身的问题。估计是通过正则表达式来高亮的，所以有些高级或新的语法可能会出错。

谢谢！
