### ISSUE TITLE
在有备份文件提示时,无响应

### ISSUE THREAD

**Issue by wyhhh** [tamlok/vnote#178]
![image](https://user-images.githubusercontent.com/28824519/37875010-e1f7c8be-306b-11e8-85e5-394f90ecf412.png)

经常在弹出存在备份文件时OS提示程序无响应,只得重启

**Comment by wyhhh** [comment]
顺便问下,需要开自动保存么,自动备份能保证内容不丢?

**Comment by tamlok** [comment]
自动保存就是定时保存文件的修改。备份文件就是将修改写到一个临时文件。

**Comment by tamlok** [comment]
请确认一下1.14下是否还有这个问题，谢谢！
