### ISSUE TITLE
附件可否像插入的图片一样，在文中标记显示？

### ISSUE THREAD

**Issue by JunjieLink** [tamlok/vnote#179]
例如插入的图片语法是
`![](images/image.png)`

那么插入附件可否是：
`![](files/file.pdf)`

这样在插入多个附件的时候，能在文中清楚地显示哪个地方引用了哪些文件。
（当然，如果可以点击打开就更加好了。）

VNote 真的很棒，一直在找这样的笔记系统，今天才在 V2EX 上看到，相见恨晚。

**Comment by tamlok** [comment]
附件其实是游离于md之外的，只是方便将一些有关系的文件放在一起。目前VNote也基本满足需求了，作为业余非盈利项目，后面的开发得看时间和精力，可以考虑支持插入附件链接。

谢谢支持！

**Comment by JunjieLink** [comment]
非常感谢，希望 VNote 越来越好！

**Comment by tamlok** [comment]
hi，

2.0支持通过幻词%att%插入当前附件目录的相对路径，结合片段功能，能比较方便地通过快捷键插入到附件的链接。

谢谢！

**Comment by JunjieLink** [comment]
实在是太棒了！Thanks!

**Comment by tamlok** [comment]
后面会支持复制附件文件路径，然后插入为相对路径。

**Comment by JunjieLink** [comment]
期待 VNote 越来越棒！
