### ISSUE TITLE
标题带序号

### ISSUE THREAD

**Issue by royoan** [tamlok/vnote#18]
你好，请问标题可以带序号吗？
例如：
1. XXXXX
   1.1 XXXXX
   1.2 XXXXX
2. XXXXX

**Comment by tamlok** [comment]
您好！是在`[TOC]`的时候带上序号吗？还是标题本身带上序号？如果是前者，后面可以实现自动在`[TOC]`里面带上序号；如果是后者，目前展示只能先由用户输入一下序号了，因为自动编号强制改变用户的输入，有时候会适得其反。

谢谢反馈！

**Comment by royoan** [comment]
我想要的效果是后者，因为这样写起来和看起来更有逻辑感， 
可以加一个开关设置， 标题自动加上序号，或不加序号，你觉得怎样？

**Comment by tamlok** [comment]
@royoan OK. 后面有时间弄一个。谢谢反馈！

**Comment by aaronnew** [comment]
大纲功能的一点建议，可以参考此项目：https://github.com/i5ting/i5ting_ztree_toc，在长文中如板书、说明文档都非常实用。期待ing。

**Comment by tamlok** [comment]
@aaronnew Thanks! 后面会添加支持！

**Comment by tamlok** [comment]
@royoan @aaronnew Hi, 已实现自动标题编号(2eb6476c3d0be747bd2c35b9c46151226e2da57d)，可以在`设置`里面开启。请关注下一个版本或者尝试最新构建版本！谢谢反馈和支持！
