### ISSUE TITLE
Can not detect new theme

### ISSUE THREAD

**Issue by Honghe** [tamlok/vnote#180]
- When reporting problems, elaborate it as detailed as possible like:
    - Version of VNote, which operating system; VNote 1.13, Ubuntu 16.04.4
    - What is the symptoms; Can not detect new theme folder even restart app.
    - What action triggered it; add new theme folder
    - How to reproduce it;

**Comment by tamlok** [comment]
Please try to copy a built-in theme, and rename the `.palette` file. You could reference the [documentation](http://vnote.readthedocs.io/en/latest/user_docs/themes_and_styles.html).

**Comment by Honghe** [comment]
OK, got it. Maybe only copy a theme folder without renaming the `.palette` file is better pratice.

**Comment by tamlok** [comment]
Yes. For now just let it be. :)
