### ISSUE TITLE
How to open developer mode just like Chrome F12

### ISSUE THREAD

**Issue by Honghe** [tamlok/vnote#181]
When reporting problems, elaborate it as detailed as possible like:
* Version of VNote, which operating system; VNote 1.13, Ubuntu 16.04.4

Thanks!

**Comment by tamlok** [comment]
According to Qt's [documentation](https://doc.qt.io/qt-5.10/qtwebengine-debugging.html), you could declare environment variable `QTWEBENGINE_REMOTE_DEBUGGING` to a local port, such as `2000`, then open Chrome and access `localhost:2000` after launching VNote.

Thanks!
