### ISSUE TITLE
自动识别成超链接

### ISSUE THREAD

**Issue by ice-doom** [tamlok/vnote#182]
当我输入的内容有xx.py时，阅读模式就自动把这个识别成一个超链接，但是我只是想把这个当成普通文字。我把它前面空出一个空格，并且还对.进行转义仍然不行。

**Comment by tamlok** [comment]
Hi，

有两个解决方法：

- 在Markdown菜单的`markdown-it选项`中的`linkify`勾选去掉，重新打开当前标签页。
- 使用反引号行内代码来括住这种特殊元素。

谢谢！
