### ISSUE TITLE
如何直接打开多个MD文件

### ISSUE THREAD

**Issue by lanlandeye** [tamlok/vnote#183]
更新至V1.12之后，发现一个问题，在左下角笔记列表中点击打开一个MD文档之后，我想再打开另外一个MD文件，这个时候，中间编辑/查看文件内容区域的Tab上会打开对应文件，但内容还未显示，就把之前打开的那个文件关闭了，只剩下后打开的文件显示在Tab上，而且不管点击左下角笔记列表中任何其他的文件名，最后只有最后一次点击的文件被打开，其他都被关闭了。如果我想打开多个文件同时显示，我需要在其他的文件上点击鼠标右键，选择“以阅读模式打开”或“以编辑模式打开”才可以多个文件同时查看/编辑

**Comment by amitbha** [comment]
好像要双击打开，单击是预览

**Comment by tamlok** [comment]
hi，这是很多用户要求的新功能，单击在当前标签页中打开，双击在新标签页中打开。

谢谢！

**Comment by lanlandeye** [comment]
学习了。非常感谢，希望 VNote 越来越好！
