### ISSUE TITLE
Why I can't open more than one tab?

### ISSUE THREAD

**Issue by fastmind2014** [tamlok/vnote#184]
version: v1.13 , OS: win7 and MacOS
When I open one article, I can't open another in a new tab. Instead, the new one shows and the old one is closed.

**Comment by tamlok** [comment]
This is a new feature: single click to open a note in current tab, double click to open in a new tab.

I will make it disabled by default in next version.

Thanks!

**Comment by tamlok** [comment]
Please download 1.14 and have a try.
