### ISSUE TITLE
编辑模式下大纲显示不正确？

### ISSUE THREAD

**Issue by LeoXing1996** [tamlok/vnote#190]
在编辑模式下，有些情况下三级标题既不高亮也不再大纲中显示，
`ctrl+T`切换到预览模式后高亮与显示均正常
![default](https://user-images.githubusercontent.com/28132635/38415159-2fbde460-39c3-11e8-97a2-db558a9ec3d6.JPG)
![default](https://user-images.githubusercontent.com/28132635/38415165-3130c27c-39c3-11e8-9d19-e2a5c5891e14.JPG)

**Comment by tamlok** [comment]
Hi,

您尝试把`举个例子`后面那个emoj去掉看看？如果可以，请将该文件发送到我邮箱，我具体看看。

谢谢！

**Comment by LeoXing1996** [comment]
去掉emoji之后好了🙃，好神奇
希望未来可以修正~

**Comment by tamlok** [comment]
@LeoXing1996 方便的话，把一个能重现这个问题的示例文件发给我，我不会打这个emoj～～ :)

**Comment by LeoXing1996** [comment]
吼啊，邮件已发送，注意查收🍳
