### ISSUE TITLE
无法加载笔记本(xx)节点(failed to file:xxx)

### ISSUE THREAD

**Issue by jibude** [tamlok/vnote#1901]
![image](https://user-images.githubusercontent.com/49974396/137697399-0ddbefaa-81ea-489b-a1f6-e1d519a88db2.png)
你好不知道操作了什么，所有笔记都无法导入。
@tamlok  
急，好多笔记，我进目录看，看见笔记也有丢失的。。大佬急，帮忙解决下

**Comment by jibude** [comment]
无法导入，无法打开，不知道为什么了？怎么解决下呢？

**Comment by tamlok** [comment]
vx_recyclebin这个文件夹里面有没有你的文件？

**Comment by tamlok** [comment]
根文件夹里面创建一个笔记本是指什么呢？根文件夹一般是指一个已存在的笔记本的文件夹，然后你在这个文件夹里面又新建一个笔记本？如果是这样，那我没测试过这种行为(因为你不能在笔记本里面新建笔记本。

我是说你看看vx_recyclebin下面的文件夹里面有没有你丢失的md文件。

**Comment by tamlok** [comment]
你是在vnote里面进行了删除笔记本的操作？软件应该会提示被删除的文件无法恢复，然后你继续点了确认？如果是这样的话，基本恢复不了了。只能通过数据修复软件，并且需要及时停止对当前盘的进一步写入。
