### ISSUE TITLE
建议增加ctrl+p功能，快捷搜索、打开笔记

### ISSUE THREAD

**Issue by rexlevin** [tamlok/vnote#1909]
参考joplin、wiz、notable、typora这些，都有ctrl+p这个功能。
如果笔记很多的话，通过ctrl+p功能，能够快速搜索、打开笔记。
下面是notable的ctrl+p的样子。
![image](https://user-images.githubusercontent.com/7332751/139174024-a33c346b-4161-47e8-8640-7fe356c82898.png)

**Comment by rexlevin** [comment]
> vnote里面这叫通用入口，2有，3还没迁移

希望这个功能尽快迁移过来，这是个特别方便、常用的功能。

**Comment by rexlevin** [comment]
这个功能还没有加上么

**Comment by tamlok** [comment]
每次看更新说明即可。

还没加

**Comment by rexlevin** [comment]
> 

快点加上吧，笔记多了这个很方便，一个组合键就可以搜笔记，比现有那个搜索方便多了。
