### ISSUE TITLE
引号问题

### ISSUE THREAD

**Issue by ice-doom** [tamlok/vnote#191]
在编辑模式下双引号是英文字符，但在阅读模式显示的时候就被转成了中文字符，好像只能把这内容加入代码块里才能显示英文字符，但这块内容不想用代码行来展示。

**Comment by tamlok** [comment]
Hi, this is a feature of Markdown-it. See this [demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%20%E5%93%88%E5%93%88%5Cn%5C%22abcd%5C%22%5Cn%5Cn%28c%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D).

It is called **typographer**.

**Comment by tamlok** [comment]
Fixed (b686cc2efea58d5aa4c7ec8926012810f5f5fd96).
