### ISSUE TITLE
Incorrect macOS shortcuts. Ctrl instead of Cmd

### ISSUE THREAD

**Issue by KineticCookie** [tamlok/vnote#192]
## Environment
- Vnote v1.14 installed via brew
- macOS 10.12.6

## Symptoms
Can't use Cmd shortcuts. Instead, it uses Ctrl. Vim mode is disabled.
I tries to save, export and open tools bar. All of them worked with Ctrl.

## How to reproduce
1. open Vnote on mac
2. create note
3. write something
4. try to save with Cmd+S

## Note
I opened `Help -> Shortcuts help` help page, and it says `On macOS, Ctrl corresponds to Command except in Vim mode.` so I think it's kinda bug.

**Comment by tamlok** [comment]
Hi! Since VNote 1.14, all `Ctrl` in the default config will be translated to `Meta`. I just forgot to change the docs. Using `Control` instead of `CMD` will make the experience more identical and minimize the conflicts with system's shortcuts (such as `CMD+G` on macOS will trigger the game bar).

Thanks!

**Comment by tamlok** [comment]
By the way, is `CMD+S` the default standard shortcut to save changes on macOS? If so, I think we need to treat it defferently.

**Comment by KineticCookie** [comment]
Hello!
> By the way, is CMD+S the default standard shortcut to save changes on macOS? If so, I think we need to treat it defferently.
In my experience, yes. TextEdit (built-in), Chrome, IntelliJ IDEA and Sublime Text 3 use Cmd+S shortcut to save. 

> What happens when you trigger CMD+G on macOS?
On macOS 10.12.6 nothing happens. Not sure about other macOS versions.

> Using Control instead of CMD will make the experience more identical and minimize the conflicts with system's shortcuts
I agree, but many applications change Ctrl to Cmd when it comes for macOS. As for me, it feels more "native" when I use Cmd shortcuts.

**Comment by tamlok** [comment]
I see. I will revert my change and let `ctrl` behave as `cmd`.

thanks
