### ISSUE TITLE
MacOS下字体大小问题.

### ISSUE THREAD

**Issue by wyhhh** [tamlok/vnote#193]
**两个问题**

1. 每新建一个文件,默认字体比较小,当我用`ctrl+鼠标滚轮`调节后,再新建又回到默认去了.所以在哪里设置字体大小.
2. 还有新建文件后默认会创建`H1`为文件名,这个我记得在`Win`下可以设置掉,`MacOS`下没找到.谢谢

**Comment by wyhhh** [comment]
补充一点,在MacOS下怎么切换`编辑模式`和`View模式`

**Comment by tamlok** [comment]
Hi,

1. 请参考[文档](http://vnote.readthedocs.io/en/latest/user_docs/themes_and_styles.html)自定义MDHL文件，改变字体大小；
2. 新建笔记的时候，有选择，请注意留意界面提示勾选；
3. `Ctrl+T`或`CMD+T`，视不同版本不一样；

谢谢！

**Comment by wyhhh** [comment]
切换是`ctrl+T`,但是切换两次后就失效了,需要点下`outline`的`title`才又可以了.

**Comment by tamlok** [comment]
I think it is the same issue with this [bug](https://bugreports.qt.io/browse/QTBUG-66207). I will use Qt 5.9 to build it in the travis CI.

**Comment by tamlok** [comment]
Should be fixed. Please download the new DMG file from [here](https://bintray.com/tamlok/vnote/vnote/1.14#files) and test again.

Thanks!
