### ISSUE TITLE
在1.14下无法切换fixit输入法

### ISSUE THREAD

**Issue by bbsteel** [tamlok/vnote#194]
VNote: VNote_x86_64_1.14.AppImage
OS: Ubuntu16.04

编辑模式下, 无法切换到fixit中文输入法

经测试, 1.13版是可以切换的.

**Comment by tamlok** [comment]
您还保留有修复这个https://github.com/tamlok/vnote/issues/185 之前的文件吗？帮忙试试那个能否正常使用？谢谢！

**Comment by tamlok** [comment]
我这边一台16.04虚拟机上测试没问题。

**Comment by bbsteel** [comment]
1.14 初次发布的版本在删除libnss.so后, 可以正常切换fixit输入法. 经过文件夹比较, 新发布的release里少了 libFcitxQt5DBusAddons.so.1  应该是问题的原因:

![2018-04-07 23-03-30](https://user-images.githubusercontent.com/4044553/38456515-02cb22ec-3ab8-11e8-826f-b5b0516f79c6.png)

**Comment by tamlok** [comment]
According to the log of the travis CI, `libFcitxQt5DBusAddons.so.1` should exist in the AppImage (at least the `squashfs-root`. I am now investigating how to remove a file in the AppImage (https://github.com/probonopd/linuxdeployqt/issues/35). Thanks!

**Comment by bbsteel** [comment]
Re-download VNote_x86_64_1.14.AppImage (md5: `c45a480af0a9717c3b4914a572d8403d`), fcitx input method is now OK, and `libFcitxQt5DBusAddons.so.1`  can be found inside Appimage.
