### ISSUE TITLE
支持全局搜索

### ISSUE THREAD

**Issue by Asymp** [tamlok/vnote#2]
请考虑支持全局搜索，在一个笔记本内的所有笔记文件钟查找需要的关键词。笔记记多了之后这个功能会很有帮助。非常感谢。

**Comment by whzecomjm** [comment]
+1

**Comment by ccjeaty** [comment]
+1024

**Comment by wuscloud** [comment]
期待

**Comment by zaixi** [comment]
+1

**Comment by shoaly** [comment]
强烈关注... 
现在市面上所有的笔记软件 都还是有点不好用, 楼主vnote确实解决了几个痛点, 
1 基于 markdown 的, 意味着可以放入git中 版本管理,
2 支持直接插图... 图片也会存在本地... 
3 vim..
4 就等最后这个全盘搜索了!!

**Comment by tamlok** [comment]
终于可以关闭这个issue了！欢迎尝试1.13！
