### ISSUE TITLE
Manually rescanning notebook structure and update _vnote.json

### ISSUE THREAD

**Issue by ANAT01** [tamlok/vnote#200]
If I move some subfolders in notebook manually (in filesystem) Vnote shown warning "Fail to open folder" in old parent folder and not show subfolder in new parent folder because Vnote read from _vnote.json "subdirectories" parameter.

Please, add feature for rescan notebook struckture (include only folders with _vnote.json inside)

**Comment by tamlok** [comment]
Hi, please move note and folders via VNote. VNote is a note-taking app instead of an editor.

Scanning folders recursively is a little non-deterministic. VNote is not so smart to decide which should be added or not now.

Thanks!

**Comment by ANAT01** [comment]
Hmm, I can't move note or folder via VNote (or don't know how)

notebook have that structure:
```
vnotebook/
├── dst
│   ├── dst.md
│   └── _vnote.json
├── src
│   ├── src.md
│   ├── subdir
│   │   ├── subdir.md
│   │   └── _vnote.json
│   └── _vnote.json
└── _vnote.json
```

I try to cut&paste `subdir.md` note or `subdir` folder from `src` to `dsc` root folders and have got Warning "Fail to paste folder ...., Vnote could not find this note(or folder if it) in any notebook"

**Comment by tamlok** [comment]
That is strange! Could you open the src md file? Please create some new folders and notes and then test it again. I am afraid you have damaged the structure of VNote's config files.

**Comment by ANAT01** [comment]
![peek 2018-04-11 16-51](https://user-images.githubusercontent.com/7475811/38615093-e55e4bc8-3da8-11e8-9637-50e05f600bb7.gif)

**Comment by ANAT01** [comment]
![peek 2018-04-11 16-51](https://user-images.githubusercontent.com/7475811/38615677-f5dc4818-3daa-11e8-8722-07f33383605f.gif)

**Comment by tamlok** [comment]
Oh, you found a serious and stupid bug I made in the last version. Please restart VNote after creating a new notebook (when you are prompted to create a folder, just cancel it) and test it again.

Thanks!
