### ISSUE TITLE
Hide markdown content in view mode

### ISSUE THREAD

**Issue by ANAT01** [tamlok/vnote#202]
Can I hide some content separated with '---' block in view mode?
I have markdown file with YAML injections, for example:
```
---
title: My Test Post
author: Johnny Q. Blogger
author_bio: >
             I blog about things, and my middle
             inital is Q. You’ll never guess
             what the ‘Q’ stands for. Trust me.
layout: post
---

# Lorem ipsum?

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
 incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
 nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu 
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in 
culpa qui officia deserunt mollit anim id est laborum.

```

Examples: [one](https://raw.githubusercontent.com/getgrav/grav/develop/user/pages/01.home/default.md), [two](https://raw.githubusercontent.com/getgrav/grav/develop/user/pages/02.typography/default.md)

**Comment by tamlok** [comment]
In my opinion, Markdown files should contain contents only, not including the metadata.

I will add an option to hide these info when in read mode.

**Comment by tamlok** [comment]
Please try 1.15 and enable it in the `Markdown-it Option` menu.

**Comment by ANAT01** [comment]
Thank you!
Hiding work!, but option not work if disabled.

![peek 2018-05-01 00-32](https://user-images.githubusercontent.com/7475811/39446293-774629c4-4cd7-11e8-8038-e33e19933374.gif)

**Comment by tamlok** [comment]
Will display it as a code block in next version.

Thanks!
