### ISSUE TITLE
和上次黑色背景一样,白色也出现偏色现象

### ISSUE THREAD

**Issue by wyhhh** [tamlok/vnote#203]
![image](https://user-images.githubusercontent.com/28824519/38741124-c5dd509a-3f6b-11e8-925c-1eed823df3bf.png)

这次变为白色,我没有动过其他设置,这应该是有问题的.

**Comment by tamlok** [comment]
hi，方便把这个文件发我邮箱吗？我得先把问题复现。

另外，提出一个issue后希望有时间的话能跟进和互动一下，不然，像上次黑色背景那个问题一样，就烂尾了。

非常感谢！

**Comment by tamlok** [comment]
另外，我看您是黑色主题和白色编辑样式，能把详细的配置情况说一下吗？
