### ISSUE TITLE
全局搜索结果在文档中的定位和高亮功能

### ISSUE THREAD

**Issue by DerekTso** [tamlok/vnote#204]
VNote 全局搜索的功能非常好用，希望可以考虑增加以下功能：

1. 全局搜索的关键字在全局搜索后，可以在文档中全部高亮起来

2. 通过双击全局搜索结果中某条目，可以在某个文档中快速定位出来

3. 对于全局搜索结果页面中的所有文档，可以一键 Collapse/Expand

**Comment by sh5525** [comment]
支持，同希望加入这些功能

**Comment by tamlok** [comment]
实现了快捷键Ctrl-B展开或折叠所有项目。请下载最新构建版本尝试。

Hi,

I just added support for different layouts via setting up a layout mapping in the settings dialog.

[build](https://bintray.com/tamlok/vnote/vnote/2.0#files)

**Comment by tamlok** [comment]
Fixed in 2.1. Please try it out. Thanks!

**Comment by leeyaunlong** [comment]
> Fixed in 2.1. Please try it out. Thanks!

2.通过双击全局搜索结果中某条目，可以在某个文档中快速定位出来.
这条还没实现啊. 比如一个文件匹配了5处, 全局搜索已经标注出来行号, 希望能双击定位到具体行

**Comment by tamlok** [comment]
@leeyaunlong 在设置，杂项里面勾选启用

**Comment by l00c00l** [comment]
> @leeyaunlong 在设置，杂项里面勾选启用

设置里没有“杂项”？现在的最新版全局搜索功能怎样开启？Ctrl+G，Ctrl+E C 或Ctrl+Alt F都试了下，没反应？

**Comment by tamlok** [comment]
最新版是公测，还没迁移。

**Comment by cheng3100** [comment]
@tamlok  hi，非常需要全局搜索功能，请问现在哪些版本可以使用这个功能？

**Comment by tamlok** [comment]
旧版本2.x都行
