### ISSUE TITLE
【建议】表格和公式实时预览

### ISSUE THREAD

**Issue by microhe** [tamlok/vnote#206]
感觉表格和公式这类的也比较适合做成实时预览的效果，毕竟很多时候写个公式或表格总是来回切换查看格式。
我也不是很喜欢typora那种全实时预览。像作者这种对于图片的处理就很好。
感觉编辑器的目标应该让用户在编辑的时候，不要来回切换。图片、表格、公式这类的最终效果不好把握，就会切换预览结果。

很喜欢这个工具，感谢作者。

**Comment by tamlok** [comment]
Hi，目前正在实现，下一个版本会带上，谢谢！

**Comment by tamlok** [comment]
已经实现啦！
