### ISSUE TITLE
OpenSUSE使用fcitix输入法无法输入中文

### ISSUE THREAD

**Issue by scu2013** [tamlok/vnote#21]
我当前使用的是OpenSuse的系统，同时使用的fcitix输入法。在打开VNote后，只能输入英文，无法打开输入法输入中文。

**Comment by scu2013** [comment]
当我移动笔记目录和写笔记两个区域中间的路线时，程序退出了，同样是在OpenSuse目录下。

**Comment by tamlok** [comment]
Hi，中文输入问题是Qt5和Fcitx的设置问题。比如在我电脑上，如果编译后的程序不能使用fcitx输入法，可以检查`/home/tamlok/bin/Qt5.7.0/5.7/gcc_64/plugins/platforminputcontexts/`目录下是否有`libfcitxplatforminputcontextplugin.so`文件。如果没有，则从`fcitx-diagnose`的输出中拷贝一个到这里面，然后重新编译就行了。
具体可以参考这篇[文章](http://www.cnblogs.com/findumars/p/5364701.html)里面的：

> 将`/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so`拷贝到Qt的安装目录`/5.3/gcc_64/plugins/platforminputcontexts`。

我也是使用openSUSE开发的，之前中文输入也是这么解决的。您可以先试一下，有什么问题随时讨论！

至于程序退出的问题，我看的不是很懂，可以详细说明一下吗？或者截图说明一下操作步骤？

谢谢使用和反馈！

**Comment by JerryLi-X** [comment]
使用 Arch 的朋友只需要执行 `yaourt -S fcitx-qt5` 就可以在 vnote 中正常使用 fcitx

**Comment by aaronnew** [comment]
Ubuntu16.04是将`/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`（不是libibusplatforminputcontextplugin.so）拷贝到Qt的安装目录`/5.7/gcc_64/plugins/platforminputcontexts/`下，然后`chmod+x  libfcitxplatforminputcontextplugin.so`，再重新编译就行了。

**Comment by lalahaha323** [comment]
> 使用Arch的朋友只需要执行`yaourt -S fcitx-qt5`就可以在vnote中正常使用fcitx

还是不行啊,这个还有什么别的解决办法

**Comment by tamlok** [comment]
@lalahaha323 从`vnote-bin` AUR下载安装VNote试试。
