### ISSUE TITLE
几个建议，亟待解决

### ISSUE THREAD

**Issue by necan** [tamlok/vnote#210]
1. 建议：支持保存代码片段，就像 boostnote 一样，同时关联笔记。
2. 建议：阅读模式双击笔记进入编辑模式，编辑模式下点击非笔记区域区域进入阅读模式，这样避免频繁点击按钮。
3. 改进工具栏图标，这些图标大小不一，很丑，图标符号还很不常见，还与我们惯用的富文本编辑器不一致，让人摸不着头脑，建议和常见的富文本编辑器图标统一下，某些图标还发虚，是没用矢量图的缘故？
    ![image](https://user-images.githubusercontent.com/25315125/38886897-e6328ab8-42a9-11e8-8451-fd662b5fff97.png)

    这是 editor.md 的图标
    ![image](https://user-images.githubusercontent.com/25315125/38887103-75705dfe-42aa-11e8-956c-dc3f78b31302.png)
4. 修改样式时，希望能立即生效，而不是退出笔记，又再次进入笔记
5. 整个界面的字体很不和谐，新建笔记本按钮和文字硕大无比。笔记字体建议默认为15px，16px太大了。
    ![image](https://user-images.githubusercontent.com/25315125/38887464-81d94104-42ab-11e8-8815-e2ad562b5c6d.png)
6. 单击左侧笔记，应该像sublime一样只在单个标签切换，双击左侧笔记才打开多标签，因为有时候只是想预览一下，不想在新标签打开笔记，当想要编辑笔记是，双击笔记后在新标签打开是比较自然的操作
7. 支持全文搜索
8. 加入笔记排序功能
    - 按创建时间排序，再次点击成逆序
    - 按修改时间排序，再次点击成逆序
    - 按文件名排序，再次点击成逆序

**Comment by tamlok** [comment]
> 1. 建议：支持保存代码片段，就像 boostnote 一样，同时关联笔记。

这个后面有计划支持。

> 2. 建议：阅读模式双击笔记进入编辑模式，编辑模式下点击非笔记区域区域进入阅读模式，这样避免频繁点击按钮。

双击一般用于选取一个词。在VNote里面推荐使用快捷键`Ctrl+T`，或者在编辑区右键菜单，不需要点击工具栏上的按钮。

> 3. 改进工具栏图标，这些图标大小不一，很丑，图标符号还很不常见，还与我们惯用的富文本编辑器不一致，让人摸不着头脑，建议和常见的富文本编辑器图标统一下，某些图标还发虚，是没用矢量图的缘故？

- 大部分图标来源于一个开源图标库[Ionicons](https://github.com/driftyco/ionicons/);
- 全部图标都是SVG矢量格式，模糊估计是图标本身的问题，后面有时间再看看；
- VNote的图标尽量力求能表达该按钮的意思，而且有些功能是没有可参照的。

> 4. 修改样式时，希望能立即生效，而不是退出笔记，又再次进入笔记

因为样式是HTML里面的CSS，所以要动态应用会比较麻烦；考虑到时间关系，这里就妥协了。

> 5. 整个界面的字体很不和谐，新建笔记本按钮和文字硕大无比。笔记字体建议默认为15px，16px太大了。

- 笔记本的设计是参照OneNote的样式的；有些控件可能比较粗糙，后面有时间再打磨一下；
- 字体16的确中文有些大，但15感觉英文比较小，毕竟笔记是长期看的，默认还是大一些吧；这个可以自定义主题和样式，自行修改CSS样式。

> 6. 单击左侧笔记，应该像sublime一样只在单个标签切换，双击左侧笔记才打开多标签，因为有时候只是想预览一下，不想在新标签打开笔记，当想要编辑笔记是，双击笔记后在新标签打开是比较自然的操作

请在设置里面打开对应选项：

![image](https://user-images.githubusercontent.com/5763157/38933826-aa05789a-434c-11e8-89f2-cd33b5ec4295.png)

> 7. 支持全文搜索

已经实现，请关注VNote的release或首页。1.13开始支持全文搜索，1.14支持通用入口。

![image](https://user-images.githubusercontent.com/5763157/38933907-d7691328-434c-11e8-8fd4-dce1a637ffb9.png)

> 8. 加入笔记排序功能
>    - 按创建时间排序，再次点击成逆序
>    - 按修改时间排序，再次点击成逆序
>    - 按文件名排序，再次点击成逆序

1.14已经支持：

![image](https://user-images.githubusercontent.com/5763157/38933942-f3be7e8c-434c-11e8-85b8-6baeceedbc0c.png)

**Comment by jjjfew** [comment]
感觉很多的显示问题都是和mac有关，作者应该是在linux或windows下开发的，导致针对mac的优化不够，在mac下确实显示得比较难看，是最近几年在mac上用过的样子最丑的软件，没有之一（没有恶意，希望作者重视下mac的用户）。

**Comment by tamlok** [comment]
@jjjfew 嗯⊙∀⊙！我都是在虚拟机上调试mac版本的，基本没用过。一般都是用户反馈有问题，然后我去虚拟机上重现，然后解决。家里用linux，公司用win，所以这两个系统的调试比较多一点。凭我一人之力很难兼顾三个平台，还是有赖于大家用户多反馈或者参与。谢谢！
