### ISSUE TITLE
how to center image

### ISSUE THREAD

**Issue by standin000** [tamlok/vnote#211]
- Version of VNote, which operating system;
v1.11.1 Win10
    - What is the symptoms;
I want to center image, and try add
```
<div align="center">
![]()
</div>
```

it doesn't work.

**Comment by tamlok** [comment]
Hi,

We could not use Markdown elements within HTML elements. So you could write the `<img>` tag like this:

```
<div align="center">
<img src='_v_images/_1524057196_27102.png' />
</div>
```

**ATTENTION**: VNote could not detect the images in `<img>` tag, so VNote will think the inserted images are no longer used and prompt for the deletion.

Another way to center **all** the images is to check the **Enable Image Caption** option:

![image](https://user-images.githubusercontent.com/5763157/38934235-d9f3a0a8-434d-11e8-9330-7f33907df698.png)

**Comment by standin000** [comment]
thanks, it work!
