### ISSUE TITLE
Sorting not maintained when creating new notes

### ISSUE THREAD

**Issue by vmexia** [tamlok/vnote#213]
If you have previously sorted your notes, lets go with a sort by **modified date desc**, and you create a new one, it will be added on the last position of the list even though the modified date is newer than the others.

**Comment by tamlok** [comment]
Yes. The sorting is manual sorting for only one folder. How about adding a `View By` combo box to alter the view order of the notes automatically without changing the order in the config file?

**Comment by tamlok** [comment]
Please update to 1.17
