### ISSUE TITLE
Ctrl+c supported in vi mode?

### ISSUE THREAD

**Issue by eggface** [tamlok/vnote#217]
It is an awesome app. I was wondering whether ctrl + c is supported in vi to replace ESC, since ESC in mbp touch bar is not such friendly. Thanks.

**Comment by tamlok** [comment]
Hi,

Currently `Ctrl+C` is not supported. You could use `Ctrl+[`, which is the standard equal of `Esc`. I will add `Ctrl+C` support soon.

Thanks!

**Comment by bbsteel** [comment]
`Ctrl+C` currently mapped to `copy` in vim mode, which I think is compatible to most scenario.
If vnote add support `Ctrl+C` as `Esc`, please remain `copy` function as `Ctrl-C` default mapping, thanks.

**Comment by tamlok** [comment]
@bbsteel Will leave it as a config just as what it is like now. :)

**Comment by eggface** [comment]
@bbsteel +1, good point.
Yes, it makes sense to most Windows app. Actually, I usually use ESC key until new MBP touch bar coming out...

**Comment by tamlok** [comment]
@eggface Is `Ctrl+[` suitable for you?

**Comment by eggface** [comment]
@tamlok , it is OK to me.

**Comment by tamlok** [comment]
Already added (de678b5d6d3cfb4d63ac89a907f68aafbfca7b3f). Please add following to `path_to_configuration_folder/vnote.ini`:

```
[global]
; Skipped keys in Vim mode
; c: Ctrl+C
; v: Ctrl+V
vim_exemption_keys=v
```

This will let Vim to handle `Ctrl+C`.

Thanks!
