### ISSUE TITLE
UI on Surface Pro is too small

### ISSUE THREAD

**Issue by Mrneet** [tamlok/vnote#218]
v1.15,  Windows 10 1703, Surface Pro 4, Default Display Setting (Scaling 200%)
![image](https://user-images.githubusercontent.com/30075289/39476089-6421a776-4d20-11e8-9db9-01d2e4d0c7c9.png)
![image](https://user-images.githubusercontent.com/30075289/39476141-90642278-4d20-11e8-8d6c-6f7bc14612d5.png)

Thanks for your work. It is a really wonderful notebook software. 

But the icons on the toolbar is too small for the HiDpi of Surface. And some menus are overlapped by the icons in File Menu.

**Comment by tamlok** [comment]
Hi,

You could edit `vnote.ini` via `File -> Open Configuration Folder` in the menu. Add the following lines to specify the icon size of the tool bar:

```
[global]
; The icon size of tool bar (in pixels)
tool_bar_icon_size=20
```

Restart VNote to let it work.

I do not have any ideas about the overlapping issue for now.

Thanks!

**Comment by Mrneet** [comment]
Thanks for your reply. It works and looks good after I specify
`tool_bar_icon_size=26`
And some font sizes (maybe the background as well) are small, too. I mark them on this figure.
![image](https://user-images.githubusercontent.com/30075289/39526162-9226705c-4de3-11e8-8004-70d879a37874.png)
As for the tab (as well as the right side), I feel VS Code perfect.
![image](https://user-images.githubusercontent.com/30075289/39526309-fd4a6f78-4de3-11e8-96a5-c419d8d95064.png)
I'm sorry that I'm not a programmer. I don't know if it is easy to modify these details. I know that some applications (VS Code, WizNote, YoMail) display very good on my laptop, so my feeling is we can do something better.

Thank you!

**Comment by tamlok** [comment]
Could you change the theme to v_native and see if the font size looks good?

I will tune those things later.

Thanks!

**Comment by Mrneet** [comment]
I changed, but the only difference is the color. Font size looks the same.

**Comment by tamlok** [comment]
Please update 1.17.

**Comment by tamlok** [comment]
Please update to 1.18. Now the menu icon has been fixed!

Thanks!
