### ISSUE TITLE
Real-time Preview Not Working

### ISSUE THREAD

**Issue by zhangzujian** [tamlok/vnote#219]
VNote x64 v1.15
Win10 Pro x64 10.0.16299.371

It's the first time I use VNote. I opened VNote, created a new notebook and a root directory, and then created a new Markdown. After I typed some content, I tried the preview function, but the preview was blank. Below is the screen snapshot.

![empty_preview](https://user-images.githubusercontent.com/13048299/39557789-b922d4fa-4ebc-11e8-9883-7d17903c4b85.png)

I tried to close the preview and reopened it (for many times), but it still showed nothing. I also checked the log file (vnote.log) and it was empty, too.

**Comment by zhangzujian** [comment]
I tried to close VNote complete and reopen it, but the problem still exists.

**Comment by tamlok** [comment]
Hi,

VNote does not provide side-by-side live preview for the whole note. It is unnecessary and distractive in the case of VNote's **In-Place Preview**. You could just view images, diagrams, and formulas in place in edit mode.

The live preview is used to preview diagrams, such as Flowchart.js, Mermaid, Graphviz, and PlantUML. If you enable Flowchart.js in the `Markdown` menu, and type some definition of a flow chart, then place the cursor within the code block, the live preview panel will display the rendered effect of that flow chart.

You could reference to this [article](https://www.v2ex.com/t/451037#reply18) if you could read Chinese. I will refine the documentation soon.

Thanks for your attention!

**Comment by zhangzujian** [comment]
Got it, thanks.
