### ISSUE TITLE
windows下添加图片有时候会失去响应

### ISSUE THREAD

**Issue by Nick-Hopps** [tamlok/vnote#221]

**Comment by tamlok** [comment]
Hi，是怎么添加图片？是复制粘贴网络上的图片吗？能稳定复现吗？无响应的时候能否截图看一下？谢谢！

如果是从网络url复制粘贴图片，有可能是在后台下载图片。

**Comment by Nick-Hopps** [comment]
我知道原因了，因为插入图片时直接读取了剪切板中的地址，而该地址对应的图片很大，导致卡死。我觉得这个功能可以改一下。

**Comment by Nick-Hopps** [comment]
比如点击添加之后再后台下载？

**Comment by tamlok** [comment]
后面我加一个滚动条吧。还是得等下载完图片后才能插入，否则有可能会丢失图片，比如还没下载完用户就关闭程序，处理逻辑就比较复杂了。

**Comment by Nick-Hopps** [comment]
麻烦你了，十分感谢，很好用哈哈。
