### ISSUE TITLE
RFE: image size (link_attributes)

### ISSUE THREAD

**Issue by nikita-moor** [tamlok/vnote#222]
VNote 1.14 | Arch Linux

What syntax should I use to control size of the inserted images? (Not related to "preview size" #120)
Are you going to implement the so called ["link_attributes"](https://pandoc.org/MANUAL.html#images):

```
![](file.jpg){ width=50% }
```

**Comment by tamlok** [comment]
Hi,

I will find whether there is such a plugin for markdown-it to specify image size. If found, I will add it.

BTW, please update VNote to 1.15 and you won't be disappointed! :)

Thanks!

**Comment by tamlok** [comment]
Hi,

Already added (dba154b2c38a923290592a7c686fceb52a9d46fc). Only supported in **markdown-it**.

Syntax:

```
![Image Alt Text](/url/to/image.png "Optional Text")

![Image Alt Text](/url/to/image.png "Image specified with width and height" =800x600)

![Image Alt Text](/url/to/image.png =800x600)

![Image Alt Text](/url/to/image.png "Image specified with width" =800x)

![Image Alt Text](/url/to/image.png "Image specified with height" =x600)
```

Thanks!

**Comment by nikita-moor** [comment]
Great, thank you! Do I understand correct syntax like `=800x600` defines an outbox? It seems the second number does not affect the image...

For example, this is a square image:
```
![]( https://raw.githubusercontent.com/tamlok/vnote/master/screenshots/vnote.png =100x100)
```
Setting it's *height* less does not make it smaller:
```
![]( https://raw.githubusercontent.com/tamlok/vnote/master/screenshots/vnote.png =100x50)
```
Setting only *height* (w/o *width*) resets it's size to original 256x256:
```
![]( https://raw.githubusercontent.com/tamlok/vnote/master/screenshots/vnote.png =x50)
```

**Comment by nikita-moor** [comment]
Yes, it works!!!

P.S. Probably I changed some settings and forgot to restart the VNote.

**Comment by tamlok** [comment]
Yes, you need to uncheck the constraint option in Markdown menu then reopen opened notes. Please refer to this [plugin](https://github.com/tatsy/markdown-it-imsize) for details.

Thanks!
