### ISSUE TITLE
Windows笔记本电脑上编辑时出错

### ISSUE THREAD

**Issue by evilwk** [tamlok/vnote#223]
在Windows笔记本电脑上面，无法编辑文件，并且编辑模式时，进行窗口最大化和窗口恢复大小操作，界面会出现缩放问题。客户端是最新版本。

![image](https://user-images.githubusercontent.com/939916/39587873-27947b1c-4f2d-11e8-96b4-d06b2d37211b.png)

**Comment by tamlok** [comment]
Hi,

尝试更新一下显卡驱动？一般这种诡异的很基本的问题，可能是显卡驱动惹的祸。

谢谢！

**Comment by evilwk** [comment]
用的Win10自动安装的显卡驱动，晚上回家试试换个显卡驱动。Thanks.
