### ISSUE TITLE
切换编辑模式会卡死，光标不动，键盘输入无效

### ISSUE THREAD

**Issue by imjcroot** [tamlok/vnote#226]
- English is preferred;
- Make the title as meaningful as possible;
- One issue for only one thing, since large issues are difficult to remember and handle;
- When reporting problems, elaborate it as detailed as possible like:
    - Version of VNote, which operating system;
    - What is the symptoms;
    - What action triggered it;
    - How to reproduce it;
- Please delete all these text and put whatever you want below. :)

**Comment by tamlok** [comment]
Hi，请详细描述系统，场景和重现步骤，谢谢！

根据您描述的有限信息，可以尝试更新一下显卡驱动，谢谢！

**Comment by tamlok** [comment]
Hi,

如果显卡驱动更新后无法解决，请添加系统变量`QT_OPENGL`，值为`angle`，然后重启VNote试试。

谢谢！
