### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by jluliuchao** [tamlok/vnote#229]
首先非常感谢作者的辛勤付出，带给我们这么好用的软件。
经过一段时间的使用，发现有以下问题：
1. ~~删除线~~不支持原地预览，进入阅读模式后显示正常。
2. mermaid不支持原地预览
3. 通过Markdown菜单开启Mermaid功能后，需要重新打开当前文档才能看到效果。

**Comment by tamlok** [comment]
Hi,

1. 删除线的效果会在下一个版本中支持；
2. 因为mermaid本身的原因，暂时预览不了，这个暂时没有啥办法；目前可以通过`Ctrl+E I`打开实时预览来预览效果；
3. 这是符合预期的，因为需要加载额外的JavaScript，所以需要重新打开标签页。

谢谢！

**Comment by tamlok** [comment]
Mermaid在导出pdf的时候也会有问题。建议使用plantuml。我觉得是mermaid实现得不太好。

**Comment by jluliuchao** [comment]
@tamlok 好的，谢谢。

**Comment by tamlok** [comment]
hi，

得在文件菜单里面的设置对话框里面启动。建议使用本地plantuml，需要安装jre，plantuml.jar和graphviz。

在线服务用的是http，隐私方面得自己考虑一下，而且在线不支持原地预览。

谢谢！

**Comment by jluliuchao** [comment]
@tamlok 我安装了jre和graphviz，下载plantuml.jar到E盘，设置如下：
![image](https://user-images.githubusercontent.com/35259060/39793635-e857f6b8-5378-11e8-8807-e16b0de4287e.png)
代码如下：
![image](https://user-images.githubusercontent.com/35259060/39793654-ff3ab35c-5378-11e8-95a2-502db67237d9.png)
实际效果如下：
![image](https://user-images.githubusercontent.com/35259060/39793673-0e8521f8-5379-11e8-9dea-2230def896ce.png)
将Plantuml设置为在线服务后，显示正常。

**Comment by jluliuchao** [comment]
@tamlok  非常感谢，本地PlatUML已经成功了。
顺便提个建议：在设置窗口中的PlantUML JAR:和Graphviz可执行文件:后面各加一个按钮，用于浏览这两个文件的路径，避免理解错误和输入错误。
