### ISSUE TITLE
导出为PDF功能交互上有问题

### ISSUE THREAD

**Issue by sadhen** [tamlok/vnote#23]
version: v1.6

一直点OK会一直重复导出

**Comment by tamlok** [comment]
是的，这个原来是打算说用户可以选择不同的页面设置，然后多次导出。不过看来也没有必要，后面会去掉。谢谢反馈~ :)

**Comment by tamlok** [comment]
Hi, 已经修复了(b4873feb4174418a51b51a46908c44765ac77d51)，下一个版本会带上，或者可以直接去Bintray下载最新构建版本。
