### ISSUE TITLE
关于列表缩进的问题

### ISSUE THREAD

**Issue by jluliuchao** [tamlok/vnote#230]
编辑模式下如下，灰色块为空格：
![image](https://user-images.githubusercontent.com/35259060/39810774-ee8fa496-53b8-11e8-88a7-4428f70a0d7a.png)
阅读模式如下：
![image](https://user-images.githubusercontent.com/35259060/39810792-fda1f3b2-53b8-11e8-9356-25d743bf722f.png)
预期效果是代码和Test Text Line 2与Test Text Line 1对齐，作为Test Item 1的子内容，而实际是后面的内容没有缩进。

**Comment by tamlok** [comment]
Hi，

关于列表下的代码块和嵌套列表，请参考帮助菜单的语法指南，也可以参考这篇文章 https://www.jianshu.com/p/7c4637c72900

总的来说就是代码块得总体缩进四个空格。

谢谢！
