### ISSUE TITLE
CodeBlock中有空白行会引起HeadingSequence失效

### ISSUE THREAD

**Issue by unain** [tamlok/vnote#231]
除非在CodeBlock后面跟个回车

![1](https://user-images.githubusercontent.com/3350190/39853145-fdd5a4a6-5452-11e8-809d-f119794cd48c.png)

**Comment by tamlok** [comment]
Hi,

标题前请留一个空行，表示块元素分隔。

谢谢！

**Comment by tamlok** [comment]
Should be fixed in 1.20.
