### ISSUE TITLE
代码块结束标志后面不能有空格？

### ISSUE THREAD

**Issue by jluliuchao** [tamlok/vnote#235]
在阅读模式下显示是一样的，是正常的。
在编辑模式下有空格：
![image](https://user-images.githubusercontent.com/35259060/39913707-728c0848-5535-11e8-967f-735071c5690d.png)
在编辑模式下没有空格：
![image](https://user-images.githubusercontent.com/35259060/39913733-8405ad5e-5535-11e8-824d-a0f6e9c5fbe8.png)

**Comment by tamlok** [comment]
结束行后面加空格是为了什么效果？后面不加空格是人为强加上去的。

**Comment by tamlok** [comment]
对于有换行需求的可以使用`Shift+Enter`来输入两个空格并换行。其他还是该`Enter`就用`Enter`吧。后面我看看容易修不。

谢谢！

**Comment by jluliuchao** [comment]
好的，上面说错了，我用的是Shift+Enter哈

**Comment by jluliuchao** [comment]
@tamlok 还有一个类似的问题，如下：
![image](https://user-images.githubusercontent.com/35259060/40411279-8c3e4e06-5ea2-11e8-99f6-fea59722041c.png)
在代码块之间有文字和图片，发现文字渲染格式出错，而图片则无法显示。发现在第一个代码块后面加上空行后，文字和图片就正常了。

**Comment by tamlok** [comment]
Should be fixed in 1.20.
