### ISSUE TITLE
_ in math equation is parsed as markdown control character in edit mode

### ISSUE THREAD

**Issue by htfy96** [tamlok/vnote#236]
- Version: 1.15. Linux
- symptoms & action to reproduce:
In edit mode, type:
```
$$ \sum_{j < i}{(\min{burst_j, \sum_{k > j}{2}})} $$
```
The above equation is not rendered correctly. It seems that `_` is identified as markdown control character here.
![screenshot from 2018-05-11 23-52-02](https://user-images.githubusercontent.com/8121231/39933743-61937d96-5576-11e8-9de6-6e96f4cb6f5a.png)

This works well in view mode.

**Comment by tamlok** [comment]
Hi,

For now please use `\` to escape `_`. The expression in edit mode is stricter than that in read mode. I am trying to modifying `markdown-it` to get rid of the escaping.

Regards,
Le

**Comment by cben** [comment]
have you looked into ready markdown-it math plugins such as:
https://www.npmjs.com/package/markdown-it-katex
https://www.npmjs.com/package/markdown-it-mathjax
https://www.npmjs.com/package/markdown-it-texmath
(there are more)?

**Comment by tamlok** [comment]
@cben, the second plugin still needs escaping some chars, while the other two plugins target Katex instead of Mathjax. The third plugin is great about the escape. I plan to tune it for Mathjax as a new markdown-it plugin. I am not an expert in JS and markdown-it. Any help in this is appreciated!

Thanks!

**Comment by theFool32** [comment]
Same problem.
It not works in read mode when use `\_` instead of `_`.
`$\sum\_i$` will looks like `∑_i`

**Comment by tamlok** [comment]
Fixed in 1.20.
