### ISSUE TITLE
Real time preview for Markdown separator syntax

### ISSUE THREAD

**Issue by pisces312** [tamlok/vnote#237]
As a user, I want to see real time preview for Markdown separator syntax in edit mode.
E.g. "---" or "===" can be shown as a separator line.

**Comment by Symbian9** [comment]
> E.g. `---` or `===` ...

... and `***` too.

Test `---`:

---

Test `===`:

===

Test `***`:

***

P.S.: What you want: color or line highlight?

**Comment by pisces312** [comment]
I want a real line in edit mode just  like different levels of titles will be shown bold in edit mode.

**Comment by tamlok** [comment]
Added in 1.20. Enjoy!
