### ISSUE TITLE
Type on anywhere by left clicking blank area

### ISSUE THREAD

**Issue by pisces312** [tamlok/vnote#238]
I prefer writing the note on Surface touch screen.
It's very easy to organize the note structure by clicking the blank area to input the content on OneNote.
VNote can do the same thing to bring a better experience on touch screen devices.

**Comment by tamlok** [comment]
You mean the container in OneNote? We could click on anywhere to insert a text container to input Markdown text? If so, it is impossible to borrow the container concept from OneNote in VNote.
