### ISSUE TITLE
vnote启用graphviz，画图没效果

### ISSUE THREAD

**Issue by DreamChase** [tamlok/vnote#239]
#os
- window10
- vnote v1.5

#bug
启用graphviz画图，显示仍为代码块。
![image](https://user-images.githubusercontent.com/24583314/39968230-7b0d783a-56fc-11e8-937c-b1d871415889.png)

![image](https://user-images.githubusercontent.com/24583314/39968130-aed7543a-56fa-11e8-821b-be3da47e2174.png)

**Comment by tamlok** [comment]
Hi，
请问设置了`dot.exe`的路径了吗？代码块的语言标明`dot`了吗？

谢谢！

**Comment by tamlok** [comment]
第16行的三个点是属于dot语法的吗？还是说您是想输入反引号？

谢谢！

**Comment by DreamChase** [comment]
一不小心打成中文符号了，我重新打成英文符号但还是没有显示。
![image](https://user-images.githubusercontent.com/24583314/39968812-8dff5aa4-5705-11e8-9408-6d2c8e039263.png)

**Comment by tamlok** [comment]
尝试把dot所在目录放到非中文路径下？

另外，帮助菜单里面有一个查看日志的项，看看日志有没有什么warning0

**Comment by DreamChase** [comment]
中文路径问题，已解决。实现如下
![image](https://user-images.githubusercontent.com/24583314/39969018-a25be96a-5708-11e8-92e1-375332eccc75.png)
谢谢哦！
