### ISSUE TITLE
Vim Mode: 光标的显示

### ISSUE THREAD

**Issue by sadhen** [tamlok/vnote#24]
should not always be a vertical bar

version: VNote 1.6

**Comment by tamlok** [comment]
Yes, VNote will always show a vertical bar cursor in Vim mode currently. Here are some reasons:

1. It seems to be a hard job to change the cursor to be a block on a character in `QTextEdit` class in Qt. In Qt, a cursor is the position between two characters.
2. VNote has images when editing, so it will be weird to have a block cursor on the images.

Anyway, I will try it again once I have finished other more urgent parts of VNote. :) By the way, VNote's Vim mode is very functional except that it does not have a block cursor.

Thanks very much for your feedback! :)

**Comment by tamlok** [comment]
@sadhen @bbsteel

Hi, finally VNote now supports Vim block cursor! (87af770612e06de30061f87ecae25ed89df04e05)

Will be released in next version. You could get the [latest build](https://bintray.com/tamlok/vnote/vnote/_latestVersion) here if you want.

![image](https://user-images.githubusercontent.com/5763157/33610687-1e0e467c-da07-11e7-86a8-2eda857f3ee7.png)

Thanks!
