### ISSUE TITLE
Provide a better way to display inline equation

### ISSUE THREAD

**Issue by htfy96** [tamlok/vnote#241]
Currently, Vnote display inline equations above each screen line, which occupy a lot of space for equation-heavy documents:
![screenshot from 2018-05-14 23-29-45](https://user-images.githubusercontent.com/8121231/40007259-ddfa8dac-57ce-11e8-9043-de7a4db5a1a4.png)

It'd better to provide an option to display inline equations right after the `$$` block in the same line, so `$f(x)$` will be rendered as `$f(x)$ [rendered image of f(x)]`.

**Comment by tamlok** [comment]
Hi,

It is difficult to image and text real inline. Qt does not provide such widget and it took me lots of energy to make in-place preview like what it is now.

So I prefer not to touch it until I get a good idea about how to implement it.

Thanks!
