### ISSUE TITLE
Improve equation rendering speed in edit mode

### ISSUE THREAD

**Issue by htfy96** [tamlok/vnote#242]
Cold rendering: For a document with ~100 equations, it takes around 1 minute to render all equations in edit mode at startup.

Warm rendering: When some paragraphs are reordered by cut&paste, all equations in these paragraphs will be rendered again, which is very time-consuming.

I was wondering is it possible to add some kind of caching to reduce the cold/warm rendering time of equations?

**Comment by tamlok** [comment]
Good point! Will be added in next version. Thanks!

**Comment by tamlok** [comment]
Please update to 1.17. :)
