### ISSUE TITLE
How to move notes between directories?

### ISSUE THREAD

**Issue by proudzhu** [tamlok/vnote#244]
VNote v1.16 on lateset windows 10, just cannot find any method to move notes between directories on the doc site. So how to do it?

**Comment by tamlok** [comment]
- Right click on a note or folder, choose copy or cut.
- Navigate to the target folder.
- In the note list, right click to paste notes.
- In the folder tree, right click to paste folder.

Thanks!

**Comment by proudzhu** [comment]
Thanks.
