### ISSUE TITLE
图片弹出效果

### ISSUE THREAD

**Issue by ice-doom** [tamlok/vnote#245]
我能够修改什么文件实现图片弹出效果？以后版本有这功能。

**Comment by tamlok** [comment]
？？？能描述详细一点吗？

**Comment by ice-doom** [comment]
就是在阅读模式时图片看不清可以点击图片后，图片弹出变大。
这是cmdmarkdown的：
![image](https://user-images.githubusercontent.com/25363717/40155204-efec23a2-59c4-11e8-84a8-029e997418e1.png)
点击后图片弹出效果：
![image](https://user-images.githubusercontent.com/25363717/40155235-1bdf9408-59c5-11e8-95bd-2eb3e7dd77e9.png)

**Comment by ice-doom** [comment]
对了，在导出html时也有这功能

**Comment by tamlok** [comment]
这个单纯CSS能实现不？

**Comment by ice-doom** [comment]
这个估计得要配合js实现了

**Comment by DreamChase** [comment]
能够添加j引用js文件么？，例如jquery-3.3.1.js

**Comment by tamlok** [comment]
已经实现了双击弹出浏览图片，下个版本会带上。

@DreamChase 引入jq感觉会引入一堆东西，还是倾向于纯js。

谢谢！

**Comment by DreamChase** [comment]
纯js，用的是DOM么

**Comment by tamlok** [comment]
@DreamChase 应该是吧。感兴趣的可以看一下最近的几个commit，找到对应的修改。

**Comment by DreamChase** [comment]
你commit么？
嗯好的，我也用纯js写了一个图片弹出，但是就是有2条多余的HTML代码，不知道你外围封装在哪里。
![2018-07-02_192232](https://user-images.githubusercontent.com/24583314/42161375-5b70c7c2-7e2d-11e8-8e49-1a94ad50c7d7.png)

这个css绚烂的时候，cursor:zoom-in/zoom-out这个属性显示不出来，不知道你有没有这样的情况。

**Comment by tamlok** [comment]
@DreamChase 你可以导出html，然后在那个html里面引用js来调试。

https://github.com/tamlok/vnote/commit/4df0d03baa7352f24dd14a0a393ede87698bfea1

**Comment by DreamChase** [comment]
我之前导出的时候，vote里面是cursor:zoom-in/zoom-out这个属性显示不出来，但在chrome是可以正常显示的，不知道是不是兼容性的问题
