### ISSUE TITLE
New feature suggestion: Import markdown files from another directory

### ISSUE THREAD

**Issue by rim99** [tamlok/vnote#247]
Since VNote is not the first documents editor usually, I suggest VNote can add a feature, which can **import older markdown files** outside.

**Comment by tamlok** [comment]
hi,

You could import multiple files into current folder via the File menu.

Thanks!

**Comment by rim99** [comment]
![2018-05-21 6 56 30](https://user-images.githubusercontent.com/13381463/40304278-b62c4cca-5d28-11e8-8c19-5839b4b89045.png)
 
Is there any switch or something likewise?

**Comment by tamlok** [comment]
Hi，“从文件新建笔记”选项会拷贝指定的文件到当前vnote文件夹下，并添加为笔记。需要注意的是相对路径的图片需要自己处理一下。

谢谢！

**Comment by rim99** [comment]
谢谢
