### ISSUE TITLE
Image inline preview doesn't support space in location

### ISSUE THREAD

**Issue by geminisaga** [tamlok/vnote#248]
The in-line image preview has  been a wonderful feature.

Just one flaw been noticed that it doesn't seem to support space in file name of the image reference

![image](https://user-images.githubusercontent.com/7713036/40284297-7b2771ca-5cd0-11e8-9b48-4b634723b55e.png)

By normal usage it seems to be ok as the adding of image actually making a copy of the image and rename it to supported format, But the issue was noticed when I convert the existing note repo to be supported by VNote.

Thanks!

**Comment by tamlok** [comment]
Hi，

URL does not support space, so VNote do it this way. You could use `%20` to replace a space. It should work!

Thanks!

**Comment by geminisaga** [comment]
Thanks! Tamlok
