### ISSUE TITLE
能否支持在目录下直接列出文件

### ISSUE THREAD

**Issue by hao117** [tamlok/vnote#249]
能否支持在目录下直接列出文件而不是只是子目录，可以子目录排前面，文件排后面；可以设置成配置选项。

**Comment by smartlin** [comment]
虽然有了从文件新建笔记功能，可以把文件加载到vnote目录，但是有时候并不想改变原来文件的位置

**Comment by tamlok** [comment]
Hi，

后面笔记列表会每个笔记显示多行，也会显示标签，所以还是倾向于分离显示。另外，合并显示代码改动太大，暂时先不考虑。

@smartlin qq群（487756074）里有同学给出了一个递归生成json文件的python脚本，可以了解一下。后面会在主页指向一些工具集合。

谢谢！
谢谢！
