### ISSUE TITLE
关于附件目录的问题

### ISSUE THREAD

**Issue by luo-chuan** [tamlok/vnote#250]
附件并不是存在 _v_attachments 文件夹中，而是存在 _v_attachments 的一个子文件夹中，而且这个子文件夹名还是一串无规律的数字。这给用户在插入附件链接时带来不便，希望改进。

**Comment by tamlok** [comment]
hi，

使用无规律数字是为了减少冲突的可能性。后面会添加快捷方式来插入附件链接，无需用户输入这一串数字。

谢谢！

**Comment by tamlok** [comment]
现在可以使用`%att%`幻词来插入当前笔记的附件文件夹的相对路径。配合片段功能，可以一个快捷键就插入当前附件文件夹相对路径，然后输入附件名字即可。
