### ISSUE TITLE
Qt 6.7 编译失败

### ISSUE THREAD

**Issue by heavysink** [tamlok/vnote#2503]
**Describe the bug**
Qt6.7改了qt_add_lupdate的格式导致编译失败:
CMake Error at /usr/lib/cmake/Qt6LinguistTools/Qt6LinguistToolsMacros.cmake:231 (message):
  No SOURCE_TARGETS nor SOURCES were given.
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6LinguistTools/Qt6LinguistToolsMacros.cmake:781 (qt6_add_lupdate)
  src/CMakeLists.txt:32 (qt_add_lupdate)
需要给定SOURCE_TARGETS和SOURCES

**To Reproduce**
1. cmake

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Qt version 6.7

**Comment by tamlok** [comment]
Should fix: https://github.com/vnotex/vnote/pull/2511
