### ISSUE TITLE
macos 阅读模式，下面Ctrl + +/-放大/缩小页面失效

### ISSUE THREAD

**Issue by hawkinchina** [tamlok/vnote#253]
# macos 阅读模式，下面Ctrl + +/-放大/缩小页面失效。
编辑模式下， Ctrl + +/-放大/缩小页面： 快捷键是ok的，**但是在阅读模式，是没有任何反应的。**

**Comment by tamlok** [comment]
Hi，

请问是哪个版本vnote？按住ctrl，滑动鼠标滚轮呢？

谢谢！

**Comment by hawkinchina** [comment]
v1.16 vnote..
1）macos阅读模式，下测试。
2）使用键盘操作，ctrl（command）+ +/-， 放大，缩小页面失效。
3） 在此模式下， 使用鼠标，滚轮是没有问题。。vim模式，主要还是关注键盘，手不离开键盘。

**Comment by tamlok** [comment]
@hawkinchina Hi, 已经知道是什么原因了，`Control`是可以的，`Command`不行。后面会修复一下。谢谢！

**Comment by tamlok** [comment]
请更新1.17。
