### ISSUE TITLE
Universal Entry时无法输入中文

### ISSUE THREAD

**Issue by losymear** [tamlok/vnote#254]
想要搜索中文笔记，比如输入`q某某笔记`,中文文字无法输入到Universal Entry,而是会出现在编辑区。所以我现在搜索时都是先复制要搜索的内容再复制到Universal Entry。请问这是什么原因？

VNote版本v1.16  macOS Sierra 10.12.6   输入法为搜狗输入法

**Comment by losymear** [comment]
![untitled](https://user-images.githubusercontent.com/30641746/40535512-e8bcc302-603b-11e8-8c12-14f4e3947f4f.gif)

**Comment by tamlok** [comment]
Hi，

在win和linux都没啥问题，mac我周末试试。您试一下点击一个附件进行重命名，看能不能输入中文？另外，其他输入法是否正常？

谢谢！

**Comment by losymear** [comment]
附件重命名也是同样的现象。
然后试了其他的语言(系统自带的中文拼音、韩语、日语)都会这样。

**Comment by tamlok** [comment]
- 附件重命名时还是没有办法输入中文，增加了右键菜单进行重命名；
- 通用入口已经可以输入中文；

请关注下一个版本。

谢谢反馈！
