### ISSUE TITLE
从磁盘中重新加载

### ISSUE THREAD

**Issue by DreamChase** [tamlok/vnote#255]
在磁盘中对文件、文件夹进行操作，如：新增，重命名。从磁盘中加载，无法加载新的文件、文件夹。

**Comment by tamlok** [comment]
Hi,

VNote是一个笔记软件，通过在每个文件夹下面使用一个`_vnote.json`的配置文件来维护笔记结构，因此，如果绕过VNote修改文件结构，需要自行修改配置文件。

**强烈建议使用VNote来管理笔记**，VNote提供基本的文件操作。

谢谢！

**Comment by tamlok** [comment]
如果不喜欢vnote来管理笔记，1.17会带上系统文件浏览栏，用于浏览外部文件。谢谢！

**Comment by ustczzh** [comment]
VNote管理的md笔记，通过同步盘，在android端通过其它app打开进行阅读和编辑时，有什么推荐么？现在暂时使用易码，但是需要针对VNote下每个文件夹进行设置。

**Comment by tamlok** [comment]
@ustczzh 暂时没什么推荐。易码阅读应该没什么问题吧？

**Comment by ustczzh** [comment]
@tamlok 使用坚果云Webdav同步，易码阅读和编辑都没问题。就是不能移动，当然这上面讲到了。易码不支持子文件夹，所有笔记都在一个目录下，通过添加标签识别和分类。所以易码查看VNote管理的笔记时，需要为每个子文件夹设置同步。如果VNote笔记本分级比较复杂，那还是比较麻烦的。

**Comment by tamlok** [comment]
@ustczzh 如果还有精力而且vnote受众比较广的话，后面会开发安卓版😂

**Comment by ustczzh** [comment]
@tamlok 极好的消息！有可能开发的话，希望一定要支持Webdav、dropbox等网盘同步。这样所有设备都能同时更新了。
