### ISSUE TITLE
编辑文件有问题

### ISSUE THREAD

**Issue by a835785342** [tamlok/vnote#256]
可以正常显示编辑后的效果，按编辑按钮后，软件会卡住，但是可以正常编辑，但是看不到正在编辑的内容，把编辑模式关后能正常显示刚刚编辑的内容

**Comment by tamlok** [comment]
hi，

请从以下两个途径尝试解决：

- 更新显卡驱动程序；
- 新建一个系统环境变量，名字是`QT_OPENGL`，值是`angle`或者`software`；改完后，重启VNote；

谢谢！

**Comment by FallenXtar** [comment]
已解决另外发现出现问题是在nVIDIA独显运行时，测试Intel集成显卡无此BUG
