### ISSUE TITLE
编辑模式下，跳转G快捷键到末尾，不起作用。

### ISSUE THREAD

**Issue by hawkinchina** [tamlok/vnote#257]
问题描述：
1）编辑模式下，跳转G快捷键到末尾，不起作用。-- failed。
2）编辑模式下， 跳转gg快捷键，可以跳到首行。。--ok

版本情况：
v1.16
操作系统：
macos 10.13.4

**Comment by losymear** [comment]
我macos 10.12.6没有问题

**Comment by tamlok** [comment]
10.13.3暂时无法复现。

**Comment by tamlok** [comment]
@hawkinchina Any update on this?
