### ISSUE TITLE
Read mode doesn't work

### ISSUE THREAD

**Issue by iosmanthus** [tamlok/vnote#258]
When I enter read mode pressing Ctrl-T, there is just a blank panel.
![screenshot from 2018-05-31 23-23-07](https://user-images.githubusercontent.com/16307070/40791238-97590960-6529-11e8-9649-727b327f0081.png)

**Comment by tamlok** [comment]
Hi,

- What is your OS?
- Using AppImage?
- Is edit mode OK?

Thanks!

**Comment by iosmanthus** [comment]
@tamlok Sorry, I am using Arch Linux. The package I installed is  `vnote-git` in AUR not an appimage. The edit mode is okey.

**Comment by tamlok** [comment]
Got it! I think you need to install `qtwebengine` package. I suggest to use appimage if that does not help. Thanks!

**Comment by iosmanthus** [comment]
@tamlok 
`qt-webengine` has been already installed as a dependence of package `vnote-git`/`vnote` 
I try to launch `vnote` in a terminal. Errors occur when I try to open a note in `Read Mode`
Here are the logs.
```
[0601/142138.071556:WARNING:stack_trace_posix.cc(699)] Failed to open file: /home/programmatore/#5505887 (deleted)
  Error: No such file or directory
[7745:7745:0601/142138.191615:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.
gio: data:text/html;charset=UTF-8,%3C%21DOCTYPE%20html%3E%0A%3Chtml%3E%0A%3Cmeta%20charset%3D%22utf-8%22%3E%0A%3Chead%3E%0A%20%20%20%20%3Cstyle%20type%3D%22text%2Fcss%22%3E%0A%20%20%20%20body%20%7B%20background-color%3A%20%23FFFFFF%20%21important%3B%20%7D%0A%0A%20%20%20%20%3C%2Fstyle%3E%0A%0A%20%20%20%20%3Cstyle%20type%3D%22text%2Fcss%22%3E%0A%20%20%20%20%20%20%20%20%40keyframes%20flash%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%200%25%20%7B%20color%3A%20%2380CBC4%3B%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%2010%25%20%7B%20color%3A%20%2300897B%3B%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%2040%25%20%7B%20color%3A%20%2300897B%3B%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%2050%25%20%7B%20color%3A%20%2380CBC4%3B%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%2060%25%20%7B%20color%3A%20%2300897B%3B%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%2090%25%20%7B%20color%3A%20%2300897B%3B%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20.highlighted-anchor%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20animation%3A%201s%20flash%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%3C%2Fstyle%3E%0A%0A%20%20%20%20%3Clink%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%20href%3D%22file%3A%2F%2F%2Fhome%2Fprogrammatore%2F.config%2Fvnote%2Fthemes%2Fv_pure%2Fv_pure.css%22%3E%0A%20%20%20%20%3Clink%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%20href%3D%22file%3A%2F%2F%2Fhome%2Fprogrammatore%2F.config%2Fvnote%2Fthemes%2Fv_pure%2Fv_pure_codeblock.css%22%3E%0A%20%20%20%20%3Cscript%20src%3D%22qrc%3A%2Fresources%2Fqwebchannel.js%22%3E%3C%2Fscript%3E%0A%20%20%20%20%3Cscript%20src%3D%22qrc%3A%2Futils%2Fhighlightjs%2Fhighlight.pack.js%22%3E%3C%2Fscript%3E%0A%20%20%20%20%3Cscript%20src%3D%22qrc%3A%2Futils%2Fmarkdown-it%2Fmarkdown-it.min.js%22%3E%3C%2Fscript%3E%0A%3Cscript%20src%3D%22qrc%3A%2Futils%2Fmarkdown-it%2Fmarkdown-it-headinganchor.js%22%3E%3C%2Fscript%3E%0A%3Cscript%20src%3D%22qrc%3A%2Futils%2Fmarkdown-it%2Fmarkdown-it-task-lists.min.js%22%3E%3C%2Fscript%3E%0A%3Cscript%20src%3D%22qrc%3A%2Futils%2Fmarkdown-it%2Fmarkdown-it-imsize.min.js%22%3E%3C%2Fscript%3E%0A%3Cscript%20src%3D%22qrc%3A%2Futils%2Fmarkdown-it%2Fmarkdown-it-footnote.min.js%22%3E%3C%2Fscript%3E%0A%3Cscript%20src%3D%22qrc%3A%2Futils%2Fmarkdown-it%2Fmarkdown-it-sup.min.js%22%3E%3C%2Fscript%3E%0A%3Cscript%20src%3D%22qrc%3A%2Futils%2Fmarkdown-it%2Fmarkdown-it-front-matter.js%22%3E%3C%2Fscript%3E%0A%3Cscript%3Evar%20VMarkdownitOption%20%3D%20%7Bhtml%3A%20true%2C%0Abreaks%3A%20true%2C%0Alinkify%3A%20true%2C%0Asub%3A%20false%2C%0Asup%3A%20true%2C%0Ametadata%3A%20true%2C%0Aemoji%3A%20false%20%7D%3B%0A%3C%2Fscript%3E%0A%3Clink%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%20href%3D%22file%3A%2F%2F%2Fhome%2Fprogrammatore%2F.config%2Fvnote%2Fthemes%2Fv_pure%2Fv_pure_mermaid.css%22%2F%3E%0A%3Cscript%20src%3D%22qrc%3A%2Futils%2Fmermaid%2FmermaidAPI.min.js%22%3E%3C%2Fscript%3E%0A%3Cscript%3Evar%20VEnableMermaid%20%3D%20true%3B%3C%2Fscript%3E%0A%3Cscript%20src%3D%22qrc%3A%2Futils%2Fflowchart.js%2Fraphael.min.js%22%3E%3C%2Fscript%3E%0A%3Cscript%20src%3D%22qrc%3A%2Futils%2Fflowchart.js%2Fflowchart.min.js%22%3E%3C%2Fscript%3E%0A%3Cscript%3Evar%20VEnableFlowchart%20%3D%20true%3B%3C%2Fscript%3E%0A%3Cscript%20type%3D%22text%2Fx-mathjax-config%22%3EMathJax.Hub.Config%28%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20tex2jax%3A%20%7BinlineMath%3A%20%5B%5B%27%24%27%2C%27%24%27%5D%2C%20%5B%27%5C%5C%28%27%2C%27%5C%5C%29%27%5D%5D%2C%0AprocessEscapes%3A%20true%2C%0AprocessClass%3A%20%22tex2jax_process%7Clanguage-mathjax%7Clang-mathjax%22%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20showProcessingMessages%3A%20false%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20messageStyle%3A%20%22none%22%7D%29%3B%0A%3C%2Fscript%3E%0A%3Cscript%20type%3D%22text%2Fjavascript%22%20async%20src%3D%22https%3A%2F%2Fcdn.bootcss.com%2Fmathjax%2F2.7.2%2FMathJax.js%3Fconfig%3DTeX-MML-AM_HTMLorMML%22%3E%3C%2Fscript%3E%0A%3Cscript%3Evar%20VEnableMathjax%20%3D%20true%3B%3C%2Fscript%3E%0A%3Cscript%3Evar%20VEnableImageCaption%20%3D%20true%3B%3C%2Fscript%3E%0A%3Cscript%20src%3D%22qrc%3A%2Futils%2Fhighlightjs%2Fhighlightjs-line-numbers.min.js%22%3E%3C%2Fscript%3E%0A%3Cscript%3Evar%20VEnableHighlightLineNumber%20%3D%20true%3B%3C%2Fscript%3E%0A%3Cscript%3Evar%20VEnableFlashAnchor%20%3D%20true%3B%3C%2Fscript%3E%0A%3Cscript%3Evar%20VStylesToInline%20%3D%20%27all%24border%3Acolor%3Adisplay%3Afont-family%3Afont-size%3Afont-style%3Awhite-space%3Aword-spacing%3Aline-height%3Atext-align%3Atext-indent%3Apadding-top%3Apadding-bottom%3Amargin-top%3Amargin-bottom%3Abackground-color%3Afont-weight%2Ccode%24font-family%3Afont-size%3Aline-height%3Acolor%3Adisplay%3Aoverfow-x%3Abackground-color%3Afont-weight%2Cli%24line-height%3Abackground-color%3Afont-weight%2Ca%24color%3Avertical-align%3Abackground-color%3Afont-weight%2Cpre%24display%3Aoverflow-y%3Aoverflow-x%3Acolor%3Afont-size%3Afont-style%3Afont-weight%3Aletter-spacing%3Atext-align%3Atext-indent%3Aword-spacing%3Abackground-color%27%3B%3C%2Fscript%3E%0A%0A%20%20%20%20%3Cscript%20src%3D%22qrc%3A%2Fresources%2Fmarkdown-it.js%22%20defer%3E%3C%2Fscript%3E%0A%20%20%20%20%3Cscript%20src%3D%22qrc%3A%2Fresources%2Fmarkdown_template.js%22%20defer%3E%3C%2Fscript%3E%0A%3C%2Fhead%3E%0A%3Cbody%3E%0A%20%20%20%20%3Cdiv%20id%3D%22content-div%22%3E%3C%2Fdiv%3E%0A%0A%20%20%20%20%3Cdiv%20id%3D%22preview-div%22%20style%3D%22display%3Anone%3B%22%3E%3C%2Fdiv%3E%0A%0A%20%20%20%20%3Cdiv%20id%3D%22inplace-preview-div%22%20style%3D%22display%3Anone%3B%22%3E%3C%2Fdiv%3E%0A%0A%20%20%20%20%3Cdiv%20id%3D%22text-html-div%22%20style%3D%22display%3Anone%3B%22%3E%3C%2Fdiv%3E%0A%3C%2Fbody%3E%0A%3C%2Fhtml%3E%0A: Operation not supported
```

**Comment by iosmanthus** [comment]
@tamlok BTW, The AppImage Version work quite well! :smiley:  Thanks!

**Comment by tamlok** [comment]
OK! I know little about the packaging in Linux. If the AppImage works, just enjoy it for now!

**Comment by Erk-** [comment]
I'll look into and see if I can figure it out.

**Comment by Erk-** [comment]
Okay this is strange, it seems that instead of opening in vnote it tries to open the page in your standard browser. It may be somethig to do with using QDesktopServices::open which opens it with xdg-open on linux.

**Comment by tamlok** [comment]
@Erk- That's weird. VNote will only call `QDesktopServices::open()` to open files with unkonw suffix.

**Comment by Erk-** [comment]
This a bit of the error
```
[0601/104735.682313:WARNING:stack_trace_posix.cc(699)] Failed to open file: /tmp/.glrZGjFV (deleted)
  Error: No such file
[0601/104735.685067:WARNING:stack_trace_posix.cc(699)] Failed to open file: /home/erk/#2338073 (deleted)
  Error: No such file
/usr/bin/xdg-open: linje 881: x-www-browser: command not found
/usr/bin/xdg-open: linje 881: x-www-browser: command not found
```

**Comment by cryptonaut** [comment]
I started having this problem as well after upgrading Qt from 5.10 to 5.11. I downgraded back to 5.10 and recompiled vnote and everything is working again so there seems to be something that changed in Qt 5.11 that is causing this issue.

**Comment by tamlok** [comment]
@cryptonaut Thanks! VNote prefers 5.9 for stability. Qt's new versions seem to introduce lots of bugs. For example, 5.10 will make all the shortcuts being triggered twice on macOS, which disables VNote's shortcuts for a long time.

**Comment by Erk-** [comment]
I'll get around to making an appimage version of the package this weekend.

**Comment by ThinCats** [comment]
Same error, same system[Arch Linux] with Qt 5.11

**Comment by tamlok** [comment]
@ThinCats Hi, you could download the `*.run` installation file from Qt instead of downgrading the one in your system.

The warning I think is caused by typo. I declare `%2` and `%3` to QString but do not pass anything to it. I need to find out where it is. :(

**Comment by tamlok** [comment]
@ThinCats You could reference the docs for details.

**Comment by actionless** [comment]
still the same with Qt 5.12 (new LTS) :crying_cat_face:

**Comment by tamlok** [comment]
@actionless I am afraid code change is needed for 5.12. Qt always intro regression in new version. I doubt whether it is necessary to support versions greater than 5.9.

btw, I am still waiting the 5.9.7 package on ubuntu 14.04 to fix the regression introduced by 5.9.6. Sigh~~

**Comment by tamlok** [comment]
@actionless I am afraid code change is needed for 5.12. Qt always intro regression in new version. I doubt whether it is necessary to support versions greater than 5.9.

btw, I am still waiting the 5.9.7 package on ubuntu 14.04 to fix the regression introduced by 5.9.6. Sigh~~

**Comment by tamlok** [comment]
@actionless I am afraid code change is needed for 5.12. Qt always intro regression in new version. I doubt whether it is necessary to support versions greater than 5.9.

btw, I am still waiting the 5.9.7 package on ubuntu 14.04 to fix the regression introduced by 5.9.6. Sigh~~

**Comment by RickCogley** [comment]
hi @tamlok and thank you for vnote. Just wanted to mention that, both my edit and read modes work fine individually, but, in the markdown preferences, selecting open in read mode has no effect. I assume that means, when I search a note and double click it, it should open in read mode. It never does; it just opens in edit mode and I need to manually switch to read mode.

Using v2.2 on MacOS.

**Comment by tamlok** [comment]
@RickCogley Hi! You need to turn it off in the misc tab of the settings (do not highlight matches when opening a result item). For now VNote supports highlighting result only in edit mode.

**Comment by RickCogley** [comment]
ah, right, that worked right away, and I can still just do cmd-f to search within the note if I need to, and get the highlighting. Now I have to decide if that overall tradeoff is going to work for me. I still have to click something to get to edit mode. Wouldn't it be cool if you could just hit `i` from read mode, lol?

**Comment by tamlok** [comment]
@RickCogley You can use `ctrl-t` to switch between read and edit mode. Using `i` will make users confused since there is a Vim mode in edit mode.

**Comment by RickCogley** [comment]
ah, of course (cmd-t on Mac for anyone searching). I now see the shortcut help. I was looking through the menus and did not see it. Thanks for the nudge in the right direction!

**Comment by actionless** [comment]
on Arch Linux it's still broken :(

as a temporary workaround i've discovered what qOwnNotes also have `vi` mode

**Comment by tamlok** [comment]
@actionless `vnote-bin` and AppImage both should work on Arch Linux. Qt 5.12 breaks something that VNote depends on, which causes this issue.

**Comment by actionless** [comment]
but in AppImage it's not using system colors, i was creating a separate issue for that, regarding qt5ct integration

**Comment by tamlok** [comment]
Hi,

It should now work with 5.12 (https://github.com/tamlok/vnote/commit/bda9bf51c18bd9a5a1f85bb8c54118126efe7ef8). So `vnote-git` in AUR should work fine now.

Thanks!

**Comment by actionless** [comment]
thanks a lot, it finally works!

however i spotted the regression with `v_native` theme, not only foreground color not distinguishable but also system font got overridden:

![2019-03-06--1551882095_1997x2082_scrot](https://user-images.githubusercontent.com/1655669/53888029-c8e51480-4023-11e9-955c-19080ff1606b.png)


here's with blank qss as was discussed in this ticket https://github.com/tamlok/vnote/issues/148:

![2019-03-06--1551882056_1997x2082_scrot](https://user-images.githubusercontent.com/1655669/53888048-d0a4b900-4023-11e9-98fa-f6d34138dd99.png)
