### ISSUE TITLE
ubuntu16.04打开笔记闪退

### ISSUE THREAD

**Issue by fengwenhua** [tamlok/vnote#259]
终端输出如下:
已放弃 (核心已转储)
[1:1:0100/000000.334455:ERROR:broker_posix.cc(41)] Invalid node channel message
Received signal 7 BUS_ADRERR 7fe06675f330
麻烦各位大佬,有没有解决方案!!!

**Comment by fengwenhua** [comment]
额...今天早上起床,再次点开,发现有没有问题了... ...期间我打开VNote后,首先关闭了代码行号,然后重新打开VNote,然后就可以点开笔记了,我以为是代码行号的问题,然后我重新打开代码行号,重启VNote,发现笔记也可以正常打开... ...这么迷的吗?!!!

**Comment by tamlok** [comment]
电脑的摆位发生变化了吧？😂
