### ISSUE TITLE
增加两项功能：隐藏上方的工具栏，设置编辑状态下的文字缩放比例

### ISSUE THREAD

**Issue by jjjfew** [tamlok/vnote#260]
# 隐藏上方的工具栏
在macbook下使用v1.16版，发现上方的工具栏图标有明显锯齿，在设置中设定工具栏大小，但找不到一个满意的大小值。因为平常用熟练后，很多快捷键都记住了，也很少会去点击上面的工具栏选项，希望在设置中增加隐藏上方工具栏的设定项，这样在13寸显示屏下，也能增加一些可视面积，更加地简洁。
![](http://p29pyjzdz.bkt.clouddn.com/20180601175055_wfPosi_Screenshot.jpeg)

# 设置编辑状态下的文字缩放比例
同样是在macbook下使用v1.16版，每次打开一个新的笔记，默认在编辑状态下显示的大小都非常小，每次都得通过command + 加号 来增大文字缩放比例。但是关闭后，下次再打开，又恢复到默认非常小的状态。我在设置中找到这项
![](http://p29pyjzdz.bkt.clouddn.com/20180601175905_RRAetu_Screenshot.jpeg)
但是修改完，只是修改了预览状态的默认缩放比例，对编辑状态无效，不知是否是bug，还是这项只是用来设置预览状态的文字缩放比例的。

# 在设置中修改参数，必须重启vNote才生效
同样是在macbook下使用v1.16版，不知道其他版本是否也有这种情况

**Comment by tamlok** [comment]
Hi,

1. 暂时不会隐藏工具栏；
2. 下一个版本会允许自定义编辑器的缩放。只有在mac下，编辑器的字体才显得特别小；
3. 有些选项是需要重新打开当前标签页才生效，有些选项是需要重启VNote才会生效，一般Tootip里面会说明；

谢谢！

**Comment by tamlok** [comment]
1.17支持编辑器自定义字体缩放了，请更新！谢谢！

**Comment by tamlok** [comment]
1.18支持隐藏工具栏了，请更新！谢谢支持！
