### ISSUE TITLE
PlantUML使用问题

### ISSUE THREAD

**Issue by yangmijun** [tamlok/vnote#262]
- V1.17 x64 版 win10，设置如下：
   - 所有设置开始为软件默认，然后把Markdown菜单下的3个图表公式选上，再打开“原地预览”
   - 设置里将PlantUML从“关闭”改为“在线服务”，并勾上“Graphviz”（本机已经安装2.3.8版），
   - 新建一个笔记，仿照官方文档，写一个公式、一个puml，一个flow。
- 第1个问题：
   -  “原地预览”有问题：公式和flow有显示“原地预览”，但中间的puml没有；
   -  切换至阅读模式发现puml能显示，所以只有puml的原地预览模式有问题。
- 第2个问题：
   -  官方截图里PlantUML设置成了“本地JAR”，plantuml.jar这个包我从官网下载了，但不知道应该放在哪里，以及“PlantUML JAR”这一项中的路径该如何填写。我尝试把这个包放进Vnote.exe同目录下，然后“PlantUML JAR”设置成“/plantuml.jar”，再把PlantUML设置成“本地JAR”，发现无效，puml无论在编辑还是阅读模式都显示不出来。所以，问题是：PlantUML要离线使用究竟要如何设置呢？路径该如何填写呢？
- 第3个问题：
  -   “Graphviz”默认是自动检测，但假如我要手动填写路径，路径格式有什么要求（windows下）？
  -  如果本机根本未安装“Graphviz”，或者自动检测没找到vnote会有什么提示？

**Comment by tamlok** [comment]
# VNote配置PlantUML和Graphviz
## 1. 什么是PlantUML和Graphviz
**PlantUML** 是一个通过简单的脚本来绘制UML图表的一个工具，比如说：

    ```puml
    @startuml
    Bob -> Alice : hello
    @enduml
    ```

可以绘制出这样的漂亮图表：

![image](https://user-images.githubusercontent.com/5763157/40868806-5587505a-6600-11e8-8699-48178feb6eaa.png)

**Graphviz** 是一个更为通用的图表绘制语言，PlantUML中的部分图表需要调用Graphviz来绘制。

下面我们以Windows为例介绍如何在VNote中使用这两个神器。

## 2. Graphviz
为了在VNote中使用Graphviz，你需要访问Graphviz的官网下载Graphviz并安装，安装完后，你需要找到`dot.exe`所在位置，如`C:\Program Files(x86)\graphviz\dot.exe`。

打开VNote的设置对话框，启用Graphviz并填写上面的路径：

![image](https://user-images.githubusercontent.com/5763157/40868809-608c8a06-6600-11e8-86fb-e45b6d66a2be.png)

重新打开所以标签页，就可以在VNote中使用Graphviz了：

    ```dot
    balabalabala
    ```

## 3. PlantUML
### 3.1. 在线PlantUML
使用在线PlantUML的好处是不用安装任何东西，但是有可能会泄露隐私，而且无法使用原地预览。

在设置对话框中选择`在线服务`并保留`PlantUML服务器`地址不变即可。

![image](https://user-images.githubusercontent.com/5763157/40868811-6b89501a-6600-11e8-928b-503c5b6ae214.png)

### 3.2. 本地PlantUML
首先，请按照上面的步骤安装`Graphviz`，并测试能成功使用。

访问PlantUML官网下载`plantuml.jar`，将其放到一个全英文的路径中，如`C:\plantuml.jar`。

请安装Java运行时。

配置VNote如下：

![image](https://user-images.githubusercontent.com/5763157/40868814-718d9b2e-6600-11e8-8731-b917bc4611d8.png)

请重新打开所以标签页，这时候应该就能正常使用PlantUML了。

### 3.3. 高级配置
如果上面的配置仍然无法使用PlantUML，而且**确认本地命令行能正确执行PlantUML**，则你可能需要改动VNote的配置文件`vnote.ini`。

`文件`，`打开配置文件夹`，使用记事本编辑`vnote.ini`。

找到`[web]`这一行，在下面新建一行，输入：

```ini
plantuml_cmd=cmd.exe /c \"java -jar C:\\plantuml.jar -charset UTF-8 -nbthread 4 -pipe -t%0\"
```

重启VNote即可。

关于`plantuml_cmd`的具体含义，参考如下：

```ini
; Custom PlantUML command to execute to convert a PlantUML diagram in local PlantUML
; Read data definition from stdin and output diagram result to stdout
; When set, other local PlantUML related settings are ignored
; %0 will be replaced with the format string like svg or png
; plantuml_cmd=/bin/sh -c \"cat | java -jar /opt/plantuml/plantuml.jar -charset UTF-8 -nbthread 4 -pipe -t%0\"
plantuml_cmd=
```

## 4. Live Preview
在编辑窗口，右键打开`图表实时预览`，即可实时预览光标所在处的图表。

**Comment by yangmijun** [comment]
OK了，我弄明白怎么回事了，实际上在上面的第4步就已经正常了，并不需要在vnote.ini文件里加1行。
在我这里不正常的原因是，我改了VNote设置后直接点的右上角X，实际上根本没关闭。彻底退出后再打开就生效了

**Comment by mymartin** [comment]
是否考虑把配置使用说明放进VNote主页的文档里？
