### ISSUE TITLE
所有笔记打开错误

### ISSUE THREAD

**Issue by microhe** [tamlok/vnote#263]
系统是 manjaro linux，今天系统更新了下，笔记都不能打开了，看了下更新列表，感觉和qt升到5.11有关....

![image](https://user-images.githubusercontent.com/12868426/40874152-5793c9fc-669e-11e8-92bc-141903771c6c.png)
![image](https://user-images.githubusercontent.com/12868426/40874212-1a7e18d2-669f-11e8-98e1-0b7a4350daf2.png)

**Comment by microhe** [comment]
刚看到 #258 ，是qt5.11的问题了

**Comment by tamlok** [comment]
是使用appimage吗？

**Comment by microhe** [comment]
是直接从git仓库编译的，就是archlinux 的aur有人打了包上去

**Comment by tamlok** [comment]
嗯嗯，这个建议使用appimage版，或者下载安装一个qt5.9自行编译，可以安装在home目录，不会影响系统，我一直都是这样做的。

**Comment by microhe** [comment]
嗯，可以了。谢谢！

**Comment by l0o0** [comment]
@tamlok  我也遇到这个问题了，我下载的是Appimage 1.18版，ubuntu 18.04 64位
```bash
❯ qmake -v
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
```
系统好像也没有安装qt。  我是需要下载安装qt9么？

**Comment by tamlok** [comment]
@l0o0 Hi, 你这个问题在设置对话框中重置一下布局即可，编辑区宽度被设为0了，右边可以拖拉一下，即可看到。谢谢！

**Comment by l0o0** [comment]
@tamlok 谢谢你的回复，非常感谢你的工具，笔记棒棒

**Comment by tamlok** [comment]
已经修复 (https://github.com/tamlok/vnote/commit/bda9bf51c18bd9a5a1f85bb8c54118126efe7ef8)。
