### ISSUE TITLE
没有编辑模式

### ISSUE THREAD

**Issue by KyleChou** [tamlok/vnote#264]
![_20180604160536](https://user-images.githubusercontent.com/15856324/40905674-3f52830a-6811-11e8-8763-7a945a808785.png)

如图~换以前版本也这样

**Comment by tamlok** [comment]
Hi,

拉一下中央那条控制条，拖动一下，编辑区域就显示出来了。

或者文件菜单，设置，重置布局，然后文件菜单里面退出，重启VNote，即可。

这是因为新版改了界面布局，所以需要清空一下布局。

谢谢！

**Comment by KyleChou** [comment]
已解决~~
