### ISSUE TITLE
怎么导入已经写好的md文档

### ISSUE THREAD

**Issue by je45** [tamlok/vnote#266]
1. vnote好像没有导入已存在md文档的功能，好像需要文件-从文件新建，不能右键选择文件夹导入或者右键新建笔记-选择导入。要从菜单栏上去操作，感觉不太好。
2. 我从磁盘重新加载，好像并不能够把我新添加的md文档读取出来。操作过程：我从其他地方复制md文档到磁盘文件夹中，右键重新加载并不能识别。
3. 在笔记本文件夹内的md文件，同一个好像可以新建多个一样的笔记。

能不能保证文件夹内的md文件和编辑器内展示的笔记保持一致，像onenote一样，动态的加载笔记本。

**Comment by tamlok** [comment]
Hi,

- VNote目前只支持在文件菜单批量复制导入笔记。或者在“浏览器”栏直接浏览外部文件，当做一个编辑器用。
- VNote在每个文件夹都有一个json配置文件来记录所有的笔记和子文件夹，重新加载只是重新加载json文件。可以写个脚本递归为某个目录添加json文件来将一个外部目录变成一个笔记本。
- 有例子吗？应该是有重名检测的。

VNote里面的目录结构和磁盘上是一致的，仅仅是需要一个配置文件来指定文件夹和笔记。如果不想配置文件，可以打开“浏览器”栏，直接浏览编辑磁盘上的文件（会缺失附件等功能）。

谢谢！

**Comment by je45** [comment]
首先谢谢开发者回复:)，重名的问题是有的。

举个例子：我先建一个笔记叫Test.md，此时磁盘中该笔记文件夹中已经生成了这个Test.md了，然后我又从文件-从文件新建笔记，选择之前新建的那个笔记Test.md，会有两个笔记，但是磁盘上只有一个。这样就会造成显示的和磁盘的不对应，删除的话也会有问题。

- 希望后续增加导入笔记功能（目前这种有点麻烦，建议增加右键到右键菜单中），_

- 希望后续重新加载文件的时候检测一下当前文件夹的文件，动态改变一下json配置文件。这样的话，如果从其他地方复制md文档到该笔记的磁盘目录时能够自动识别，也不必再重复导入了。（onenote的自动检测就很棒，随便在磁盘目录中怎么增删，都可以重新组建新的笔记本）

**Comment by tamlok** [comment]
Hi,

- 重名这个的确是个bug，谢谢反馈！
- 后面允许用户指定后缀名，然后检测并加入指定后缀的外部文件吧。

**Comment by officeplayer** [comment]
我的外部文件也是 `*.md` 文件与 `media` 文件夹（存放图片）同级别，`*.md` 文件中插入的图片使用相对路径，首先将 `*.md` 文件与 `media` 文件夹复制到 VNote 相应文件夹下，然后在 VNote 中进行导入操作：`文件` > `从文件新建笔记`，找到 VNote 相应文件夹下的 `*.md` 文件即可成功导入，图片也不会有问题。

**Comment by tamlok** [comment]
Please try 1.21 and re-open the issue again if the problem is not solved. :) VNote now support creating notebook from external directory.
