### ISSUE TITLE
在编辑状态和阅读状态（command + t）切换， 应该以光标编辑当前所在的行的视野为标准；

### ISSUE THREAD

**Issue by hawkinchina** [tamlok/vnote#267]
在编辑状态和阅读状态（command + t）切换， 应该以光标当前所在的行的视野为标准；

比如：一共10行， 当前光标编辑在第5行（编辑状态）， 我想看看阅读状态下的效果。发现当前5行，不在
当前的编辑的位置， 要用鼠标，上下翻滚动才能看到第5行的情况， 

特别是在文章很长的时候，非得要用鼠标上下翻滚，去定位当前编辑所在的地方，这种现象，非常不方便。。

**Comment by tamlok** [comment]
Hi,

目前VNote在阅读编辑切换的时候，只进行标题层级的同步，即确保切换后处于同一个标题下面。

文字级别的同步还没有实现。

谢谢！
