### ISSUE TITLE
【疑问】代码块包裹的代码显示样式并没有与普通样式分离

### ISSUE THREAD

**Issue by ChangeHow** [tamlok/vnote#27]
在我的VNote中，代码块``包裹的样式，仅仅是颜色发生改变，并没有框和灰色的底色进行包裹，致使单词和正文糅杂在一起，不知道是本来编辑器的渲染样式就是这样还是因为我设置的原因，希望解答

**Comment by tamlok** [comment]
您好！在编辑模式中，VNote仅仅是对代码块进行语法高亮（默认是紫色的字体）；在阅读模式下，VNote默认样式是有边框和底色的。

根据我的使用体验，一般代码块前后都会有一个空行，所以揉杂这个问题个人感觉还好。之所以没有弄灰色底色，是因为在编辑的时候，一般底色啥的都是只针对一行中有内容的那些区域，而不是整个区域。后面有时间的话，我可以再调研一下。

谢谢使用和反馈！:)

**Comment by ChangeHow** [comment]
谢谢回答，我刚刚仔细的找了下设置，检查了下样式，发现确实是仅仅只有紫色的样式，出于习惯还是改成了有边框包裹的，感谢，找了很久终于找到一款能用markdown写笔记的应用，正在熟练中，如果能加入代码提示就更好了

**Comment by tamlok** [comment]
@ChangeHow 哦，我误会了，我以为您说的是代码块，原来是行内代码。行内代码没有针对特定代码语言的语法高亮，但是样式是可以自行调节的。我将默认的去掉边框和底色是因为有时候我写笔记行内代码有点多，边框多起来的话，阅读感觉老是磕磕碰碰的，所以就改为紫色了。您可以自行修改样式！

您说的代码提示是指什么呢？基于缓冲区的自动补全吗？这个我后面是计划添加的。

谢谢使用！

**Comment by ChangeHow** [comment]
是的，是自动补全，我试过一款叫harropad的编辑器，补全是挺强大的，但是强制性太强了，很多时候不想用建议代码也会自动补全，然后不得不去删除，如果是有这个计划，小小的建议是，补全的方式希望不要太强势

**Comment by tamlok** [comment]
@ChangeHow OK！放心，VNote会遵循Vim的自动补全来设计，`Ctrl+N/P`激活补全。VNote在很多设计上都会参考Vim，所以用户是有绝对的自由权的。:) 自动补全肯定会加入的，敬请期待！

再次感谢使用！
