### ISSUE TITLE
建议合并笔记本列和工具列

### ISSUE THREAD

**Issue by zengdb** [tamlok/vnote#270]
现在笔记本占了一列，工具占了一列，导致中间正文的宽度不够，建议把笔记本和工具这两列合并，因为实际使用中，只有大纲列表用得多一些，别的可以用的时候切换。

**Comment by tamlok** [comment]
Hi,

左边栏是导航栏，主要用于文件夹笔记的导航；工具栏和搜索栏都是功能性面板，很多情况可能是需要和左边的导航面板紧密结合的，而不是互斥。比如，我打开一篇笔记a，看一下它的大纲，觉得不是要找的，于是打开笔记b，再看大纲，以此类推。如果合并在一起，那就得来回切换。

`Ctrl+E E`可以隐藏左边导航栏，`Ctrl+E T`可以隐藏工具侧边栏，`Ctrl+E C`可以隐藏搜索侧边栏。

谢谢！

**Comment by wuscloud** [comment]
我也有这个想法，1366*768的分辨率太小了，1920*1080就应该不用考虑这个问题了。以后1080p肯定是主流

**Comment by tamlok** [comment]
@wuscloud 现在两个面板已经合为一体了，只是内容还是区分开来而已。我一般编辑的时候都会顺手`Ctrl+E E`，直接将编辑栏放到最大。
