### ISSUE TITLE
导航栏和大纲视图窗口宽度调整

### ISSUE THREAD

**Issue by DreamChase** [tamlok/vnote#271]
文章层次多，大纲视图遮掩，调整宽度以便阅读。但是每次调整完，当再次打开vnote，恢复到初始宽度。
初始宽度设置？

**Comment by tamlok** [comment]
hi,

- Win?
- 设置驻留系统托盘吗？
- 调整后，Ctrl-Q 退出vnote再启动试试？

谢谢！

**Comment by DreamChase** [comment]
已解决，谢谢！
