### ISSUE TITLE
Graphviz图导出pdf中文乱码

### ISSUE THREAD

**Issue by jluliuchao** [tamlok/vnote#272]
在VNote中显示是正常的，如下：
![image](https://user-images.githubusercontent.com/35259060/41647411-e079667e-74a8-11e8-867f-f5579fc3d402.png)
但导出pdf后，pdf中如下：
![image](https://user-images.githubusercontent.com/35259060/41647443-fd83aacc-74a8-11e8-96af-362d8d179c02.png)
无论是否使用wkhtmltopdf，导出的Graphviz图都是乱码。

**Comment by tamlok** [comment]
请问是win 10吗？如果是，系统的区域是中国吗？

谢谢！

**Comment by jluliuchao** [comment]
系统是Win7 64位，系统区域是中国，导出html正常。

**Comment by tamlok** [comment]
已经修复！谢谢！
