### ISSUE TITLE
mac版显示部分emoji问题

### ISSUE THREAD

**Issue by jjjfew** [tamlok/vnote#278]
版本v1.18
不能通过系统全局的`Control + command + 空格键` 调出emoji输入法 
显示大部分emoji表情正常，但以下数字表情显示异常
正常显示
1️⃣
错误显示
![](http://p29pyjzdz.bkt.clouddn.com/20180626112010_9ljOsi_Screenshot.jpeg)

**Comment by tamlok** [comment]
请尝试一下1.20，调了一下字体，应该会好一点。
