### ISSUE TITLE
建议增加浏览器预览效果

### ISSUE THREAD

**Issue by summyer** [tamlok/vnote#279]
- English is preferred;
- Make the title as meaningful as possible;
- One issue for only one thing, since large issues are difficult to remember and handle;
- When reporting problems, elaborate it as detailed as possible like:
    - Version of VNote, which operating system;
    - What is the symptoms;
    - What action triggered it;
    - How to reproduce it;
- Please delete all these text and put whatever you want below. :)

**Comment by tamlok** [comment]
Hi，VNote不需要两边实时预览，具体可参考主页文档说明。谢谢！
