### ISSUE TITLE
文本高亮及颜色设置

### ISSUE THREAD

**Issue by JPingAMMS** [tamlok/vnote#28]
希望可以添加高亮文本（Mark/Highlight）。以及颜色修改。谢谢！

**Comment by tamlok** [comment]
您好，谢谢使用和反馈！

- 高亮文本具体是啥意思呢？是说可以标注某一段文字不同颜色吗？
- 颜色修改是指哪方面呢？目前VNote支持编辑和阅读时的样式自定义，在菜单里面有对应的选项。

谢谢！

**Comment by JPingAMMS** [comment]
您好，是指文字的背景色。就是PDF阅读器提供的高亮文本。在一些markdown的编辑器中用“==高亮文本==”表示。

**Comment by tamlok** [comment]
@JPingAMMS 那应该是扩展语法，作用应该对应于md里面的加粗。考虑到兼容性，VNote可能不会支持这个扩展语法。不过有计划支持通过HTML标记来高亮文本，比如`<font color=red>text</font>`这样，VNote会提供方便的方式来添加和修改类似的高亮。你觉得呢？

**Comment by JPingAMMS** [comment]
谢谢你的提示！确实是HTML标记就可以了。

**Comment by tamlok** [comment]
@JPingAMMS 不客气！目前先这样写着吧，后面VNote会提供非常方便的方式来输入这一串东西，而且在编辑模式中就会以相应的颜色高亮显示。这样放到别的md编辑器也是兼容的。谢谢使用和反馈！
