### ISSUE TITLE
flowchart & mermaid流程图渲染错误when flowchart & mermaid mixed in one document，render result is not expected

### ISSUE THREAD

**Issue by hypersl** [tamlok/vnote#280]
# new_note_001
-----------------------------------------------------------------

```flow
st=>start: Start
e=>end
op=>operation: My Operation
cond=>condition: Yes or No?

st->op->cond
cond(yes)->e
cond(no)->op
​```

```mermaid
graph TD;
  A-->B;
  A-->C;
  B-->D;
  C-->D;
```

上面是用例，最新版本x64 portable，win7 x64下VNote默认配置未改动。用的网上找的流程图例子，直接显示错误。而交换mermaid段和flow端，则可以正常渲染
![image](https://user-images.githubusercontent.com/12387736/41960716-0eb87460-7a23-11e8-80f4-0c15cf070269.png)
![image](https://user-images.githubusercontent.com/12387736/41960733-173a2048-7a23-11e8-89a6-cc805fbe081e.png)

**Comment by tamlok** [comment]
Hi,

Flowchart的结束` ``` `那一行前面有一个特殊字符，将该特殊字符删除或将该行删除后重新输入` ``` `即可。
