### ISSUE TITLE
Failed to create note

### ISSUE THREAD

**Issue by vmexia** [tamlok/vnote#283]
Hello,

I noticed that the text pasted to the note name input its not processed for "invisible" characters like new line "\n", which leads to an error when you try to create that note. Could you please add pre-processing to remove those chars from the text? If not, at least add the detailed error info to the new note and note info popup (instead of prompting the error right away). Currently, the only way to check what is going on is checking the logs.

Thanks for your work,
Vitor

**Comment by tamlok** [comment]
Confirmed and fixed! Thanks!
