### ISSUE TITLE
编辑时中文显示不全，会被滚动条挡住

### ISSUE THREAD

**Issue by losymear** [tamlok/vnote#284]
<img width="668" alt="000tmp" src="https://user-images.githubusercontent.com/30641746/42123373-9e00d0c4-7c83-11e8-8450-135b5a7022b8.png">

**Comment by tamlok** [comment]
是一直有这个问题吗？win的话更新一下显卡驱动看看？

**Comment by losymear** [comment]
系统是macOS Sierra10.12.6，问题不知道是什么时候出现的..
我把Theme从v_pure换成v_native,没有了滚动条也就没这个问题了...

**Comment by tamlok** [comment]
oh，有空我在mac下看看，估计可能是样式有问题。

**Comment by tamlok** [comment]
Hi,

目前我无法重现这个问题。您可以尝试将`v_pure.qss`里面`QScrollBar`相关的条目都删除了：

- "文件" 菜单，"打开配置文件夹"；
- `themes/v_pure/v_pure.qss`;
- 删除[这些行](https://github.com/tamlok/vnote/blob/40424b79312257a10fa18ddc85180c59fd423f30/src/resources/themes/v_pure/v_pure.qss#L974-L1112)

**Comment by tamlok** [comment]
已经找到根源，请参考 https://github.com/tamlok/vnote/issues/454
