### ISSUE TITLE
YAML front matter

### ISSUE THREAD

**Issue by ultranity** [tamlok/vnote#286]
以前用hexo之类标签、分类等设定都是用 YAML front matter完成的。看到最近推了文档tag功能，有个建议，是不是可以参考hexo使用front—matter把这些文档信息记录在md文件内，感觉会比现在这种记录在单独的json文件内要直观些（或许会有性能上的影响？）。至少现在vnote并不支持YAML 或json 编写的文档标记，算是个缺憾
放个参考链接 [hexo文档：front-matter](https://hexo.io/zh-cn/docs/front-matter.html)

**Comment by tamlok** [comment]
Hi,

目前VNote支持显示YAML信息。VNote的出发点是使用其他任意编辑器都能轻松地浏览和编辑笔记文件，而将元数据放在笔记文件里面会使得笔记的可读性变差，所以VNote倾向于使用配置文件来保存笔记的元数据。
