### ISSUE TITLE
这闪退似乎有些严重啊

### ISSUE THREAD

**Issue by qw4096** [tamlok/vnote#287]
win10 64位 1709，下的最新版的64位，闪退了好几次了

**Comment by tamlok** [comment]
是什么操作导致呢？能稳定复现吗？谢谢！

**Comment by qw4096** [comment]
@tamlok 闪退好几次，好多操作都会，打开了几次，都顶不过2分钟，哪些操作不记得了，就记得检查更新的时候闪退过

**Comment by dyinuoh** [comment]
Hi! @tamlok 我在 Windows 7 64bit 作業系統上使用 VNote 時，也常遇到在 **關閉分頁** 時程式閃退。

**Comment by tamlok** [comment]
@qw4096 @dyinuoh 在`文件`菜单选择`打开配置文件夹`，里面会有一个`vnote.log`日志文件。您可以尝试把它删除了，然后打开VNote，尝试复现闪退的操作，闪退后将该文件发给我看一下。

我在使用过程中基本没有遇到闪退，我会尽量尝试复现一下。

另外，建议检查是否有显卡驱动更新。

谢谢！
