### ISSUE TITLE
VNote - Unable to type in Text Box (Internet Explorer)

### ISSUE THREAD

**Issue by aceism** [tamlok/vnote#288]
Hi,
I have noticed an issue with a customer where they have recently updated their LEX Software, and since the update he has been unable to type in the text box at all when replying to someones emails when using Internet Explorer; he can type in who he wants to send the email to, and the subject line, but when he tries to type in the main text box it would not even let him click into the box to start typing, it works fine on Chrome but they really need VNote to work on IE. LEX Support was called and said to clear any cached files on IE, which I did but this has not seemed to fix the issue.
(Sorry that I can't provide any information on what version of VNote is running as I am unable to access the customers machine at the moment)
Any help would be greatly appreciated!!

**Comment by tamlok** [comment]
Hi,
I am confused by your scenario. VNote here means a Markdown note-taking application for desktop. It should not be related with IE. Do you mean this VNote project?

Thanks!
