### ISSUE TITLE
[linux] Appimage & input methods

### ISSUE THREAD

**Issue by nikita-moor** [tamlok/vnote#289]
OS: **Arch Linux**
Input method: **ibus**

Using Appimage release v1.19 (and earlier) I cannot switch keyboard layout. If I have started `vnote` when US-International layout was active, then I cannot switch to Arab or Chinese (for example). However, if I activate Arab layout and then execute `vnote`, then I can type Arab without problems, but cannot switch back to US.

I use input method `ibus` and it worked fine with the AUR package (before the bug in Qt 5.11 #258), so is Appimage edition's support for complex scripts (e.g. Chinese) is not full?

Probably, [this thread](https://github.com/probonopd/linuxdeployqt/issues/131) can be the solution, however I know nothing about the Qt and Appimage.

#83 is not releated.

**Comment by probonopd** [comment]
Possibly `platforminputcontexts` need to be bundled. 
https://github.com/probonopd/linuxdeployqt/issues/131

**Comment by nikita-moor** [comment]
The problem is not solved to me, however it seems you have done everything from your side. Thank you.
