### ISSUE TITLE
不能跳转到其他的笔记链接

### ISSUE THREAD

**Issue by xianzhon** [tamlok/vnote#29]
不能像其他笔记本管理软件(zim)一样，支持内部笔记链接，目前的行为是，可以点击，然后使用默认的打开工具打开这个文件，但是即使设置成vnode打开，然后它不支持markdown文件。

版本: 1.7 (on mac)
e.g.
```
 [link to another file](./another.md)
```

**Comment by tamlok** [comment]
Hi，是的，目前VNote还不支持内部笔记链接跳转，后面会支持。不过，因为VNote没有数据库管理，所以如果笔记重命名，那么该笔记的所有引用链接都会失效。后面VNote会通过支持其他一些特性来将VNote内部的各个笔记关联起来。

谢谢反馈！

**Comment by tamlok** [comment]
Hi 目前VNote支持从命令行传入要打开的文件参数，所以应该是可以配置成默认的md打开方式，在Linux和Win上测试是没有问题的了。另外，内部笔记链接已经支持了(b5646a2b34e50f6d7bb596a9f4f708afe202e59a)，欢迎下载最新1.8版使用！

谢谢！

**Comment by xianzhon** [comment]
@tamlok 非常感谢及时实现功能。有个问题，刚刚测试时发现，对于所有*.md字符串都当做url链接来跳转，这个有什么特别的用意吗？目前的行为，容易误导用户去点击，然后点了之后，是打不开的，所以不太理解。

示例如下
```
This is a markdown file string: test.md (now this one is also displayed as a link)
This is a link to another markdown file: [anther note here](test.md)
```

**Comment by tamlok** [comment]
@xianzhon Hi 这是渲染引擎的一个行为，好像是啥智能链接，即像网址这种东西，你可以直接写就行，不用`[xx](xxxx.com)`这样括起来，渲染的时候会自动将它转为链接。看来`test.md`这种形式也是被当作链接来处理，而且是绝对路径，所以找不到文件。一般对于文件名这种`.`的高危符号，我都会使用行内代码。

后面有时间可以考虑把这个功能的开关选项暴露出来，让用户自己选择。

所以，还是使用`[xxx](test.md)`这种标准形式来作为笔记链接比较好！

谢谢！

**Comment by HgyHgyHgy** [comment]
跳转到不是同一个文件夹下的笔记？

**Comment by kerhbal** [comment]
@HgyHgyHgy  `./`是同层， `../` 是父层， `../../` 是父父层，以此类推

**Comment by ycwu1030** [comment]
想问一下，笔记重命名，或者笔记本重命名，或者移动位置之后的 链接失效问题 以后会考虑吗？

**Comment by tamlok** [comment]
以后会考虑。

**Comment by iEverX** [comment]
@tamlok 请问内部链接是否支持笔记本内的绝对路径？

**Comment by tamlok** [comment]
@iEverX 应该支持，试一下就知道了。复制一个笔记的路径，然后粘贴在编辑器中，有提示。

**Comment by iEverX** [comment]
@tamlok 试了以下，是可以支持相对路径和绝对路径，不过不支持相对 note book 的路径。

比如 
```
notebook
  |-- root_A
    |-- A.txt
  |-- root_B
    |-- B.txt
```
如果在 `B.txt` 里引用 `A.txt`，目前可以使用 `../root_A/A.txt`，也可以用 `/path/to/notebook/root_A/A.txt`，另外一直是否可以支持比如 `@/root_A/A.txt` 这样的写法。

相比绝对路径的优势不说了。相比与相对路径，两个文件只见的相对路径在层级较多的时，不是一目了然的，而相对与笔记本的路径则非常清晰

**Comment by tamlok** [comment]
@iEverX 相对笔记本的写法不是标准语法哦，这样写出来的笔记用其他编辑器打开就没意义了。

插入相对路径时，不用自己手动输入，直接右键复制那个笔记的路径，然后在编辑器粘贴即可。
