### ISSUE TITLE
关于阅读模式下图片查看功能的小问题

### ISSUE THREAD

**Issue by jluliuchao** [tamlok/vnote#290]
1.19加入了在阅读模式下查看图表的功能，有一个小问题：查看图片时，鼠标指针在图片上时，滚轮是放大和缩小，这是正常的。而当指针在图片区域外时，滑动滚轮会看到图片后面的文章在翻页，这是正常的吗？

**Comment by tamlok** [comment]
正常的。因为放大的时候是以鼠标在图片的位置为中心的，当鼠标在图片外时，也就不进行缩放了。
