### ISSUE TITLE
Vnote doesn't start (Win10)

### ISSUE THREAD

**Issue by Yersh** [tamlok/vnote#292]
Subj. 
When I don't reboot computer for a week or so, sometimes Vnote doesn't start. It just sits it memory and eats 12% of CPU. [TaskManager screenshot.](https://i.imgur.com/SXjLFxl.png) Trying to start it again just adds more processes. 
It works fine after your reboot PC. 
Windows 1607 (Build 14393.2035)

**Comment by Yersh** [comment]
> How about end VNote.exe in task manager and start VNote then?

No, it doesn't change anything.

**Comment by tamlok** [comment]
Do not know what I can do in VNote for this. :(
