### ISSUE TITLE
Custom font problems

### ISSUE THREAD

**Issue by Yersh** [tamlok/vnote#293]
I'm trying to make custom theme for Vnote. Found out that font settings in .mdhl file are ignored. Vnotes uses font settings from .qss file (QWidget{font-family}) both for interface and text editor.

**Comment by tamlok** [comment]
Could you share your custom theme?

**Comment by Yersh** [comment]
I just cloned moonlight theme and started to change fonts, to see what renders better. 
[Here is yandex-disk link.](https://yadi.sk/d/EWCnENUs3YrbNc)
I put different fonts in .mdhl file and .qss file. Vnote renders Consolas font from .qss file both in texteditor and UI.

**Comment by tamlok** [comment]
It is a bug. I will fix it in next version.

Thanks!

**Comment by tamlok** [comment]
Should be fixed in 1.20 now. Have a try.
