### ISSUE TITLE
公式的矩阵中换行 \\ 无法换行

### ISSUE THREAD

**Issue by lalalajiangbiyaosi** [tamlok/vnote#297]
- English is preferred;
- Make the title as meaningful as possible;
- One issue for only one thing, since large issues are difficult to remember and handle;
- When reporting problems, elaborate it as detailed as possible like:
    - Version of VNote, which operating system;
    - What is the symptoms;
    - What action triggered it;
    - How to reproduce it;
- Please delete all these text and put whatever you want below. :)

**Comment by lalalajiangbiyaosi** [comment]
$$\begin{matrix} 1 & x & x^2 \\ 1 & y & y^2 \\ 1 & z & z^2 \end{matrix}$$ 
在markdown-it渲染器中无法正确渲染，更换渲染器只有在hoedown中可以正确渲染

**Comment by tamlok** [comment]
目前需要转义，或者放在代码块路面，具体参考帮助菜单的语法值指南。

下一个版本改进后无需转义即可。

**Comment by tamlok** [comment]
1.20已经修复。
