### ISSUE TITLE
痛苦，能否把保存的图片名称中的_去掉

### ISSUE THREAD

**Issue by sx98083714** [tamlok/vnote#298]
自动保存的图片以_开头，然后上传我的千牛云上时，就报错不能上传，只好一个一个改，要么找改名工具批量改，能否把这_去掉，或者支持自定义，比如可以按日期加数字之类命名呢？
希望能改一下，感谢付出的人们！

**Comment by tamlok** [comment]
Hi, 是只有图片文件名有这个问题吗？配置文件`_vnote.json`有没有问题？千牛云是有什么可以配置的吗？谢谢！

**Comment by sx98083714** [comment]
谢谢回复！
_vnote.json可以配置保存下来的图片名称格式吗？
千牛云我用的是wordpress里一个插件，上传时，这个插件拒绝开关是_的文件名，所以必须把文件名改一下才可以上传。
还有一个问题，我插入一个带完整url的图片，比如http://img.taosoeasy.com/wp-content/uploads/2018/07/b05595570d70476b9743c25544478edf.jpeg-default（带有图片格式 ），插入时自动变成一个相对路径，我用的是图片按钮来插入的，只能手动在![]()中插入这个url。

是从昨天晚上看到更新，准备从为知笔记切换到这个用的，目前感觉运行速度蛮好的，为知笔记有点嫌庞大，多任务时电脑吃不消，修改个东西，会有那么一点点卡顿，这个目前没有，另外没有插入表格的功能，这个偶尔也需要用下，有的话最好了。

谢谢回复哦！

**Comment by sx98083714** [comment]
不好意思更正下，我用的是七牛云，打错了。

**Comment by tamlok** [comment]
- 下一个版本会加上一个配置允许用户自定义图片文件名的前缀；
- 如果要单纯插入图片URL的话，需要自己手动书写Markdown的图片格式；可以配置一个Snippet来加速输入过程，具体参考文档；
- 表格功能目前还没有进行优化；

谢谢！

**Comment by sx98083714** [comment]
哦，好的，谢谢如此神速的回复！
url是规律的，我上传好后，用查找替换批量替换似乎也很快 :)
再次感谢，期待软件越来越好，周末愉快！

**Comment by DreamChase** [comment]
表格，能够支持复杂表格么，或者引用外部表格插件

**Comment by tamlok** [comment]
@DreamChase 怎么复杂法？

@sx98083714 这周预计会发布新版本，马上就不用痛苦了:)

**Comment by DreamChase** [comment]
@tamlok  我现在写的有些表格是用html的，需要跨行跨列，普通的单行表格有些情况下不适用。貌似markdown本身是不支持跨行跨列的表格

**Comment by tamlok** [comment]
1.20已经默认非下划线开头。

@DreamChase 后面会设计一下表格，简单的用md，复杂的用html。

**Comment by lxq1** [comment]
@DreamChase 可以使用PicGo的工具，这是一款我用过的很不错的图床上传工具，推荐给你。https://github.com/Molunerfinn/PicGo

**Comment by Eyion** [comment]
1. VN可以一键发布到其他平台吗？比如微信、WordPress
2. 图床除了Github和码云，可以设置其他类型的吗？比如兼容S3协议的
3. 插入本地图片时，支持Piclist直接上传到图床吗？
