### ISSUE TITLE
Is there no Debian installation package?

### ISSUE THREAD

**Issue by a854363956** [tamlok/vnote#299]
I find that there seems to be no support for the Debian system in the support system.Because I didn't see the DEB installation package

**Comment by tamlok** [comment]
Yes, we appreciate any help to package VNote on major diatributions. I spent a lot of time struggling with Linux packaging. It is really painful. I think developers should concentrate on the development while maintainers from distributions help to import the app into their repos.

Packages for openSUSE and Arch are maintained by users.

Thanks!
