### ISSUE TITLE
通过模板新建笔记功能

### ISSUE THREAD

**Issue by Asymp** [tamlok/vnote#3]
可以将笔记保存为模板，在新建笔记文件时，可以选取模板新建。减少一些重复性工作。非常感谢

**Comment by Necolo** [comment]
这个我也有需求。

**Comment by tamlok** [comment]
Hi, 已经支持笔记模板(78a86cddc01d9f458cf7ce78d865eb1c99c6a3e2)，请关注下一个版本1.10。

目前不支持将已有笔记标记为模板，需要手动拷贝到模板目录。因为模板支持**幻词**，如`%no%`表示笔记名去除后缀部分，`%da%`表示当前日期等，所以为了避免当前笔记中包含`%`等敏感字符，不支持直接从已有笔记新建模板。

谢谢！
