### ISSUE TITLE
【需求】通过快捷键打开一个笔记

### ISSUE THREAD

**Issue by xianzhon** [tamlok/vnote#30]
打开Vnote后，但我需要打开一个笔记本的时候，我需要用鼠标点击具体的某一个笔记，但笔记层次很深，笔记很多时，这样很不方便。如果能提供一个快捷键(e.g. Ctrl+O)，那么输入部分文件名，弹出一个匹配的列表，从而用鼠标或者方向键选择一个目标笔记打开。

版本: 1.7 (on mac)

**Comment by tamlok** [comment]
Hi, VNote会支持类似于Sublime Text一样的任意跳转搜索框。另外，VNote后面会支持常用笔记列表。

谢谢使用和反馈！:)

**Comment by tamlok** [comment]
VNote已经支持**通用入口**了，可以随意打开任意笔记，欢迎下载1.14试用！
