### ISSUE TITLE
导出 Markdown 时，插入的文件不能被导出

### ISSUE THREAD

**Issue by officeplayer** [tamlok/vnote#304]
导出 Markdown 时，图片和附件可以一并导出，但在文中以例如 `[mkmd.bat](file/mkmd.bat)` 这种方式插入的文件不会被导出，有没有办法解决？（我目前是手动操作）

**Comment by tamlok** [comment]
VNote只会管理通过VNote插入的图片和附件，对于文本内容不做其他解析。

建议作为附件插入。后面会提供方式来将某个附件文件插入链接到当前位置。
