### ISSUE TITLE
从一处拖动选中文本到另一处时不显示插入光标

### ISSUE THREAD

**Issue by officeplayer** [tamlok/vnote#305]
从文中一处拖动选中的文本到文中另一处，目标位置不显示插入光标，这样不是很方便，不能明确知道是否已经移动到目标插入位置。

**Comment by tamlok** [comment]
下个版本会修复，谢谢！

**Comment by tamlok** [comment]
@qgmzhna 这个请更新一下显卡驱动？应该不是同一个问题。

**Comment by officeplayer** [comment]
是不是和#310一个问题啊

**Comment by qgmzhna** [comment]
@tamlok @officeplayer 找到问题了。笔记本电脑双显卡，我全局设置的是用独显，编辑文档时编辑页面不动（但实际内容已经变动）；改用核显无此问题。

**Comment by tamlok** [comment]
1.20已经修复。

**Comment by officeplayer** [comment]
问题已解决，赞！
