### ISSUE TITLE
公式相关的渲染问题

### ISSUE THREAD

**Issue by officeplayer** [tamlok/vnote#306]
当 `Markdown` > `Markdown-it选项` > 勾选 `上标` & `下标` 时，如下形式一、二可以渲染正常，而形式三、四则不能正确渲染：

形式一：

```
a<sup>2</sup>+b<sup>2</sup>=c<sup>2</sup>
```

形式二（那个反斜杠\该去掉）：

```
```mathjax
$$
a^2+b^2=c^2
$$
\```
```
形式三：

```
$a^2+b^2=c^2$
```
形式四：

```
$$a^2+b^2=c^2$$

**Comment by tamlok** [comment]
hi，

- 上标的语法是`29^th^`，下标的语法是`H~2~O`；
- 公式下一个版本会修复，这几个形式应该都没问题。

**Comment by tamlok** [comment]
1.20已经修复。

**Comment by officeplayer** [comment]
棒棒的，没问题了！
