### ISSUE TITLE
如何将工具栏嵌入整体窗口

### ISSUE THREAD

**Issue by roojay520** [tamlok/vnote#31]
你好，我好奇的点了某个选项，导致工具 _大纲与主窗口分开，我该如何还原回去？

**Comment by tamlok** [comment]
@roojay520 Hi, 只需要把用鼠标把它拖回原来的地方然后释放鼠标即可。如下图：

![outline](https://user-images.githubusercontent.com/5763157/29004023-a829a478-7af3-11e7-811f-f3eba3011781.gif)

谢谢使用！

**Comment by roojay520** [comment]
非常感谢！
