### ISSUE TITLE
增加更新图片链接功能

### ISSUE THREAD

**Issue by officeplayer** [tamlok/vnote#310]
为了行文流畅，我经常一边截图、一边插图写文章，文章写差不多的时候，我会来到图片目录下，对图片进行处理（比如剪裁、标注等），再回到 vnote 中的时候，图片没有变化，要么手动将插图的那句文本删个字再加上，图就变过来了，或者重启一下。
希望能加入更新图片链接的功能，对单张、整篇里所有图片都可以用的那种。

**Comment by tamlok** [comment]
hi，标签页右键菜单里面有重新加载功能，可以尝试一下。

**Comment by officeplayer** [comment]
我试了，打开vnote，打开一个笔记，然后在其图片文件夹对图片进行了剪裁，右键单击顶部该笔记的标签，右键菜单中选 从磁盘中重新加载，图片依然没变（编辑模式和阅读模式）。

**Comment by tamlok** [comment]
1.20已经修复，请尝试一下。

**Comment by officeplayer** [comment]
先保存，再重新载入，图片更新了，棒！
