### ISSUE TITLE
关于大纲与插入光标的一个建议

### ISSUE THREAD

**Issue by officeplayer** [tamlok/vnote#312]
在编辑模式下，通过大纲跳转笔记位置，希望光标能自动定位到笔记中相应位置并成为焦点。

**Comment by tamlok** [comment]
请更新1.20

**Comment by officeplayer** [comment]
我还是觉着不方便，编辑模式还是应该光标自动第；定位到在在大纲处点到的相应位置，阅读模式下可以焦点一直在大纲窗格

**Comment by tamlok** [comment]
单击改变焦点会导致一个问题：我本来是想聚焦大纲，然后上下导航的；但我单击一下大纲条目后，大纲就失去焦点了。
