### ISSUE TITLE
Documentation 中的一处疑问

### ISSUE THREAD

**Issue by officeplayer** [tamlok/vnote#315]
http://vnote.readthedocs.io/en/latest/index.html
Frequently Asked Questions
How to make VNote more “portable”?
However, please no ce that VNote will store the notebook’s path in the conﬁgura on ﬁle, so it may read a wrong path and complain about errors if you copy VNote to another computer.
貌似现在笔记路径存放在 session.ini 文件中了吧。

**Comment by tamlok** [comment]
是的，session.ini也算是配置文件。
