### ISSUE TITLE
Linux下编译错误

### ISSUE THREAD

**Issue by add358** [tamlok/vnote#316]
编译环境： Ubuntu 14.04， Qt-5.11.1, GCC-4.9.4
编译出错现象： Error compiling js file: ../../../src/utils/markdown-it/markdown-it-imsize.min.js:1:1532: error: Syntax error

**Comment by tamlok** [comment]
编译命令是？

很奇怪，js文件为啥会被编译？

**Comment by add358** [comment]
/home/jake/lib/Qt5.11.1/5.11.1/gcc_64/bin/qmlcachegen --resource=/home/jake/Downloads/vnote/src/vnote.qrc -o utils_markdown-it_markdown-it-imsize.min_js.cpp ../../../src/utils/markdown-it/markdown-it-imsize.min.js
是不是版本太高了，不兼容。 我在该位置加上";"可以解决这个问题， 但后续其他js文件编译也有其他问题。 js不是很熟悉

**Comment by add358** [comment]
直接用qtcreator打开VNote.pro工程文件进行编译的， 应该是没问题的吧？

**Comment by tamlok** [comment]
比较奇怪。试试下载一个5.9看看？能把具体步骤和截图贴一下吗？

**Comment by add358** [comment]
用5.11编译Release版本会出现这个问题，编译Debug版本没有出现。
用5.9编译两个版本都不会出现这个问题，不过会出现另一个问题，提示没有dbus库， 看了下系统是有安装的。

> /home/jake/lib/Qt5.9.6/5.9.6/gcc_64/lib/libQt5WebEngineCore.so: undefined reference to `dbus_bus_register@LIBDBUS_1_3'
make[1]: Leaving directory `/home/jake/Downloads/vnote/build/build-VNote-Desktop_Qt_5_9_6_GCC_64bit-Release/src'
/home/jake/lib/Qt5.9.6/5.9.6/gcc_64/lib/libQt5WebEngineCore.so: undefined reference to `dbus_watch_get_data@LIBDBUS_1_3'
/home/jake/lib/Qt5.9.6/5.9.6/gcc_64/lib/libQt5WebEngineCore.so: undefined reference to `dbus_connection_close@LIBDBUS_1_3'
/home/jake/lib/Qt5.9.6/5.9.6/gcc_64/lib/libQt5WebEngineCore.so: undefined reference to `dbus_message_get_signature@LIBDBUS_1_3'

**Comment by tamlok** [comment]
会不会是14.04的dbus版本太低了呢？如果实在编译不了，就使用appimage吧。不过，appimage也是在14.04上面构建的。

**Comment by itviewer** [comment]
打开项目后，设置下，
项目—构建步骤，取消勾选“Enable Qt Quick Compiler”
