### ISSUE TITLE
Table of Content 的生成？

### ISSUE THREAD

**Issue by Yixiaohan** [tamlok/vnote#317]
是否可以生成 Table of Content？

类似于这样的效果？
https://github.com/CyC2018/Interview-Notebook/blob/master/notes/Redis.md

**Comment by officeplayer** [comment]
导出pdf时勾选使用wkhtmltopdf，勾选启用目录

**Comment by tamlok** [comment]
在文档中添加:

```
[toc]
```

**Comment by officeplayer** [comment]
markdown语法是[toc]

**Comment by Yixiaohan** [comment]
非常感谢
