### ISSUE TITLE
flowchar 不支持 parallel

### ISSUE THREAD

**Issue by fortystory** [tamlok/vnote#318]
如[flowchar.js.org](http://flowchart.js.org/)上第一个例子

**Comment by tamlok** [comment]
Parallel特性是2018年4月新引入的，VNote需要更新Flowchart才能支持。下一个版本会支持。

**Comment by fortystory** [comment]
多謝

**Comment by tamlok** [comment]
Please try 1.21 and re-open the issue again if the problem is not solved. :)
