### ISSUE TITLE
建议：左侧笔记本管理功能

### ISSUE THREAD

**Issue by officeplayer** [tamlok/vnote#319]
建议增加通过左侧笔记本、笔记面板管理笔记，可以通过拖拽改变笔记本、文件夹的层级关系。

**Comment by tamlok** [comment]
目前可以右键复制剪切粘贴来在笔记之间移动笔记或文件夹。是指这个功能吗？

**Comment by officeplayer** [comment]
是的，就这个功能

**Comment by tamlok** [comment]
Fixed in 2.1. Please try it out. Thanks!
