### ISSUE TITLE
代码行不显示行号

### ISSUE THREAD

**Issue by waterdr0p** [tamlok/vnote#32]
建议使用 typora2 的UI和使用方式，或macdown 的使用方式，结果笔记本管理功能，会很完美

**Comment by tamlok** [comment]
您好，谢谢使用！“代码行不显示行号”是指阅读模式下代码块里面不显示行号吗？目前，在编辑模式下，您可以启用编辑区域的行号（菜单“编辑”）。在阅读模式下，暂时还没有行号显示。

正如REAMDE里面说的，Typora的交互逻辑是Markdown的另一个极端，有点违背Markdown的设计初衷。VNote是采用一种折中的方法来减少Markdown编辑与阅读之间的割裂感。后面VNote也会借鉴其他的编辑器的方法，来获得更舒适的Markdown编辑体验，希望能继续关注！

谢谢！

**Comment by waterdr0p** [comment]
不是所有行号，那个功能我尝试过。我希望代码片段会显示行号，代码有5行，那么行号1-5，其它文本正常显示。
另外，图标栏的图标太大，也比较生硬，建议用户可隐藏。就是快捷访问的图标：新建根文件夹、新建笔记、笔记信息、删除笔记...那一行菜单。
编辑区域可显示快速切换多个笔记，这个功能很快，建议左对齐，最好有sublime 的切换体验。

**Comment by tamlok** [comment]
@waterdr0p 谢谢反馈和建议！

- 编辑时代码行号短期内VNote不会支持，因为VNote只是对不同的Markdown语法进行不同的样式高亮，并没有区分对待这些元素，这也符合Markdown作为简单标记文本的理念。
- 您是在macOS下吗？我后面看看图标栏的图标能否变小一点。目前在Win和Linux上感觉大小还行，不过在macOS上就有点略大。
- 左对齐是哪个部件左对齐呢？后面VNote会像Sublime Text一样，支持弹出一个搜索框，随意跳转，敬请关注。

谢谢！

**Comment by tamlok** [comment]
@waterdr0p Hi，按照您的建议，把工具栏图标变小后果然精致不少，谢谢！欢迎下载1.8版本使用！

**Comment by tamlok** [comment]
@waterdr0p Hi, 已经实现编辑和阅读模式下代码块的行号显示(7fd2273aad128f5df5788a42e1e814039c780cbe)，可以关注下一个版本或者尝试最新构建版本。谢谢反馈和支持！
