### ISSUE TITLE
v1.2的Mac版字体大小的bug

### ISSUE THREAD

**Issue by jjjfew** [tamlok/vnote#320]
mac版本升级到v1.2后，在编译模式下无法修改正文的字体大小了，按command + +后，只有标题会变大，正文的默认字体大小非常小，并且在设置中的编辑模式下字体缩放也失效了。
![](http://p29pyjzdz.bkt.clouddn.com/20180724180425_nrVwt8_Screenshot.jpeg)

**Comment by tamlok** [comment]
请先修改默认主题下面v_pure.mdhl文件里面的font-size来自定义字体大小。后面会修复。

**Comment by officeplayer** [comment]
Windows下一样的问题

**Comment by tamlok** [comment]
The zoom bug in edit mode has been fixed now. Please try the latest [build](https://bintray.com/tamlok/vnote/vnote/1.20) if you need it.

Thanks!

**Comment by tamlok** [comment]
Please try 1.21 and re-open the issue again if the problem is not solved. :)
