### ISSUE TITLE
Failed to search notes with tags that start/end with "#" in [Tags] panel

### ISSUE THREAD

**Issue by DingSa** [tamlok/vnote#323]
OS: Windows 10 Home Edition 17134
VNote version : 1.20
Symptoms: VNote will show the warning "Empty tag detected!..." 
How to reproduce it: Add a "C#" tag to the note and try to search it by double clicking the "C#" tag in the [Tags] panel.

**Comment by tamlok** [comment]
Fixed (47503fddfe3275485fd012c6c08f197859a63667). Thanks!

**Comment by tamlok** [comment]
Please try 1.21 and re-open the issue again if the problem is not solved. :)
