### ISSUE TITLE
有代码段时画面闪动的问题

### ISSUE THREAD

**Issue by jluliuchao** [tamlok/vnote#329]
测试文件和录像见附件。
[画面闪动Bug.zip](https://github.com/tamlok/vnote/files/2255880/Bug.zip)

**Comment by tamlok** [comment]
Hi,

嵌套的代码块请在前面空一行，如下：

    1. 测试  
    测试
    Test  
    
        ```c
         /* Output and update for atomic system: '<Root>/Subsystem' */
        void Test_Subsystem(uint8_T rtu_In1, B_Subsystem_Test_T *localB,
        ```

**Comment by tamlok** [comment]
那可能是我这边还没发布的优化，等下一个版本试试看。

**Comment by jluliuchao** [comment]
好的，我现在用的是1.20版本。不过奇怪的是：只有在第二个代码块下面输入文字才会出现闪动，而在第一个代码块下面输入文字并不会出现闪动。

**Comment by tamlok** [comment]
Please try 1.21 and re-open the issue again if the problem is not solved. :)

**Comment by jluliuchao** [comment]
反馈一下，1.21版本已解决此问题。
