### ISSUE TITLE
[需求]希望可以配置点击笔记时默认是预览还是编辑

### ISSUE THREAD

**Issue by lanmeng-org** [tamlok/vnote#33]
目前点击一个笔记的时候默认是预览状态,也就是渲染后的样式.

但是我每次点击笔记渲染都需要3~5秒的时间, 点了之后就是白页, 过一会才显示内容, 很影响使用.

希望可以添加一个选项, 可以选择点击笔记默认是进入编辑还是预览.

**Comment by tamlok** [comment]
hi，您用的是哪个版本？是自己编译的吗？目前我的打开一个笔记一般最多2秒。后面可以添加一个配置。

谢谢！

**Comment by lanmeng-org** [comment]
VNote_win_X64_portable_1.7

快的时候差不多2秒, 不过大多数时候都是3秒以上, 慢的时候就得5秒左右了.

**Comment by tamlok** [comment]
@lanmeng-org Hi, 已经实现可配置默认打开模式(f050d7d81475ea3a6264ebaa478630b507cad297)，可以在`设置`菜单中进行配置。请关注下一个版本，或者尝试最新构建版本。谢谢反馈和支持！

**Comment by lanmeng-org** [comment]
谢谢！
