### ISSUE TITLE
toolbar buttons do not restore their appearance when toggling edit/view mode

### ISSUE THREAD

**Issue by hgue** [tamlok/vnote#333]
I noticed a display bug in the toolbar here running Arch and the AppImages 1.20 an 1.19.
In both versions the toolbar icons for content formatting do not restore their solid state on change between edit and view mode. I can reproduce that when hitting Ctrl+T multiple times toggling mode and putting the cursor in the note in when in edit mode. The toolbar icons (e.g. bold) is useable and will get a solid (not shadowed) state when clicking on it. All other are greyed out as long as they are not clicked.

An example is attached here showing the italic button solid and all other shaded:

![screenshot_toolbar](https://user-images.githubusercontent.com/8872714/43680403-3546647c-983a-11e8-86b2-b4e6ccac6425.png)

**Comment by tamlok** [comment]
So those buttons are grey but clickable?

**Comment by hgue** [comment]
Great!

**Comment by tamlok** [comment]
Please try 1.21.
