### ISSUE TITLE
some marks could not be escaped in code block while in editing mode

### ISSUE THREAD

**Issue by hypnoswang** [tamlok/vnote#334]
it has been supposed that all the markdown marks should be escaped in the code block while in editing mode. But I got the below result when I try to put some comment content into the two ``` code-block marks in editing mode:

```
### This should be an comment
## This should be another comment
```

But what I get in editing mode is that: the first line comment is interpreted as level 3 title and the the second line is interpreted as level 2 title.

But in the preview mode, the interpretation has no problem.

![20180806115615956](https://user-images.githubusercontent.com/7484241/43696274-c5451452-996f-11e8-8881-ca89f6b8e409.jpg)

**Comment by hypnoswang** [comment]
I've got the solution: we need add at least on empty line before and after the code block

**Comment by tamlok** [comment]
Yes. For code block nested in a list, we should add one line before the code block and indent all the whole code block.
