### ISSUE TITLE
能否增加编辑模式下不显示图片的设置选项

### ISSUE THREAD

**Issue by i2Worker** [tamlok/vnote#335]
你好，在编辑模式下，现在默认是会显示插入的图片的，这样有时候感觉会影响编辑的感觉，都是文字在一起感觉更好，可能是个人习惯，呵呵，所以不知道有没有办法，让个人自己选择，有这样一个选项，让编辑模式不显示图片，谢谢！

**Comment by i2Worker** [comment]
我自己找到了，配置文件中有一个配置项：enable_preview_images=true

**Comment by tamlok** [comment]
在markdown菜单里面有开关选项

**Comment by i2Worker** [comment]
嗯，主要是没有理解好“原地预览”，呵呵。
