### ISSUE TITLE
Manage notes on Android phone

### ISSUE THREAD

**Issue by seth100** [tamlok/vnote#336]
Hi,

the VNote app is great, but I need to sync notes with my Android phone too.
So I'm using [Markor](https://github.com/gsantner/markor) to open markdown notes on my phone.
The problem is that the Markor app also sees the "*v_*" folders that VNote creates.
Is there a way to prevent VNote from creating those folders?
Or do you know any other app to manage VNote notes on the phone?

Thanks

**Comment by tamlok** [comment]
Hi,

VNote needs these folders to manage notes. I am afraid we need to wait before someone develop VNote for mobile.

**Comment by seth100** [comment]
Ok, it's a pity.
It would be possibile to add the possibility to update json file when I click "reload from disk" so that I have changed the folders structure from phone I can reload it from VNote?

**Comment by tamlok** [comment]
No. I am afraid you need to write a python script to scan through your folders and add new files to the json config file manually.

**Comment by tamlok** [comment]
By the way, you could just use VNote as an editor to edit your notes. VNote supports listing external files.

**Comment by hgue** [comment]
What about scanning all markdown files in background when starting vnote? The application could add new files missing in the json file as already mentioned here or delete all markdown files that do not exist anymore on disk. There could also be a dialog shown to the user what to do in that case.
Building a Python script for that should be easy, but a pure C++  solution would show a better performance.
I also think this would be a very good feature when going mobile using synchronization solutions like syncthing.

**Comment by tamlok** [comment]
@huge What about markdown files in attachment folders?It is trivial to handle all corner cases. For now I don't have much time for these extended scenarios. Few people participate in the development of VNote. I think for now a python script is OK since user know exactly what they want.
