### ISSUE TITLE
有时无法即时显示新建或删除的笔记

### ISSUE THREAD

**Issue by FallenXtar** [tamlok/vnote#337]
Win10 Enterprise 1803
新建或删除笔记后，笔记本侧栏没有即时刷新，有时需要手动重新从硬盘读取笔记，有时则根本打不开右键菜单
[vnote.log](https://github.com/tamlok/vnote/files/2270409/vnote.log)

**Comment by tamlok** [comment]
Hi,

- 你是从VNote里面删除和新建笔记吗？
- 从log里面只看到两个相关的信息。手动修改过`_vnote.json`文件吗？

   ```
    Warning:fail to read directory configuration file: "C:/Users/Administrator/Documents/vnote_notebooks/vnotebook/_vnote.json"
    Warning:fail to read notebook configuration "C:/Users/Administrator/Documents/vnote_notebooks/vnotebook"
    ```
- 尝试新建一个笔记本，然后操作试试？

**Comment by FallenXtar** [comment]
- 是在程序中删除和新建的。
- 并未修改过_vnote.json，尝试过重置Vnote，在新路径重新安装Vnote，均无效。
- [新的问题出现，请参阅附件
![record1](https://user-images.githubusercontent.com/19383008/43873514-66ddbf08-9bb9-11e8-9dc8-72679a695145.gif)

- 尝试在其它位置新建笔记本，成功消除之前的问题，但出现了新的问题

**Comment by tamlok** [comment]
Hi,

请尝试更新显卡驱动。参考 (https://github.com/tamlok/vnote/issues/256) 和 (https://github.com/tamlok/vnote/issues/226)。

**Comment by FallenXtar** [comment]
已解决
另外测试发现此问题仅出现在nVIDIA独立显卡运行下，Intel集成显卡无此问题
