### ISSUE TITLE
提个建议：输出PDF的时候，能按照标题层级输出对应的标签

### ISSUE THREAD

**Issue by ddyllen-z** [tamlok/vnote#339]
这样PDF查看的时候，右侧就有会导航标签，找东西方便点。

**Comment by ddyllen-z** [comment]
@tamlok 刚试了下，确实可以。好吧，没发现这个可以生成标签，生成的PDF还是没有自带导出的好看。

**Comment by tamlok** [comment]
wkhtml2pdf和pandoc都有很多参数，你有这方面要求的可以研究研究。自带的导出的文件大小比较大。另外，也可以尝试导出HTML，嵌入图片，也是一个文件，最大限度保留原格式。
