### ISSUE TITLE
【需求】移动目录或者笔记到另一个目录

### ISSUE THREAD

**Issue by xianzhon** [tamlok/vnote#34]
需求：支持移动一篇笔记或者目录到另外一个目录
目的：修正目录的层级结构，例如发现某篇笔记应该归为另外一类，或者某个子目录放到另外一个目录下更合适。
操作：
1. 拖动一篇笔记到另外一个目录时，移动效果
2. 拖动一个目录到另外一个目录时，递归地将其子目录及其他笔记都移动到目标目录

研究了一下代码，这个功能似乎改动还挺大，涉及到笔记里面引用其他笔记的路径，以及图片的路径等。
仅提出来，方便以后增加这个功能。优先级低于“全局搜索”，“快捷键任意打开笔记”等需求。

**Comment by tamlok** [comment]
Hi, 目前VNote支持文件和文件夹的移动（笔记本内或笔记本间），不过需要使用右键菜单里面的复制和粘贴，暂时还没有实现拖放操作而已，移动功能是完全没有问题的。拖放操作后面也会实现，但是正如您所说，优先级比较低。
谢谢反馈~~！

**Comment by xianzhon** [comment]
Sorry. 是我没有注意到右键菜单，原来是有这个功能呢，赞！
