### ISSUE TITLE
UI freezes in edit mode when Live Preview for Diagrams is disabled

### ISSUE THREAD

**Issue by PaperCube** [tamlok/vnote#340]
Version 1.20 ```dace19119f3e516d5e5e1e3b21d63a999f8032e6 ```
Running on Windows 10, 17134.191
UI freezes in edit mode when Live Preview for Diagrams is disabled, while menus are still able to show up with corresponding actions. If I enable Live Preview for Diagrams or exit edit-mode, everything goes back normal.   

To reproduce this issue, open a markdown document, edit it through action in right-click menu, disable Live Preview for Diagrams, and user interface stops responding.

**Note :** Though user interface "isn't responding", the application can still handle all input actions correctly but I can see no response and Windows **doesn't** report that the app isn't responding (which means it is responding but just user interface freezes.)

**Comment by PaperCube** [comment]
![img](https://user-images.githubusercontent.com/7395735/43952188-c14d788e-9cc7-11e8-9158-ce313fef014c.png)
As is seen, when I resize window when it's frozen, display just scales but isn't repainted.

**Comment by tamlok** [comment]
Hi,

I think it is similar as https://github.com/tamlok/vnote/issues/337

Please update the driver of display card, or use the integrated display card for VNote.

Thanks!

**Comment by PaperCube** [comment]
It turned out that both using integrated display card and adding environment variable `QT_OPENGL` with value `angle` or `software` **work**.

Thank you very much!

P.S. I think it would be better if you could put this problem and its workaround somewhere easy to spot if it is encountered from time to time because it seems common to have a NVidia + Intel dual graphic cards nowadays.

**Comment by tamlok** [comment]
Integrated display card is preferred. `angle` and `software` solution may show performance regression.

Issues on github are the best place to show issues user met during the use. :) This issue will surely help other guys.
