### ISSUE TITLE
Add tags/labels to chapters ("DONE", "TODO", "WIP", etc.)

### ISSUE THREAD

**Issue by Symbian9** [tamlok/vnote#341]
Is it possible add tags/labels for chapter title such as shown on image:

- https://twitter.com/ValberSleepless/status/1028394813157240837/
![pic](https://pbs.twimg.com/media/DkWXDtyXcAE4j80.jpg:orig)

**Comment by tamlok** [comment]
Hi,

I am afraid you need to use `# <span class="todo">TODO</span> Title` and add the CSS `todo` to the CSS style file. Or use `<font color="red">TODO</font>`.

BTW, you could use **Snippet** to assist the input.

Thanks!
