### ISSUE TITLE
删除文档，文档的标签依然残留

### ISSUE THREAD

**Issue by DreamChase** [tamlok/vnote#342]
删除文档，文档的标签依然残留

双击标签显示文档能否更改为单击

**Comment by tamlok** [comment]
这只是个松散的标签系统。当激活一个标签的时候，其实是执行一个查找。当找不到结果时，会提示是一个空标签，提示用户删除。

因为是查找操作，比较耗时，双击出发会比较好。

**Comment by tamlok** [comment]
双击空标签，如果没有对应的笔记显示，这时候不会提示删除标签吗？

**Comment by DreamChase** [comment]
哦，原来死这样，已解决。
