### ISSUE TITLE
文件无法编辑

### ISSUE THREAD

**Issue by Amb1t0in** [tamlok/vnote#343]
文件进入编辑模式，光标消失，无法显示编辑内容，但是切换到预览模式时内容存在，求助

**Comment by Amb1t0in** [comment]
Warning:QCssParser::parseHexColor: Unknown color name '#content_fg'
Warning:QCssParser::parseHexColor: Unknown color name '#content_fg'
Warning:QCssParser::parseHexColor: Unknown color name '#content_fg'
Warning:QWindowsWindow::setGeometry: Unable to set geometry 504x313+2654+553 on QWidgetWindow/'VNewNotebookDialogClassWindow'. Resulting geometry:  506x321+2654+553 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 504x313, maximum size: 504x313).
Warning:QWindowsWindow::setGeometry: Unable to set geometry 370x109+2750+664 on QWidgetWindow/'VNewDirDialogClassWindow'. Resulting geometry:  372x117+2750+664 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 370x109, maximum size: 370x109).
Warning:QWindowsWindow::setGeometry: Unable to set geometry 443x195+2651+582 on QWidgetWindow/'VNewFileDialogClassWindow'. Resulting geometry:  445x203+2651+582 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 443x195, maximum size: 443x195).
Warning:QWindowsWindow::setGeometry: Unable to set geometry 443x195+2651+582 on QWidgetWindow/'VNewFileDialogClassWindow'. Resulting geometry:  445x203+2651+582 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 443x195, maximum size: 443x195).
Warning:QWindowsWindow::setGeometry: Unable to set geometry 370x109+2687+626 on QWidgetWindow/'VNewDirDialogClassWindow'. Resulting geometry:  372x117+2687+626 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 370x109, maximum size: 370x109).
Warning:QWindowsWindow::setGeometry: Unable to set geometry 504x311+2591+515 on QWidgetWindow/'VNewNotebookDialogClassWindow'. Resulting geometry:  506x319+2591+515 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 504x311, maximum size: 504x311).
Warning:QWindowsWindow::setGeometry: Unable to set geometry 370x109+2687+626 on QWidgetWindow/'VNewDirDialogClassWindow'. Resulting geometry:  372x117+2687+626 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 370x109, maximum size: 370x109).
Warning:QWindowsWindow::setGeometry: Unable to set geometry 443x195+2651+582 on QWidgetWindow/'VNewFileDialogClassWindow'. Resulting geometry:  445x203+2651+582 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 443x195, maximum size: 443x195).
Warning:QWindowsWindow::setGeometry: Unable to set geometry 370x109+2687+626 on QWidgetWindow/'VNewDirDialogClassWindow'. Resulting geometry:  372x117+2687+626 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 370x109, maximum size: 370x109).
Warning:QCssParser::parseHexColor: Unknown color name '#content_fg'
Warning:QCssParser::parseHexColor: Unknown color name '#content_fg'
Warning:QCssParser::parseHexColor: Unknown color name '#content_fg'
日志文件如上

**Comment by tamlok** [comment]
https://github.com/tamlok/vnote/issues/340

请使用集成显卡或者更新显卡驱动。

**Comment by Amb1t0in** [comment]
谢谢，已经解决
