### ISSUE TITLE
VNote_win_X64_portable_1.21打开笔记闪退

### ISSUE THREAD

**Issue by RichyYang** [tamlok/vnote#344]
VNote_win_X64_portable_1.21可以新建笔记，但是CTRL+T也会闪退。打开之前的笔记也会闪退。

Version=1
EventType=APPCRASH
EventTime=131786243418406689
ReportType=2
Consent=1
UploadTime=131786243421208946
ReportStatus=268435456
ReportIdentifier=6a1f84b9-43a3-4f43-b7dc-57791ba6708e
IntegratorReportIdentifier=36316ac0-b600-495f-96bc-fb94f760c514
Wow64Host=34404
NsAppName=VNote.exe
OriginalFilename=VNote.exe
AppSessionGuid=00002b60-0001-0012-a14f-88dee332d401
TargetAppId=W:0006ae3019baa6fea35fd9dc5d99a8dd161800000904!0000905a30dbe7b5801cdd741665fe3e0f912df412eb!VNote.exe
TargetAppVer=2018//08//10:15:02:58!0!VNote.exe
BootId=4294967295
TargetAsId=292
UserImpactVector=808452912
IsFatal=1
Response.BucketId=38526cf0a83952119f2f8507916a801c
Response.BucketTable=4
Response.LegacyBucketId=2247161006632108060
Response.type=4
Sig[0].Name=应用程序名
Sig[0].Value=VNote.exe
Sig[1].Name=应用程序版本
Sig[1].Value=0.0.0.0
Sig[2].Name=应用程序时间戳
Sig[2].Value=5b6da922
Sig[3].Name=故障模块名称
Sig[3].Value=ig9icd64.dll
Sig[4].Name=故障模块版本
Sig[4].Value=23.20.16.4973
Sig[5].Name=故障模块时间戳
Sig[5].Value=5a96b1e5
Sig[6].Name=异常代码
Sig[6].Value=c0000005
Sig[7].Name=异常偏移
Sig[7].Value=00000000005fbb6b
DynamicSig[1].Name=OS 版本
DynamicSig[1].Value=10.0.17134.2.0.0.256.48
DynamicSig[2].Name=区域设置 ID
DynamicSig[2].Value=2052
DynamicSig[22].Name=其他信息 1
DynamicSig[22].Value=f65c
DynamicSig[23].Name=其他信息 2
DynamicSig[23].Value=f65c509b3d1d32d026337fc6de531ac4
DynamicSig[24].Name=其他信息 3
DynamicSig[24].Value=1b42
DynamicSig[25].Name=其他信息 4
DynamicSig[25].Value=1b4243d49d59672641fb32061ff74ec6
UI[2]=D:\VNote\VNote.exe
LoadedModule[0]=D:\VNote\VNote.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\SYSTEM32\apphelp.dll
LoadedModule[5]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[6]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[7]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[8]=D:\VNote\Qt5PrintSupport.dll
LoadedModule[9]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[10]=D:\VNote\Qt5WebEngineWidgets.dll
LoadedModule[11]=C:\WINDOWS\System32\shcore.dll
LoadedModule[12]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[13]=C:\WINDOWS\System32\combase.dll
LoadedModule[14]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[15]=C:\WINDOWS\System32\windows.storage.dll
LoadedModule[16]=D:\VNote\Qt5Widgets.dll
LoadedModule[17]=C:\WINDOWS\System32\advapi32.dll
LoadedModule[18]=C:\WINDOWS\System32\sechost.dll
LoadedModule[19]=C:\WINDOWS\System32\shlwapi.dll
LoadedModule[20]=C:\WINDOWS\System32\COMDLG32.dll
LoadedModule[21]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[22]=C:\WINDOWS\System32\USER32.dll
LoadedModule[23]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[24]=C:\WINDOWS\System32\win32u.dll
LoadedModule[25]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[26]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[27]=C:\WINDOWS\System32\profapi.dll
LoadedModule[28]=C:\WINDOWS\System32\powrprof.dll
LoadedModule[29]=C:\WINDOWS\System32\FLTLIB.DLL
LoadedModule[30]=D:\VNote\Qt5WebChannel.dll
LoadedModule[31]=D:\VNote\Qt5Network.dll
LoadedModule[32]=D:\VNote\Qt5Gui.dll
LoadedModule[33]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[34]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[35]=C:\WINDOWS\System32\MSASN1.dll
LoadedModule[36]=C:\WINDOWS\System32\ole32.dll
LoadedModule[37]=D:\VNote\Qt5Core.dll
LoadedModule[38]=C:\WINDOWS\SYSTEM32\MSVCP140.dll
LoadedModule[39]=C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
LoadedModule[40]=C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
LoadedModule[41]=C:\WINDOWS\SYSTEM32\UxTheme.dll
LoadedModule[42]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17134.191_none_fb3e94b130690543\COMCTL32.dll
LoadedModule[43]=C:\WINDOWS\SYSTEM32\dwmapi.dll
LoadedModule[44]=D:\VNote\Qt5Qml.dll
LoadedModule[45]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[46]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[47]=C:\WINDOWS\System32\NSI.dll
LoadedModule[48]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[49]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[50]=C:\WINDOWS\SYSTEM32\MPR.dll
LoadedModule[51]=C:\WINDOWS\SYSTEM32\PROPSYS.dll
LoadedModule[52]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[53]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[54]=C:\WINDOWS\SYSTEM32\WINMMBASE.dll
LoadedModule[55]=D:\VNote\Qt5QuickWidgets.dll
LoadedModule[56]=D:\VNote\Qt5Quick.dll
LoadedModule[57]=D:\VNote\Qt5WebEngineCore.dll
LoadedModule[58]=C:\WINDOWS\System32\PSAPI.DLL
LoadedModule[59]=D:\VNote\Qt5Positioning.dll
LoadedModule[60]=C:\WINDOWS\SYSTEM32\dbghelp.dll
LoadedModule[61]=C:\WINDOWS\SYSTEM32\USP10.dll
LoadedModule[62]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[63]=C:\WINDOWS\SYSTEM32\DWrite.dll
LoadedModule[64]=C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
LoadedModule[65]=C:\WINDOWS\SYSTEM32\ncrypt.dll
LoadedModule[66]=C:\WINDOWS\SYSTEM32\urlmon.dll
LoadedModule[67]=C:\WINDOWS\SYSTEM32\Secur32.dll
LoadedModule[68]=C:\WINDOWS\SYSTEM32\WINHTTP.dll
LoadedModule[69]=C:\WINDOWS\SYSTEM32\d3d9.dll
LoadedModule[70]=C:\WINDOWS\SYSTEM32\dxva2.dll
LoadedModule[71]=C:\WINDOWS\SYSTEM32\d3d11.dll
LoadedModule[72]=C:\WINDOWS\SYSTEM32\dxgi.dll
LoadedModule[73]=C:\WINDOWS\SYSTEM32\FONTSUB.dll
LoadedModule[74]=C:\WINDOWS\SYSTEM32\NTASN1.dll
LoadedModule[75]=C:\WINDOWS\SYSTEM32\iertutil.dll
LoadedModule[76]=C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
LoadedModule[77]=C:\WINDOWS\SYSTEM32\SSPICLI.DLL
LoadedModule[78]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[79]=C:\WINDOWS\System32\dtrampo.dll
LoadedModule[80]=D:\VNote\platforms\qwindows.dll
LoadedModule[81]=C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_059678b57bd15114\igd9dxva64.dll
LoadedModule[82]=C:\WINDOWS\SYSTEM32\opengl32.dll
LoadedModule[83]=C:\WINDOWS\SYSTEM32\GLU32.dll
LoadedModule[84]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[85]=C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_059678b57bd15114\ig9icd64.dll
LoadedModule[86]=C:\WINDOWS\SYSTEM32\WTSAPI32.dll
LoadedModule[87]=C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_059678b57bd15114\igc64.dll
LoadedModule[88]=D:\VNote\imageformats\qico.dll
LoadedModule[89]=D:\VNote\imageformats\qgif.dll
LoadedModule[90]=D:\VNote\imageformats\qicns.dll
LoadedModule[91]=D:\VNote\imageformats\qjpeg.dll
LoadedModule[92]=D:\VNote\imageformats\qsvg.dll
LoadedModule[93]=D:\VNote\Qt5Svg.dll
LoadedModule[94]=D:\VNote\imageformats\qtga.dll
LoadedModule[95]=D:\VNote\imageformats\qtiff.dll
LoadedModule[96]=D:\VNote\imageformats\qwbmp.dll
LoadedModule[97]=D:\VNote\imageformats\qwebp.dll
LoadedModule[98]=D:\VNote\iconengines\qsvgicon.dll
LoadedModule[99]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[100]=C:\WINDOWS\system32\dataexchange.dll
LoadedModule[101]=C:\WINDOWS\system32\dcomp.dll
LoadedModule[102]=C:\WINDOWS\system32\twinapi.appcore.dll
LoadedModule[103]=C:\WINDOWS\system32\RMCLIENT.dll
LoadedModule[104]=C:\WINDOWS\System32\TextInputFramework.dll
LoadedModule[105]=C:\WINDOWS\System32\CoreUIComponents.dll
LoadedModule[106]=C:\WINDOWS\System32\CoreMessaging.dll
LoadedModule[107]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[108]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[109]=C:\Windows\system32\baiducnTSF.dll
LoadedModule[110]=C:\WINDOWS\System32\imagehlp.dll
LoadedModule[111]=C:\Program Files (x86)\Baidu\BaiduPinyin\5.4.4920.0\UIPFullx64.dll
LoadedModule[112]=C:\WINDOWS\SYSTEM32\OLEACC.dll
LoadedModule[113]=C:\WINDOWS\SYSTEM32\MSIMG32.dll
LoadedModule[114]=C:\Program Files (x86)\Baidu\BaiduPinyin\5.4.4920.0\configurex64.dll
LoadedModule[115]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.17134.191_none_2c2987968afb7f11\gdiplus.dll
LoadedModule[116]=C:\Program Files (x86)\Baidu\BaiduPinyin\5.4.4920.0\imefreetypex64.dll
LoadedModule[117]=C:\Program Files (x86)\Baidu\BaiduPinyin\5.4.4920.0\imepngx64.dll
LoadedModule[118]=C:\Program Files (x86)\Baidu\BaiduPinyin\5.4.4920.0\imezlibx64.dll
LoadedModule[119]=C:\Windows\System32\twinapi.dll
LoadedModule[120]=C:\WINDOWS\system32\NLAapi.dll
LoadedModule[121]=C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[122]=C:\WINDOWS\System32\SETUPAPI.dll
LoadedModule[123]=C:\WINDOWS\SYSTEM32\DEVOBJ.dll
LoadedModule[124]=C:\WINDOWS\System32\WINTRUST.dll
LoadedModule[125]=C:\WINDOWS\system32\audioses.dll
LoadedModule[126]=C:\WINDOWS\system32\MMDevAPI.DLL
LoadedModule[127]=C:\WINDOWS\system32\AVRT.dll
LoadedModule[128]=C:\WINDOWS\SYSTEM32\mscms.dll
LoadedModule[129]=C:\WINDOWS\SYSTEM32\ColorAdapterClient.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=17134
OsInfo[3].Key=ubr
OsInfo[3].Value=191
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=2052
OsInfo[7].Key=geoid
OsInfo[7].Value=45
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=79203
OsInfo[15].Key=osinsty
OsInfo[15].Value=3
OsInfo[16].Key=iever
OsInfo[16].Value=11.165.17134.0-11.0.75
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=16280
OsInfo[19].Key=svolsz
OsInfo[19].Value=117
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=180410
OsInfo[22].Key=bldtm
OsInfo[22].Value=1804
OsInfo[23].Key=bldbrch
OsInfo[23].Value=rs4_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.17134.191.amd64fre.rs4_release.180410-1804
OsInfo[30].Key=buildflightid
OsInfo[30].Value=0AA5E289-E8CB-4F08-ACEB-971D71933A65.1
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[33].Value=RS:185A
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
FriendlyEventName=已停止工作
ConsentKey=APPCRASH
AppName=VNote
AppPath=D:\VNote\VNote.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=408331B250BD274CFD04A8B5C80847DF
MetadataHash=997405660

**Comment by tamlok** [comment]
Similar issue as (https://github.com/tamlok/vnote/issues/340).

请为VNote使用集成显卡或更新显卡驱动。
