### ISSUE TITLE
can not enable vim mode in 1.21 - 不能在1.21中启用vim模式

### ISSUE THREAD

**Issue by fansf** [tamlok/vnote#345]
win10 1709

1.19
![1 19](https://user-images.githubusercontent.com/19767516/44056710-97dcc1c4-9f7b-11e8-8825-270752562d2c.png)

1.21
![1 21](https://user-images.githubusercontent.com/19767516/44057245-22f60bb6-9f7d-11e8-8c22-81f1938fc84f.png)

修改vnote.ini配置文件可以开启vim模式，但在1.19中有效，在1.21中无效。  
I can enable the vim mode by changing the option in vnote.ini, but it works in 1.19, not 1.21

原谅我蹩脚的英文。。。

**Comment by tamlok** [comment]
hi，每次更新的时候记得留意更新信息里面的注意事项。因为很多人误触vim，所以把开关挪到设置对话框了，你需要到那里去开启。
