### ISSUE TITLE
Some content cause high CPU usage

### ISSUE THREAD

**Issue by 0x4C43** [tamlok/vnote#347]
# Version & OS
v1.21
Windows10 

# Symptoms
Some content may cause high CPU usage.
![image](https://user-images.githubusercontent.com/4470919/44297378-e611fa00-a302-11e8-8417-5c74fb5c3e01.png)

# Reproduce
1.  File/New Notes From Files/open [crash.zip](https://github.com/tamlok/vnote/files/2299254/crash.zip);
2.  "Ctrl + T" check to edit mode will tigger crash.

**Comment by tamlok** [comment]
Thanks! I will check it. BTW, please reset layout to make toolbar buttons in order.

**Comment by tamlok** [comment]
There are many special characters in your note. Please wrap them in a fenced code block.

**Comment by 0x4C43** [comment]
OK, I got it. But why do these special characters cause high CPU usage?

**Comment by tamlok** [comment]
The parser cannot handle control characters properly. I will look back in the future.
