### ISSUE TITLE
[BUG]某些情况下，代码区域中的#被识别为标题

### ISSUE THREAD

**Issue by wuscloud** [tamlok/vnote#350]
vnote 1.20
编辑模式下
当代码区域上存在一行文本（没有空行间隔）的情况下，代码区域中的井号会被识别为标题并自动加上标题序号

**Comment by wuscloud** [comment]
之前不存在这个问题，当打开以前的笔记时，会影响到之前的笔记，导致格式目录混乱

**Comment by wuscloud** [comment]
刚刚新开一个文档测试，并没有复现问题。

**Comment by wuscloud** [comment]
稍等，我找到笔记中一个有问题的文档，我录个屏你看看

**Comment by wuscloud** [comment]
```
#  注释内容1

#  注释内容2
```

如上内容，编辑模式下代码区域包含两行注释，注释之间有一个空行，此时在代码区域之上添加一条文档，这两行注释就会被识别成标题，您测试看看

**Comment by tamlok** [comment]
这是语法。代码块前一般要空一行，否则会识别为行内代码。特殊情况是，直接标题下的代码块不用空行。
