### ISSUE TITLE
[Request] Copy Note Path

### ISSUE THREAD

**Issue by Warning-Forever** [tamlok/vnote#351]
Hello,
Great program :1st_place_medal: , thank you very much.

I have a request, if I may. Is it possible to add item "Copy Note Path" in the context menu of a note. Or add this string into the window that appears when you click F2 (rename)?

For example, the path of a note like this:
C:\Users\1\Documents\vnote_notebooks\Test\Example.md

**Comment by tamlok** [comment]
Added in 2.0.
