### ISSUE TITLE
Rmd files are not handled by VNote

### ISSUE THREAD

**Issue by N0rbert** [tamlok/vnote#352]
Steps to reproduce:
1. Prepare some file with R Markdown syntax 
```
---
title: "Hello world"
output: html_document
---

# Hello World!

Hello world!

1. one 
1. two
1. three
```
and save it as `filename.Rmd`

2. Try to open `filename.Rmd` from VNote

Expected results:
* VNote opens file, knows that it contains Markdown and allows user to view and edit it

Actual results:
* VNote does not open file (not detects it as Markdown), does not allow user to view and edit it. File is opened in RStudio instead (if it is installed or in default application if not). 

Note: I'm running VNote 1.22 on Ubuntu 16.04 LTS amd64.

**Comment by tamlok** [comment]
Hi,

You need to specify customized suffixes for Markdown files in `vnote.ini` in your configuration folder. Add this to the `[global]` section and restart VNote.

```
; Suffixes list of Markdown files separated by ,
; Case-insensitive
markdown_suffix=md,markdown,mkd,rmd
```

**Comment by N0rbert** [comment]
Thank you very much!
Now it works. I'll remember this ini-file setting in `~/.config/vnote/vnote.ini` :)
