### ISSUE TITLE
「从剪贴板中插入图片」对话框中的「图片标题」后的文本框中无法输入一些符号、不能粘贴文本

### ISSUE THREAD

**Issue by officeplayer** [tamlok/vnote#354]
1. 复制图片；
2. 在 VNote 中粘贴图片，弹出「从剪贴板中插入图片」对话框；
3. 在「图片标题」后的文本框中无法输入 `「` 、`」` 符号（我使用「小狼毫」输入法，键盘 `[`、`]` 分别映射到 `「` 、`」` ）；
4. 再从其他程序复制文本到「图片标题」后的文本框中无法完成粘贴。

**Comment by tamlok** [comment]
中括号是图片语法的标记，不能使用。

**Comment by officeplayer** [comment]
是说这个文本框只认键值么？那为啥粘贴其他文本过来也不行呢？是剪贴板被占用了么？

**Comment by tamlok** [comment]
已经修复了。
