### ISSUE TITLE
转义符号的问题

### ISSUE THREAD

**Issue by officeplayer** [tamlok/vnote#355]
我本想在文中使用一对「`」将快捷键「Ctrl+`」包起来，但由于「`」是特殊符号，需使用「\」进行转义，写成「`Ctrl+\``」，但并不能得到想要的效果。

**Comment by tamlok** [comment]
请参考软件帮助菜单中的语法指南：

![image](https://user-images.githubusercontent.com/5763157/44565349-3c1aed80-a79a-11e8-90d4-1f919bceceae.png)

**Comment by officeplayer** [comment]
```
`` Ctrl+` ``
```
感谢，看了我该找个时间把帮助从提从头带我带到位到尾仔细看一遍才行。

**Comment by officeplayer** [comment]
```
`` Ctrl+` ``
```
感谢，看来我该找个时间把帮助从提从头带我带到位到尾仔细看一遍才行。

**Comment by tamlok** [comment]
应该这样呀，不然帮助就白写了～～
