### ISSUE TITLE
The buttons Up and Down don't work in "Outline"

### ISSUE THREAD

**Issue by Warning-Forever** [tamlok/vnote#358]
Hello,
In v. 1.19 if I click on item (headline) in the field "Outline", I can move up and down through these items with the buttons Up and Down and view in the note will jump to the corresponding headline. But now this doesn't work. Now, if I click on one of those items and then press the button Up (or Down), the note begins slightly moving up (or down) if the focus would remain in the note's field.

My conf.: Windows 7 x64

**Comment by tamlok** [comment]
After clicking an item in the outline, edit area will get focus.

If you want to navigate in the outline:

- Click the outline title or space in outline tool;
- `ctrl+e w` to enter navigation mode.

**Comment by Warning-Forever** [comment]
> Click the outline title

This works, thanks. So now to navigate with arrow buttons in Outline I should click an item in Outline and then click the tab "Outline".

> or space in outline tool;

This doesn't work. The button Space simply scrolls the note screen by screen.

**Comment by tamlok** [comment]
It means clicking mouse at the space in outline tool.
