### ISSUE TITLE
VNote converts JPG to PNG

### ISSUE THREAD

**Issue by Warning-Forever** [tamlok/vnote#360]
Hi,
When I paste an image link from the internet to a JPG picture ("Insert As Image"), VNote saves this picture as PNG. For example, the picture [JPG](https://bigfishgames-a.akamaihd.net/en_5-realms-of-cards/screen2.jpg) (**107KB**) becomes PNG (**533KB**). Why is that? Can I switch this off in options?

**Comment by tamlok** [comment]
Fixed (7c7b9e8a3d3dc477bcabd95096fc4efb6d083284). VNote now try to download it to a local temp file and insert image form a local temp file, which will keep the image format.

**Comment by Warning-Forever** [comment]
:+1:
Thanks.
