### ISSUE TITLE
[fr] integration with hugo or hexo?

### ISSUE THREAD

**Issue by renothing** [tamlok/vnote#361]
we know that both hugo and hexo are welcome static site generator which support markdown well. but there is no gui editor for them. maybe vnote can be the best choice. but need some integration works for hugo/hexo category/tag support. how about this idea?

**Comment by tamlok** [comment]
VNote is my part-time work, so these extension works may need to be postponed. After two years of development, there is still only one main contributor. ;( Always, PR and HELP is highly appreciated.
