### ISSUE TITLE
Win10 x64 预览MD笔记 闪退

### ISSUE THREAD

**Issue by BackTrackCRoot** [tamlok/vnote#362]
使用x64 最新版本的VNote 写完笔记后，保存预览程序瞬间崩溃，使用更新检测界面出现僵死状态。
没有找到错误日志的输出。再次打开再次预览笔记仍旧崩溃。

**Comment by tamlok** [comment]
Hi,

和(https://github.com/tamlok/vnote/issues/340)是同一个问题。请指定VNote使用集成显卡或更新显卡驱动。谢谢！

**Comment by BackTrackCRoot** [comment]
使用集显仍旧崩溃 Intel 630集显

**Comment by BackTrackCRoot** [comment]
经查询在`ig9icd64.dll`上发生了内存溢出，该DLL所属Intel 驱动，但是我的驱动是Win10 已经给更新到了最新的版本，无法再更新了……所以怎么解决呢。

**Comment by BackTrackCRoot** [comment]
使用N卡独立显卡解决问题。集显不正常。

**Comment by BackTrackCRoot** [comment]
独显仍旧不正常，推荐添加环境变量`QT_OPENGL`，变量内容`angle` 或者 `software`，软件可以正常渲染。
http://doc.qt.io/qt-5/windows-requirements.html
