### ISSUE TITLE
代码块

### ISSUE THREAD

**Issue by ice-doom** [tamlok/vnote#363]
- English is preferred;
- Make the title as meaningful as possible;
- One issue for only one thing, since large issues are difficult to remember and handle;
- When reporting problems, elaborate it as detailed as possible like:
    - Version of VNote, which operating system;
    - What is the symptoms;
    - What action triggered it;
    - How to reproduce it;
- Please delete all these text and put whatever you want below. :)

代码块换行后，阅读模式多出一个空格，我这里是POST请求包内容，复制出来的内容会多出个空格导致错误，这有办法解决？
![image](https://user-images.githubusercontent.com/25363717/44651302-8c54b280-aa1b-11e8-9c66-a94758f1e122.png)

**Comment by tamlok** [comment]
Hi，

这里无法复现。建议以后提issue的时候，能按照格式要求，把如何复现的详细步骤和必备材料都给出。这样才更方便解决问题，节省开发者的时间。

谢谢！
