### ISSUE TITLE
v1.22富文本粘贴的进一步建议  Further advice of copying rich text to markdown(for v1.22)

### ISSUE THREAD

**Issue by kerHbal** [tamlok/vnote#365]
**场景**
从OneNote复制到vnote，图片会复制为其路径：
`
![](file:///C:/Users/xxx/AppData/Local/Packages/Microsoft.Office.OneNote_df7eyedbwe/TempState/msohtmlclip/clip_image001.jpg)
`
此时我需要右键点击复制图片，然后把以上整段图片引用删除，再把复制的图片粘贴回来，这时图片就在此笔记对应的图片文件夹里了

**建议**
希望保存富文本时能加入图片本地化的功能，例如提示是否将网页上/本地其他位置的图片复制到笔记对应图片文件夹。

谢谢

**Comment by timgogochen** [comment]
支持，能直接贴图片是吸引我从Leanote 转过来的一个原因，但最好能把图片本地化，否则我们保存的HTML文档还需要依赖原服务器。

**Comment by tamlok** [comment]
Added. Please try https://bintray.com/tamlok/vnote/vnote/2.0#files

**Comment by kerHbal** [comment]
@tamlok 太棒啦！网页和本地图片都成功，唯一有问题的地方是OneNote自己机器识别胡写的图片atltext包含回车，在渲染阅读模式下可以识别图片，但在编辑模式下无法识别导致这种图片的本地化没有成功。
这个问题应该比较小众，且感觉目前这种带回车的文本也不好解决，不行就算了。
![image](https://user-images.githubusercontent.com/11629684/46874928-625b2200-ce08-11e8-97ff-ee9c73cc928b.png)
![image](https://user-images.githubusercontent.com/11629684/46875023-9f271900-ce08-11e8-8c19-fb28be160d84.png)

**Comment by tamlok** [comment]
这个后面可以过滤掉，简单

**Comment by kerHbal** [comment]
@tamlok 如果要过滤的话希望考虑直接把alttext清空，或是在图片文件的命名上不受alttext影响，要不然图片有些凌乱，谢谢！
![image](https://user-images.githubusercontent.com/11629684/46879475-28901880-ce14-11e8-8475-102080f81060.png)

**Comment by kerHbal** [comment]
@tamlok 再附加一个例子，希望能把alttext直接删了了事。。。谢谢！！
![image](https://user-images.githubusercontent.com/11629684/46907457-ade0ff00-cee0-11e8-9b0c-18704d4ec7c9.png)

**Comment by tamlok** [comment]
Fixed in 2.1. Please try it out. Thanks!
