### ISSUE TITLE
更新功能

### ISSUE THREAD

**Issue by xbyl** [tamlok/vnote#368]
更新失败，未翻墙
希望作者能够提供墙内更新源

另外版本1.2中：保存并预览再编辑 光标变粗无法输入点击标题选择按钮才能变回正常光标

**Comment by tamlok** [comment]
Hi,

- 是从官网下载的程序吗？应该只是openSSL缺失了，无法检查更新信息。不过VNote的检查更新也仅仅是访问github检查更新信息，并没有自动更新功能。
- 是否开启了Vim功能？在设置里面把Vim关闭即可。
