### ISSUE TITLE
The latest version 1.22 code block preview failed

### ISSUE THREAD

**Issue by He11oLx** [tamlok/vnote#369]
![1](https://user-images.githubusercontent.com/41121010/44760915-97225b00-ab73-11e8-9fd5-69f60ed3f44b.png)
As above. The version 1.19 and 1.16 can preview correctly.
But the latest version 1.22 must add a blank line.
This is very strange.
Is my configuration wrong?

**Comment by tamlok** [comment]
Hi,

One blank line before the fenced code block (after a non-block element) is the expected behavior.

Thanks!
