### ISSUE TITLE
字体调节

### ISSUE THREAD

**Issue by blackredscarf** [tamlok/vnote#370]
请问能调节字体，字体大小吗？还有就是导出的PDF字体太大了

**Comment by tamlok** [comment]
Hi,

- 请参考 (https://vnote.readthedocs.io/zh_CN/latest/user_docs/themes_and_styles.html) 进行自定义主题或样式；
- 请参考上面的文档使用导出的高级功能；

**Comment by blackredscarf** [comment]
@tamlok 
我有些明白了，默认的pdf导出是使用对于主题的css配置对吗？我把css中的font-size从16改成12，导出的pdf字体确实变小了，编辑面板可以拖动放大，字体多少都无所谓。

但也有两个问题，
- 一个是编辑器那些提示组件的字体也变小了；
- 二是虽然字体变小了，但mathjax公式字体依旧很大，这个不完全语法控制，因为我用typora导出的pdf大小就非常适中美观。

**Comment by tamlok** [comment]
- 是Windows吗？Windows的好像强制放大了。
- 请尝试wkhtmltopdf来导出。

**Comment by blackredscarf** [comment]
@tamlok
我把`v.native.css`中的font-size改成12
```
p, ul, ol {
    font-size: 12px;
    line-height: 24px;
}
```

1. 然后导出PDF后，出现这样的问题：

<img src="https://i.loli.net/2018/08/31/5b88c839801e0.png" width="600px">


2. 以及编辑器也出现了这个问题，如下图：

<img src="https://i.loli.net/2018/08/31/5b88c8bea5daf.png" width="600px">

**Comment by tamlok** [comment]
试试改body的字体属性？

**Comment by blackredscarf** [comment]
@tamlok 
修改body的字体属性确实能把公式字体减小，但文本字体属性以p标签优先，如果也减小了就会出现上述第二个问题。

**Comment by tamlok** [comment]
导出的时候，可以选择不同的css样式。建议复制一份默认的css，然后修改为导出专用的，放到VNote的对应文件夹即可。具体请参考文档。
