### ISSUE TITLE
能否增加一个设置，可以设置默认粘贴行为？

### ISSUE THREAD

**Issue by Nick-Hopps** [tamlok/vnote#373]
**PLEASE elaborate the issue in detail**  
**请详细描述问题**

OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):

How to Repro (如何复现):

**Comment by loggerhead** [comment]
请问此 issue 是支持了还是因为没描述被关闭了？

**Comment by tamlok** [comment]
应该是没有描述被关闭了。
