### ISSUE TITLE
table输入优化

### ISSUE THREAD

**Issue by zhengjianqiao** [tamlok/vnote#374]
希望增强table输入功能。希望能想org-mode一样，
输入：
|aaa|bbbb|ccc|
|-
就能自动输出完整的表格
|aaa|bbbb|ccc|
|--|--|--|
并且能够自动对齐
|523423|223123|3123|
|--------|-------|-------|
|523423|223123|3123|

**Comment by tamlok** [comment]
2.2已经支持！
