### ISSUE TITLE
Captain Mode shortcuts don't work if the keyboard layout is not English

### ISSUE THREAD

**Issue by Warning-Forever** [tamlok/vnote#375]
Hi,
When I switch the keyboard layout from English to Russian, Captain Mode shortcuts stop working. For example, if I want to press **Ctrl+E,E**, first I press **Ctrl+E**, I can see as the text "_VNote_" in the toolbar flashes, but then when I press **E**, nothing happens.

In the English layout, Captain Mode shortcuts work well.

For comparison, plain shortcuts as **Ctrl+B** or **Ctrl+I** work well in both layouts.

ADDED:
Captain Mode shortcuts as **Ctrl+E,\<digit\>** also work well in both layouts.
So I think I'll simply remap those shortcuts that I need :)

**Comment by tamlok** [comment]
Hi,

Will `E` in Russian layout input another character instead of the `e` character?

I think I could do something in VNote side to fix this. But I need more information about the difference between English and Russian layout.

Thanks!

**Comment by Warning-Forever** [comment]
Yes, there are differences. In this pic you can see them.

![Rus](http://rones.su/wp-content/uploads/spmbt_layout.png)

Here's online converter: https://awsm-tools.com/text/keyboard-layout

1. Select **From:** _Qwerty_, **To:** _Russian Qwerty_
2. Type a Latin letter
3. Press _Convert_
You'll see the Russian letter.

But I think the first part of a Captain Mode shortcut (Ctrl+E) works in the Russian layout. What doesn't work is the second part (the single letter key). So I don't know how you can solve this collision.

**Comment by tamlok** [comment]
Hi,

I just added support for different layouts via setting up a layout mapping in the settings dialog.

Could you please help to check it by downloading the latest [build](https://bintray.com/tamlok/vnote/vnote/2.0#files)?

Thanks!

**Comment by Warning-Forever** [comment]
Hi

In version 2.0 of September, 21, Captain Mode shortcuts work correctly by default.

In new version with configurable setting they do not work by default. Actually, I can't figure out what I should do to make them work. Do I need to remap every key? If so, it's too much to work. Better to leave it as in v2.0.

**Comment by tamlok** [comment]
2.0 only works in windows. You need to map the key in new build.

**Comment by Warning-Forever** [comment]
> You need to map the key in new build.

Okay, I did that. It works fine in Windows 7.
