### ISSUE TITLE
插入图片的一点意见和整合git功能

### ISSUE THREAD

**Issue by makai3** [tamlok/vnote#376]
你好,我有两个不成熟的提议,您看看可行不?
1.插入图片时,复制图片到`./${filename}.assets`文件夹(参见typora的功能),便于管理和维护文章的资源
2.整合git服务,可以同步到我的gitlab上(同步到github或者码云什么的上也行啊,这都是俺滴心血)...

**Comment by tamlok** [comment]
Hi,

- 如果文件改名了怎么办呢？目前集中放在`_v_images`下好像也没有什么不好。通过导出Markdown，能将一个笔记独立导出。
- VNote目前不负责同步，用户可以选择自己喜欢的方式来同步自己的数据，只需要同步笔记本根文件夹即可。所以，可以写一个脚本，在vnote结束后自动把文件夹下的所有文件都add并push。
