### ISSUE TITLE
富文本复制过来的表格格式

### ISSUE THREAD

**Issue by kerHbal** [tamlok/vnote#377]
在网页里复制表格，粘贴过来是如下的html格式
![snipaste_2018-09-01_19-31-55](https://user-images.githubusercontent.com/11629684/44950742-f4413980-ae1d-11e8-96b7-2775d75605fc.png)
不知能不能自动优化为markdown格式呢？

谢谢

**Comment by tamlok** [comment]
已经实现了无表头的转换，下一个版本会带上。
