### ISSUE TITLE
笔记文件夹，笔记顺序能够自由调整

### ISSUE THREAD

**Issue by DreamChase** [tamlok/vnote#378]
最近做相关技术整理，但是往往新添加的笔记按照现在的排序方式，不是很满足需求。
希望能够随意调整笔记文件夹，笔记的顺序。
楼主闲时考虑一下哦。

**Comment by tamlok** [comment]
鼠标右键，排序，想怎么排就怎么排。

**Comment by DreamChase** [comment]
我的明白
