### ISSUE TITLE
全屏各种操作都无反应

### ISSUE THREAD

**Issue by joycekilllove2018** [tamlok/vnote#379]
**PLEASE elaborate the issue in detail**  
**请详细描述问题**

OS Version (操作系统): Windows7 64

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
全屏F11后，点击菜单无反应，整个软件看上去卡死，其实没死，在下拉菜单（其实看不到东西）相应的位置点击，可以开启菜单功。

How to Repro (如何复现):
F11全屏后，点击菜单。

**Comment by tamlok** [comment]
全屏这个问题我这边复现不了，所以暂时不知道怎么解决。暂时先别用全屏吧。

或者尝试添加环境变量，参考 https://github.com/tamlok/vnote/issues/226

**Comment by kerHbal** [comment]
复现此情况有个前提，如果全屏以后不点开任意笔记则无任何问题。如果全屏以后先从笔记本中打开一个笔记，屏幕会闪一下黑色，然后凡是需要展开菜单二次选择条目的按钮都看似没反应，实际上只是菜单隐形了。而只用点一次的例如上方的新建笔记按钮就没有问题。

**Comment by kerHbal** [comment]
@tamlok 又试了一下，除了刚打开vnote没有点开任意笔记时全屏一切正常以外，只要在点开过任意笔记，哪怕把笔记页面都关闭，此时再试图全屏还是会出问题

**Comment by tamlok** [comment]
添加环境变量有用吗？

**Comment by kerHbal** [comment]
@tamlok 添加环境变量以后就好了，没有问题了

**Comment by tamlok** [comment]
那就好，估计也是显卡驱动的问题，opengl。谢谢耐心测试和反馈。

**Comment by joycekilllove2018** [comment]
添加系统变量后，问题解决。
