### ISSUE TITLE
[需求]将已有的"*.md"文档导入到VNote管理与编辑功能。

### ISSUE THREAD

**Issue by zhenghualiang** [tamlok/vnote#38]
@tamlok Hi,感谢您的开发，很有创意！
我现在已经开始使用VNote，确实如您开发该软件的初衷，解决了很多文本编辑的“痛点”。
我的问题是：由于以前已经建立了不少"*.md"文档，现在开始使用VNote，发现没办法直接将已有的文件夹及相关文档导入到VNote来管理与修改。
一个解决办法似乎是通过修改相应的“_vnote.json”可以实现，但文档较多时感觉修改起来还是有点麻烦。
不知道是我的操作不当，还是目前还不具备该功能。

如果目前还不具备该功能，能否考虑加入该功能，其优先级可能比导出等更优先。

再次感谢您的开发，希望越来越好用！！！

**Comment by tamlok** [comment]
@zhenghualiang Hi，谢谢使用！目前VNote才文件菜单有一个从外部文件新建笔记的功能，可以批量地将您指定的一系列文件**复制**到当前笔记本的当前文件夹下面，作为新建的笔记，也许您可以尝试一下这个方式。

需要注意的是：

- 原来的文件还是没有被作为笔记来管理，这个“导入”只是通过复制指定的文件来新建笔记；
- 如果有相对路径的图片，这个方式并没有将图片也一并复制过来，所以可能需要您自己复制一下；
- 这样的一个好处是，您原来的笔记可以作为一个备份，可以避免因为刚用VNote误操作误删数据；
- 另外，我建议笔记用到再导入到VNote中，我在为知笔记上的两千篇笔记也是按需导入到VNote中，也是一个整理的过程；
- VNote也可以选为默认的MD文件打开方式，这样双击外部的MD文件就能直接调用VNote来阅读和编辑，效果也挺不错；不过，还是建议使用VNote中的管理体系来管理笔记；

目前不实现根据一个目录里面的文件来生成笔记本的功能，一个考虑是作为一个笔记软件（而不是编辑器），VNote希望能对数据有较强的断言和控制，这也是为什么强制选定一个笔记本根目录时要使用空目录的原因。如果导入已有目录作为文件夹，VNote不知道哪些文件是应该导入的（比如后面VNote支持的富文本文件就是没有后缀的）。

很多编辑器直接调用文件系统的目录结构来进行导航，是因为它们没有自己的管理结构。

不知道您是怎么考虑的呢？欢迎讨论！

再次感谢使用和反馈！ :)

**Comment by zhenghualiang** [comment]
@tamlok 嗯！是我的操作不当，只使用“打开”这个菜单，没有使用“从文件新建笔记”这个菜单。
完全同意您的设计逻辑，VNote确实需要对数据有较强的断言和控制，否则容易将管理的文件夹和导入的文件夹混在一起。

另：在您非常详细的回答中还提到“在为知笔记上的两千篇笔记也是按需导入到VNote中”，请问是批量自动导入吗？还是一篇篇先整理后再复制粘贴到VNote里？

不好意思，由于操作不当导致没有理解好您的设计，同时又增加了一个问题，哈。
谢谢！

**Comment by tamlok** [comment]
@zhenghualiang 客气！迁移笔记的时候，我是用到哪篇就手动复制拷贝文本过VNote的，因为：

- 为知笔记的Markdown其实也是富文本保存的，格式混乱，强迫症受不了；
- 为知笔记的Markdown语法略有改动，比如行末不用两个空格都可以换行；
- 图片还是得自己手动插入；

所以，我现在是两个笔记都装上，有空就整理几篇以前的笔记。为知笔记里面的我也不删除，毕竟有时候无聊可以手机看一下以前的笔记；转移了就打个标记。愚公移山～～

:)

**Comment by zhenghualiang** [comment]
非常感谢。如果要从外部“导入”已经存在的MarkDown文档，请点击菜单栏“从文件新建笔记”。
