### ISSUE TITLE
Can the feature "Parse HTML and Paste" be turned off?

### ISSUE THREAD

**Issue by neonkaaaaa** [tamlok/vnote#380]
Well, it's quite annoying and timeating when you just want to paste some text. And every time you need to paste you must go through that process: "Ctrl+V" -> "button down" -> "Enter".

Is there some solution to turn this feature off?
Or maybe to put in on some different shortcut?

**Comment by tamlok** [comment]
Will be removed in next version. You could download the latest build if you can't wait. :)

Thanks!

**Comment by timgogochen** [comment]
Yes, I have same trouble, and if I copy the data form webside, due it include pictures ,The Picture will not put into notes,  and there three option very embarrassed。

**Comment by tamlok** [comment]
Now you could parse&paste via context menu or `Ctrl+E P`.
