### ISSUE TITLE
The size of "Line Number"

### ISSUE THREAD

**Issue by Warning-Forever** [tamlok/vnote#381]
Hi,
Is it possible to change the size of "Line Number"?

Here's how it looks in v 1.22:

![1.22](https://image.ibb.co/ixjfze/1_22_Segoe_12_zoom.png)

But I'd like it to be smaller, like in v 1.19:

![1.19](https://image.ibb.co/f5KzQK/1_19_Segoe_12.png)

But I can't figure out how I can change its size.

**Comment by tamlok** [comment]
It is not configurable. Will make it smaller in next version.

**Comment by Warning-Forever** [comment]
Thank you.

> _It is not configurable._

I've noticed that Line Number changes accordingly to the size of main font and/or "Editor zoom delta", so it seems configurable. But it would be better to make these elements work independently.

**Comment by Warning-Forever** [comment]
Well, I'll start to learn C++ :)
