### ISSUE TITLE
調整 Editor zoom delta，編輯區背景色忽略 theme 設定變白色

### ISSUE THREAD

**Issue by KreenChang** [tamlok/vnote#383]
**PLEASE elaborate the issue in detail**  
**请详细描述问题**

**OS Version (操作系统):** Windows 10 64-bit

**VNote Version (VNote版本):** VNote_win_X64_portable_1.22.zip

**Symptoms (表现):**

調整 Settings 裡 Read/Edit  的  Editor zoom delta 任何數字後，編輯區底色變白色，附上參考圖：

- 調整前：
![調整前](https://i.imgur.com/WS32cHI.png)
- 調整後：
![調整後](https://i.imgur.com/HvMLXbU.png)

**How to Repro (如何复现):**
 
調整 Settings 裡 Read/Edit  的  Editor zoom delta 任何數字後重新啟動。之後改回原始數字 1，編輯區背景依然是白色。只有在 Settings 裡按 Reset VNote 並重新啟動才能將編輯區的背景顏色變回 theme 的顏色。
 
備註：用 Ctrl + 滑鼠滾輪放大縮小字體不會出現此 bug，但也不會記住縮放比例。

**Comment by tamlok** [comment]
Hi,

Should be fixed in 2.0.
