### ISSUE TITLE
Changing "Editor zoom delta" doesn't affect highlighted code

### ISSUE THREAD

**Issue by Warning-Forever** [tamlok/vnote#385]
Hi,
Changing  "Editor zoom delta" doesn't affect highlighted text in fenced code.

Screenshots:

* **Editor zoom delta = 0**

![](https://image.ibb.co/duZmee/EZD_0.png)

* **Editor zoom delta = 4**

![](https://image.ibb.co/kpTF5K/EZD_4.png)

* **Editor zoom delta = -4**

![](https://image.ibb.co/ckTyQK/EZD_4.png)

Highlighted code remains always the same size.

ADDED:
I must say that I added the line `font-size: +1` to the section FENCEDCODEBLOCK in mdhl-file.
Also, if you set a fixed size of this font, the highlighted text won't be affected by zoom delta, too.

**Comment by Warning-Forever** [comment]
Issue 2.

As you can see in the screenshots above, if I change "Editor zoom delta" to any numbers different from 0, the background color changes to white, although in all of three cases the setting is the same - "System".

**Comment by tamlok** [comment]
Should be fixed in 2.0.
