### ISSUE TITLE
readme里的下载链接无效

### ISSUE THREAD

**Issue by Tairraos** [tamlok/vnote#391]
readme里的下载链接无效，只会显示一些信息，没有真实的下载链接。建议链接到github release page。

**Comment by tamlok** [comment]
您好，能截个图吗？

**Comment by Tairraos** [comment]
赞超快速回复。

![image](https://user-images.githubusercontent.com/185069/45412957-92e55a00-b6aa-11e8-88b4-630b19e14958.png)

![image](https://user-images.githubusercontent.com/185069/45412846-5285dc00-b6aa-11e8-877e-58d24d45d3e0.png)

**Comment by Tairraos** [comment]
另外，我是brew安装失败了才转成下载的。brew安装的时候停在某个步骤不会动了，等了很久我只能杀了进程，回来下载dmg包了。
我是从这个位置下载的：

![image](https://user-images.githubusercontent.com/185069/45413021-b4464600-b6aa-11e8-8e98-34e6283b0783.png)

![image](https://user-images.githubusercontent.com/185069/45413082-e48de480-b6aa-11e8-85bb-f3b0af871633.png)

**Comment by tamlok** [comment]
在点开的那个链接的页面中files下面。这个是最新构建版本，可能不稳定。你可以去百度云上面下载最新一个发布的版本。

**Comment by tamlok** [comment]
HI,

1. QQ群: `487756074`;
2. 请参考官方文档进行主题自定义；
3. 格式或者图片不一样，建议按需迁移；
4. 标签居中这个是macOS默认样式，我以为macOS的都这样子；
5. 可以通过配置文件修改，详细请看文档；
6. 体积大是因为QtWebEngine的原因，相当于内嵌一个chrome内核；

谢谢！

**Comment by Tairraos** [comment]
谢谢
