### ISSUE TITLE
升级1.22后， 左边的panel包含当前笔记的文档列表，怎么没有了？？

### ISSUE THREAD

**Issue by hawkinchina** [tamlok/vnote#393]
> **PLEASE elaborate the issue in detail**  
> **请详细描述问题**
升级1.22后， 左边的panel包含当前笔记的文档列表，怎么没有了？？
******

OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):

How to Repro (如何复现):

**Comment by tamlok** [comment]
在文件菜单的设置里面重置一下布局试试。

**Comment by hawkinchina** [comment]
可以了，建议升级后（我之前是1.16版本）， 这些布局最好采用初始重置；，另外，建议，这个panel的开关，类似工具，工具栏，在查看菜单里面，统一勾选，

**Comment by hawkinchina** [comment]
建议，github里面，搞个qq开发群，国内大家的有问题，可以反馈/咨询即时一下。。

**Comment by tamlok** [comment]
QQ: 487756074

更新的时候需要查看更新信息，有一些注意事项会在里面说明。

**Comment by hawkinchina** [comment]
good。。
