### ISSUE TITLE
deepin 15.7 百分百闪退

### ISSUE THREAD

**Issue by fourj** [tamlok/vnote#396]
> **PLEASE elaborate the issue in detail**  
> **请详细描述问题**

******

OS Version (操作系统): Deepin Linux 15.7

VNote Version (VNote版本): 1.22 - Appimage

Symptoms (表现):
把在其他markdown笔记写的复制过来，保存，滑动鼠标中键，或者切换几个md文档的tab，vnote会退出，几率100%。最后手打：（行首一个tab）var a = 1
复制30行（未验证多少行）保存，再操作，100%闪退。
![_ _20180914125020](https://user-images.githubusercontent.com/22838895/45530384-ea0b3c00-b81c-11e8-93ec-1a73bfaf460e.png)

另外多次卡死强制结束程序，有几率打开vnote立即闪退。

How to Repro (如何复现):
滑动鼠标中键，切换几个md文档的tab，vnote会退出，100%复制

**Comment by tamlok** [comment]
在命令行`./VNote.AppImage -d`运行，然后看看闪退的时候输出了什么？也可以留意一下配置文件夹里面的`vnote.log`文件。

应用商店下载的VNote有问题吗？
