### ISSUE TITLE
image is bigger than preview window

### ISSUE THREAD

**Issue by fghhfg** [tamlok/vnote#398]
OS Version (操作系统): win7

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
How to Repro (如何复现):
if pixel of image (2000 * 2000 px) bigger than program (1000 * 1000 px), it can only show port of the image.

### advice
**always reduce the image**, let it fit into windows, so users don't have to scroll the horizontal / vertical bar

**Comment by kerHbal** [comment]
上方菜单:
Markdown---限制图片宽度
Markdown---限制原地预览宽度

Upper menu:
Markdown--- Constrain the width of images
Markdown--- Constrain the width of in-place review

**Comment by fghhfg** [comment]
@kerHbal thx, I believe this one should be default enable

**Comment by kerHbal** [comment]
@fghhfg yes, I also took some time to find that.

**Comment by tamlok** [comment]
Please refer to the markdown guide help doc in the help menu. We can specify size of image in the link text.
