### ISSUE TITLE
支持流程图、时序图

### ISSUE THREAD

**Issue by geoffreycheungr** [tamlok/vnote#4]
Btw：看到这个软件太兴奋了啊~~！特地注册个帐号上来回复~！
平时写笔记，用的是wikidpad，之所以不用更美观的Markdown，就是因为图片插入太TNND烦人了。
虽然难得插入图片，但是还要调整命名，还要整理目录，想想就想放弃。
目前手头有攒了5年多的wiki笔记，正在考虑要不要全部切换到vnote下面，工作量巨大啊。

文档结构图实际上还是挺重要的，可以考虑放到左侧固定栏目下面，虽然宽屏，但是也占了好宽的一片空间。

另外，导出html/pdf的功能，希望增加呀。

**Comment by tamlok** [comment]
谢谢使用！

- 流程图和时序图通过`Mermaid`已经支持了；
- 文档结构图放在右边主要是考虑之后添加高级搜索功能。另外，如果觉得编辑区域不够，可以经常切换扩展模式`Ctrl+E`；
- 后面肯定会支持导出功能的！

:)
