### ISSUE TITLE
给您推荐一款markdown编辑器，希望能有一点灵感

### ISSUE THREAD

**Issue by ofly** [tamlok/vnote#40]
Typora（https://typora.io/）

**Comment by jingle0927** [comment]
搭车  https://github.com/ivarptr/yu-writer.site 这个不错

**Comment by tamlok** [comment]
@ofly 谢谢！这个Typora之前也用过几天，后来感觉矫枉过正了，就不用了。
@jingle0927 谢谢！这个在V2EX上看过推荐的。

其实，在实现VNote之前我已经用过不少的Markdown编辑器或笔记软件。实在是觉得总有太多的不满意，才想着捣鼓一个VNote。后面等把一些现有的想法都实现后，会再逐个试一下当前的一些编辑器，看有没有什么能借鉴的！

谢谢！
