### ISSUE TITLE
Unable paste  a cut note to an empty folder.

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#400]
> **PLEASE elaborate the issue in detail**  
> **请详细描述问题**

******

OS Version (操作系统): Windows

VNote Version (VNote版本): Latest (最新)

Symptoms (表现): right mouse context menu doesn't show 'paste'

How to Repro (如何复现):
1. create an empty folder
2. cut a note from any other folder
3. right-mouse click the empty folder, context menu doesn't show 'paste' option.

**Comment by kerHbal** [comment]
![image](https://user-images.githubusercontent.com/11629684/45588926-0675aa00-b8eb-11e8-832f-b6fce88d30ca.png)

Right-mouse click the left bottom field(the yellow part)

**Comment by seaspeak** [comment]
I see. I'll close the issue.

**Comment by seaspeak** [comment]
I see. I'll close the issue.
