### ISSUE TITLE
Vnote ignores LaTeX equations declared by \begin{equation} ... \end{equation} block

### ISSUE THREAD

**Issue by N0rbert** [tamlok/vnote#401]
Steps to reproduce:

* prepare text Markdown document with some LaTeX equations inside the `\begin{equation} ... \end{equation}` block:

```
# Doing Math

Simple inline math is shown normally $a^2 + b^2 = 
c^2$.

But LaTeX equation below will not shown:

\begin{equation}
J(\theta) = \frac 1 2 \sum_{i=1}^m (h_\theta(x^{(i)})-y^{(i)})^2
\end{equation}
```

Expected result:
* VNote renders math inside `\begin{equation} ... \end{equation}` block. This behavior is expected to get compatibility with RMarkdown and other Markdown dialects. For example ReText renders this correctly, but [fails with inline `$...$` math](https://github.com/retext-project/retext/issues/387).

     > ![retext-eq2](https://user-images.githubusercontent.com/309456/45601272-fd7ff800-ba12-11e8-8daf-3891f2e35e64.png)

Actual result:
* VNote does not render math inside `\begin{equation} ... \end{equation}` block and shows it as is.

    > ![vnote-eq](https://user-images.githubusercontent.com/309456/45601146-f0faa000-ba10-11e8-9575-98e9d312c7b5.png)

Note: I'm running VNote 1.22 on Ubuntu 16.04 LTS amd64.

**Comment by N0rbert** [comment]
@fanxinping
> Hi!
> You need to add `$$` like this
> ![image](https://user-images.githubusercontent.com/23021820/45604818-a86fd080-ba6a-11e8-9e67-ac9f0b4e6ae9.png)

Let me clarify the problem. I'm trying to use VNote (or ReText, I'm testing both) as Markdown editor for RMarkdown documents with [_bookdown_](https://bookdown.org/yihui/bookdown) extensions.

Usually such documents are created from [RStudio](https://www.rstudio.com/) and then converted to desired formats from it. But RStudio is no WYSIWYG editor, and it is slow. So I decided to use simple Markdown editor on the first stage and then use RStudio to build final document (HTML, PDF, EPUB, DOCX and so on).

The proposed syntax with `$$...$$` [is not supported by _bookdown_](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#equations) - the resulting equations will lose their labels and numbering and will not render in PDF at all (with "LaTeX Error: Bad math environment delimiter." error).

So if it possible please support syntax below without any modification:

```
\begin{equation} 
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation} 
```

I hope I can use VNote to edit my bookdown documents after fixing this bug :)

**Comment by N0rbert** [comment]
Version 2.1 still does not want  to render `equation` blocks with labels as in code below:

```
\begin{equation} 
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation} 
```

**Comment by tamlok** [comment]
Try:

    ```mathjax
    \begin{equation} 
      f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
      (\#eq:binom)
    \end{equation} 
    ```

**Comment by N0rbert** [comment]
Dear tamlok!
Thank you for reply. It works. But I have too many equations in simple`\begin{equation} ...  (\#eq:binom)
\end{equation} ` form.

Could you please support this simple syntax by default or may be configurable?

**Comment by tamlok** [comment]
@N0rbert Hi, it needs extra effort to support it in both read and edit mode. I will consider it when I have time and some other necessary features are finished.

Thanks!

**Comment by tamlok** [comment]
Fixed. Please try the [latest build](https://bintray.com/tamlok/vnote/vnote/2.1).

**Comment by N0rbert** [comment]
It works as expected. Thank you!
Do not forget to release it here, on GitHub :)

**Comment by N0rbert** [comment]
The equation below:

```
\begin{equation}
f\left(k\right) =\binom{n}{k} p^k\left(1-p\right)^{n k}
(#eq:binom)
\end{equation}
```

renders as plain text in latest VNote 2.4. 
Seems to be a regression.

**Comment by tamlok** [comment]
A regression. Fixed https://github.com/vnotex/vnote/commit/956842f1026755a98ff0f0dc99b06fc68d1a228d

Thank you!
