### ISSUE TITLE
VNOTE不能编辑内容,编辑内容的文本控件总是卡死状态!!

### ISSUE THREAD

**Issue by zzlufida** [tamlok/vnote#405]
我系统下的所有版本VNOTE可以正常预览最终MD的效果,但是只要使用CTRL+T切换到编辑,就卡主了,但是录入字虽然控件上看不到,如果你在使用CTRL+T切换过来,还能看到刚才录入的字,如果再切换到编辑模式,编辑控件里面有你写的字,但是不能编辑,是卡死的.如果你此时缩放窗体,整个窗体感觉就像是一张图片一样在缩放,特别奇怪.
******
正常的情况
![image](https://user-images.githubusercontent.com/32918530/45729399-eb62ad00-bbfe-11e8-93c9-523d3530068b.png)

不正常的情况
![image](https://user-images.githubusercontent.com/32918530/45729363-c79f6700-bbfe-11e8-9067-471889d0af75.png)

OS Version (操作系统): Windows 10

VNote Version (VNote版本): Latest (1.22)

Symptoms (表现):

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

请尝试更新显卡驱动，或者分配VNote使用集成显卡，或者新建一个环境变量。

参考： https://github.com/tamlok/vnote/issues/256

谢谢！
