### ISSUE TITLE
visual模式下，在一行里面，选择几个字符。。怎么选择的这个几个字符的背景，和整个行的背景一样都是浅蓝色的。导致看不清，哪些字符被选择了。。

### ISSUE THREAD

**Issue by hawkinchina** [tamlok/vnote#407]
> **PLEASE elaborate the issue in detail**  
> **请详细描述问题**
【问题描述】：visual模式下，在一行里面，选择几个字符。。发现选择的这个几个字符的背景，和整个行的背景一样都是浅蓝色的。导致看不清，哪些字符被选择了。
编辑器式样： v_pure
******

Version (操作系统):,, macOS 10.13
VNote Version (VNote版本): Latest (最新) V1.22
How to Repro (如何复现): VNOTE,采用支持vim模式， 在visual模式下，即可。可重现。

**Comment by tamlok** [comment]
Hi,

这是因为macOS上设置选择文本的前景色和背景色无效。已经将当前行的颜色变为橙色了。新版应该好了。谢谢！
