### ISSUE TITLE
[Suggestion] No need to prompt the user to reload a file if the file is not active

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#408]
> **PLEASE elaborate the issue in detail**  
> **请详细描述问题**

******

OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
If a file is changed by an external editor, VNote always prompt the user the update, even the file is not the current/active file tab.

Suggestion:
Move the prompt code to where just after the activation of the file tab.

How to Repro (如何复现):

**Comment by tamlok** [comment]
Added. Please try the latest build https://bintray.com/tamlok/vnote/vnote/2.0#files .

**Comment by seaspeak** [comment]
confirmed.
