### ISSUE TITLE
[需求]通过F2快捷键实现笔记的改名

### ISSUE THREAD

**Issue by zhenghualiang** [tamlok/vnote#41]
现有的笔记要改名时，可以通过右键＝＝信息改名。
存在问题：1.隐藏的比较深，不好找。2.改名不够快捷。
建议：通过F2快捷键实现笔记的改名。
谢谢！

**Comment by tamlok** [comment]
@zhenghualiang Hi，考虑到实现成本，下一步暂时只会添加F2快捷键来弹出`信息`对话框（也能在不用鼠标的情况下完成整个操作），不会像目前通用的那样直接原位修改。:) 谢谢反馈！

**Comment by zhenghualiang** [comment]
太好了，谢谢！

**Comment by tamlok** [comment]
@zhenghualiang Hi, 已经实现了`F2`和`Ctrl+C`等快捷键(7a0a2c552bb1b303f3d587e9e64d6aa98d349b65)，请关注下一个版本。或者，可以下载最新构建版本尝鲜～ 谢谢反馈和支持！

**Comment by zhenghualiang** [comment]
哇，太好了，谢谢！
