### ISSUE TITLE
VNote 1.22 在 Arch Linux 上启动时界面出现异常

### ISSUE THREAD

**Issue by ljca** [tamlok/vnote#412]
> &nbsp;&nbsp;当我在 Arch Linux 上初次启动 VNote 1.22 时，它的编辑器都不见了，只留下了工具和笔记本。我必须要手动点击二下工具栏上的扩展才会恢复正常。。。

******

OS Version (操作系统): Arch Linux
VNote Version (VNote版本): Latest (最新)
Symptoms (表现):
启动时编辑器消失，只留下了工具和扩展（笔记本）
How to Repro (如何复现):
只有点击工具栏上的扩展按钮才会恢复正常。

**Comment by tamlok** [comment]
是刚更新吗？试着在设置里面重置布局。
