### ISSUE TITLE
全屏关掉再打开有bug

### ISSUE THREAD

**Issue by lengthmin** [tamlok/vnote#413]
******

OS Version (操作系统): Windows

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
开全屏之后关掉再打开全屏有问题。

How to Repro (如何复现):
关掉再打开。

![image](https://user-images.githubusercontent.com/13938334/45916701-0f431e80-be9d-11e8-9a12-3bba816d754e.png)

**Comment by tamlok** [comment]
Hi,

请按以下操作顺序进行排查和解决：

- 更新显卡驱动；
- 指定vnote使用集成显卡；
- 新建一个系统变量，QT_OPENGL，值为angle或者software，重启电脑。

一般都是显卡导致的opengl问题。

谢谢！

**Comment by lengthmin** [comment]
已解决！谢谢
