### ISSUE TITLE
关于标签的一点构想

### ISSUE THREAD

**Issue by lengthmin** [tamlok/vnote#415]
之前手机上用过一个叫`易码`的app，里面的标签实现是通过文件名来实现的。
文件名中有"@xxx"的标签就是xxx

**Comment by tamlok** [comment]
Hi,

VNote的设计出发点是即使没有VNote也能使用任意一个编辑器很方便地管理和编辑笔记，所以文件名字还是不要塞进太多信息的比较好。否则，一堆文件都是`@xxx`开头的，感觉比较违和。

另外一种做法是在笔记里面塞进几行YAML元数据，把title和tag等加进去。不过，我感觉还是元数据和笔记分离会比较好一点。

谢谢！

**Comment by lengthmin** [comment]
如果文件名添加标签有个好处：还可以在不使用vnote的情况下用文件管理器搜索标签。

把`@`放在文件名尾部就对笔记的辨认少一点。

只是提个建议而已~

**Comment by tamlok** [comment]
的确有这个好处。但是文件名有文件名的字符限制，而且还是倾向于保留文件名的干净。

谢谢！

**Comment by lengthmin** [comment]
ok～

**Comment by davidnsw** [comment]
> Hi,
> 
> VNote的设计出发点是即使没有VNote也能使用任意一个编辑器很方便地管理和编辑笔记，所以文件名字还是不要塞进太多信息的比较好。否则，一堆文件都是`@xxx`开头的，感觉比较违和。
> 
> 另外一种做法是在笔记里面塞进几行YAML元数据，把title和tag等加进去。不过，我感觉还是元数据和笔记分离会比较好一点。
> 
> 谢谢！

说出了我的心声
