### ISSUE TITLE
Nouveau segmentation fault

### ISSUE THREAD

**Issue by fodrice** [tamlok/vnote#417]
When trying to open appimage on my old laptop with nouveau (gentoo linux-up to date with stable kernel and mesa) I got Segmentation fault. It appers when app starting to render preview (swithing off in-line preview doen't help).

```
nouveau: kernel rejected pushbuf: Нет такого файла или каталога
nouveau: ch9: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch9: buf 00000000 00000002 00000004 00000004 00000000
nouveau: kernel rejected pushbuf: Нет такого файла или каталога
nouveau: ch9: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch9: buf 00000000 00000002 00000004 00000004 00000000
nouveau: kernel rejected pushbuf: Нет такого файла или каталога
nouveau: ch9: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch9: buf 00000000 00000002 00000004 00000004 00000000
nouveau: kernel rejected pushbuf: Нет такого файла или каталога
nouveau: ch9: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch9: buf 00000000 00000002 00000004 00000004 00000000
nouveau: kernel rejected pushbuf: Нет такого файла или каталога
nouveau: ch9: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch9: buf 00000000 00000002 00000004 00000004 00000000
Segmentation fault
```
" Нет такого файла или каталога" Means no such file or directory.

  
My system

gentoo-linux-4.14.67
mesa-18.1.8
qt-5.9.6
kde-5.12.6

VNote version 1.22

Also,. Is it possible to fully disable QWebEngine workers ? It could be useful on such laptops to improve editing performance.

**Comment by fodrice** [comment]
Tried ```QT_OPENGL=software``` and ```QT_OPENGL=angle``` - get similar crash. 
```nouveau: kernel rejected pushbuf: ....```

Perhaps problem in old qt version. Could you use qt-5.9.6 instead of qt-5.9.3 in appimage? 

And how about option "Disable QWebEngine" just to switch off all preview.

**Comment by tamlok** [comment]
Searching the error `nouveau: kernel rejected pushbuf` shows several similar issues. I am afraid it is something about display card driver and Qt.

I will update to 5.9.6 later.

VNote uses `QWebEngine` to run some javascript. It is feasible to remove QWebEngine from VNote at the cost of missing some features, but it may need lots of efforts.

**Comment by fodrice** [comment]
Tried your appimage on my second laptop. Xorg just sudenlly freezes without any message. Same operating system and packages but old radeon video.

**Comment by tamlok** [comment]
Hi,

Already updated to 5.9.6. You could download the latest build [here](https://bintray.com/tamlok/vnote/vnote/2.0#files) and test again.

I am sure that it is caused by the openGL. Another user reported that it works fine after he changed to Nvidia's proprietary driver.

In Windows, some users solve this issue by assigning VNote to the integrated display card.

Thanks!

**Comment by fodrice** [comment]
New build fixed amd R600 opensource driver. But not nouveau. 
Yes, i think this is driver's problem too. 2018 Still no nvidia opensource driver for 10 years old laptop.
