### ISSUE TITLE
Do I have to run the app from the AppImage everytime?

### ISSUE THREAD

**Issue by asamolion** [tamlok/vnote#422]
I'm trying out VNote on Linux Mint 19,
However, many apps get added to the menu and to the shell once the AppImage has been executed, No entry is added to the apps in the start menu and I have to navigate to the AppImage file and run it from there every time.

Is this the normal way to use VNote? Is it possible to have an entry of it in the menu?

Thanks in advance.

**Comment by asamolion** [comment]
I see. So the AppImage is the recommended way. Cool!

Thanks for responding so quickly!

**Comment by asamolion** [comment]
Is there a way to automatically add the desktop file on first run?

I'm willing to implement this if someone can guide me.

**Comment by tamlok** [comment]
@probonopd may be able to help.

**Comment by asamolion** [comment]
@probonopd Cool, thanks!
