### ISSUE TITLE
PlantUML - how to use?

### ISSUE THREAD

**Issue by drendar** [tamlok/vnote#424]
> **PLEASE elaborate the issue in detail**  
> **请详细描述问题**

Documentation does not describe how to use the PlantUML feature - how do you use this?

I've tried creating a code block containing puml but in the preview it just displays the code - doesn't render the diagram.

Please note I'm a new user and so I may be doing something wrong, but I can find no info on how to use this.  Thanks!

******

OS Version (操作系统): Windows 10 64bit

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):  No documentation on how to use PlantUML feature

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

Please check the settings dialog in the file menu. You need to enable online server or setup local plantuml jar environment.

Thanks!

**Comment by drendar** [comment]
Bingo!

For anyone else searching you then have to encase the puml code in triple backticks with puml appended to the first.

e.g.

    ```puml
    @startuml
    Bob -> Alice : hello
    @enduml
    ```

  Thanks!
