### ISSUE TITLE
字体颜色

### ISSUE THREAD

**Issue by GitHubJays** [tamlok/vnote#426]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):希望能够添加快速选择或者常用字体颜色设置的快捷键

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

请问是什么字体颜色呢？

如果是语法高亮配色，这个通过css或mdhl文件进行定义，用户可以自定义新的配色或主题。

如果是类似于富文本的字体颜色，基础md并不支持也不推荐为某些文本使用不同颜色。可以通过`<mark>`或`<font>`来改变文本颜色。通过带有快捷键的片段功能，能快速输入。

另外，希望问题能详细一点，有具体例子和场景，这样节省时间，谢谢！
