### ISSUE TITLE
如何插入emoji？

### ISSUE THREAD

**Issue by kerHbal** [tamlok/vnote#427]
OS Version : Windows

VNote Version: Latest

Markdown-it选项里的emoji已被开启
如图，在有emoji的时候会出现图片自动消失问题，消失的图片可以在笔记本回收站找到。
但并不是所有emoji都会有这问题，目前只测试了几个
会出问题的：💎💡🔑
不会出问题但明显会卡一下的：⌛️
![1](https://user-images.githubusercontent.com/11629684/46167093-e5a24280-c262-11e8-9d70-063f28c0f0bd.gif)

**Comment by tamlok** [comment]
Hi,

这是因为直接插入的emoji图片估计是Unicode编码，编辑模式的解析器对这个支持不好，所以并未解析到有图片链接存在。

如果在编辑模式出现高亮不对的地方，一般建议编辑一下，让所有元素都正确高亮。

md-it的emoji功能是指插入可读纯文本，并不是直接插入emoji，例如`[smile]`会在阅读模式下渲染为一个笑脸。

谢谢！

**Comment by kerHbal** [comment]
OK，懂了。多谢！

**Comment by kerHbal** [comment]
不过我发现好像[smile]也不行，只支持 https://github.com/markdown-it/markdown-it-emoji/blob/master/lib/data/shortcuts.js 里面的shortcut，感觉太少了。。。
![snipaste_2018-09-27_20-30-05](https://user-images.githubusercontent.com/11629684/46181536-780f0a00-c294-11e8-885c-f7c2e58397e9.png)
![snipaste_2018-09-27_20-30-12](https://user-images.githubusercontent.com/11629684/46181538-7b09fa80-c294-11e8-88f1-8a312b103dea.png)

**Comment by kerHbal** [comment]
哦我发现这里面的也可以，这是全套的
https://gist.github.com/rxaviers/7360908
![image](https://user-images.githubusercontent.com/11629684/46181670-2adf6800-c295-11e8-877d-90109cabf52e.png)
![image](https://user-images.githubusercontent.com/11629684/46181682-3cc10b00-c295-11e8-9069-e7b29f405669.png)

**Comment by tamlok** [comment]
是的，应该是支持Github全套表情的。我比较少用，一时记错写法了 :(

**Comment by kerHbal** [comment]
嗯我也是想用里面的某些物体当重点标志，配合全文搜索一起用，直接找到所有笔记里有同样标记的地方

**Comment by tamlok** [comment]
2.1 可以直接插入emoji了，可以尝试一下。

**Comment by youmoxiaozi** [comment]
> 2.1可以直接插入emoji了，可以尝试一下。

:gem:
:grinning:
:smiley:

:one:

输入这些怎么不起作用？

**Comment by tamlok** [comment]
@youmoxiaozi Hi，需要在Markdown菜单下面的Markdown-it选项里面勾选emoji，重启vnote。
