### ISSUE TITLE
字体颜色、居中对齐的问题

### ISSUE THREAD

**Issue by librix** [tamlok/vnote#428]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):HTML 代码在文本中显示很长。颜色值和代码输入不方便，且显示方式上与文本混杂很怪异。居中、居右操作不便。

How to Repro (如何复现): 

> `在 md 文件中输入<font color="red">紅色</font> <div style="color:orange; margin:0px auto;text-align: center;">文字顏色為橘色</div> 这段文字。`

Question：现在是有有成熟的输入方式？若无，可否添加 shortcuts 为选中文字插入这两段代码，并且显示方式上做一些优化。比如：在选中文字的时候可以弹出一个样式修改器。样式修改器按钮可以自定义代码。
![image](https://user-images.githubusercontent.com/10742127/46188859-27dc8a00-c31e-11e8-9ce6-1173f239bd65.png)
感觉使用正则表达式替换就很方便，比如`~s/(mark)/<font color="red">$1<\/font>/ig`

**Comment by tamlok** [comment]
Hi,

- Markdown的理念是文本与样式分离，而且强调文本一般是粗体或斜体来进行，很少用到颜色进行区分；
- 如果一定要使用颜色，建议优先使用`<mark>abc</mark>`标记，VNote能识别该标记并在编辑模式下进行着色；
- 如果一定要用`<font color='red'>abc</font>`标记，也是可以的，这个比较简短；
- 对于`<div style="color:orange; margin:0px auto;text-align: center;">`这种，建议使用`<div class="bala">`方式，并自定义CSS样式文件；
- VNote通过**片段**来实现快捷键快速插入文本，具体请参考[文档](https://vnote.readthedocs.io/en/latest/user_docs/snippet.html) 。

谢谢！
