### ISSUE TITLE
【需求】Mathjax不工作，请求支持本地模式

### ISSUE THREAD

**Issue by zhnuaa** [tamlok/vnote#43]
mathjax完全没响应。看起来像是像是采用了在线的mathjax解析服务？天朝的网络条件下，完全不好使。所以，可能的话请支持本地mathjax解析支持。

**Comment by Hsins** [comment]
四月份的時候，MathJax官方關閉了 CDN…

**Comment by zhnuaa** [comment]
> 四月份的時候，MathJax官方關閉了 CDN…
这样的话，可以直接把代码里的mathjax网址指定本地mathjax就ok了吧。。。

**Comment by Hsins** [comment]
那當然，但 MathJax 本身就大了，可以下載來放在本地目錄後再相對指向過去

**Comment by tamlok** [comment]
@zhnuaa 我这边测试倒是没啥问题。之前的确有CDN关闭的警告信息，但是后来好像没有了。您的之前能正常工作吗？后面会支持配置Mathjax的地址，这样您就可以下载到本地，然后指定本地的文件来进行渲染。因为太大了，所以不会集成进VNote里面。谢谢反馈！

**Comment by zhnuaa** [comment]
@tamlok 前两天测试都不能正常渲染。今天试了下，工作正常了。应该还是网络不稳定的原因。如果能支持配置本地mathjax那就完美了

**Comment by tamlok** [comment]
@zhnuaa @Hsins Hi, 目前已经实现(d955dedcb7c58bc9442706fec8a96a7b100e9037)可以自定义MathJax路径和配置了，可以参考[Wiki](https://github.com/tamlok/vnote/wiki/FAQ#how-to-specify-custom-mathjax)。 请关注下一个版本。

谢谢反馈！
