### ISSUE TITLE
[Retina Macbook Pro] The Icons At The Tool Bar Are Very Blurred

### ISSUE THREAD

**Issue by yanzhang0219** [tamlok/vnote#430]
OS Version (操作系统): macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
<img width="766" alt="screen shot 2018-10-01 at 7 13 52 pm" src="https://user-images.githubusercontent.com/11582667/46325710-6b4d2780-c5ae-11e8-9eb6-2dfde16aa5df.png">
As shown above (try to click the figure to get a larger image which will show this issue clearly), the icons there are very very blurred on Retina (high resolution) Macbook Pro. I know you do not have a mac so it is not convenient for you to test and polish it. Just let you know this. Hope in the future, you can improve it to perfect this amazing note-taking beast. Thank you. 

How to Repro (如何复现):
Just open VNote under macOS. :)

**Comment by tamlok** [comment]
Fixed in 2.1. Please try it out. Thanks!
