### ISSUE TITLE
number before tab title is unnecessary

### ISSUE THREAD

**Issue by fghhfg** [tamlok/vnote#437]
OS Version (操作系统): Windows7
VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
```
1.title_name  2.title_name  3.title_name   ...
```
![2018-10-06 22_43_05-vnote - vnotebook c__users_eight_documents_vnote_notebooks_vnotebook_roottt_ne](https://user-images.githubusercontent.com/1284845/46572512-9c1bcb00-c9b9-11e8-962a-8a591b976f47.jpg)

suggest:
number before tab title is unnecessary and confused,
just change number style or delete it...

**Comment by tamlok** [comment]
Hi,

We could jump to a specific tab by hitting `Ctrl+E` and the number, such as `Ctrl+E 2` to jump to tab 2.

I do not see any difference between your suggested style and the original one.

Thanks!
