### ISSUE TITLE
suggest: In-Place Preview for link

### ISSUE THREAD

**Issue by fghhfg** [tamlok/vnote#438]
In-Place Preview for clickable link

---
clickable link below markdown syntax in edited mode
or just make link clickable in edited mode

something like this:
```
[title](https://github.com/tamlok/vnote/issues/438)     <------ markdown syntax
title     <---------------------------------------------------- clickable link 
```

user can click link without jump to read mode

**Comment by tamlok** [comment]
Hi,

To preview what, the webpage?

Thanks!

**Comment by fghhfg** [comment]
clickable link below markdown syntax in edited mode

**Comment by tamlok** [comment]
Hi,

Please right click on the link (or image link) in edit mode, you could see corresponding actions in the context menu.

Thanks!
