### ISSUE TITLE
黑屏怎么解？

### ISSUE THREAD

**Issue by Aquarian-Age** [tamlok/vnote#439]
OS Version (操作系统):   Linux

VNote Version Latest (最新) 2.0

Symptoms (表现):
预览状态黑屏 右键点击编辑 之后可看到内容 然而预览还是黑屏 无解。。。。
[1007/085844.597190:WARNING:stack_trace_posix.cc(648)] Failed to open file: /home/xuan/#2110119 (deleted)
  Error: 没有那个文件或目录
[30502:30728:1007/085844.923362:ERROR:nss_util.cc(750)] After loading Root Certs, loaded==false: NSS error code: -8018
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::removePaths: list is empty

How to Repro (如何复现):

**Comment by tamlok** [comment]
hi，

请详细描述一下环境：

- ArchLinux?
- 自行编译还是appimage？如果自己编译，qt版本？

看提示是nssutils库的问题。

**Comment by Aquarian-Age** [comment]
openSUSE 15.0
最开始用appimage没发现这个问题
后来自己拉源码编译安装 昨天出现了这个问题
QT版本系统默认的5.9.4

**Comment by tamlok** [comment]
Hi,

应该不是vnote的问题。系统上有QtCreator吗？可以运行一下里面的一个Markdown Editor的例子，该例子也是调用QWebEngineProcess来预览网页的，测试一下能否正常运行？

谢谢！
