### ISSUE TITLE
设置保存在AppData\Roaming\VNote 无法达到便携的目的

### ISSUE THREAD

**Issue by heartnn** [tamlok/vnote#44]
怎么设置才能保存在当前目录，方便携带？

**Comment by tamlok** [comment]
Hi，这是因为配置文件里面包含有路径，比如笔记本的根目录之类的，即使保存了带着走，在别的电脑上还是很可能会出错的。您能说一下具体的使用场景吗？比如有啥需求之类的。看看有没有啥变通方法。谢谢！

**Comment by heartnn** [comment]
我现在用syncthing同步两台电脑，路径不一样实在是不方便，另外笔记本的确是无法使用相对路径的，目前只能用mklink链接过去了。

**Comment by tamlok** [comment]
@heartnn hi，我目前的使用方式是只用网盘同步数据，vnote程序在两台电脑上是独立的，在每台电脑上分别导入笔记本(同一个笔记本，但不同路径，名字随意)，这样就可以跨机器编辑同一个笔记本了。这样的好处是数据和程序分离，程序也没必要同步过去。

后面我考虑把笔记本这种数据从配置文件里面独立出来吧，然后程序优先使用程序所在目录下的配置文件。但配置文件里面其实还是会有部分配置是依赖于不同机器的。

谢谢反馈！

**Comment by heartnn** [comment]
了解了，多谢回复，感觉现在mklink也不是不能接受。

**Comment by tamlok** [comment]
Hi, VNote将会支持优先读取可执行文件所在目录的`vnote.ini`配置文件 (01acd03a7199bbb22a758586644d42c3eebdccd8)。敬请关注下一个版本。谢谢！

**Comment by Stivenke** [comment]
> 
> 
> 怎么设置才能保存在当前目录，方便携带？

我做了一个 portable 包，你可以试试看，https://github.com/tamlok/vnote/issues/676

**Comment by heartnn** [comment]
自己做了一个cmd， 之前好像没发过来

```
@echo off
if not exist "%CD%\Profile\AppData\Roaming" mkdir "%CD%\Profile\AppData\Roaming"
if not exist "%CD%\Notes" mkdir "%CD%\Notes"
if not exist "%CD%\Profile\AppData\Local\Temp" mkdir "%CD%\Profile\AppData\Local\Temp"
set USERPROFILE=%CD%\profile
set APPDATA=%CD%\Profile\AppData
set TEMP=%CD%\Profile\AppData\Local\Temp
set TMP=%CD%\Profile\AppData\Local\Temp
if not exist "%CD%\Notes" goto message
goto start

:message
echo PORTABLE VNote
echo -------------------------------
echo Please point path in VNote:  .\Notes
echo.
pause 

:start
start App\VNote.exe /I
```
