### ISSUE TITLE
貌似不能通过拖放改变笔记目录

### ISSUE THREAD

**Issue by mx1680** [tamlok/vnote#440]
手动移动文件到目标目录下并更新目录下的_vnote.json，重新打开软件仍然没有生效，后来发现需要“重新从磁盘加载”才可以。不过这样还是不太方便。
另外，我发现从html粘贴代码时有些字符会被过度用\转义，对表格的支持也不太好，不知html2markdown是通过第三方实现的还是自己实现的，希望可以改进。

**Comment by tamlok** [comment]
Hi,

目前支持右键菜单复制粘贴移动笔记和文件夹，类似于系统的文件管理：

![image](https://user-images.githubusercontent.com/5763157/46578423-446d7600-ca32-11e8-86a7-eea527a28f98.png)

对于html2markdown，使用的是[turndown](https://github.com/domchristie/turndown)，JS实现，有兴趣的可以改进PR。对应文件在 [vnote/utils](https://github.com/tamlok/vnote/tree/master/src/utils/turndown).

谢谢！

**Comment by mx1680** [comment]
建议参考Library.NET界面构成，将附件进行分类（笔记、源代码、文件、网址、网页等）并以页签方式显示在编辑器窗口下方。

![library_net](https://user-images.githubusercontent.com/43845474/46899237-6f891700-cec3-11e8-811e-2036cf46448c.jpg)

**Comment by tamlok** [comment]
![drag drop](https://user-images.githubusercontent.com/5763157/46900442-99c1e100-ce91-11e8-8553-c195e516fa02.gif)

- 之前是用用户提出双击关闭标签页的，这个也比较常见，而且也符合操作习惯：当需要关闭某些标签页的时候，鼠标应该会放在标签页那一栏上面，双击关闭比较方便；而切换模式的时候，鼠标不一定在标签页上面，这时候快捷键`Ctrl+T`或右键菜单都比较快捷。
- 关于附件的管理和分类，这个后面等支持插件了，由插件来完成吧，我就不挖坑了:)

谢谢！

**Comment by mx1680** [comment]
奇怪，我这边下载的版本不支持拖拽。光标多数在编辑区域，感觉如果双击编辑区快速切换模式会比较方便，必竟这个动作会用得比较多。

**Comment by tamlok** [comment]
哦，误会了，原来你说的是双击编辑区域。双击编辑区域在很多软件上面默认的行为是选定所在单词或者整个句子，这个默认行为还是不要改变比较好。

**Comment by tamlok** [comment]
Fixed in 2.1. Please try it out. Thanks!
