### ISSUE TITLE
建议增加纯文本粘贴快捷键

### ISSUE THREAD

**Issue by tootal** [tamlok/vnote#441]
OS Version (操作系统): Windows
VNote Version (VNote版本): Latest (最新)

# Symptoms (表现):
从onenote复制文字到vnote会弹出粘贴选项框。
（不过这貌似是onenote的问题）
目前可以用Ctrl+E p 纯文本粘贴，但操作较多时较为不便。
建议增加快捷键实现纯文本粘贴（Ctrl+Shift+V）

**Comment by tamlok** [comment]
Added. Please try https://bintray.com/tamlok/vnote/vnote/2.0#files

**Comment by geoffreycheungr** [comment]
这个在其他软件中也会遇到，目前我用 Pure Text 一个小软件来帮助粘贴纯文本，可以应用于所有软件。
供参考。

**Comment by tamlok** [comment]
Fixed in 2.1. Please try it out. Thanks!
