### ISSUE TITLE
表格的优化

### ISSUE THREAD

**Issue by l0o0** [tamlok/vnote#442]
你好，在markdown下写表格真是痛苦。不知道有没有方法可以方便的写表格？可以参考下typora里面的表格写法，感觉挺方便的。  
还有就是从 excel里复制的表格，不知道能不在vnote里生成表格呢？

**Comment by tamlok** [comment]
Hi,

- 表格输入VNote还没有进行优化，请继续关注；
- 请下载[最新构建版](https://bintray.com/tamlok/vnote/vnote/2.0#files)，已经实现了从excel粘贴为表格，但是需要自己把第一行表格挪动为表头；

谢谢！
