### ISSUE TITLE
plantuml无法画类图

### ISSUE THREAD

**Issue by LiguangZhang** [tamlok/vnote#448]
OS Version (操作系统): Linux, 

VNote Version (VNote版本): Latest 

Symptoms (表现):

plantuml类图画不出来, 其他类型都没问题. 比如序列图 activity图等都没问题

How to Repro (如何复现):

@startuml
Class01 <|-- Class02:泛化
Class03 <-- Class04:关联
Class05 *-- Class06:组合
Class07 o-- Class08:聚合
Class09 -- Class10
@enduml

Dot Executable: dot
File does not exist
Cannot find Graphviz. You should try
@startuml
testdot
@enduml
or
java -jar plantuml.jar -testdot

**Comment by tamlok** [comment]
上面就有答案了呀，没有安装graphviz

**Comment by LiguangZhang** [comment]
已经安装了, ubuntu下是/usr/bin/dot
点击Test, 结果也是success.
唯独类图画不了, plantuml的其他类型图, 序列图 activity图 流程图等都没问题.

**Comment by tamlok** [comment]
命令行下面执行：

java -jar plantuml.jar -testdot


输出是什么？先确保在命令行下面可以正常转换类图。

**Comment by LiguangZhang** [comment]
$ java -jar plantuml.jar -testdot
The environment variable GRAPHVIZ_DOT has not been set
Dot executable is /usr/bin/dot
Dot version: dot - graphviz version 2.36.0 (20140111.2315)
Installation seems OK. File generation OK

**Comment by tamlok** [comment]
那你在vnote里面设置一下dot的路径，或者声明一下那个环境变量，再试试？

**Comment by LiguangZhang** [comment]
好了, 设置了环境变量后可以了, 多谢
