### ISSUE TITLE
添加公式编号

### ISSUE THREAD

**Issue by JsuKya** [tamlok/vnote#449]
OS Version (操作系统): Windows 10 64位

VNote Version (VNote版本): Latest (最新)

首先十分感谢作者的辛勤付出，我之前用的是cmd_markdown，但是对fortran的代码高亮支持不好，但VNote的支持就十分好，准备后面转向VNote。

因为我写的笔记里面经常有比较多的公式，所以我想问下是否能够对行间公式（latex里面的equation或者align等）加入编号？

**Comment by tamlok** [comment]
后面会加入支持，敬请关注。

**Comment by tamlok** [comment]
Fixed in 2.1. Please try it out. Thanks!

**Comment by JsuKya** [comment]
十分感谢作者这么快就添加了相关功能，我试用了一下，就还有一些想法。

首先这个功能对于单行的公式来说已经够用了，但如果是多行公式，类似Latex里面的align环境，就没法对每行公式编号了，只能对整体编号，像下面这种
![default](https://user-images.githubusercontent.com/4434145/47619423-c0f9ee80-dade-11e8-838b-a001e13a0c45.png)
但是align在latex里面默认是对每行公式都进行编号的，如下所示
![default](https://user-images.githubusercontent.com/4434145/47619327-cb67b880-dadd-11e8-8b6d-6545765c9ffe.png)

所以，编号能不能采用Latex的思路，通过选择不同的公式环境（如align或者aligned）来实现不同的编号方式，下面的是aligned环境的编号效果
![default](https://user-images.githubusercontent.com/4434145/47619400-88f2ab80-dade-11e8-8dc8-ca7fdba860fc.png)

谢谢

**Comment by tamlok** [comment]
后面我看看mathjax的配置。

**Comment by jdhao** [comment]
It is not wise to give four equations only one equation number.  The `aligned` environment is for one equation which is two long in one line. The `align` environment is for multiple equations which you want to group together.

**Comment by jdhao** [comment]
I have written a post about how to config Mathjax for automatic equation numbering for my Hexo blog. I think the configuration is the same. 
The configuration I use is : 
```
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"]  ],
      processEscapes: true,
      skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
    },
    TeX: {equationNumbers: { autoNumber: "AMS" }}
  });
</script>
```

The complete post can be found [here](https://jdhao.github.io/2018/01/25/hexo-mathjax-equation-number/).

**Comment by tamlok** [comment]
@jdhao Thanks! Already fixed.

**Comment by Stivenke** [comment]
公式编号，建议是否添加设置选项，由用户选择开启或关闭。

**Comment by tamlok** [comment]
@Stivenke 这个是有什么困扰吗？在公式里面不写的话，是不会自动编号的吧？

**Comment by Summerslyb** [comment]
@tamlok @jdhao How to config <script> in Vnote?

**Comment by tamlok** [comment]
@Summerslyb For now it is hard-coded. You may need to change the code and compile VNote from source. You could take a look at https://github.com/tamlok/vnote/blob/56715bc9a5c8377e9234eb8d2e06ed377b179b32/src/utils/vutils.cpp#L791 if you want.

**Comment by Summerslyb** [comment]
@tamlok Would you mind adding options for the configuration of Mathjax in the configuration menu?

**Comment by tamlok** [comment]
@Summerslyb Will be supported in the future.
