### ISSUE TITLE
【需求】自动保存

### ISSUE THREAD

**Issue by Necolo** [tamlok/vnote#45]
VNOTE是目前为止我用过最满意的一款markdown笔记管理软件，感谢作者带来的这么好的工具。

不过上个周末笔记写着写着家里突然断电了，于是笔记白写了。希望增加自动保存功能，用户可以设置每"n"分钟自动保存一次。

**Comment by tamlok** [comment]
Hi，谢谢支持！

后面会加上类似于Vim一样的swp缓存文件，重新打开的时候会提示恢复。

谢谢！

**Comment by tamlok** [comment]
Hi, 1.10已经支持备份文件，编辑的时候，所有改动会（每3秒）自动保存在一个`.vswp`文件中。如果VNote意外退出，VNote会提示恢复。

自动保存我觉得其实有点不太实用，因为有时候只是简单打开浏览一下也可能不小心就改动了什么。当然如果配合文件历史版本啥的，就比较实用。所以，目前采用的是Vim的交换文件的方法。

不知道能满足您的要求不？
