### ISSUE TITLE
部分加粗无效

### ISSUE THREAD

**Issue by Memento1990** [tamlok/vnote#450]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
将 **伪阳性率(FPR)**定义为 X 轴，**真阳性率(TPR)**定义为 Y 轴。
上面这句话，在两个定义的“定”字前加上空格，预览时才会加粗，否则只会在编辑是是加粗状态。

How to Repro (如何复现):
将 **伪阳性率(FPR)**定义为 X 轴，**真阳性率(TPR)**定义为 Y 轴。

**Comment by tamlok** [comment]
https://github.com/tamlok/vnote/issues/429

需要在`**`后面加一个空格。
