### ISSUE TITLE
Ubuntu18.04下重启后根目录需要重新指定

### ISSUE THREAD

**Issue by mzkingk** [tamlok/vnote#451]
感谢开发者开发出这么好的md编辑器，并且让我在Linux下也可以用它！！！
系统:  Ubuntu18.04
我一直用的Ubuntu18.04，gnome桌面版，但每次重启电脑过后打开vnote就又要重新指定浏览的根目录，很麻烦

因为其它原因，重装过多次系统了，但每次把vnote重新下下来使用，重启之后都有这个问题

**Comment by tamlok** [comment]
如果使用的是浏览器来浏览外部文件（而不是内部笔记本），那么需要按一下旁边那个⭐来收藏当前根目录，这样vnote就会保存该记录。

因为用户可以随时指定一个文件夹作为根目录（在一个文件夹上右键），所以如果默认都保存会很乱。

谢谢！
