### ISSUE TITLE
[Feature Request] add "APPLY" button to make setting's change in effect immediately

### ISSUE THREAD

**Issue by bbsteel** [tamlok/vnote#452]
OS Version (操作系统):  Linux

VNote Version (VNote版本): 2.0

If we can instead APPLY change immediately: 
1. No need to restart Vnote to make setting's change in effect, especially visual setting.
2. No need to reconfigure setting if Vnote crashed. (currently Vnote is easy to crash in my Ubuntu16.04) 

If apply is a bit difficult to implement this feature, a restart button is much appreciate.

**Comment by tamlok** [comment]
hi,

Some settings only require re-open current tabs. For theme, it is hard to suppoer on-line change.

Why do you need to reconfigure settings when VNote crashes? Take an example?

For the crash, could you add -d as the launch argument and send me the log after VNote crashes? I have not seen frequent crash in my daily use.

Thanks!

**Comment by tamlok** [comment]
Add `Restart` action in 2.1. Please try it out. Thanks!
