### ISSUE TITLE
写了一个.desktop文件，应用图标在dock栏无法显示

### ISSUE THREAD

**Issue by metanoia1989** [tamlok/vnote#453]
OS Version (操作系统):  Deepin Linux 15.7

VNote Version (VNote版本): Latest (最新)

Symptoms (表现): 写了一个.desktop文件，在应用菜单里vnote能显示图标，运行应用之后dock栏却无法显示图标。
![Imgur](https://i.imgur.com/52QXwde.png)
![vnote icons](https://i.imgur.com/qEUh6GU.png)

.desktop文件内容如下
```
[Desktop Entry]
Name=Vnote
Comment=Text Markdown Editor
GenericName=Markdown Editor
Exec=/home/smithadam/Applications/VNote-2.0-x86_64.AppImage
Icon=vnote
Type=Application
StartupNotify=true
Categories=Qt;Editor
MimeType=application/x-vnote
```

**Comment by tamlok** [comment]
Hi,

desktop里面icon的搜寻路径好像是有指定的，你可以把appimage解压了，将里面的图标提取出来，放在那个固定路径里面，再试试看？

或者可以试试 ˋappimagedˋ daemon 或者 AppImageLauncher工具.

**Comment by metanoia1989** [comment]
> Hi,
> 
> desktop里面icon的搜寻路径好像是有指定的，你可以把appimage解压了，将里面的图标提取出来，放在那个固定路径里面，再试试看？
> 
> 或者可以试试 ˋappimagedˋ daemon 或者 AppImageLauncher工具.

把之前的.desktop文件刪除掉了，再用 AppImageLauncher 运行，dock栏能正常显示图标了
