### ISSUE TITLE
macOS下滚动条遮挡窗口内容

### ISSUE THREAD

**Issue by runnerWSX** [tamlok/vnote#454]
OS Version (操作系统): macOS 10.12.6

VNote Version (VNote版本): 最新2.0

Symptoms (表现):
![image](https://user-images.githubusercontent.com/32385550/46988109-ac564780-d129-11e8-9b55-b88a230a734e.png)
无法滚动到最下面，导致部分文件看不到

**Comment by tamlok** [comment]
hi，

用Mojave虚拟机显示正常。

- 可以尝试声明环境变量`QT_OPENGL=software`，然后启动vnote；
- 如果不行，可以尝试切换到主题`v_native`，重启vnote。

**Comment by runnerWSX** [comment]
系统升级到Mojave  10.14 (18A391)，滚动条还是无法滚动到最下面，只有v_native主题生效，其他主题都有这个问题,，修改环境变量也没有用。

**Comment by tamlok** [comment]
native那里好像没有显示横向滚动条。我后面再看看。估计是我的虚拟机问题，没有真实的硬件，谢谢帮忙测试！

**Comment by tamlok** [comment]
Hi,

已经找到根源了，和https://github.com/tamlok/vnote/issues/284 一样的问题。macos有一个特性是自动隐藏滚动条，Qt在这种情况下，如果自定义滚动条的样式的话，会出现滚动条没有隐藏的问题，参考 https://bugreports.qt.io/browse/QTBUG-63381 。

可以参考下面任意一个方法进行解决：

1. 在macos系统配置里面，将滚动条设置为总是显示；
2. VNote启动的时候，添加参数`-style Fusion`，指定使用Linux样式；
3. 删除对应主题的`*.qss`文件里面关于`QScrollBar`相关的配置，这样会使用默认样式，在暗色主题下比较刺眼；

谢谢！
