### ISSUE TITLE
从知乎页面复制内容时正确复制所包含的公式

### ISSUE THREAD

**Issue by kerHbal** [tamlok/vnote#455]
Windows

vnote：Latest build，集成了图片本地fetch功能

我看到你已经在着手解决fetch图片时的alttext问题了，首先十分感谢如此及时的开发进度，同时也觉得正好现在把这个问题提出来，因为知乎的公式类似于图片。
**背景：**
知乎页面的公式是tex，如果右键存储则为svg格式。从网页html代码来看有些网页的公式有alttext（[例](https://daily.zhihu.com/story/9651376)）有些没有alttext（[例](https://daily.zhihu.com/story/9466152)）

**直接复制markdown的情况：**
如果页面包含一定数量的公式，例如举例的第一个页面，复制后会卡住一会儿，然后消耗巨量内存，且编辑模式能看到很大的公式原地预览，阅读模式看不到公式。
![image](https://user-images.githubusercontent.com/11629684/47030162-29d68380-d13b-11e8-9ceb-c1dab396c02b.png)

**暂时的解决办法：**
- 公式有alttext的页面直接复制为markdown以后一个个把公式`![xxx](xxxxxxx)`改为`$xxx$`
- 公式没有alttext的页面需要手动输入

**需求：**
希望能有方法在复制内容时把网页上svg形式的公式变回Mathjax的文本`$xxx$`。谢谢！

**Comment by tamlok** [comment]
谢谢反馈，已经修复。

**Comment by kerHbal** [comment]
多谢！！

**Comment by tamlok** [comment]
Fixed in 2.1. Please try it out. Thanks!

**Comment by dc3671** [comment]
@tamlok 似乎知乎最近又改了公式的HTML格式（[例子](https://zhuanlan.zhihu.com/p/36101196)），

```html
<img src="https://www.zhihu.com/equation?tex=s_t+%3D+tanh%28W_xx_t%2BW_s+s_%7Bt-1%7D%2Bb%29" 
alt="[公式]" eeimg="1" data-formula="s_t = tanh(W_xx_t+W_s s_{t-1}+b)">
```

公式内容放在了data-formula里，而非alt里，这个能不能再支持一下？
