### ISSUE TITLE
[请教问题] 转换\n为换行

### ISSUE THREAD

**Issue by wuscloud** [tamlok/vnote#457]
我有个使用上的问题想请教，您建议打开"转换\n为换行"配置吗？

如果打开这个配置，肯定会非常方便，但是我又担心这种方式不通用，因为是在解析器级别解决的这个问题，和Markdown语法不符，所以很纠结，目前都没有打开这个选项。

**Comment by tamlok** [comment]
这个看个人喜好吧，我是关闭的。这样确保有最大的兼容性。在vnote里面`shift+enter`是插入两个空格并回车，所以也不是太不方便。

不过，个人记笔记的话，我一般都是直接多加一行空行，反正空行不用钱，多点间隙，结构也更清晰。

**Comment by wuscloud** [comment]
嗯，我明白了，多谢
