### ISSUE TITLE
md 文件缩放级别记忆问题

### ISSUE THREAD

**Issue by ly11tea** [tamlok/vnote#459]
OS Version (操作系统): Windows, Linux, macOS
macos（10.13.6） linux（deepin） 其他操作系统暂未测试
VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
对某个markdown文件进行鼠标滚轮缩放到非默认级别后 再次进入这个页面会自动变为最小缩放级别

How to Repro (如何复现):
见上文

**Comment by tamlok** [comment]
Hi,

因为用滚轮缩放是方便临时放大缩小的，比如展示的时候。如果要固定缩放，请到文件菜单中的设置对话框中进行调整。谢谢！
