### ISSUE TITLE
【misc需求】希望增加markdown实例文件

### ISSUE THREAD

**Issue by ly11tea** [tamlok/vnote#460]
希望在初始化日志的时候增加这个gallery里面的实例文件 
以及在snippet中增加一些默认的markdown高级些的语法示例
这样更方便新手吧
![image](https://user-images.githubusercontent.com/21007482/47226386-f6258300-d3f2-11e8-9265-7cb97ca98b53.png)

**Comment by tamlok** [comment]
Hi,

帮助菜单中有详细的语法指南，基本包含了所有的语法，都是带有示例的，可以参考一下。另外，帮助菜单也有快捷键的说明，如果希望掌握一些高阶的用法，推荐参考。

后面会考虑添加一个示例文档来展示所有语法元素。

谢谢！
