### ISSUE TITLE
vnote crash when switch to read-mode

### ISSUE THREAD

**Issue by bbsteel** [tamlok/vnote#461]
OS Version (操作系统): ubuntu 16.04

VNote Version (VNote版本): 2.0

Symptoms (表现):
When switch to read-mode, vnote will crash. I have attached the error-log and my system basic diagnose report. It seems that video card driver which I installed conflict with webbrowser: https://bugs.launchpad.net/ubuntu/+source/qtmir/+bug/1553328

Vnote log:
```
user config: "editor/key_mode" QVariant(QString, "1")
default config: "editor/enable_smart_im_in_vim_mode" QVariant(QString, "true")
default config: "editor/vim_leader_key" QVariant(QString, " ")
default config: "editor/enable_tab_highlight" QVariant(QString, "false")
nouveau: kernel rejected pushbuf: 没有那个文件或目录
nouveau: ch12: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch12: buf 00000000 00000002 00000004 00000004 00000000
nouveau: kernel rejected pushbuf: 没有那个文件或目录
nouveau: ch12: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch12: buf 00000000 00000002 00000004 00000004 00000000
nouveau: kernel rejected pushbuf: 没有那个文件或目录
nouveau: ch12: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch12: buf 00000000 00000002 00000004 00000004 00000000
VNote-2.0-x86_64.AppImage: ../../nouveau/pushbuf.c:727：nouveau_pushbuf_data: 假设 ‘kref’ 失败。
```

system basic log:
```
=========================================================================================================================
 NVIDIA Corporation G96M [GeForce 9650M GT]
OpenGL Vendor:  nouveau
OpenGL Renderer:  NV96
OpenGL Version:  3.0 Mesa 18.0.5
Client glx vendor:  Mesa Project and SGI
Client glx version:  1.4
Server glx vendor:  SGI
Server glx version:  1.4
GLX version:  1.4
OpenGLES PVS:  OpenGL ES 3.0 Mesa 18.0.5
OpenGLES PSLVS:  OpenGL ES GLSL ES 3.00
Kernel driver in use:  nouveau
Total Memory prefetchable: 16M - 32M - 
Total Memory non-prefetchable: 256M - 
Present resolution:     1920x1080 pixels (508x286 millimeters)
 minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192


=================================================== Machine =============================================================
Machine: x86_64

OS Type: Linux

Hostname: 

OS Release: 4.15.0-36-generic

Build Date: #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018

================================================ Installed Kernels ======================================================
S
vmlinuz-4.15.0-34-generic
vmlinuz-4.15.0-36-generic
===================================================== Cmdline ===========================================================
BOOT_IMAGE=/vmlinuz-4.15.0-36-generic root=UUID=060e2f03-f031-48e5-b0a0-1e6f72190286 ro verbose
```

**Comment by tamlok** [comment]
Would you mind to try declare environment variable `QT_OPENGL` and try the value `software` or `angle`, then launch VNote again.

**Comment by bbsteel** [comment]
> Would you mind to try declare environment variable `QT_OPENGL` and try the value `software` or `angle`, then launch VNote again.

unfortunately, neither `software` nor `angle` value for `QT_OPENGL` could work. Vnote still crash at switching mode.

`QT_OPENGL=software`

> default config: "editor/enable_tab_highlight" QVariant(QString, "false")
nouveau: kernel rejected pushbuf: 没有那个文件或目录
nouveau: ch8: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch8: buf 00000000 00000002 00000004 00000004 00000000
nouveau: kernel rejected pushbuf: 没有那个文件或目录
nouveau: ch8: krec 0 pushes 2 bufs 14 relocs 0
nouveau: ch8: buf 00000000 00000002 00000004 00000004 00000000
nouveau: ch8: buf 00000001 00000035 00000002 00000002 00000000
nouveau: ch8: buf 00000002 00000013 00000002 00000002 00000000
nouveau: ch8: buf 00000003 00000007 00000002 00000002 00000000
nouveau: ch8: buf 00000004 0000000a 00000002 00000002 00000000
nouveau: ch8: buf 00000005 0000000b 00000002 00000002 00000000
nouveau: ch8: buf 00000006 00000008 00000002 00000002 00000000
nouveau: ch8: buf 00000007 00000006 00000004 00000000 00000004
nouveau: ch8: buf 00000008 00000011 00000002 00000000 00000002
nouveau: ch8: buf 00000009 0000002b 00000004 00000004 00000000
nouveau: ch8: buf 0000000a 00000015 00000002 00000002 00000002
nouveau: ch8: buf 0000000b 00000048 00000004 00000004 00000000
nouveau: ch8: buf 0000000c 00000047 00000002 00000002 00000002
nouveau: ch8: buf 0000000d 00000041 00000002 00000000 00000002
nouveau: ch8: psh 00000000 00000085c4 00000088a4
nouveau:    0x0004721c
nouveau:    0x0fac6881
nouveau:    0x00086ff4

> ======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f80ba9667e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f80ba96f37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f80ba97353c]
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x54395c)[0x7f80a2bea95c]
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x543b47)[0x7f80a2beab47]
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x5d939f)[0x7f80a2c8039f]
/usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2(+0x3b8b)[0x7f80a2293b8b]
/usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2(+0x3e3f)[0x7f80a2293e3f]
/usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2(nouveau_pushbuf_kick+0x10)[0x7f80a2294a00]
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x5d9836)[0x7f80a2c80836]
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x257261)[0x7f80a28fe261]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x1c2cb14)[0x7f80b5e36b14]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x1bc9155)[0x7f80b5dd3155]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x1bc9278)[0x7f80b5dd3278]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x1b4ce81)[0x7f80b5d56e81]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x1b80fa8)[0x7f80b5d8afa8]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x1be441b)[0x7f80b5dee41b]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x1b39ec5)[0x7f80b5d43ec5]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x413fa08)[0x7f80b8349a08]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x4143209)[0x7f80b834d209]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x40c3e77)[0x7f80b82cde77]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x413d6d2)[0x7f80b83476d2]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x413d78e)[0x7f80b834778e]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x11edce3)[0x7f80b53f7ce3]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x11934e0)[0x7f80b539d4e0]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x11952ed)[0x7f80b539f2ed]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x11961e6)[0x7f80b53a01e6]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x1196529)[0x7f80b53a0529]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x11928e2)[0x7f80b539c8e2]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x11ae118)[0x7f80b53b8118]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x11c5d36)[0x7f80b53cfd36]
/tmp/.mount_VNote-EqKKSt/usr/bin/../lib/libQt5WebEngineCore.so.5(+0x11c1fed)[0x7f80b53cbfed]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f80b3b936ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f80ba9f641d]

`QT_OPENGL=angle`

> user config: "editor/key_mode" QVariant(QString, "1")
default config: "editor/enable_smart_im_in_vim_mode" QVariant(QString, "true")
default config: "editor/vim_leader_key" QVariant(QString, " ")
default config: "editor/enable_tab_highlight" QVariant(QString, "false")
nouveau: kernel rejected pushbuf: 没有那个文件或目录
nouveau: ch8: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch8: buf 00000000 00000002 00000004 00000004 00000000
nouveau: kernel rejected pushbuf: 没有那个文件或目录
nouveau: ch8: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch8: buf 00000000 00000002 00000004 00000004 00000000
VNote-2.0-x86_64.AppImage: ../../nouveau/pushbuf.c:727：nouveau_pushbuf_data: 假设 ‘kref’ 失败。

**Comment by bbsteel** [comment]
> I think it is caused by the nouveau driver. Same as #417. It seems that I can do nothing about this. :(

Yeah, after install NVIDIA proprietary  driver, crash problem is fixed.
