### ISSUE TITLE
预览界面文字渲染模糊

### ISSUE THREAD

**Issue by hzhu212** [tamlok/vnote#463]
OS Version (操作系统): Windows

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):

预览界面文字渲染模糊，所有文字都好像蒙上了一层阴影。如图：

> 抱歉，做成截图似乎不那么清楚了，在屏幕上直接看会非常明显。

![image](https://user-images.githubusercontent.com/19285447/47405631-0cca3200-d785-11e8-91a2-dadde97d529e.png)

仔细观察发现，大部分文字的周围都有 1px 的灰度描边，导致看起来模糊不清。

除了编辑窗口外，周围的目录窗口、大纲、菜单栏，虽然字体很小，但依然清晰锐利。所以应该不是电脑显示的问题。

后来我怀疑是字体问题，于是我就修改`v_pure.css`文件，换了多个字体，但没有明显的改善。

目前，只有把预览页面放大到非常大（大概是 300%），才能修复这个问题。作为对比，在浏览器上，13px 的中文微软雅黑已经可以渲染到非常锐利了。

所以，这是否可能是 Qt 组件渲染的问题？

How to Repro (如何复现):

预览任意 Markdown 文件。

**Comment by tamlok** [comment]
Fixed in 2.1. Please try it out. Thanks!
