### ISSUE TITLE
左侧笔记本上下布局能否设置为两竖列

### ISSUE THREAD

**Issue by agppp** [tamlok/vnote#466]
请问左侧笔记本和笔记现在是上下布局，在笔记本电脑上显示内容有限，能否设置为两竖列，可以看到更多的内容

**Comment by tamlok** [comment]
早期版本就是两列的，后面有说太碍地儿，就加了一个现在这样的紧凑模式，再后来就把原来两列的给删了。后面考虑加上吧。

另外，可以`ctrl-g m`使用通用入口来浏览当前文件夹的内容。

**Comment by heartnn** [comment]
还是喜欢原来的两竖列，现在显示器都是宽屏的，左右空间还是很富裕的，但上下就比较紧凑了。

**Comment by tamlok** [comment]
已经添加支持了。可以下载[最新构建版本](https://bintray.com/tamlok/vnote/vnote/2.1#files)

谢谢！

**Comment by agppp** [comment]
已经下载了2.1版本，如何进行设置呢？

**Comment by kerHbal** [comment]
![snipaste_2018-11-04_21-14-13](https://user-images.githubusercontent.com/11629684/47974215-ab546e00-e076-11e8-852e-dec468721b5a.png)

**Comment by agppp** [comment]
我下的VNote_win_X64_portable_2.1.zip，并没有这个按钮

**Comment by kerHbal** [comment]
用上面说的最新构建版本，这种小修改作者在等到下个版本的时候才会发到GitHub上来，理论上还是测试的版本

**Comment by agppp** [comment]
> 
> 
> 用上面说的最新构建版本，这种小修改作者在等到下个版本的时候才会发到GitHub上来，理论上还是测试的版本

没注意最新构建版不是github版，非常感谢

**Comment by kerHbal** [comment]
没事~
