### ISSUE TITLE
Windows下最新build显示问题

### ISSUE THREAD

**Issue by kerHbal** [tamlok/vnote#467]
OS Version (操作系统): Windows

VNote Version (VNote版本): 昨天更新的bintray

我看build又更新了就下下来看了看：）
然后发现在我的电脑上显示效果没有老版好，不知是不是我电脑显示的问题：
1. 控件变大了，这个感觉还好
2. 左侧文件夹目录的行高感觉太大了，占地方
3. 左侧文件夹目录的字体渲染感觉放弃治疗了。。。
4. 正文字体变大了，我需要在设置里调小才不显得占地方。。。

老版：
![snipaste_2018-10-26_11-17-49](https://user-images.githubusercontent.com/11629684/47575826-f224c400-d910-11e8-989a-2c75713a4ccb.png)
新版：
![snipaste_2018-10-26_11-18-23](https://user-images.githubusercontent.com/11629684/47576350-35cbfd80-d912-11e8-93b4-dce9db1a9296.png)

老版左侧字体：
![snipaste_2018-10-26_15-09-42](https://user-images.githubusercontent.com/11629684/47587583-5bb4ca80-d931-11e8-89e6-9b83d3d0cccd.png)

新版左侧字体：
![snipaste_2018-10-26_15-10-23](https://user-images.githubusercontent.com/11629684/47587591-5e172480-d931-11e8-80f5-d30d180ca8a7.png)

**Comment by tamlok** [comment]
Hi,

能麻烦测试一下pure主题有这样的变化吗？不知道是不是qt的版本升级了的祸。

**Comment by kerHbal** [comment]
貌似也变大了，字体也有问题
![snipaste_2018-10-26_21-04-52](https://user-images.githubusercontent.com/11629684/47597945-e661ed80-d962-11e8-990b-9a07549cf674.png)
![snipaste_2018-10-26_21-02-21](https://user-images.githubusercontent.com/11629684/47597947-e95cde00-d962-11e8-9da0-b1ab30355a56.png)
![snipaste_2018-10-26_21-06-43](https://user-images.githubusercontent.com/11629684/47597960-127d6e80-d963-11e8-9f99-b1f768346ff7.png)
![snipaste_2018-10-26_21-00-36](https://user-images.githubusercontent.com/11629684/47597962-14473200-d963-11e8-967f-481ec1f9db5c.png)

**Comment by kerHbal** [comment]
编辑模式字体大小没有变化但是渲染也出问题了
![snipaste_2018-10-26_21-11-23](https://user-images.githubusercontent.com/11629684/47598041-58870200-d964-11e8-98ce-4c2172216efb.png)
![snipaste_2018-10-26_21-12-12](https://user-images.githubusercontent.com/11629684/47598042-59b82f00-d964-11e8-9adc-f3987b29e00c.png)
![snipaste_2018-10-26_21-15-13](https://user-images.githubusercontent.com/11629684/47598044-5d4bb600-d964-11e8-9c0d-f80bdc17e507.png)
![snipaste_2018-10-26_21-14-43](https://user-images.githubusercontent.com/11629684/47598046-5e7ce300-d964-11e8-9f18-6a7e597dc6b3.png)

**Comment by tamlok** [comment]
您屏幕分辨率是多大？显示器尺寸呢？不知道是不是针对高分屏的优化带来了副作用。

**Comment by kerHbal** [comment]
@tamlok 是有可能，我的是14寸的 3200*1800 高分屏，Windows默认放大250%

**Comment by tamlok** [comment]
这样，你把`v_pure.qss`里面的`$`都替换成空格删除了，重启vnote，看看有没有问题：

类似于这种的，所有的`$`字符都删了：

```
QMainWindow::separator {
    background: @dock_separator_bg;
    width: $2px;
    height: $2px;
}
```

**Comment by kerHbal** [comment]
@tamlok 还是这样没有变化。这次的图都是新版的
![snipaste_2018-10-26_21-39-06](https://user-images.githubusercontent.com/11629684/47598300-08aa3a00-d968-11e8-8c87-19a29a0c0f04.png)
![snipaste_2018-10-26_21-40-34](https://user-images.githubusercontent.com/11629684/47598301-0c3dc100-d968-11e8-92e1-6ecd83e799ff.png)
![snipaste_2018-10-26_21-39-16](https://user-images.githubusercontent.com/11629684/47598302-0d6eee00-d968-11e8-9f6b-19623834ad68.png)
![snipaste_2018-10-26_21-40-05](https://user-images.githubusercontent.com/11629684/47598305-0ea01b00-d968-11e8-84bc-a7ec65ab95d7.png)

**Comment by tamlok** [comment]
其他程序的缩放是这样子的吗？

**Comment by kerHbal** [comment]
@tamlok 其他的没有，不太清楚还有什么程序是QT的

**Comment by kerHbal** [comment]
@tamlok 我用Windows系统自带的高DPI放大，override软件的放大，结果全糊了
![snipaste_2018-10-26_21-59-59](https://user-images.githubusercontent.com/11629684/47598521-b880a700-d96a-11e8-94f9-a46f2f9711ef.png)

**Comment by tamlok** [comment]
我尝试修复了，10分钟后你看看有没有新的build，现在正在build了。

其实，有可能目前这样的放大才是正确的，之前的都是我手工放大尺寸的。😂

**Comment by tamlok** [comment]
测试前记得把themes文件夹删除了，vnote会输出未修改的主题。

**Comment by tamlok** [comment]
是的，别太激进了。谢谢反馈呀！刚准备发布。

后面高分屏上有任何觉得奇怪的问题麻烦反馈一下哈。我一般外接显示器用，很少机会测试。
