### ISSUE TITLE
[需求] Vim mode: Insert Mode和Normal mode 更加明显的差异化

### ISSUE THREAD

**Issue by bbsteel** [tamlok/vnote#47]
感谢带来这么个优秀的markdown知识管理软件.

本来也想提的是vim mode 下insert和normal之间光标形状可以区分的建议, 见到在[这个issue](https://github.com/tamlok/vnote/issues/24)已经被提出, 而且解答了, 

其实我实质的需求是目前normal mode 和insert mode之间没有太明显的差异, 仅仅屏幕下方"正常"变为"插入", 太不显眼. 有时会忘了在normal模式, 而ctrl C 失败(这是另一个快捷键自定义的问题)

建议让两种模式更加的差异化, 抛砖引玉一下: 

- 插入模式光标闪烁, 正常模式光标停止
- 高亮行根据不同模式显示差异不大但能分辨的颜色.

**Comment by tamlok** [comment]
hi，下一个版本里面，当前行高亮色在正常模式是灰色，插入模式是紫色，可视模式是蓝色，区分度应该可以。

**Comment by bbsteel** [comment]
多谢！我认为现阶段加上你所说的功能应该足够了。
