### ISSUE TITLE
给个建议,自动让光标处于屏幕中间

### ISSUE THREAD

**Issue by wyhhh** [tamlok/vnote#471]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):类似Typora的那个什么模型,就是让光标永远定位在屏幕中间,因为如果不这样有时光标在最底下,要自己拉动屏幕,比较麻烦

How to Repro (如何复现):

**Comment by tamlok** [comment]
Fixed. Please try the [latest build](https://bintray.com/tamlok/vnote/vnote/2.1).
