### ISSUE TITLE
能不能出个快捷表格的模板?

### ISSUE THREAD

**Issue by wyhhh** [tamlok/vnote#473]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
表格一个个字符打太麻烦,可以先询问行和列数,然后直接出模板,就像typora类似

How to Repro (如何复现):

**Comment by tamlok** [comment]
2.2初步优化了表格，请更新尝试！快捷键会在后续添加。
