### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by wyhhh** [tamlok/vnote#475]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):虽然实时显示数学公式创意很好,但排版实在是太难看了,再加上软件整体UI设计,给人感觉难受.就是在设计方面对于一个软件也是非常必要的.回去再用typora觉得,真舒服,只是typora反映慢

How to Repro (如何复现):

**Comment by tamlok** [comment]
UI我就是在无能为力了，而且千人千面，大家处理Markdown的方式不一样而已。VNote也有自己的长处，比如全文搜索、通用入口、窗口分割和Vim快捷键等等。

数学公式可以在Markdown菜单里把原地预览关闭了。后面会添加一些细化的开关。

谢谢！

**Comment by kerHbal** [comment]
内容排版可以参考这个，并且不局限与这里说的，可以在网上找到很多类似的css主题。不过无法对公式排版产生影响：
http://sspai.com/post/43873 
至于UI，也可以自行定制但是就很麻烦了，我觉得native那个主题的UI就不错，简洁明了
