### ISSUE TITLE
拼音韵母声调显示问题

### ISSUE THREAD

**Issue by mshdyh** [tamlok/vnote#476]
OS Version (操作系统): Windows 10

VNote Version (VNote版本): 2.0 (最新)

Symptoms (表现):
如以下几个例子，liǔ、zuǒ、lǘ，会出现声调错位到拼音后面以及声调符号显示缺失的现象。编辑模式下是正常的。不知道是不是默认字体的原因。

How to Repro (如何复现):

**Comment by tamlok** [comment]
@kerHbal 有什么字体推荐吗？

**Comment by kerHbal** [comment]
@tamlok 对字体没有研究，之前为了省事我改CSS的时候把除了微软雅黑的都删了😂，现在发现排名第二个的英文字体也挺漂亮的

**Comment by tamlok** [comment]
Fixed. Please try the [latest build](https://bintray.com/tamlok/vnote/vnote/2.1).

**Comment by mshdyh** [comment]
升级了最新的2.1 问题还是存在，看了上面的对话，默默进入主题文件夹把css中Verdana和Helvetica的顺序换了
