### ISSUE TITLE
mathjax bug

### ISSUE THREAD

**Issue by AngryDisk** [tamlok/vnote#477]
OS Version (操作系统): Linux

VNote Version (VNote版本): Latest (最新) 2.0

Symptoms (表现):

![2jvbh8f k nn0v n6sjct](https://user-images.githubusercontent.com/6115495/47766746-51b51200-dd0b-11e8-9af5-a12d56847c78.png)

mathjax 的说明中是支持在 text中使用 $ $ 的 但是vnote 识别错误。

[mathjax 说明 13](https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference)

>Spaces MathJax usually decides for itself how to space formulas, using a complex set of rules. Putting extra literal spaces into formulas will not change the amount of space MathJax puts in: a␣b and a␣␣␣␣b are both ab. To add more space, use \, for a thin space ab; \; for a wider space ab.  \quad and \qquad are large spaces: ab, ab.
>
>To set plain text, use \text{…}: {x∈s∣x is extra large}. You can nest $…$ inside of \text{…}.

How to Repro (如何复现):

**Comment by tamlok** [comment]
Fixed. Please try the [latest build](https://bintray.com/tamlok/vnote/vnote/2.1).
