### ISSUE TITLE
增加更多的图像渲染，如：Wavedrom

### ISSUE THREAD

**Issue by MineFujiko** [tamlok/vnote#479]
OS Version (操作系统): Windows

VNote Version (VNote版本): Latest (最新)

愿求：希望能够增加[Wavedrom](https://wavedrom.com/)的支持。

以前，一直在VS CODE上使用[Markdown Preview Enhenced](https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/)插件，来写Markdown，其中，支持提供更强的Markdwon功能，尤其是更多的图像渲染。希望作者能够借鉴，或者直接移植过来，提升Markdown的功能。

最后，非常感谢作者能够提供如此好用的Markdown笔记软件。BEST WISHES!

**Comment by tamlok** [comment]
已经支持，下一个版本会带上。

谢谢！

**Comment by phdbreak99** [comment]
请问如何在markdown里面插入wavedrom？没有找到例子。谢谢
