### ISSUE TITLE
[需求] vim mode下能够自定义快捷键

### ISSUE THREAD

**Issue by bbsteel** [tamlok/vnote#48]
建议vim mode下能够对某些按键组合进行自定义, 最主要的就是常用到成为标准的 ctrl + c , ctrl + v.  (后者原本的功能我一般用ctrl+q代替)

一种思路是在vim mode下自定义快捷键

另一种思路是idea的vim插件: ideavim , 用户可以选择某些快捷键由IDE控制, 还是由vim 模式控制.

**Comment by tamlok** [comment]
Hi, 已经实现了通过配置来启用`Ctrl+C/V` (c2973d9e23eff6e1cd6931225eb6e92fbc05fdec)，将在下一个版本带上。

谢谢！
