### ISSUE TITLE
“从磁盘中重新加载”功能不起作用

### ISSUE THREAD

**Issue by tianxie** [tamlok/vnote#480]
OS Version (操作系统): Windows 10

VNote Version (VNote版本): 2.1

Symptoms (表现):

选中文件夹，右键点击“从磁盘中重新加载”，文件列表没有刷新。

How to Repro (如何复现):

使用文件资源管理器在VNote外部删除一条笔记，在VNote里使用“从磁盘中重新加载”功能，已经删除的笔记仍然在文件列表里。

**Comment by tamlok** [comment]
Hi,

1. “重新加载”是指重新读取`_vnote.json`文件；
2. 如果使用内部笔记本功能，请不要绕过VNote来管理文件，否则，请手动维护`_vnote.json`文件；
3. 如果有经常在VNote外部整理文件的需求，可以使用“浏览器”功能来浏览编辑外部文件，将VNote当作编辑器使用，此时，标签和附件不起作用。

现在，可以手动在文件列表里面删除该不存在的文件即可。

谢谢！

**Comment by tianxie** [comment]
明白了，感谢回复！
