### ISSUE TITLE
Mathjax 两只虫

### ISSUE THREAD

**Issue by kerHbal** [tamlok/vnote#481]
Windows
VNote Version: Latest (Nov 02, 2018)

1. 这个可能不是bug，`$$...$$` 前面需要空一行否则无效
2. DPI放大的bug，在阅读模式下右键Mathjax的公式
![snipaste_2018-11-02_11-15-19](https://user-images.githubusercontent.com/11629684/47923736-9ae29e80-de90-11e8-8aab-dd42c76c7613.png)

**Comment by tamlok** [comment]
- 需要空一行是因为这是一个块元素；
- 那个右键菜单是mathjax的，暂时不管了啦。

谢谢！
