### ISSUE TITLE
Firefox and OneNote stopped working

### ISSUE THREAD

**Issue by jspille** [tamlok/vnote#483]
OS Version (操作系统): Windows 10 - No Admin Rights - Company configuration

VNote Version (VNote版本): Latest 2.1 portable - No install rights

Symptoms (表现):

> If vnote is running and I open/close Firefox and/or Microsoft OneNote an Error occurred.
"Firefox/Onenote stopped working" 

> If vnote is **not** running, everything is normal.

How to Repro (如何复现):

> Start vnote and open/close Firefox and/or Microsoft OneNote one to three times.

**Comment by tamlok** [comment]
Hi,

This is weird. Try to update the display card driver or declare `QT_OPENGL=angle`?

You could reference the [FAQs](https://vnote.readthedocs.io/en/latest/user_docs/faqs.html#menu-does-not-work-in-fullscreen-mode) here.

Thanks!
