### ISSUE TITLE
阅读模式是空白的，不显示内容

### ISSUE THREAD

**Issue by immikez** [tamlok/vnote#486]
OS Version (操作系统): Windows, Linux, macOS
Linux
VNote Version (VNote版本): Latest (最新)
Latest
Symptoms (表现):
编辑模式正常，但是阅读模式是空白的，如何解决？

How to Repro (如何复现):

**Comment by tamlok** [comment]
arch?自行编译？appimage?

**Comment by immikez** [comment]
archlinux
yay 或是 yaourt安装的。
________________________________
发件人: Le Tan <notifications@github.com>
发送时间: 2018年11月6日 4:04
收件人: tamlok/vnote
抄送: immikez; Author
主题: Re: [tamlok/vnote] 阅读模式是空白的，不显示内容 (#486)


arch?自行编译？appimage?

―

**Comment by tamlok** [comment]
https://github.com/tamlok/vnote/issues/258

建议下载appimage或者自行5.9编译。

**Comment by tamlok** [comment]
已经修复 (https://github.com/tamlok/vnote/commit/bda9bf51c18bd9a5a1f85bb8c54118126efe7ef8)。
