### ISSUE TITLE
代码中有空行时，编辑模式下格式有问题

### ISSUE THREAD

**Issue by l0o0** [tamlok/vnote#487]
![default](https://user-images.githubusercontent.com/2743744/48054071-51bf8100-e1e7-11e8-90fe-369bcfa8c27a.png)

如果把37行的空行去掉，
![default](https://user-images.githubusercontent.com/2743744/48054096-64d25100-e1e7-11e8-9871-ed8d0cfcac78.png)

**Comment by l0o0** [comment]
@tamlok 不好意思啊，想不到是我的不规范。。。。

**Comment by tamlok** [comment]
没事，不同的编辑器使用的语法不太一样而已
