### ISSUE TITLE
希望能够识别带有空格的笔记标题

### ISSUE THREAD

**Issue by IanGoo** [tamlok/vnote#488]
OS Version (操作系统): Windows, Linux

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
希望能够识别带有空格的笔记标题。
好像现在在标题中出现空格的话，无法使用`[]()`的方式直接链接。似乎作者的意思是希望用户全部使用下划线来代替空格？不过作为非程序员实在是没有这个习惯。。这样的话，就需要在引用链接的时候手动插入%20替代空格，使用起来还是挺费劲的(敲%手容易抽筋doge)。
之前用的另一个PKM是Zim，它其实也不直接支持页面标题带空格，但是它对链接里的空格做了自动识别，将它等同为下划线处理。文件名依然是new_page.txt但是在别的页面里使用[[new page]]依然是识别到这个new_page.txt当中。
Zim上的其他一些闪光点
Zim带有浓重的Dokuwiki的风格，做PKM是非常给力的——奈何Bug满天飞于是弃用。有一些功能要是能够实现的话那就真的绝赞了。

- 插入链接的时候不用输入`.md`
- 在某个笔记中使用超链接链接到某个不存在的笔记的时候，可以出现在笔记列表当中(当然该笔记并不存在)。
- 某个笔记删除或者更名之后，反向链接到该笔记的链接也相应删除或者更名

嗯……基本上是Wiki的思路。如果能实现的话，Zim的作者可能会哭……吧……

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

- URL是规定空格必须使用`%20`来转义的。
- VNote的设计理念是一切都开放，即使使用一个普通的编辑器也能方便地编辑和管理VNote的笔记；所以使用的Markdown语法也主要都是基本语法，为了可移植性，VNote不能忽略`md`后缀以及私自替换空格为下划线之类的。

在VNote中，要插入文件链接，可以参考以下方法：

1. 将外部文件插入为附件，并插入到该附件的链接到笔记中。这可以通过直接拖拽文件到编辑区域完成，或者复制一个文件，然后在VNote中粘贴，VNote会提示对应的动作。
2. 插入一个到笔记本中另外一个笔记的链接。这可以通过插入相对路径的链接来完成。在笔记列表中，右键菜单，复制文件路径，然后粘贴到VNote的编辑区域，选择作为相对路径插入，即可。VNote会自动处理空格。

至于，链接的后期维护和更新，这一块暂时还没开发。但是由于使用的是非数据库，而且用户能绕过VNote来管理笔记，所以在一致性维护方面还需要设计。

谢谢关注！

**Comment by IanGoo** [comment]
> 
> 
> Hi,
> 
>     * URL是规定空格必须使用`%20`来转义的。
> 
>     * VNote的设计理念是一切都开放，即使使用一个普通的编辑器也能方便地编辑和管理VNote的笔记；所以使用的Markdown语法也主要都是基本语法，为了可移植性，VNote不能忽略`md`后缀以及私自替换空格为下划线之类的。
> 
> 
> 在VNote中，要插入文件链接，可以参考以下方法：
> 
>     1. 将外部文件插入为附件，并插入到该附件的链接到笔记中。这可以通过直接拖拽文件到编辑区域完成，或者复制一个文件，然后在VNote中粘贴，VNote会提示对应的动作。
> 
>     2. 插入一个到笔记本中另外一个笔记的链接。这可以通过插入相对路径的链接来完成。在笔记列表中，右键菜单，复制文件路径，然后粘贴到VNote的编辑区域，选择作为相对路径插入，即可。VNote会自动处理空格。
> 
> 
> 至于，链接的后期维护和更新，这一块暂时还没开发。但是由于使用的是非数据库，而且用户能绕过VNote来管理笔记，所以在一致性维护方面还需要设计。
> 
> 谢谢关注！

Hmm我想，绕过VNote直接在笔记目录里折腾的用户应该有“自己乱折腾会一团糟”的觉悟……吧……
我刚刚试了一下，如果直接用第三方MD编辑器打开笔记文件的话，Typora可以直接使用带有空格的文件名，应该是对空格做了解析，像是`[Honda NSX](Honda NSX.md)`这样的超链接就能够正常跳转，而VSCode就必须加上`%20`。
或者考虑加个开关和警告？
不知道像我这样把笔记软件当个人Wiki来用的比例占到多大，在这种大量有链接而且链接地址自己都很清楚的时候的使用场合当中直接手不离键盘敲`[...](xxx.md)`的速度比复制文件名然后让软件自己转换空格为`%20`再插入到笔记当中的效率要高得多，这也是我从Zim切换到VNote之后遇到的最大的痛点了。
现在正在靠AHK顶着。。。

**Comment by tamlok** [comment]
Hi,

Typora的语法本身就不是很标准主流的那种。

这个改动涉及到底层语法解析，暂时先不改吧。后面看能不能通过插件的形式来支持吧。

目前，你可以试试用片段功能，一个快捷键插入`%20`，例如`Ctrl+E S S`之类的。

谢谢！
