### ISSUE TITLE
请问如何添加标签？

### ISSUE THREAD

**Issue by agppp** [tamlok/vnote#489]
请问如何添加标签？

**Comment by kerHbal** [comment]
![2](https://user-images.githubusercontent.com/11629684/48173286-1a2d0380-e2d1-11e8-9223-1f3f83b14b1b.gif)

**Comment by roachsinai** [comment]
如果一个标签下面只有一个文章，然后将这个文章的标签删除的话，`vnote`中仍然保留了那个标签，不会自己消失，是这样么？
