### ISSUE TITLE
openSUSE leap42.3 使用fcitix输入法无法输入中文

### ISSUE THREAD

**Issue by zzndb** [tamlok/vnote#49]
因为官方源里 qt 版本未到5.7， 便自行下载了[tuna源](https://mirrors.tuna.tsinghua.edu.cn/#)提供的 qt5.91 自行按照wiki编译  

并且参照了另一个已关闭的issue**添加了系统`/usr/lib64/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`文件**到指定的qt5.91目录

编译安装之后任然无法输入中文。

**Comment by tamlok** [comment]
Hi, 您用的是fcitx输入法吗？fcitx的版本是多少呢？有可能是tnua提供的qt5.91依赖的fcitx版本和您系统上的不对应。这种情况可能需要自行编译fcitx。

您试过AppImage运行吗？

谢谢反馈！

**Comment by zzndb** [comment]
嗯，自行编译fcitx-qt5后完美解决中文输入问题，谢谢
