### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by woniuxia** [tamlok/vnote#494]
提个小建议。
能否将一份笔记的图片放在一个文件里面。
而不是把一个笔记本的图片放在一起。
感觉浏览图片的时候稍有麻烦。
作者辛苦了。十分感谢。

**Comment by tamlok** [comment]
hi,

每个笔记的图片单独放在一个文件夹里面，会使得图片链接比较复杂，而且文件夹过多。代码改动较大，暂时先不改动了。

谢谢！

**Comment by woniuxia** [comment]
好的，谢谢。
还有个问题，我看您有优化表格的计划，大概什么时候会完成？

**Comment by tamlok** [comment]
生活所逼，😂，这个得明年了啦。

**Comment by woniuxia** [comment]
好的，辛苦作者大大。

**Comment by woniuxia** [comment]
![image](https://user-images.githubusercontent.com/16383685/48414368-77b7c900-e785-11e8-8a3e-ff5a07465d7b.png)
老哥看下这个问题。

**Comment by tamlok** [comment]
https://vnote.readthedocs.io/en/latest/user_docs/faqs.html

按照这里的最后一个问题进行处理，声明一个环境变量。

**Comment by woniuxia** [comment]
老哥，没成功。能帮忙看看吗？需要提供些什么信息吗？
# Vnote
export QT_OPENGL=software

**Comment by tamlok** [comment]
才注意到不是Windows。。。

说一下详细环境，显卡之类的吧。

**Comment by woniuxia** [comment]
系统: deepin 15.7
显卡：Intel Corporation HD Graphics 530

**Comment by tamlok** [comment]
appimage吗？vnote的版本？

**Comment by woniuxia** [comment]
用的最新版本的：VNote-2.1-x86_64.AppImage

**Comment by tamlok** [comment]
重置一下布局看看吧，暂时不清楚了~第一次听说这个问题。

**Comment by woniuxia** [comment]
![image](https://user-images.githubusercontent.com/16383685/48470277-f2d3ba80-e82b-11e8-9de1-5822799bdaf1.png)

重置后第一次移动没问题。再重启，打开又不行了额
