### ISSUE TITLE
【故障】将笔记下一个md文件拖动到文件夹区域时候，VNote崩溃，必现

### ISSUE THREAD

**Issue by yiltoncent** [tamlok/vnote#495]
OS Version (操作系统): Windows, Linux, macOS
Windows X86

VNote Version (VNote版本): Latest (最新)
V2.1
Symptoms (表现):
将左侧笔记栏的某一个md文件拖到文件夹区域，放开鼠标，VNote出现崩溃，必现

How to Repro (如何复现):
如上

**Comment by tamlok** [comment]
已经修复！谢谢@kerHbal
