### ISSUE TITLE
【需求】vim 可以选择使用系统剪贴板

### ISSUE THREAD

**Issue by colorwin** [tamlok/vnote#499]
OS Version (操作系统): macOS

VNote Version (VNote版本): 2.1

Symptoms (表现):

![image](https://user-images.githubusercontent.com/11376543/48405545-69f64980-e76d-11e8-96fa-2c6f25373171.png)
希望 vim 模式支持使用系统剪贴板

**Comment by tamlok** [comment]
请使用`"+`指定使用剪切板寄存器，如`+yp`。

快捷按键为`Space-P`，具体请参考帮助菜单中的快捷键帮助。

谢谢！

**Comment by colorwin** [comment]
> 请使用`"+`指定使用剪切板寄存器，如`"+y`。
> 
> 快捷按键为`Space-y`，具体请参考帮助菜单中的快捷键帮助。
> 
> 谢谢！

谢谢这么快回复，有这个快捷键确实方便一点。如果能支持直接使用系统剪切板就更好了，写笔记经常需要从系统外面复制东西。

**Comment by colorwin** [comment]
> 直接支持会很混乱，容易丢失系统剪切板的内容，因为vim里面随便删除一些字符也会覆盖剪切板。
> 
> 可以鼠标右键粘贴，或者ctrl-v，这样也是直接操作系统剪切板。

我在原生 vim ，还有 Atom 等编辑器的 vim 插件都是直接用系统剪切板的。至于"vim里面随便删除一些字符也会覆盖剪切板"，这个后果是预料之中的，个人并没有觉得混乱，在我上述的编辑器也都是这个结果。我相信对于愿意选择 vim 使用系统剪贴板的人都会接受这一点。

ctrl-v 需要先进入 insert 模式。不如 normal 模式 `p`  自然。 vnote 下经常从系统复制了，`p`一下发现错了，然后 `u` `i` `ctrl-v`。

**Comment by tamlok** [comment]
直接space-p就好了，还是顺手的。

vim的实现主要都是根据我的使用习惯来搞得，所以可能个人风格浓了一点。后面有时间会考虑添加更多配置。

谢谢！
