### ISSUE TITLE
希望能够自定义渲染效果

### ISSUE THREAD

**Issue by NathanIceSea** [tamlok/vnote#5]
非常喜欢基于文件系统的资源管理目录，用惯了Scrivener实在不能更赞

不过我注意到由于**缺乏css自定义渲染以及字体等选项**，无论是编辑界面还是预览界面似乎都不足够友好
不知道作者有没有在这方面做些改进的意愿呢...

不过总之，是相当不错的软件，加油！

（不知何年何月C++才能学到可以看源码...Orz）

**Comment by tamlok** [comment]
你好！谢谢使用！

VNote实现时也是通过类似CSS等文件来定义样式的，目前只是内部指定并嵌套到EXE中，所以要自定义是一件很简单的事情。后面肯定会添加自定义选项的，请放心！

可以加入Q群(487756074)哈～欢迎多多反馈！

谢谢！

**Comment by tamlok** [comment]
您好，现在支持编辑和阅读模式的样式自定义了。将对应的样式文件拷贝到指定文件夹即可！

30ee1e92d8301449c49ec970be2a52fa55c668c7
