### ISSUE TITLE
插入图片对话框中title可不可以空着

### ISSUE THREAD

**Issue by heartnn** [tamlok/vnote#50]
虽然默认image没什么，空着还是习惯了。不知道这算bug吗？

**Comment by tamlok** [comment]
不算Bug吧，title可以在阅读的时候在图片下方作为标题显示。

我已经修改了代码，后面可以支持空标题，默认也是空标题。敬请关注新版！

谢谢反馈！

**Comment by heartnn** [comment]
多谢指导。
