### ISSUE TITLE
Undo not working...

### ISSUE THREAD

**Issue by biffster** [tamlok/vnote#500]
OS Version (操作系统): Windows, Linux, macOS
Linux Mint (Sylvia), XFCE. Also tried with 

VNote Version (VNote版本): Latest (最新)
2.1 AppImage

Symptoms (表现):
Using VIM mode, cannot undo. Tried both :u (which generates  "Not an editor command :u" ) and CTRL+Z (no error returned), neither worked. This was occurring in the 2.0 AppImage also.

How to Repro (如何复现):
Type a few letters on a line, type "<esc>dd" to delete that line, then type :u - this should undo the last change and put the line back. 
Type a few letters on a line, type "<esc>dd" to delete that line, then press <CTRL>-z.  This actually  shouldn't work since I'm in vim mode, but I wanted to try since :w was not working.

**Comment by tamlok** [comment]
As far as I know, undo in Vim is pressing `u`, redo is `ctrl-r`.

Command line mode in Vim is poor supported in VNote.

Thanks!

**Comment by biffster** [comment]
I'll be damned, you just taught me something about vim! All these years I've been using it, I thought that undo was ":u". I didn't know it was just "u" until your reply. Imagine all those wasted key presses for the unnecessary colons.  :smiley:
