### ISSUE TITLE
如何设置标题快捷键

### ISSUE THREAD

**Issue by YeomanYe** [tamlok/vnote#501]
OS Version (操作系统): Windows, Linux, macOS
Windows10最新版本
VNote Version (VNote版本): Latest (最新)
VNote最新版 2.1

设置标题有快捷键吗，就是对于h1~h6的标题能用快捷键敲出来吗，在编辑模式下

**Comment by tamlok** [comment]
Hi,

帮助菜单里面有个快捷键帮助文档，请参考一下。

`Ctrl+1`

**Comment by YeomanYe** [comment]
好的，谢谢
