### ISSUE TITLE
通用入口没有反应

### ISSUE THREAD

**Issue by YeomanYe** [tamlok/vnote#502]
OS Version (操作系统): 
win 10最新版
VNote Version (VNote版本): Latest (最新)
vnote 2.1
Symptoms (表现):
通用入口没有反应，使用ctrl + g显示了通用入口。输入内容回车后，没有返回结果

How to Repro (如何复现):
一台win10最新系统 + vnote2.1

![qq 20181115132139](https://user-images.githubusercontent.com/18027354/48532207-646a4200-e8da-11e8-980c-54ef84c662ef.png)

**Comment by tamlok** [comment]
Hi，

得根据提示，再按一个按键，然后直接输入内容，比如搜索当前笔记本的笔记名，需要先按一个`e`，然后再输入内容，即开始搜索，不用回车。

**Comment by YeomanYe** [comment]
好的，谢谢大佬
