### ISSUE TITLE
支持多行编辑吗？

### ISSUE THREAD

**Issue by YeomanYe** [tamlok/vnote#504]
OS Version (操作系统): Windows, Linux, macOS
win10
VNote Version (VNote版本): Latest (最新)
vnote 2.1
Symptoms (表现):
不知道如何进行多行编辑，目前编辑器支持多行编辑吗？

**Comment by tamlok** [comment]
不支持，可以设置快捷键调用外部编辑器进行编辑。

**Comment by YeomanYe** [comment]
那怎么用快捷键打开外部编辑器呢？

**Comment by tamlok** [comment]
笔记列表里面，一个笔记上面右键，打开，添加外部程序。

多看看各种菜单即可。

**Comment by YeomanYe** [comment]
噢噢，好的，谢谢

**Comment by MrLoading** [comment]
使用体验非常棒了,希望能添加多行编辑功能,如果有按Ctrl选择多焦点/按Alt选择整列 就完美了.
