### ISSUE TITLE
一些不成熟的建议

### ISSUE THREAD

**Issue by YeomanYe** [tamlok/vnote#505]
- 使用其他编辑器打开文档，不在vnote中关闭。或者提供个设置选项可以设置为不在vnote中关闭
- 其他编辑器保存后vnote直接更改，不出提示进行选择是否加载，或者加个配置项。让用户选择是否提醒。
- 添加列表项快捷键，就是选中文本后，在每一段的开头加上`-`符号或者序列数字。

**Comment by tamlok** [comment]
Hi,

- 请参考[配置](https://github.com/tamlok/vnote/blob/64d2aab76a58f1744655c25d55d25e375400ca03/src/resources/vnote.ini#L201)，添加到`vnote.ini`；
- 这是个不好的特性，文件有改动，用户还是得清楚才好，不然就乱了；
- 这个等后面插件吧；

谢谢！
