### ISSUE TITLE
介绍里只有vim没有emacs好影响emacser的情感

### ISSUE THREAD

**Issue by coding-master-1** [tamlok/vnote#506]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):

作为一个6年多的emacs用户，觉得你们这个编辑器是我见过最好看最正常的了！

可是你们的介绍竟然是vim……觉得好不开心，有种迷之敌意。。

能不能换个title 而且不要vvv啥的。。

比如 the most friendly editor take the advance over vim or emacs 之类的？（不会被打的吧 = =）

How to Repro (如何复现):

不知道是不是只有我一个emacser会这样子

**Comment by Kinka** [comment]
maybe you've got the wrong tickets. this is train is boun for VIM world.

**Comment by coding-master-1** [comment]
> vnote是根据我在vim中的使用经验来设计和开发的，所以都会带上v。
> 
> 我对emacs不是很熟悉，添加一套额外的快捷键绑定可能需要一点时间。
> 
> VNote loves emacs!

快捷键绑定什么的我已经放弃了……跟着你们我没意见。。

最近跟一些其他圈子的程序员聊天，发现不同的工具链（teams，环境，工作经历……）下面的（或者说上面的人）的common sense是不同的 TwT 

Aesthetics 是支持你们的！（虽然我只是个小屁孩……）但是 Common Sense 上面做 Context Switch，还是颇费功夫啊（这是我想指出的为什么文案影响了我的感情的原因……）

我会继续关注你们的更新的！     ：-P

**Comment by tamlok** [comment]
文案已经没有vim了😂
