### ISSUE TITLE
Glitchy PUML preview in edit mode

### ISSUE THREAD

**Issue by 49616e** [tamlok/vnote#508]
OS Version (操作系统): Linux, openSUSE Tumbleweed

VNote Version (VNote版本): Latest (2.1)

PlantUML Version: 2018.12

Symptoms (表现):
All PUML previews in edit mode are glitchy, but the diagrams show up just fine in read mode.
![image](https://user-images.githubusercontent.com/39971507/48676456-2c952000-eba2-11e8-9e55-a4d0588fd226.png)

![image](https://user-images.githubusercontent.com/39971507/48676468-6403cc80-eba2-11e8-977f-6adc1416a180.png)

How to Repro (如何复现):
Enter edit mode and write a PUML code snippet. 

By the way, I'm unable to reproduce this bug on Fedora 29 (gnome on wayland, with the exact same binaries of vnote and plantuml). It only happens on my openSUSE + KDE machine for some reason.

**Comment by tamlok** [comment]
I am using openSUSE and KDE, too. However I could not repro it. Is your display card integrated or not? What is the driver?

Thanks!

**Comment by 49616e** [comment]
I'm using a hybrid setup (laptop), but I believe the system is using the integrated Intel HD 530 right now, because I never bothered to install the proprietary driver for the Nvidia card. The discrete graphics card is running with nouveau if that matters.

**Comment by tamlok** [comment]
Can you test it by adding a background directive in your uml definition, such as a white background?

**Comment by 49616e** [comment]
![image](https://user-images.githubusercontent.com/39971507/48921416-9d0dab00-eeda-11e8-92cd-924a3f624835.png)

Tried both monochrome and white background, didn't really make a difference unfortunately.

**Comment by tamlok** [comment]
I can repro this in `v_pure` theme. Are you using this theme? I will investigate it. You could now switch to `v_detorte` theme to see if that still exists.

Thanks!

**Comment by 49616e** [comment]
Yes, I was using vpure (since it's the default), switching the theme to vdetorte resolved the issue. Thanks for the suggestion.
![image](https://user-images.githubusercontent.com/39971507/48964730-d92f3180-efe8-11e8-9689-e89c8bcfc3b5.png)

P.S. The more I try to tinker with it, the more trippy the preview gets. 
![image](https://user-images.githubusercontent.com/39971507/48964722-c3ba0780-efe8-11e8-91a8-1a1ec8d3e2d8.png)

**Comment by 49616e** [comment]
Thanks for the quick fix, closing for now. :)
