### ISSUE TITLE
【需求】增加文件名搜索

### ISSUE THREAD

**Issue by heartnn** [tamlok/vnote#51]
不奢求全文搜索，但是没发现任何搜索功能，希望至少能搜索文件名。

**Comment by tamlok** [comment]
搜索功能是一个非常重要的功能，后面会设计并实现，还得等一段时间。
目前一个方法是使用诸如ag/find/grep等外部搜索工具，直接搜索笔记本对应的文件夹。
谢谢！

**Comment by heartnn** [comment]
windows用户泪奔了，没办法装了个everything。

**Comment by tamlok** [comment]
@heartnn ag是跨平台的，在win下能正常使用，速度还挺快的。我Vim都是默认配置ag来搜索。

**Comment by heartnn** [comment]
@tamlok 多谢推荐，去试试看
