### ISSUE TITLE
标签tag的小bug

### ISSUE THREAD

**Issue by kerHbal** [tamlok/vnote#511]
OS Version (操作系统): Windows

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
标签输入框残留，切换笔记后之前输入的标签单词还在

How to Repro (如何复现):
首先给任意笔记添加一个标签macOS,此步是让系统内有此标签
然后新建一个笔记，用自动补全的功能添加标签（输入m，方向键上，回车）可见输入框已经有残留了
![2018-11-19_10-01-11](https://user-images.githubusercontent.com/11629684/48715092-3474b480-ebe2-11e8-9af3-39bbd64693e9.gif)
然后切换到一个没有标签的笔记，右下角还有残留
![image](https://user-images.githubusercontent.com/11629684/48715146-566e3700-ebe2-11e8-8a6a-815d362a749c.png)

**Comment by tamlok** [comment]
已经修复，谢谢！
