### ISSUE TITLE
从搜索结果打开笔记的时候总是以编辑模式进入？

### ISSUE THREAD

**Issue by IanGoo** [tamlok/vnote#512]
OS Version (操作系统): Windows, Linux,

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
从搜索结果列表中双击打开的时候总是以编辑模式打开笔记。是否可以修改成跟随`设置-Markdown-打开模式`。目前我的这个选项是设置成的阅读模式，在笔记列表中打开是没问题的，但是从搜索结果列表打开一直都是以编辑模式进去，还需要多按一下`Ctrl-T`。

How to Repro (如何复现):

**Comment by IanGoo** [comment]
主要考虑到从搜索模式找某条笔记，一般是想要阅读其中的内容吧，似乎阅读模式用得会更多一些。

**Comment by tamlok** [comment]
hi,

设置里面的杂项有一个选项可以关闭。如果关闭，将不会在阅读模式里面高亮搜索结果。

谢谢！

**Comment by IanGoo** [comment]
> 
> 
> hi,
> 
> 设置里面的杂项有一个选项可以关闭。如果关闭，将不会在阅读模式里面高亮搜索结果。
> 
> 谢谢！

😲😲😲原来这样……
