### ISSUE TITLE
打开文件后编辑界面假死

### ISSUE THREAD

**Issue by Lisuaki** [tamlok/vnote#513]
OS Version (操作系统): Windows 1809 LTSC

VNote Version (VNote版本): 2.1 x64/x86 (最新)

Symptoms (表现):
新建文件后编辑完毕后保存，用阅读模式打开没问题，但是用编辑模式打开后软件就假死了。

假死这个说法比较含糊，具体情况是：
1.文本编辑区保持文件打开的状态静止不动，光标也不闪烁，进行任何操作界面都不会变化，但是编辑的话虽然不会显示但是实际上是正常编辑的；
2.此时拉伸窗口的话界面和文字都会像图片一样被拉伸变形；
3.除了文本编辑区外的所有按钮都能正常点击并响应功能，文本编辑区也可以正常右键；
4.右键选择“**图表实时预览**”，然后软件恢复正常，取消“**图表实时预览**”又会恢复假死状态，只要开着“图表实时预览”的话就能正常运行，顺便ctrl+E没用；
5.不是文件的问题，自带的readme.md打开照样也这样，文件路径换了也没用，软件所有设置啊渲染器选择主题啥的改了都没用，x86x64都一样，文件夹里的vcredist安了也没用。

总之说白了就是编辑模式打开文件，界面就死机了。不是程序员啊我也不知道到底描述清楚了没orz

How to Repro (如何复现):
打开已有文件就会这样，次次都会没有例外= =

**Comment by tamlok** [comment]
Hi,

Windows的显卡驱动问题。可以参考文档 https://vnote.readthedocs.io/zh_CN/latest/user_docs/faqs.html#

建议添加一个环境变量`QT_OPENGL`，值为`angle`。然后重启VNote，应该就解决了。下一个版本会在设置中添加对应的选项。

谢谢！

**Comment by Lisuaki** [comment]
哇回复得好快！居然有doc还写的这么清楚orz是我没仔细多找找就贸然写issue打扰大大了，惭愧惭愧

照着方法用了下果然完美的解决了呢（撒花感谢*★,°*:.☆(￣▽￣)/$:*.°★* 。

**Comment by tamlok** [comment]
@Lisuaki 我上面是指你的问题描述得很详细，可以作为issue的典范～谢谢～
