### ISSUE TITLE
alert语法似乎无效

### ISSUE THREAD

**Issue by kerHbal** [tamlok/vnote#514]
OS Version (操作系统): Windows

VNote Version (VNote版本): Latest build from bintray.com

Symptoms (表现):
需要有别的设置吗？已经启用markdown-it
![2018-11-22_19-26-01](https://user-images.githubusercontent.com/11629684/48924968-acfe9e00-ee8c-11e8-958c-2fa3929b2cae.gif)

**Comment by tamlok** [comment]
把配置文件夹下面的resources删了，重启vnote。

**Comment by kerHbal** [comment]
@tamlok 哦哦可以啦！
