### ISSUE TITLE
图片插入BUG

### ISSUE THREAD

**Issue by kangjianwei** [tamlok/vnote#515]
OS Version (操作系统): Windows 10

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):

插入图片时，无法识别带空格的路径。

**Comment by tamlok** [comment]
Hi,

请具体描述操作和问题。

如果是自行插入图片，请在路径里面将所有空格替换为`%20`。如果是通过VNote的插入图片插入，一般来说不会有这个问题。请具体说明一些，以确定是不是bug。

谢谢！

**Comment by kangjianwei** [comment]
### 对于自行插入图片，想看到效果，需要满足：

1. 路径不能包含空格，如果存在空格，需使用`%20`代替，有几个空格使用几个`%20`;
2. 路径使用斜杠`/`，而不是反斜杠`\`.

针对第一条：这样操作太麻烦了，每次得手动输入`%20`。
针对第二条：windows上复制的路径是反斜杠`\`，这意味着也得手动改成斜杠`/`后才能显示，非常麻烦。

### 对于VNote工具栏插入图片：

使用此功能后，会在资源文件夹下创建一个_v_images文件夹，并把待插入的图片复制了一份到_v_images里，并且图片的名字也变成一串数字...抓狂...

**所以，两个插入方案都不尽人意...**

**Comment by tamlok** [comment]
1. 关于空格和斜杠的限制都是标准URL的限制。
2. 通过VNote插入图片，意味着VNote管理图片，所以图片命名尽量都是无冲突的随机命名。
3. 您的应用场景可以在复制图片然后在vnote里面粘贴（或者直接拖放到VNote中），VNote会弹窗提示，这时候选择插入相对路径，然后手动在前面加上一个`!`即可。

谢谢！

**Comment by kangjianwei** [comment]
好的好的，感谢耐心回答，看来只能拖放了...

谁让我是强迫症...

**Comment by tamlok** [comment]
增加了“插入相对图片链接”的功能，能解决你这个问题，直接拖拽或者复制图片后粘贴即可。
