### ISSUE TITLE
【功能改进】图片插入

### ISSUE THREAD

**Issue by kangjianwei** [tamlok/vnote#516]
OS Version (操作系统): Windows 10

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
从工具栏选择插入图片时，点击"浏览文件"按钮，默认进入的是C盘的用户目录。
是否可以更改为默认进入当前文档目录，且记忆上次打开的目录？

**Comment by tamlok** [comment]
Hi,

成功插入一张图片后，VNote应该是会记忆该位置的。重启VNote，该记忆会失效。请具体描述复现步骤。

对于内部笔记来说，一般插入的图片都不会来自和笔记同目录，所以默认是用户文档目录。

谢谢！

**Comment by kangjianwei** [comment]
个人习惯是将文档本身和文档所需的资源放在一个文件夹。

所以才建议首次插入图片时，可以直接定位到文档本身的路径，这样插入资源就方便了。

如果这个功能不是大众化的需求，那么要是能增加一个定制选项就好了...

另外可否定制默认的资源目录，而不是每次都进入用户目录...

**Comment by tamlok** [comment]
所以，您是使用VNote编辑外部文件，而不是使用内建的笔记本管理？

后面可以考虑判断如果是外部文件，则直接定位到文档本身。也会把VNote的记忆存放到配置文件中。

谢谢！

**Comment by kangjianwei** [comment]
期待后续版本...

辛苦...

**Comment by tamlok** [comment]
已经增加全局图片位置记忆。
