### ISSUE TITLE
Slack link is unavailable

### ISSUE THREAD

**Issue by guoqi** [tamlok/vnote#517]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
Release中的Slack链接已经失效了，希望作者更新下哈～

How to Repro (如何复现):
点击链接即可～

**Comment by tamlok** [comment]
Thanks! I am now working on a new homepage. Will update the slack link later.

**Comment by tamlok** [comment]
已经更新！

https://join.slack.com/t/vnote/shared_invite/enQtNDg2MzY0NDg3NzI4LTQ1Yzk1YjA5MjAyYTU0MjJkMTUxNmRiYWQ2YjlkOWU0ZGZlMTFlZTAxNzg0ZGUyNzI0ZGY2NDg4MmU1M2FkMDg

欢迎访问新主页： https://tamlok.github.io/vnote
