### ISSUE TITLE
能否添加一个详细的构建文档

### ISSUE THREAD

**Issue by jonwinters** [tamlok/vnote#520]
能否添加一个详细的构建说明文档

我执行了.travis_macos.sh 

/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula
```
git checkout 13d52537d1e0e5f913de4639012 qt.rb
error: pathspec '13d52537d1e0e5f913de4639012' did not match any file(s) known to git.
```
出现了这个问题

**Comment by tamlok** [comment]
那个脚本是用于Travis持续构建的，不适合本地构建。

构建文档请参考： https://tamlok.github.io/vnote/zh_cn/#!docs/%E5%BC%80%E5%8F%91%E8%80%85/%E6%9E%84%E5%BB%BAVNote.md

谢谢！

**Comment by tamlok** [comment]
可以qt官网直接下载qt的安装文件，安装后用qt creator打开构建。
