### ISSUE TITLE
使用快捷键打开外部编辑器bug

### ISSUE THREAD

**Issue by YeomanYe** [tamlok/vnote#521]
OS Version (操作系统): Windows, Linux, macOS
Windows 10
VNote Version (VNote版本): Latest (最新)
Latest
Symptoms (表现):
刚打开编辑器第一次不能使用快捷键打开外部编辑器，必须要右键一次后，才能使用快捷键打开

How to Repro (如何复现):
打开编辑器，选择一个笔记，使用快捷键F12打开

**Comment by tamlok** [comment]
谢谢反馈！已经修复！
