### ISSUE TITLE
Linux下导出为pdf失败

### ISSUE THREAD

**Issue by Li-Zhenghua** [tamlok/vnote#522]
OS Version (操作系统):  Arch Linux

VNote Version (VNote版本): vnote-git-2.1.33

Symptoms (表现):

将markdown文件导出为pdf失败, 使用内置引擎和wkhtmltopdf都失败.

**Comment by tamlok** [comment]
hi，

是下载的appimage吗？

导出对话框下面有一个控制台输出，有什么出错信息吗？

谢谢！

**Comment by Li-Zhenghua** [comment]
+ 用的是archlinuxcn仓库的包

+ 只显示导出笔记失败,没有错误信息

**Comment by tamlok** [comment]
使用的是vnote-bin吗？

**Comment by Li-Zhenghua** [comment]
pacman里显示版本号是:vnote-git-v2.1.33.g324d8ab-1

**Comment by tamlok** [comment]
请参考github主页，使用vnote-bin包，你现在用的那个因为arch是用qt5.11编译，不稳定。

如果bin也不行，可以尝试下载appimage。

谢谢！

**Comment by Li-Zhenghua** [comment]
改用AUR的vnote-bin包后可以正常导出了
