### ISSUE TITLE
vnote 的按键问题

### ISSUE THREAD

**Issue by jonwinters** [tamlok/vnote#523]
macos

最新

normal 模式 输入 Shift+g 先抬起Shift键 后抬起g 会触发两次输入：

 一个是vim的normal G (编辑光标到底部)  
然后shift键 先抬起 后放下键盘的g 又会触发一次 Shift按键

我实测系统的vim 是不会出现这个问题的
因为我是用shift切换 中英文输入法的，所以这个很影响体验 看能否解决

**Comment by jonwinters** [comment]
关闭 smart input 解决问题

**Comment by tamlok** [comment]
Hi,

`Smart Input`是在Vim切换普通和插入模式的时候，自动禁用或启用输入法，比如插入模式是中文输入法，切换到普通模式会禁用输入法，这时候可以直接输入字母命令；再次进入编辑模式后，会重新启用输入法，方便继续输入。

谢谢！

**Comment by jonwinters** [comment]
@tamlok  哈，我已经习惯自己切换输入法了 主要是其它软件也没有这个功能，所以还是自己控制比较好哈
