### ISSUE TITLE
[需求] 图片路径配置

### ISSUE THREAD

**Issue by zzl93** [tamlok/vnote#525]
OS Version (操作系统): deepin Manjaro 18.0.0

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
vnote中插入图片地址为  `![image](_v_images/image.jpg)`
但是我想要的  `![image](./_v_images/image.jpg)`样子地址，vnote也能识别这个地址并显示图片
我试了自定义图片文件夹设置，但是哪里不能输入`/`
还有外部文件设置输入了`./`，但是下次插入图片还是忽略了`./`

我就是不想每次插入图片还要在图片路径前加一个`./`

作者辛苦了，感谢作者提供这么好的工具！

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi，已经添加支持了，下个版本或者最新构建版会支持。需要在配置文件夹里面的`vnote.ini`添加如下几行：

https://github.com/tamlok/vnote/blob/64960cc3c542e22e7443d344e67644c9de56fe58/src/resources/vnote.ini#L549

```ini
[markdown]
prepend_dot_in_relative_path=true
```

**Comment by tamlok** [comment]
2.2版本已经支持！
