### ISSUE TITLE
Please include `qt5ct` platform plugin to AppImage

### ISSUE THREAD

**Issue by actionless** [tamlok/vnote#526]
see https://github.com/AppImage/AppImages/issues/88#issuecomment-443493028

It will allow native look for VNote app if Qt5 is tuned by Qt5 Configuration Tool: https://sourceforge.net/projects/qt5ct/

**Comment by tamlok** [comment]
Hi,

Do you have specific steps to do this?

By the way, which theme do you choose in VNote? Please choose `v_native` and restart VNote to check if that works.

Thanks!

**Comment by actionless** [comment]
please see the discussion in AppImage repo which i linked above, it seems what you need to add extra arguments to qt-deploy command, to include qt5ct platform plugins

just using v_native in this case will fallback to default Fusion theme because qt5ct platform plugin is not available for statically built qt

**Comment by tamlok** [comment]
Hi,

It should be bundled in AppImage now (https://github.com/tamlok/vnote/commit/e534eec083c32ec2e04146a7ce8871a162da11aa). Please give it a try.

**Comment by tamlok** [comment]
You could try the latest build https://bintray.com/tamlok/vnote/vnote/_latestVersion

**Comment by actionless** [comment]
i've downloaded latest AppImage and it still doesn't see qt5ct

but as someone not familiar with qt5ct or c++ generally i can't advice how to fix it :(

**Comment by tamlok** [comment]
but if you extract that appimage, you could find libqt5ct.so in it.

**Comment by actionless** [comment]
i would `@` here qt5ct dev but their project is on sourceforge

however current aur build, as you mentioned, works fine with the latest qt now, so this issue is not so severe

also i think mb could be better to leave it open in case if someone with experience with qt5ct and qt packaging stumble upon it

**Comment by tamlok** [comment]
Will try to compile it from source in CI.

**Comment by tamlok** [comment]
Now compile qt5ct from [source](https://travis-ci.org/tamlok/vnote/jobs/503109714) and it should work. Please help to test the latest [AppImage](https://bintray.com/tamlok/vnote/vnote/2.3#files).

**Comment by actionless** [comment]
thanks a lot for researching this!
it now see qt5ct settings correctly!
