### ISSUE TITLE
无法关闭右侧工具栏

### ISSUE THREAD

**Issue by zzndb** [tamlok/vnote#527]
OS Version (操作系统): openSUSE Tumbleweed

VNote Version (VNote版本): AppImage version: 2.1

Symptoms (表现): **程序启动后**默认打开文件(搜索, 通过左栏)也打开了右侧工具栏, 然而工具栏也没有任何内容显示, 通过快捷键`Ctrl-e+T`可以打开工具栏显示, 再次通过快捷键操作也无法隐藏, 通过手动调整工具栏尺寸后可收回.

How to Repro (如何复现): 如上操作即可

---

* 截图演示
![vnote_toolsbar](https://user-images.githubusercontent.com/20870493/49513984-8c6e1500-f88a-11e8-87e4-5baaecf02349.gif)

**Comment by tamlok** [comment]
Hi,

是使用独立显卡吗？估计是显卡驱动的问题。

另外，通用入口中输入key后不用空格，直接输入要搜索的关键字即可。

谢谢！

**Comment by zzndb** [comment]
集成显卡 😂

![image](https://user-images.githubusercontent.com/20870493/49514495-1ff41580-f88c-11e8-9200-3a033f79d006.png)

**Comment by tamlok** [comment]
XFCE吗？

**Comment by zzndb** [comment]
KDE 


![screenshot_20181205_211258](https://user-images.githubusercontent.com/20870493/49515693-90506600-f88f-11e8-857f-f800ac50b4e7.png)

**Comment by tamlok** [comment]
![screenshot_20181205_211918](https://user-images.githubusercontent.com/5763157/49516031-719e9f00-f890-11e8-96ea-1c1aec207127.png)

我的也是KDE，倒没有这个问题。我下载AppImage试试。

最后如果实在不行，可以把工具栏关闭了，然后重启VNote，这样默认就不会开启工具栏。这样的情况下，打开并关闭工具栏，不知道会是什么效果呢？

大纲可以在通用入口`Ctrl+G Y`中查看。

**Comment by tamlok** [comment]
只要没看到“工具栏”三个字，那就说明工具栏已经隐藏了，只是主窗口没有重新改变尺寸而已。Qt真是多坑呀。我后面看看。

**Comment by zzndb** [comment]
:joy:

谢谢开发者

**Comment by tamlok** [comment]
发现我本地编译的没有问题，AppImage有问题。我看是不是Qt版本问题。

**Comment by tamlok** [comment]
It is caused by a regression in Qt 5.9.6 https://bugreports.qt.io/browse/QTBUG-68939

Already fixed in 5.9.7, I sitll need to wait for the publishment of 5.9.7 in Ubuntu.

**Comment by tamlok** [comment]
Fixed after upgrading to Qt 5.9.7. You could download the latest build [here](https://bintray.com/tamlok/vnote/vnote/2.2#files).
