### ISSUE TITLE
最大化窗口在关闭时出现这个问题

### ISSUE THREAD

**Issue by mzy666888** [tamlok/vnote#528]
OS Version (操作系统): Windows

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
最大化窗体是关闭，在还原时出现这个情况
![image](https://user-images.githubusercontent.com/2587129/49560765-a96c1c00-f94e-11e8-9a02-1cdd5b6be70e.png)

How to Repro (如何复现):

**Comment by mzy666888** [comment]
这个情况

**Comment by tamlok** [comment]
hi，

请参考文档进行解决，一般是显卡问题。

https://tamlok.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#toc_7
