### ISSUE TITLE
请问如何进入vim模式

### ISSUE THREAD

**Issue by SangKuanJi** [tamlok/vnote#529]
OS Version (操作系统): Windows10

VNote Version (VNote版本): 21

Symptoms (表现):
使用快捷键 Ctrl - T 进入编辑模式
想移动光标, h/j/k/l  但是都直接输入成字符了
使用 esc  退出, 回到了阅读模式.
使用 i 想进入编辑模式. 无果
菜单 : 文件, 编辑, 查看, markdown, 帮助 , 找遍了也没有进入vim模式(我记得以前有?)

vnote.readthedocs.io/zh_CN/latest/ 文档我看完了, 也不知道怎么进入vim模式

How to Repro (如何复现):

**Comment by tamlok** [comment]
在文件菜单的设置里面，阅读/编辑下面有一个按键模式。

**Comment by SangKuanJi** [comment]
感谢回复,
可以了

**Comment by tamlok** [comment]
> 建议直接在 README 中写了吧，我也找了好久。

软件每次更新完后首次启动的时候会显示一个welcome page，里面写有。后面会完善一下。放在设置里面主要是因为之前放在编辑菜单的时候很多用户不知道是什么但又打开了，然后一堆issue说不能输入之类的。

**Comment by breathiness** [comment]
> 在文件菜单的设置里面，阅读/编辑下面有一个按键模式。

您好，我在设置里打开了vim模式，但是为什么还是没有任何变化？

**Comment by tamlok** [comment]
@breathiness 需要重新打开当前标签页

**Comment by breathiness** [comment]
> @breathiness 需要重新打开当前标签页

原来如此……非常感谢！

**Comment by Summerslyb** [comment]
建议在文档中或者常见问题里写清楚

**Comment by Sirman** [comment]
请问，如何在vim 模式下 将插入模式与正常模式的切换键esc，映射为类似 jk,j。 谢谢

**Comment by tamlok** [comment]
@Sirman 暂时不支持映射，可以使用`ctrl+c`或者`ctrl+[`.

**Comment by Sirman** [comment]
@tamlok 了解 谢谢
