### ISSUE TITLE
代码框的上下间隔不同

### ISSUE THREAD

**Issue by wuscloud** [tamlok/vnote#53]
测试
```
/**

*/

public class Demo {
	public static void main(String[] args) {
		System.out.println("hello vnote !");
	}
}
```
测试

问题是：
上面的两个"测试"和代码框的间隔距离是不同的

**Comment by tamlok** [comment]
Hi，这个是因为默认的CSS在处理段落的时候，下边距认为设置大一点，所以对于`测试`这个块，其上边的空白是要比下边的空白少的。目前您可以复制一份默认的`default.css`，然后把里面的`bottom-margin=24px`删了。后面我会调整一下。谢谢！

**Comment by wuscloud** [comment]
非常感谢。我试了下，改成margin-bottom: 10px;看起来更好一点
