### ISSUE TITLE
导出文档如果含有空文件夹无法导入

### ISSUE THREAD

**Issue by kolnick** [tamlok/vnote#531]
OS Version (操作系统): Windows

VNote Version (VNote版本): Latest (最新)

Symptoms (表现): 导出文档如果含有空文件夹无法导入

How to Repro (如何复现): 导出文档如果含有空文件夹无法导入

**Comment by tamlok** [comment]
hi,能具体说一下场景和操作吗？导出后，为啥需要导入呢？

谢谢！

**Comment by kolnick** [comment]
主要可能会换电脑所以测试了一下 这个功能  只要文件夹他是一个空文件夹他就无法在vnote树目录显示出来

**Comment by tamlok** [comment]
导入（从外部文件夹构建笔记本）的时候，vnote只能猜测哪些是用户想要的文件，因此只会遍历md文件极其文件夹。

**Comment by kolnick** [comment]
那就很蛋疼了这个问题， 空文件夹 无法显示

**Comment by tamlok** [comment]
你可以写个脚本遍历一下，加到_vnote.json中即可。

**Comment by tamlok** [comment]
另外一种选择是把vnote当做编辑器，编辑外部文件，左边面板第三个标签页是浏览外部文件的。

**Comment by kolnick** [comment]
可以加个打开软件需要输入密码功能吗

**Comment by tamlok** [comment]
VNote的笔记本都是纯文本明文，所以如果要加密，得把数据也加密，比较复杂，这个需求得等后面有时间再考虑了。

**Comment by kolnick** [comment]
嗯是的 最好是不能看到有文件夹结构 对用户看到的话只有一个文件
