### ISSUE TITLE
Mac版本导出无法在Windows上使用

### ISSUE THREAD

**Issue by kolnick** [tamlok/vnote#532]
OS Version (操作系统): Windows,  macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):Mac版本导出无法在Windows上使用

How to Repro (如何复现):Mac版本导出无法在Windows上使用

**Comment by tamlok** [comment]
hi，能具体说一下场景和操作吗？

如果需要mac和pc之间同步，正确操作应该是使用第三方网盘把笔记本根文件夹对应的文件夹同步好，然后在另一台电脑添加笔记本，根文件夹选择你同步过来的之前的那个笔记本根文件夹，vnote会直接识别。

导出功能只是为了分享第三方。导入功能也是只是为了导入外部文件。

谢谢！
