### ISSUE TITLE
Vnote opens a Konqueror dialog for Read mode in KDE environment.

### ISSUE THREAD

**Issue by kbumsik** [tamlok/vnote#539]
OS Version: Arch Linux

VNote Version: 2.0

Symptoms:

Hi,
I use latest Arch Linux with KDE. VNote runs mostly fine but only one critical thing: When I open a file in Read mode, Vnote opens a Konqueror window instead of rendering it in Vnote. It is fine in Edit mode.

I guess it is because KDE and Konqueror is written in Qt so that opening a file triggers Konqueror as the default behavior. 

How to Repro:

1. Prepare KDE and Konqueror.
2. Open Vnote.
3. Double-click any files in Read Mode.
4. Konqueror is opened and the file tab in Vnote is just blank.

**Comment by tamlok** [comment]
Please use `vnote-bin` or the AppImage, and try again.

**Comment by kbumsik** [comment]
Running vnote in command line (is this `vnote-bin` you mean?) seems have the same issue. But running AppImage seems fine :)

**Comment by tamlok** [comment]
Do you use `vnote-bin` or `vnote-git` from AUR?

**Comment by kbumsik** [comment]
I originally used `vnote-bin` but installing `vnote-git` doesn't solve the issue.

**Comment by tamlok** [comment]
`vnote-bin` should work. I am not sure what happen to the package. @SilverBut Do you have any ideas?

I am afraid you need to use AppImage for now.
