### ISSUE TITLE
功能建议：折叠列表

### ISSUE THREAD

**Issue by woniuxia** [tamlok/vnote#542]
建议折叠列表功能。效果如下。辛苦作者。
![image](https://user-images.githubusercontent.com/16383685/50051777-5286f380-0153-11e9-8e93-b2e10a781c10.png)
![image](https://user-images.githubusercontent.com/16383685/50051776-4dc23f80-0153-11e9-9719-a00977f09dbc.png)

**Comment by tamlok** [comment]
hi,

vnote的设计理念是尽量保持markdown纯文本的简单性，所以一切内容都是纯文本并辅助以图片预览。这种折叠的方式不太符合当前风格。后面会添加折叠任意文本行的方式。

谢谢！

**Comment by henices** [comment]
希望不要做成默认折叠， 可以提供一个选项。

**Comment by woniuxia** [comment]
好的，多谢。作者辛苦。
