### ISSUE TITLE
markdown 数学公式用pandoc导出pdf失败

### ISSUE THREAD

**Issue by hlyang1992** [tamlok/vnote#547]
OS Version (操作系统): Window

VNote Version (VNote版本): Latest (最新)

How to Repro (如何复现):

当公式中包含`equation`等环境时, 导出pdf 用pandoc失败,如下面的内容

```
$$
\begin{equation}
E=mc^2
\label{a}
\end{equation}
$$

please see Eq. $\eqref{a}$
```

使用导出命令:
`pandoc   --resource-path=.:"%3" --css="%2" --css="%4" -s -o "%1" "%0" --pdf-engine=xelatex`
详细导出配置为:

![snipaste_2018-12-20_19-25-25](https://user-images.githubusercontent.com/2081913/50282252-1f16d280-048d-11e9-9c00-fd21d564139f.png)

输出内容为:
```
>>> 导出到 C:/Users/lenovo/Documents/vnote_exports 。
>>> 正在导出笔记 E:/Dropbox/vnote/分子动力学/new_note.md 。
>>> pandoc   --resource-path=.:"E:/Dropbox/vnote/分子动力学" --css="file:\\\C:\Users\lenovo\AppData\Roaming\vnote\themes\v_native\v_native.css" --css="file:\\\C:\Users\lenovo\AppData\Roaming\vnote\themes\v_native\v_native_codeblock.css" -s -o "C:\Users\lenovo\Documents\vnote_exports\new_note_003.pdf" "E:\Dropbox\vnote\分子动力学\new_note.md" --pdf-engine=xelatex
>>> Error producing PDF.
! LaTeX Error: Bad math environment delimiter.



See the LaTeX manual or LaTeX Companion for explanation.

Type  H <return>  for immediate help.

 ...                                              

                                                  

l.63 \begin{equation}



>>> 导出笔记 E:/Dropbox/vnote/分子动力学/new_note.md 失败。
>>> 导出了 0 个笔记。
```
如果源格式选择`html`, 可以生成PDF但生成的内容有误.

**Comment by tamlok** [comment]
这个应该是pandoc问题，如果从markdown格式进行导出，你得看看pandoc里面markdown格式中的公式是怎么写的，不一定是$。

如果是从html格式导出，到处后内容是怎么样的呢？

**Comment by hlyang1992** [comment]
从html导出是这样的，可能时pandoc的问题，我去看看。

![snipaste_2018-12-21_09-37-53](https://user-images.githubusercontent.com/2081913/50319833-5ffdfe00-0504-11e9-88b2-94da3a35b255.png)

**Comment by hlyang1992** [comment]
@tamlok 已经解决了，应该这样写，

```
\begin{equation}
E=mc^2
\label{a}
\end{equation}

please see Eq. $\eqref{a}$
```

而不是这样写，

```
$$
\begin{equation}
E=mc^2
\label{a}
\end{equation}
$$

please see Eq. $\eqref{a}$
```
