### ISSUE TITLE
Copied content won't show the last line in OneNote 2010

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#55]
From preview mode, copy and paste to OneNote 2016/2010.
The last line of the copy content never shows.

Though the problem doesn't happen with Word 2016, I doubt that might be due to some tags not enclosed correctly. Of course, highly possible Qt's  bug, not VNote's.

**Comment by tamlok** [comment]
Hi, I could not reproduce this issue. Could you please share a sample note which causes issues on your side?

Thanks!

**Comment by seaspeak** [comment]
Please see the attachment.
Note that OneNote2010 has indent and lastline problem; 2016 only has indent problem.

platform: OneNote 32-bit, Microsoft Windows [Version 10.0.14393]
[onenote-indent-lastline.zip](https://github.com/tamlok/vnote/files/1461776/onenote-indent-lastline.zip)




OneNote 2010 (left), OneNote 2016 32bit.

**Comment by tamlok** [comment]
Hi, I still could not reproduce the lastline-missing issue with your file. The indentation issue is a known issue. VNote use QWebEngineProcess to display the HTML. It is strange that it is fine when copying from Chrome and pasting into OneNoe. I will investigate the HTML export/copy stuff later. For now, you could just use `Shift+Tab` to unindent the text manually.

**Comment by seaspeak** [comment]
I tried the 'new' 1.9, and the lasline-missing issue still exists.
I'm using English version Windows 10 and OneNote 2010, not sure if this
matters.

**Comment by tamlok** [comment]
I do not have OneNote 2010 installed (maybe need downloading several GB installer?). As OneNote 2010 is somewhat obsolete, I suggest to not fix this for now. What do you think of it? Thanks!

**Comment by seaspeak** [comment]
Sure. It is a relatively minor issue. You should close it temporarily and keep going.

**Comment by seaspeak** [comment]
I looked into the Qt5 `QApplication.clipbaord()`.

Qt5 generates html in format: `<!--StartFragment-->.............<!--EndFragment-->`

OneNote2010/2016 accept format: `<html><body><!--StartFragment-->.............<!--EndFragment--></body></html>`

If tags `<html>` and `<body>` are added, the lastline-missing and indent issues will both be resolved. The tags are sufficient, attributes are unnecessary.

[clipboard.zip](https://github.com/tamlok/vnote/files/1491338/clipboard.zip)

**Comment by tamlok** [comment]
Cool! Thanks for your investigation! I will take a look into this.

Could you please provide more details about the crash? Could we reproduce it?

Thanks!

**Comment by tamlok** [comment]
I tried adding `<html><body><!--StartFragment--> ... <!--EndFragment--></body></html>` around the copied html. I could not tell if there is any difference, since I could not re-produce the last-line-missing issue.

**Comment by seaspeak** [comment]
Add <html><body></body></html> also fix the indent issue as I mentioned here. [download](https://github.com/tamlok/vnote/files/1461776/onenote-indent-lastline.zip) 

Can you reproduce the indent problem?

**Comment by tamlok** [comment]
I implemented the adding logic in a wrong way. I have fix it and it works fine now. (8a26bda8ba8563c3f6846295c2ad7aeaa4851a4a)

By the way, I have added a context menu item called `Copy without Background`, which makes it amazing to copy/paste into OneNote or Word.

**Comment by seaspeak** [comment]
_vnote_ v.1.11.1
Confirm also works great with OneNote 2010.

"copy without background color" is really convenient. But I hope it could be more dark-theme friendly. Dark themes have light color words, so words pasted without a background color will be unreadable. (but pasting with background is also ugly)

I think there are maybe two solutions for this.
1. let users freely apply different theme styles to the copied texts. Users may choose to use different color styles, especially light colors, while they use dark theme to edit or view the texts.
2. Switch themes without restarting _vnote_. The last resort.

**Comment by tamlok** [comment]
I will add a mapping of colors to a theme to replace colors literally after copy.

**Comment by tamlok** [comment]
Already added a mapping in (324d7cd444091ad5ab579a81b0f7f5). Thanks!

**Comment by seaspeak** [comment]
Where can I found the Windows daily build to test?

**vnote 1.11.1**
Another copy issue is _vnote_ doesn't copy highlights tagged by `<mark>`, e.g., `<mark>hilight</mark>`.

**Comment by tamlok** [comment]
You could just download the artifacts [here](https://ci.appveyor.com/project/tamlok/vnote/build/1.11.1.125/job/fbu3byq6ao8b561r/artifacts). You could just download the EXE to update.

`<mark>` seems not to be recognized when copied. Will test it in Windows later.

**Comment by tamlok** [comment]
`<mark>` is not recognized by OneNote. So I am afraid there is nothing VNote could do here.

**Comment by seaspeak** [comment]
I see. I was not aware of that.

Per [here](https://stackoverflow.com/questions/25104738/text-highlight-in-markdown?answertab=active#tab-top), `<mark>` and `<span style="background-color: #FFFF00; color:000000">` are suggested for highlighting. 

I think I'll use a snippet to insert `<span>` for compatibility. But I can't find any document about snippet.

1. How to call for a snippet with its shortcut ([a-z])?
2. What is the type "Html" for? (I always got "not applicable")
3. Can I combind the two into one snippet? `<span style="background-color: #FFFF00; color:000000">@@</span>` or `<span style="background-color: #FFFF00; color:000000">$$</span>@@`

**Comment by tamlok** [comment]
- You could reference [wiki](https://github.com/tamlok/vnote/wiki/VNote%E4%B9%8B%E7%89%87%E6%AE%B5(Snippet)) if you could read Chinese. I am writing documentation in English these days.
- Using `<span>` has a trouble if you copy content without background. I will make the logic specific for OneNote later. I suggest you to still use the `<Mark>`. I will translate it into span after copy.

**Comment by tamlok** [comment]
Hi, I have added documentation about snippet in English [here](http://vnote.readthedocs.io/en/latest/user_docs/snippet.html).

Thanks!
