### ISSUE TITLE
如何设置显示空格

### ISSUE THREAD

**Issue by yi-Xu-0100** [tamlok/vnote#550]
OS Version (操作系统): Windows

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
文字内容可能错误夹带空格，希望能够显示空格，防止这样的问题。

How to Repro (如何复现):
在任何一段话的逗号处后面加空格，隐蔽且不易察觉。

现在只有能够在每段的最后有空格才能显示出来，但可能还需要更高级的设置选项，我没有找到相关的问题和设置，希望能够得到解答，谢谢！

**Comment by tamlok** [comment]
Qt的编辑器是支持显示空白字符的，但是VNote目前还没有暴露接口。等后面插件支持吧。但如果通篇的空白字符都显示出来，估计画面不会太好看。

谢谢！

**Comment by yi-Xu-0100** [comment]
我原本是使用notepad++写md文件的，其中显示空格的方式是使用中心虚点表示空格，感觉基本能够忽视，有问题也能看出来，奈何md渲染没有，Vnote感觉很好，要是能支持插件，想来是一件幸事，谢谢解答，这个就先关闭了，谢谢！
