### ISSUE TITLE
vnote 中不显示文件夹内的笔记,说找不到路径

### ISSUE THREAD

**Issue by A35102** [tamlok/vnote#551]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):

How to Repro (如何复现):

**Comment by tamlok** [comment]
详细一点呀大哥！

**Comment by A35102** [comment]
![image](https://user-images.githubusercontent.com/45157132/50412572-5d244580-0843-11e9-8095-c0dd5c873886.png)
详细的忘了怎么写的  大概内容是 打开VNote 提示找不到 D:\AF\FD\destiny(我的笔记路径) ,VNode里边只显示空的destiny文件夹了,别的都不显示 ,选从磁盘重新加载也没用 .    现在这个截图是我重新往destiny 里边写了文件

**Comment by tamlok** [comment]
VNote会在每一个目录下面都有一个`_vnote.json`配置文件，如果该配置文件不存在，则会报错说找不到。

issue模板里面也有相关信息提示，下次可以说一下具体什么场景，什么错误，做了什么操作，如何复现。

如果是通过网盘同步过来的，可以看一下`_vnote.json`有没有被同步过来。另外，不要绕过vnote来操作笔记本下面的文件。

**Comment by A35102** [comment]
好的~  多谢~

**Comment by miner-k** [comment]
OS version： windows
Vnote version：2.7.1
symptoms：
![image](https://user-images.githubusercontent.com/29174800/61183658-58f03600-a676-11e9-9dbd-aadd1551ca62.png)

![image](https://user-images.githubusercontent.com/29174800/61183660-67d6e880-a676-11e9-96d1-21a331cf5754.png)

使用“从磁盘中加载” 无法加载到这个目录下新增加的文件lv3.md

**Comment by tamlok** [comment]
笔记本是由笔记索引文件跟踪记录的，外部文件需要导入到vnote中。

**Comment by miner-k** [comment]
![image](https://user-images.githubusercontent.com/29174800/61224498-4a2a8180-a751-11e9-96b2-41ace623256e.png)
是使用这个吧，我操作了，但是没有看到。

**Comment by tamlok** [comment]
这个操作是重新加载json索引文件，你需要在文件菜单从外部文件新建笔记。

**Comment by miner-k** [comment]
看到了，谢谢大哥。
