### ISSUE TITLE
[BUG]图片自动删除

### ISSUE THREAD

**Issue by kangjianwei** [tamlok/vnote#555]
两个文件插入同一张图片，如果在其中一个文件中删掉那张图片，另一个文件中的图片也跟着进了回收站...这是不是有些不合理...

**Comment by tamlok** [comment]
插入图片的时候请别直接复制链接文本，这样两个文件会引用同一个图片。应该复制图片再粘贴，这样会复制多一份图片。

vnote当前只会检查图片是否在当前文件被使用，这是松散的笔记结构决定的，很难跨笔记维护引用。

误删的图片可以在笔记的回收站里面找回来。
