### ISSUE TITLE
改进: 关于文档名字中不能包含/, `.` , `..`以及Windows上的那一堆破烂字符的问题?

### ISSUE THREAD

**Issue by biluohc** [tamlok/vnote#56]
可否考虑_vnote.json里的md的属性里添加一个name属性, 然后路径是name通过编码产生的(就是那些路径不能有的特殊字符被编码了)?

编码方式可以参考Url的编码, %+字符的十六进制数值.

我原来也打算写个MarkDown笔记本软件的,  但知道不是容易的项目, 因为自己没有什么GUI编程和写编辑器的经验..
感谢你的工作.

**Comment by tamlok** [comment]
Hi, VNote的想法来源于当初使用Vim来编辑和维护md笔记的体验，所以设计的初衷就是尽量简单化，以便即使在没有VNote的情况下，也能直观方便地管理和编辑已有笔记。所以VNote采用的是基于文件夹的笔记本、纯文本的配置文件（没有数据库），争取一切对用户透明但又无需用户操心过多细节。

为了兼顾跨平台，在文件命名上只能按照限制最严格的平台来制定规则，包括一堆非法字符、大小写不敏感等等。这样，简单地配合第三方网盘同步服务，就能实现在不同PC上编辑一个笔记本。

如果加入编码或者一层抽象(note name -> file name)，可能对用户不是很直观，一旦脱离VNote，笔记的查找和管理就比较困难了。当然，主要还是实现成本可能有点大，所以目前还是先放一下，把一些基本的核心的编辑功能先实现了（比如全文搜索、表格插入等等）。

您觉得怎么样呢？您是在什么场景下有特殊符号的命名需求？

谢谢关注！

**Comment by biluohc** [comment]
我仔细思考了下，发现是原来用cherrytree产生的误区，因为cherrytree的对文档的h1，h2等的大纲视图显示并不好，所以我趋向于使用标题做节点的名字。
它的数据是存在sqlite或者xml里的，
就没有特殊字符的困扰。
这样倒是笔记可选加密。

原来也试过zim，采用的某种维基语法，最后还是放弃了，虽然它有个好用的大纲。

我原来打算做的也是基于文本+json之类的配置文件的笔记。

但对标准的文档来说，含特殊字符的标题应该放到文档内部。虽然可能会导致文档太长，但是vnote有个好用的大纲侧栏，这些就不是问题了。

抱歉，打扰了，请您用心做核心编辑功能吧!

另外，界面就只有文档编辑框可以改颜色?两边的目录和大纲一片白，晚上看着有些吃力，还是我没找到设置。

**Comment by tamlok** [comment]
您太客气啦！

1. 我现在的一个习惯是使用一级标题作为文档标题，整个文档只有一个一级标题，然后新建笔记的时候，支持自动插入笔记名作为一级标题；
2. 目前还没支持换肤，所以只能编辑框换底色，我一般是选择`LightGrey`，后面会出暗色主题。另外，在晚上推荐使用f.lux或者redshift之类的工具，毕竟很多软件或页面都是雪花花的白，黑白来回切换还是挺晃眼的。

:) 谢谢使用！
