### ISSUE TITLE
Ubuntu 18.04上运行.travis_linux.sh 脚本，不能安装成功

### ISSUE THREAD

**Issue by gigglesun** [tamlok/vnote#561]
OS Version (操作系统): Ubuntu 18.04

VNote Version (VNote版本): 最新

Symptoms (表现):
git clone or down load source 后，进入vnote目录，改变.travis_linux.sh脚本权限，运行；
1. 该脚本部分语句运行成功，部分失败，不能生成VNote-${version}-x86_64.AppImage文件
2. 重启Ubuntu后发现不能Ubuntu的GUI界面，尝试多种方法，卸载和重装ubuntu-desktop/lightdm/gdm3等都不可以

How to Repro (如何复现):
在Ubuntu上运行该脚本（强烈不建议，会导致Ubuntu不能正常工作，进不了图形用户界面）

**Comment by tamlok** [comment]
Hi,

`.travis_linux.sh`是用于Travis上面持续构建的脚本，并不是给用户运行的。

自行构建VNote请参考[官方文档](https://tamlok.github.io/vnote/zh_cn/#!docs/%E5%BC%80%E5%8F%91%E8%80%85/%E6%9E%84%E5%BB%BAVNote.md)。最简单的就是下载一个Qt 5.9的绿色安装文件`*.run`，然后双击安装qt到你的home目录，打开QtCreator，导入VNote项目，构建即可。也可以使用命令行。

谢谢！

**Comment by gigglesun** [comment]
Hi, tamlok,

多谢答复，我现在想删除这些误安装的包，不知道哪些包会导致ubuntu进入不了图形用户界面，libxkbcommon-0.5.0？ 这些安装的包应该不能用ubuntu的包管理命令sudo apt-get remove xxx吧，该怎么删除呢，花了好多时间在这个上面不能搞定，不知能不能给些提示，多谢。

Best regards.

**Comment by tamlok** [comment]
这个脚本会下载源码编译安装几个软件：

1. libxkbcommon
2. extra-cmake-modules
3. fcitx-qt5

参考这个脚本 https://github.com/tamlok/vnote/blob/b9d1164d8dbb286d089883b65a235492781b0446/.travis_linux.sh#L15 ，对应的目录应该是`libxkb-common-0.5.0`和`extra-cmake-modules`和`fcitx-qt5`，进到这些目录下面执行`sudo make uninstall`试试。

至于进步了图形界面，你可以根据具体的错误提示搜索一下解决方案，我也不太清楚。

谢谢！
