### ISSUE TITLE
Behaviors of pasting "Fenced Code Block" to Word2016/OneNote2016

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#57]
No line breaks in OneNote2016
![image](https://user-images.githubusercontent.com/8821870/32781979-e0c45080-c981-11e7-915a-700c23a20d70.png)

Please consider to remove the background color in Word2016
![image](https://user-images.githubusercontent.com/8821870/32782042-0c3daacc-c982-11e7-930b-e08bc6356f35.png)

**Comment by tamlok** [comment]
Hi, it is caused by [Highlight.js](https://github.com/isagalaev/highlight.js/). Will keep eyes on it.

Currently you could select one more line outside of the code block and copy, then manually remove the background color of it after pasting in OneNote (by selecting "No Color" in the background color of text). Here is the effect:

![image](https://user-images.githubusercontent.com/5763157/32834671-57ad0ce8-ca3e-11e7-9324-89e6630d9adb.png)

![image](https://user-images.githubusercontent.com/5763157/32834605-1d9b16a8-ca3e-11e7-8ec4-b1dfeb2a2792.png)

**Comment by seaspeak** [comment]
Even pasted text looks right in 2016, it doesn't feel right. Sometimes I have to hit ENTER twice to get a new line. The first ENTER will move the cursor to the head of the next line, and the second ENTER finally get a new line. 

I guess all the quirk behaviors of pasting to OneNote2016 ( also 2010 in another issue [lastline-missing]) are cause by Linux/Windows line breaks ('/n' and '/n/r').

As I know, Qt store line break as '\n' internally, and will automatically convert it. But I still like to ask your opinion: is that possible to replace '\n' with '\n\r' by programmers before pasting? Or maybe it is not related to the problem at all?

**Comment by tamlok** [comment]
I think it is not related to the line ending character, but I will take a look at the clipboard to see what's inside. Do you encounter this issue when copying in read mode or edit mode? If it is edit mode, then it may result from the line ending. If it is read mode, VNote use QWebEngine to display the content (it is a Chromium browser).

You could open this [Highlight.js](https://highlightjs.org/static/demo/) demo and copy the code blocks there and then paste in OneNote. It is the same behavior as VNote. If we change the CSS style of the `hljs` class to `display: inline-block`, then the one-line issue is gone. But the code block will not expand to the whole screen width. Do you think it is acceptable like this?

![image](https://user-images.githubusercontent.com/5763157/32991157-23e662de-cd71-11e7-9656-22228ec1c310.png)

**Comment by seaspeak** [comment]
About 'two enters to get a new line', now I understand that's becuase I'm trying to enter a new line between two `<span>`. That's how OneNote deal with `\s`/`\n` between two `<span>`. The

**Comment by tamlok** [comment]
I check it in detail. When we select the code block, it just gets something like `<span>...</span>`, not `<pre><code>...`, so wen pasted, it is just one line. If we select the whole code block by selecting the last "new line" space, then it gets the whole code block `<pre><code> ...` which is the desired behavior.

I think we could add some button at the top right corner via Javascript to copy the code block.
