### ISSUE TITLE
To turn off the table cells auto-width

### ISSUE THREAD

**Issue by neonkaaaaa** [tamlok/vnote#573]
That's a very cool feature - autotune the cells width, so you can edit text with comfort.
But sometimes especially when there is a lot of text in the cell and not so much in the others the autotune is completely awful. The result is: long empty lines.
Maybe it will be good to give the choice for a user: allow or not to allow the table cells auto-width?

**Comment by tamlok** [comment]
Now there is a switch in the edit menu in v2.3.
