### ISSUE TITLE
scroll bar cover half of the rightest character in edit-mode

### ISSUE THREAD

**Issue by bbsteel** [tamlok/vnote#576]
OS Version (操作系统): macOS

VNote Version (VNote版本): 2.2

Symptoms (表现):

in macOS:

<img width="239" alt="2019-01-13 9 16 02" src="https://user-images.githubusercontent.com/4044553/51085735-65074380-1778-11e9-84f3-38c82b1b098c.png">

How to Repro (如何复现):

**Comment by tamlok** [comment]
Please refer to https://github.com/tamlok/vnote/issues/454

**Comment by bbsteel** [comment]
> Please refer to #454

Set scroll bar to alway display in Mac OS system config solve this problem. thanks!
