### ISSUE TITLE
建议增加两种格式的样式显示：==高亮==，以及++下划线++

### ISSUE THREAD

**Issue by amosCc** [tamlok/vnote#578]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):

How to Repro (如何复现):
——
建议说明：
==高亮==，这个有些编辑器有，有的没有……
++下划线++，这个目前只看见有道云笔记有这个语法……

（新手，不会修改样式-_-b）

另外，可以像typora那样自定义是否使用这个语法就好了，那个软件可以自己勾选是否使用上下标之类的……

**Comment by tamlok** [comment]
Hi,

这两种语法好像都是不太通用的扩展语法，[Commonmark](https://commonmark.org/) 里面没有支持。对于这种扩展，VNote一般会比较克制。

- 高亮可以使用`<mark>ABC</mark>`；
- 下划线可以使用`<u>ABC</u>`；
