### ISSUE TITLE
Cannot render latex in ubuntu 18.04

### ISSUE THREAD

**Issue by duyatfit** [tamlok/vnote#579]
OS Version (操作系统): Linux

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
I'm using the Linux version, and all Latex formulas are shown as is without any rendering.

![image](https://user-images.githubusercontent.com/40762881/51196538-99e9d680-18ef-11e9-8e15-fdec4543c508.png)

How to Repro (如何复现):
Use the AppImage for Linux. Write some Latex and check.

**Comment by tamlok** [comment]
Do you check MathJax in Markdown menu to enable it?
