### ISSUE TITLE
请问我新建根文件夹，怎么切换到之前的default根文件夹下

### ISSUE THREAD

**Issue by wuscloud** [tamlok/vnote#58]
新建根文件夹之后，发现切不回去了

**Comment by tamlok** [comment]
看你的情况应该是切换成了单列面板模式，切换回双列模式即可以看到文件夹树。快捷键是ctrl+e p，工具栏里面也可以设置。

**Comment by wuscloud** [comment]
是的，我找到原因了，我把第二个面板往左拖，覆盖了第一个面板，所以切换回双列模式也没有发现。最后把第二个面板往右拖才看见。非常感谢
