### ISSUE TITLE
预览模式下的字体发虚，阅读很费眼睛，能否让用设定这个字体呢？

### ISSUE THREAD

**Issue by roro4ever** [tamlok/vnote#581]
OS Version (操作系统): 
Windows 10  17134.471

因为对win10 的宋体和微软雅黑不满意，我用了 [mactype 最新版 2018.1-beta5](https://github.com/snowie2000/mactype) + IOF字体中的 Xcross Blade，注册表加载“热替换”。

VNote Version (VNote版本): 2.2

Symptoms (表现):
在VNOTE中可以设置编辑模式下的字体，我将其设置为Xcross Blade，效果非常好。
![image](https://user-images.githubusercontent.com/3501102/51296472-51e5c380-1a57-11e9-92d5-49ccbe99c53a.png)

但预览模式下，文字发虚，阅读费眼睛，而且找不到可以设置字体的地方。
![image](https://user-images.githubusercontent.com/3501102/51296543-97a28c00-1a57-11e9-8af3-100d7f7c45c7.png)

希望增加一个选项可以设置预览的字体，或者由原来的选项统一控制。

**Comment by tamlok** [comment]
请自定义主题里面的css样式，具体参考官方文档。
