### ISSUE TITLE
打开应用和笔记时卡顿

### ISSUE THREAD

**Issue by hzjdyf** [tamlok/vnote#583]
OS Version (操作系统): macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
打开应用时，系统会出现10秒左右的卡顿（除了鼠标什么都操作不了）；
进入应用后，打开一个笔记会出现同样的问题。
难道跟文件个数有关系吗？

How to Repro (如何复现):

**Comment by tamlok** [comment]
这个不太清楚~~估计和macos相关，不知道是不是qt的问题。

**Comment by hzjdyf** [comment]
@tamlok 之前一直都挺好用的，这两天刚出现的问题。实在不想把笔记都迁移走

**Comment by tamlok** [comment]
系统有更新过吗？

**Comment by hzjdyf** [comment]
更新过，但不记得是不是更新马上出现的问题。

**Comment by hzjdyf** [comment]
![image](https://user-images.githubusercontent.com/22190839/51321030-ab241600-1a9c-11e9-8a56-48efd26bcec6.png)
系统是2018.12.15更新的，是更新后过了一段时间才出现的问题。

**Comment by tamlok** [comment]
您是程序员吗？有xcode环境吗？可以的话，可以尝试使用qt 5.9.7自行编译一下vnote。

**Comment by hzjdyf** [comment]
有相关文档吗？我电脑上有xcode。我不是程序员

**Comment by hzjdyf** [comment]
我回退到了2.0版本OK了。

**Comment by tamlok** [comment]
2.2和2.1都有问题？

**Comment by hzjdyf** [comment]
是的

**Comment by tamlok** [comment]
那您先用着这个版本。后面我看能不能更新一下构建用的qt的版本。

**Comment by hzjdyf** [comment]
2.0刚装好是好的，这会儿又不行了。可能是我电脑的问题

**Comment by weishx** [comment]
我是win10软件版本是2.2打开和保存一个300多行的md文件时也会有几秒钟的无响应

**Comment by tamlok** [comment]
@weishx 先把所有笔记关了，然后在设置里面换一下opengl选项，重启vnote试试。一定记得关闭前先把所有笔记关闭了。

**Comment by willtse** [comment]
我也有这个同样的问题

OS Version (操作系统): macOS 10.14.2

VNote Version (VNote版本): 2.2 

Symptoms (表现):
1、打开应用时，系统会出现10秒-30秒(貌似和上次退出前打开的标签页数目有关，越多时间越长)左右的卡顿（除了鼠标什么都操作不了）；
2、进入应用后，每打开一个笔记会出现同样的问题；
3、使用右键菜单或者⌥+⌘+N新建笔记时，输入文件名后点击确定后，在新的笔记的标签页出来后系统也会卡顿5秒-10秒。

最开始试用vnote的时候貌似是2.0版，好像没发现这些问题，升级到2.2后才转移了十几篇笔记过来后开始准备主力使用vnote才发现有卡顿的问题。

**Comment by tamlok** [comment]
Hi, 请尝试2.3版本，据个别用户反馈，卡顿现象改善不少。
