### ISSUE TITLE
不可以直接在笔记本新建文件么？

### ISSUE THREAD

**Issue by roachsinai** [tamlok/vnote#584]
是必须先在笔记本添加一个文件夹才能新建文件么？

**Comment by roachsinai** [comment]
那能不能添加这个功能呢？

**Comment by tamlok** [comment]
估计不能。当前是选定一个文件夹然后再显示该文件夹下的笔记，如果笔记直接放在笔记本下面的话，比较难显示。

建议可以尝试一下浏览器功能，浏览编辑外部文件。

**Comment by roachsinai** [comment]
好的！
