### ISSUE TITLE
我想自定义一个主题，该如何操作？当我把主题设置为黑色背景后，编辑栏仍然是白色的？还有就是 vim 模式在哪里开启？

### ISSUE THREAD

**Issue by hj1933** [tamlok/vnote#590]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):

How to Repro (如何复现):

**Comment by hj1933** [comment]
by the way，我想插入表格时，快捷键 Ctrl+. 毫无反应？  win7系统

**Comment by tamlok** [comment]
hi,

自定义主题请参考文档；

切换主题在文件菜单下面的主题中，切换后重启。

vim在设置对话框中。

看看是不是和其他快捷键有冲突了。

**Comment by hj1933** [comment]
![](https://raw.githubusercontent.com/hj1933/img/master/img/20190123111139.png)
黑色主题应用，编辑栏也是白色的？

**Comment by tamlok** [comment]
请确保编辑菜单下面的样式里面选择的是系统默认或者和主题同名字的，然后重启。

**Comment by hj1933** [comment]
已解决，多谢！

**Comment by suzumiyasmith** [comment]
> vim在设置对话框中。

where is the dialog? I cannot find it.

( I've already wasted 2 hours trying enter vim mode.

**Comment by tamlok** [comment]
@suzumiyasmith Sorry about that. File menu, Settings, Read/Edit, Key Mode, Vim, then restart VNote.
