### ISSUE TITLE
fail to create shared memory segment: macOS 10.14.2

### ISSUE THREAD

**Issue by raivivek** [tamlok/vnote#591]
OS Version (操作系统): macOS 10.14.2

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
```
fail to create shared memory segment
fail to attach to the shared memory segment "QSharedMemory::handle:: UNIX key file doesn't exist"
```

How to Repro (如何复现):

Installed vNote and tried to open; but app doesn't open. When launched using terminal, message above was printed.

**Comment by tamlok** [comment]
是从官网下载的dmg吗？

https://github.com/shadowsocks/shadowsocks-qt5/issues/227

尝试更新一下系统？

**Comment by raivivek** [comment]
Yes, I tried both ways -- dmg from official website and through `brew cask install vnote`.

The system appears to be on the latest update. I can try rebooting though.

**Comment by raivivek** [comment]
Okay -- rebooting fixed it.
