### ISSUE TITLE
系统托盘设置无效

### ISSUE THREAD

**Issue by Memento1990** [tamlok/vnote#594]
OS Version (操作系统): Windows10

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
取消系统托盘设置，然后重启程序，系统托盘仍存在；

How to Repro (如何复现):

**Comment by Memento1990** [comment]
> 怎么重启的？重启电脑后再试试？

我是通过“文件”菜单下的重启程序的。需要重启电脑么？OK，我试试~

**Comment by Memento1990** [comment]
抱歉，是我理解错误，系统托盘设置指的是关闭程序后是否最小化到系统托盘里。我以为是是否在系统托盘中显示图标。

**Comment by Mlearn** [comment]
希望能将设置->常规 中的 [系统托盘]选框更新为意义更明确的名称，比如[关闭软件最小化到托盘]。

同时增加一个 [同时显示系统托盘] 的选项。

这样的话，
1、只勾选[同时显示系统托盘]，打开软件的时候，系统托盘有图标显示；
2、只勾选[关闭软件最小化到托盘]，打开软件的时候，系统托盘没有图标，当关闭软件窗口时候软件会最小化到系统托盘进入后台，之后可以通过点击系统托盘来重新打开软件窗口；
3、同时勾选[同时显示系统托盘]、[关闭软件最小化到托盘]，就可以同时实现1、2两点的需求。

有这样的需求个人觉得是符合软件高度定制的精神的。同时对于很多功能洁癖者来说，也是能希望尽量掌控手中的软件行为。

**Comment by tamlok** [comment]
这个选项有Tooltip应该是提示关闭软件最小化到托盘的。

因为GUI选项实现起来比较耗时和无聊，所以很多配置项都没有在GUI界面里面暴露，都是在`vnote.ini`配置文件里面。后面会慢慢精细化。

**Comment by Mlearn** [comment]
OK 的，个人开发这么一个功能丰富的软件也是够费精力了。先主后次，希望能一直开发下去。点赞。
