### ISSUE TITLE
bintray 测试版目前无关闭 【新功能user track】的选项

### ISSUE THREAD

**Issue by kerhbal** [tamlok/vnote#597]
OS Version (操作系统): Windows

VNote Version (VNote版本): Bintray Latest (最新)

Symptoms (表现):

看到代码里有询问动作，但在软件里没有发现，是没有开发完成还是我这出问题了？这种地方出bug容易引起误会

**Comment by tamlok** [comment]
新版本才会提示

**Comment by kerhbal** [comment]
@tamlok 了解了👌
