### ISSUE TITLE
发现关闭已打开的标签也要花好多点击呀。弄个一键关闭并保存所有标签（md文件）的按钮比较有用

### ISSUE THREAD

**Issue by HgyHgyHgy** [tamlok/vnote#599]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):

How to Repro (如何复现):
弄个一键关闭并保存所有标签（md文件）的按钮比较有用

**Comment by tamlok** [comment]
右键菜单，关闭全部
