### ISSUE TITLE
Ubuntu16.04 编译报错

### ISSUE THREAD

**Issue by 7polo** [tamlok/vnote#6]
### 编译环境
+ Qt5.7
+ VNote-v1.1

### 错误信息
```
:-1: error: [sub-hoedown-make_first] Error 2
```

**Comment by tamlok** [comment]
您好！这个问题可以按照以下步骤进行排查：

1. 确认`hoedown` 文件夹存在于代码根目录下面并且不为空。如果不存在，请执行`git submodule update --init`.
2. 请执行`qmake --version`确认使用的版本号是Qt5.7；
3. 编译和安装步骤可以参考我下面这个脚本：

    ```
    #!/bin/sh
    mkdir -p build
    cd build
    qmake CONFIG-=debug CONFIG+=release ../VNote.pro
    make -j4
    sudo make install
    ```

如果还有问题可以大家进一步讨论！目前根据您反馈的信息，我只想到这些。另外，也可以加Q群讨论！

谢谢使用！！！

**Comment by 7polo** [comment]
成功编译了, 十分感谢, 希望这款软件越来越好 加油

**Comment by tamlok** [comment]
欢迎反馈使用体验！:)

**Comment by vagra** [comment]
确实 Qt Creator 打开目录时就报告 hoedown 目录下找不到 .pro 文件，执行 git submodule update --init 才行。

这一条要不要写进编译文档里？

**Comment by tamlok** [comment]
@vagra 官方文档一直写有，只是很少人看
