### ISSUE TITLE
使用快捷键无法退出VNote

### ISSUE THREAD

**Issue by 11hwu2** [tamlok/vnote#60]
Hi，我在Ubuntu16.04.2下的Gnome Terminal中运行./VNote_x86_64_1.9.AppImage时，遇到了使用快捷键Ctrl+Q是无法退出程序问题。右击File->Quit是可以正常退出的。

**Comment by tamlok** [comment]
Hi, 我测试了一下，的确如您所说。请更新一下，下载1.10版本，我试过没有这个问题。如果您这边还是不能退出，请继续反馈！

谢谢！

**Comment by 11hwu2** [comment]
Hi，我测试了下1.10版本，此问题已经得到解决，感谢^_^
