### ISSUE TITLE
从别的地方复制带换行的文本，无法很容易的变成引用块

### ISSUE THREAD

**Issue by chenbin11200** [tamlok/vnote#600]
OS Version (操作系统): Windows,

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
从别的地方复制带换行的文本，无法很容易的变成引用块，例如：
复制：
abc
  cdf
  hui
希望能在vnote中很容易变成：
> abc
>   cdf
>   hui

How to Repro (如何复现):

**Comment by kerhbal** [comment]
右键粘贴为块引用
