### ISSUE TITLE
Vnote如何迁移笔记呢？

### ISSUE THREAD

**Issue by roro4ever** [tamlok/vnote#601]
OS Version (操作系统): Windows 10

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
笔记默认保存在C盘，感觉不安全，有时候装系统忘了把数据拷出，笔记就没了，如何迁移到其他位置呢？

我看图片文件夹 啥的都可以自定义。

How to Repro (如何复现):

**Comment by kerhbal** [comment]
直接把笔记本根文件夹复制到随便一个地方，然后再vnote里添加笔记本，选那个新地方，vnote会自动识别已有的笔记本结构
