### ISSUE TITLE
Disabling analytics

### ISSUE THREAD

**Issue by 49616e** [tamlok/vnote#606]
OS Version (操作系统): Linux

VNote Version (VNote版本): Latest (最新)

Could you please add an option in the settings menu to disable analytics? I don't really want the application to be sending requests to https://tajs.qq.com every once in a while. I've looked into the code and there's supposed to be a popup asking if the user wants it enabled after an update, but personally I don't remember seeing such a popup before.

**Comment by kerhbal** [comment]
https://github.com/tamlok/vnote/issues/597
According to the developer, the function will be implemented in updates later.

**Comment by 49616e** [comment]
Alright, thanks. Should have done a bit more searching before opening a new issue. :ok_hand:
