### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by jerry011235** [tamlok/vnote#61]
首先vnote非常好！感谢作者的付出！
1.能否参考[SimpleMDE Theme Base](http://simplemde-theme-base.mazimd.com/) 的工具栏。
主要喜欢 H 按钮，按一下是一级目录，再按，是二级目录。
还有左右分屏的按钮，就是可以边写边预览。
希望把他们都集成到vnote里。
2.打开`vnote.ini`后 在哪里可以设置： `配置文件` 的目录为 `可执行文件所在目录` #44

**Comment by tamlok** [comment]
Hi,

1. 目前VNote支持快捷键`Ctrl+<Num>`来插入1到6级标题，不知道这个能否替代这个按钮？
2. VNote暂时不会支持实时预览。VNote的设计理念是在无需实时预览的情况下最小化Markdown的编辑和阅读的割裂感。比如VNote会在编辑模式原地预览图片链接。使用VNote来编辑Markdown带来的专注和舒畅，是实时预览无法带来的。
3. 如果需要读取可执行文件目录的配置，只需要把当前的那几个配置文件剪切到可执行文件目录下即可，VNote会优先读取该目录下的配置文件。

谢谢反馈！

**Comment by jerry011235** [comment]
感谢回复！如果可以的话还是希望 增加一个“标题”按钮。😄

**Comment by tamlok** [comment]
log的问题已经修复了，下一个版本会带上。

那个h按钮做成按钮菜单好不好？即有一个箭头弹出下拉菜单，有6个按钮对应6个标题。

**Comment by jerry011235** [comment]
`h按钮做成按钮菜单`真是好主意，棒极了！
另外我看了[靡不有初，鲜克有终——写在VNote半周岁](http://www.jianshu.com/p/3b8e0e70cd48)，觉得您说的`编辑和阅读的割裂感`在理，编辑写作时就是要专注才对。
于是我找了些专注写作的软件，您参考下。
1. [Q10](http://baara.com/q10/)
2. [OmmWriter](http://www.appinn.com/ommwriter/)
3. [FocusWriter](https://gottcode.org/focuswriter/)

结合上述软件的优势，可以做个全屏按钮，或者叫纯净写作按钮，点击后窗口占到显示器的全屏（类似Q10），只有编辑窗口，工具栏和菜单栏滑过显示/淡入淡出（类似FocusWriter）都可以。

**Comment by jerry011235** [comment]
另外，粗体、斜体、行内代码那一排的按钮，应该是**选中文字后**按一下加粗，再按一下取消，就是恢复成原来的状态，这样比较好。
而光标在**未选择文字**的情况下，按一下变成****,然后光标居中；再点一下，再加****，然后光标居中。
其实就和[SimpleMDE Theme Base](http://simplemde-theme-base.mazimd.com/)一样，代码可以参考它的。
该作者其实更新了[码字编辑器](http://mazimd.com/pages/new)，感觉不错，不过还是希望vnote的`预览`和`返回编辑`按钮能放在右侧或自定义位置。

**Comment by tamlok** [comment]
好的！谢谢反馈和建议！会根据需要和开发难度详细设计一下。

**Comment by tamlok** [comment]
目前，已经添加了一个标题工具栏按钮，用于应用标题样式。粗体等操作，在不选择文本的情况下，按一次是加粗，不输入任何文字的情况下，再按一次取消加粗。后面会添加在选择文本的情况下，如果已经加粗，再按一次取消加粗。
