### ISSUE TITLE
有没有和我一样的，图片没渲染出来？

### ISSUE THREAD

**Issue by hj1933** [tamlok/vnote#611]
win10 系统，之前重装了系统，发现现在图片渲染不出来
![](https://raw.githubusercontent.com/hj1933/img/master/iimg/20190201112420.png)

**Comment by tamlok** [comment]
阅读模式可以吗？


试试新建一个笔记，然后插入图片，试试行不行？

**Comment by hj1933** [comment]
阅读模式OK，新建笔记也不行

**Comment by tamlok** [comment]
vnote版本号是？把图片网址发给我？插入图片能否渲染？可能是这个图片的地址问题。

**Comment by HgyHgyHgy** [comment]
图片中就已经有网址了

**Comment by tamlok** [comment]
@HgyHgyHgy 所以我复现问题还得对着图片敲一遍毫无规律的比长城还长的网址。。。

初步估计是githubcontent的问题。

**Comment by youmoxiaozi** [comment]
### 确实碰到了一样的问题，在编辑和预览模式显示正常。导出pdf没有图片（我的图是本地连接）
![222](https://user-images.githubusercontent.com/26620499/53018784-39216100-348e-11e9-9dcd-f24ec8c14cdc.png)

pdf 设置：

![333](https://user-images.githubusercontent.com/26620499/53018913-843b7400-348e-11e9-9062-4d7c368bf48b.png)

pdf文件显示：
![111](https://user-images.githubusercontent.com/26620499/53019042-d1b7e100-348e-11e9-9edf-e02d4f306d6b.png)
