### ISSUE TITLE
没有找到关闭当前文档的功能，每次打开好不方便

### ISSUE THREAD

**Issue by Tridu33** [tamlok/vnote#612]
OS Version (操作系统): Windows

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):没有找到关闭当前文档的功能，每次打开好不方便。每次打开文档之后关闭都要用鼠标。用了Vnote之后还要用鼠标，感觉太不舒服了。

How to Repro (如何复现):

**Comment by tamlok** [comment]
`ctrl-e x`?看看帮助菜单里面的快捷键帮助。

**Comment by HgyHgyHgy** [comment]
关闭文档操作比较常用，如果可以自定义快捷键就比较好。这样按ctrl-e，再按x,虽然也不是很麻烦。

**Comment by tamlok** [comment]
@HgyHgyHgy 文件菜单里面有自定义快捷键入口？
