### ISSUE TITLE
粘贴带空位路径的问题，插入链接功能对于有空位的路径无效，可否自动支持带空位路径

### ISSUE THREAD

**Issue by HgyHgyHgy** [tamlok/vnote#616]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):

How to Repro (如何复现):
vnote的链接路径要求用%20代替空位，能否支持直接空位的路径，或者自动把带空位的路径转换成.md链接支持的路径?

**Comment by tamlok** [comment]
20%是标准要求，这个没办法。请问哪个场景不会自动转为20%呢？

**Comment by HgyHgyHgy** [comment]
在win10的资源管理器中直接复制路径，以及其他一些可以复制文件夹路径的软件中，复制的路径都是没那个%20，而是直接是空位，粘贴到vnote添加超链接的输入框，确定后，依然是没%20。结果超链接就无效了。

.md是可以含%20,但是用vnote添加超链接的输入框输入的路径，应该自动转换成.md支持的路径才好吧？
不然，要自己输入个%20代替空格。这个和.md的标准无关。

**Comment by HgyHgyHgy** [comment]
直接复制粘贴，好像是自动转换未含%20的。但添加超链接那个就不支持自动转换。

**Comment by HgyHgyHgy** [comment]
这个可以直接复制，然后粘贴实现。之前是复制了路径，再在添加链接框里粘贴。这样走了弯路。
