### ISSUE TITLE
Mac 下无法换行

### ISSUE THREAD

**Issue by banduoba** [tamlok/vnote#617]
OS Version (操作系统): macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
写文章使用回车换行,预览模式下没有换行还是在同一行

How to Repro (如何复现):
输入任意文字回车换行,点击预览,显示在一行

**Comment by banduoba** [comment]
我测试了下 必须两行文字之间有一行空行才自动换行,回车键换行无效 请问是 bug 还是本身就是这样的

**Comment by tamlok** [comment]
这是md标准语法，在markdown菜单的选项那里可以打开换行。

**Comment by banduoba** [comment]
ok 谢谢 已解决

**Comment by miurahr** [comment]
Can we close here?
