### ISSUE TITLE
.md新建显示正常，但是保存关闭后，再打开无法显示

### ISSUE THREAD

**Issue by hewenjian** [tamlok/vnote#620]
OS Version (操作系统): Windows, Linux, macOS
![image](https://user-images.githubusercontent.com/8112629/52514247-f7511900-2c4a-11e9-8595-01151497a105.png)

VNote Version (VNote版本): Latest (最新)
VNote_win_x86_portable_2.2
Symptoms (表现):
新建时显示正常，也能正常使用。
![image](https://user-images.githubusercontent.com/8112629/52514268-1d76b900-2c4b-11e9-8e39-b9227431c3fa.png)
但是，保存关闭，再打开，全是一片黑
![image](https://user-images.githubusercontent.com/8112629/52514287-4a2ad080-2c4b-11e9-8821-2bd4ebf58554.png)
PS:
移动鼠标，某些位置鼠标箭头会由箭头变成I，但是，即使箭头变成I，还是无法编辑。
How to Repro (如何复现):
同上

**Comment by hewenjian** [comment]
我发现，拖动鼠标能显示里面的内容，有一个禁止显示的图标

**Comment by tamlok** [comment]
看一下帮助文档的常见问题的最后部分，显卡驱动的问题。

**Comment by hewenjian** [comment]
以上这4个问题可能是由显卡驱动引起的。建议解决步骤：

如果是Windows系统，可以尝试更新显卡驱动；
--老电脑，显卡驱动已无更新
尝试指定VNote使用集成显卡；
--电脑只有集成显卡
如果还不能解决，尝试新建一个系统环境变量QT_OPENGL，可以尝试的值包括desktop或angle或software。
--已尝试添加QT_OPENGL系统变量，三个值都无效果
在以上操作之后，需要重启VNote。

**Comment by hewenjian** [comment]
请问“阅读模式”和“编辑模式”有什么不一样？
使用编辑就能正常显示，但是，一旦保存切回阅读就一片黑

**Comment by kerhbal** [comment]
试试新建**用户**环境变量？可能没什么帮助，不过我就是这样解决类似问题的

**Comment by hewenjian** [comment]
谢谢，不过“用户变量”和“系统变量”我都试过了，确定无效果

**Comment by tamlok** [comment]
重启vnote了吗？

**Comment by hewenjian** [comment]
有，“重启”和“退出”都试了

**Comment by hewenjian** [comment]
果然是显卡问题，找了一早上的显卡驱动，更新了后终于正常了。
谢谢。
