### ISSUE TITLE
安装后打开笔记md文件出现错误

### ISSUE THREAD

**Issue by qiuzhiqian** [tamlok/vnote#628]
OS Version (操作系统): Archlinux+KDE

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):在笔记软件中随便双击打开一个笔记文件，都会出现错误，错误提示为：未找到文件：data:text/html;charset=UTF-8,%3C%21DOCTYPE html%3E%0A%3Chtml%3E%0A%3Chead%3E%0A    %3Cmeta charset%3D%22utf-8%22%3E%0A%0A........

注：不知道为啥，传截图一直失败，如果需要截图，我可以邮件发给你

How to Repro (如何复现):

**Comment by tamlok** [comment]
请安装`vnote-bin`或者官方appimage。

**Comment by qiuzhiqian** [comment]
> 请安装`vnote-bin`或者官方appimage。

重新安装了vnote-bin后，问题依旧

**Comment by tamlok** [comment]
arch linux会使用qt 5.12来编译vnote，qt自己有bug，所以会导致阅读模式有问题。vnote-bin应该是不会有问题的。实在有问题，就尝试appimage吧。

**Comment by qiuzhiqian** [comment]
> arch linux会使用qt 5.12来编译vnote，qt自己有bug，所以会导致阅读模式有问题。vnote-bin应该是不会有问题的。实在有问题，就尝试appimage吧。

装了vnote-bin，重启一次电脑后就正常了，谢谢
