### ISSUE TITLE
全屏打开的问题

### ISSUE THREAD

**Issue by zhzjwd** [tamlok/vnote#63]
最大化状态下打开时，无法正常最大化显示，需要重新手动最大化才能正常显示
win10 Pro x64 1703
如图
![](https://ipfs.io/ipfs/QmaBNA6djt8yhDc373Gxf5uG91aQbRgLqzXzQ2eA3F6jxs?4.gif)

**Comment by tamlok** [comment]
Hi，我之前偶然也遇到这个问题。请问是什么平台呢？(win7/win10, 32/64) 是每次都这样子吗？我这边暂时复现不了。初步怀疑是显卡驱动问题。

谢谢！

**Comment by zhzjwd** [comment]
英伟达显卡
Intel CPU

**Comment by tamlok** [comment]
是win10 64吗？尝试更新一下显卡驱动？

**Comment by zhzjwd** [comment]
之前是 1703 刚更新了 1709 ，现在正常了，不知道啥原因。。。

**Comment by tamlok** [comment]
Good! 是的，这种显示上的问题往往是显卡驱动，之前我的也试过显示错位，更新驱动后解决。谢谢支持！
