### ISSUE TITLE
Links to other VNote notes

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#632]
OS Version (操作系统): Linux

VNote Version (VNote版本): Latest (最新)

Symptoms (表现): linking to other Vnote notes not possible?

How to Repro (如何复现):

II have not found this feature so I assume it is not there. If I am right. is there a possibility to add it?

**Comment by tamlok** [comment]
Copy thee file path of one note in the note list via context menu, then paste in editor and you will see.

**Comment by DutchPete** [comment]
Brilliant, yes that works !
What about a link to a file outside of VNote?  For example in a VNote note I would like to make a link to a PDF file in a non-VNote folder. Is that possible?

**Comment by tamlok** [comment]
Spaces in URL should be escaped to `20%`. Just copy your image file and paste in the editor. Manual maintenance is not needed.

**Comment by DutchPete** [comment]
Copy/paste is OK for a one-off image because it does not change anymore. But I also have an image that is a screenshot of an Excel sheet, and that image gets updated as the Excel sheet changes.
In that case I need a link in my note so it updates dynamically. When you say
"Spaces in URL should be escaped to `20%`, what do you mean exactly? Can you take the 2nd link I provided above as an example and show what it should look like?

BTW, I want to congratulate you on a very interesting note management app. People tend to confuse note-taking and note management. VNote is note-taking AND note management, and has a lot of features. I just discovered it 2 days ago.

**Comment by tamlok** [comment]
Hi,

The second example should be `*![events feb 19](/home/peter/Documents/2019%20events/events20%feb%202019.png)`.

Thank you!

Ref: https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20

**Comment by DutchPete** [comment]
Thank you Le Tan, that works. Basically any gaps in the link should filled with `%20`. BTW, not 20%   ;-)

**Comment by DutchPete** [comment]
Is there a possibility to link to a specific header or paragraph in a note? Sometimes it is called an *anchor*.

**Comment by DutchPete** [comment]
This is certainly a [Markdown feature](https://stackoverflow.com/questions/6695439/how-to-link-to-a-named-anchor-in-multimarkdown) but does not seem to be supported by VNote.
Am I right? If so, will VNote eventually be amended to support this?
