### ISSUE TITLE
Copy/paste Excel matrix

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#634]
OS Version (操作系统): Linux

VNote Version (VNote版本): Latest (最新)

Symptoms (表现): currently VNote does not seem to allow that a matrix made in Excel is pasted into VNote. If that statement is correct, is it possible to have that feature?

How to Repro (如何复现):

**Comment by kerhbal** [comment]
Do you mean this operation?

![69bbca83ly1fx0t0vmuyvg20](https://user-images.githubusercontent.com/11629684/53031744-6ee92a00-343b-11e9-8b29-50f6215391c3.gif)

**Comment by DutchPete** [comment]
Yes, I mean what you show in the GIF, just a simple copy/paste of a block of numbers in rows and columns, like you show.

1 aspect that is important to bear in mind is that in Excel (or LibreOffice Calc) rows and columns can be hidden. So if a block of numbers has hidden rows and/or columns, then is copied, those hidden rows and/or columns should NOT be pasted. At the moment, when one pastes such a block, those hidden rows and/or numbers are pasted :-((

**Comment by kerhbal** [comment]
It seems act differently on my side.

![69bbca83ly1fx0t0vmuyvg20](https://user-images.githubusercontent.com/11629684/53040819-5f281080-3450-11e9-88a6-d07ea65ecff8.gif)

**Comment by DutchPete** [comment]
OK, maybe it is because I use FreeOffice Planmaker, instead of Excel.
I tried it with LibreOffice, that gives 3 choices: paste as mage, image link, or as text.
Typora supports the paste from Planmaker as a table without the hidden rows.

So, there is something about Planmaker that VNote does not support. OK, I accept.
Thanks for your time.

**Comment by kerhbal** [comment]
Maybe you can test with [copyq](https://hluk.github.io/CopyQ/) , a clipboard software, to see what's actually in the clipboard. And you can find if anything is different in libreoffice. BTW, to paste as markdown in vnote, you can right click at blank place and choose "paste as markdown ".
**Here is my steps:**
![image](https://user-images.githubusercontent.com/11629684/53104362-3ad63d80-34fd-11e9-913e-fe0f06641c83.png)
**hide it:**
![image](https://user-images.githubusercontent.com/11629684/53104393-49bcf000-34fd-11e9-9f46-d72eab58cebd.png)

**and copy:**
![image](https://user-images.githubusercontent.com/11629684/53104448-5f321a00-34fd-11e9-9e95-98162e207259.png)

**there are two formats in my clipboard:** 
**the plain text:**
![image](https://user-images.githubusercontent.com/11629684/53104489-74a74400-34fd-11e9-9f1f-166829a257d6.png)

**html:**

```html

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/xxx/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/xxx/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.75in .7in .75in .7in;
	mso-header-margin:.3in;
	mso-footer-margin:.3in;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
-->
</style>
</head>

<body link="#0563C1" vlink="#954F72">

<table border=0 cellpadding=0 cellspacing=0 width=201 style='border-collapse:
 collapse;width:150pt'>
<!--StartFragment-->
 <col width=67 span=3 style='width:50pt'>
 <tr height=19 style='height:14.4pt'>
  <td height=19 width=67 style='height:14.4pt;width:50pt'>show</td>
  <td width=67 style='width:50pt'>show</td>
  <td width=67 style='width:50pt'>show</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'>show</td>
  <td>show</td>
  <td>show</td>
 </tr>
<!--EndFragment-->
</table>

</body>

</html>

```

**Comment by DutchPete** [comment]
Kerhbal, you guys are amazing !! Pasting as markdown works !! Another "hurdle" overcome. I did not have to use CopyQ for analysis. Having said that, CopyQ seems to be a useful and powerful tool.
