### ISSUE TITLE
Highlight text

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#635]
OS Version (操作系统): Linux

VNote Version (VNote版本): Latest (最新)

Symptoms (表现): I have not found an option to turn on highlighting of ordinary text. Markdown editors that offer this feature usually do so by == on either side of a word.
Is it possible to offer this feature in VNote?

How to Repro (如何复现):

**Comment by kerhbal** [comment]
According to the founder @tamlok 
Highlighting is not part of github flavored markdown syntax, so it may not be supported in vnote. But you can use html code to do that:
`<mark>xxx</mark>`
![image](https://user-images.githubusercontent.com/11629684/53050718-f9478300-3467-11e9-8707-a3658afc3f29.png)

**Comment by tamlok** [comment]
Or `<mark>`

**Comment by DutchPete** [comment]
You are right, it's not part of github flavored markdown syntax, sorry to have troubled you.
In any case the HTML syntax works. Many thanks.
