### ISSUE TITLE
Opening HTML file

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#637]
OS Version (操作系统): Linux

VNote Version (VNote版本): Latest (最新)

Symptoms (表现): the more I learn about VNote the more I like it. I just made an interesting discovery: VNote can open an HTML file perfectly, well, almost perfectly as I will explain.
When I open an HTML file, VNote opens it, but when I go to the *Edit* mode amendments are not picked up. For that to work, I open a new, blank note, then copy/paste the HTML text into it, and amendments are picked up. My question is: is there a way so I do not have to go through  the new page > copy/paste routine? Am I doing something wrong?

FYI, Typora cannot open HTML files, makes a jumble out the text. Typora is just a markdown editor/note-taking app, of course, whereas VNote is a note-taking/management app. My current note-taking/management app is Cherrytree (CT), and I use Typora for writing some basic texts. CT saves the files in a proprietary .ctb format, and only supports export of notes to plain text files or to HTML files.

I no longer want to be locked into CT, so am considering how to best migrate to an app that offers perfect portability of my notes. Having them in .md format achieves portability, VNote offers good management, as well as note-taking. I am seriously considering exporting my CT notes as HTML files, then opening them in VNote, where I can amend and keep them. Apart from the issue outlined in the 1st paragraph, there are other issues, such as having to reset headers, re-establish links between notes, etc. All of that is very time-consuming, but seems to be worthwhile from a long term perspective.

How to Repro (如何复现):

**Comment by DutchPete** [comment]
Any ideas about the issue in paragraph 1?
And if you have some suggestions how to best migrate from CT please let me know too.

BTW, I did a bit of advertising for VNote - see comments section on each of these webpages:
[](https://www.ghacks.net/2018/12/23/boostnote-is-an-open-source-onenote-alternative/#comment-4403809)
[](https://www.omgubuntu.co.uk/2017/11/notes-up-markdown-editor-for-linux)

**Comment by tamlok** [comment]
Hi,

VNote's support for HTML is not complete yet. I suggest to copy rich text content of one note in CT and ParseAsMarkdown in VNote (in the context menu) when necessary. That is migrate notes one by one when you need that note.

**Comment by DutchPete** [comment]
Yes that works, many thanks.
