### ISSUE TITLE
<pre></pre> block always shows the scroll bar

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#64]
![image](https://user-images.githubusercontent.com/8821870/33702456-9443cea4-db5e-11e7-8e1f-f1e55bf9d9fd.png)
It is not a bug, I think. But it's nice to not have the scroll bar.

**Comment by tamlok** [comment]
Do you mean a fenced code block? It does not show the scroll bar here:

![image](https://user-images.githubusercontent.com/5763157/33766346-0a43f13e-dc58-11e7-83f9-adccbdeac56c.png)

Could you provide the Markdown text?

Thanks!

**Comment by seaspeak** [comment]
It's not markdown language. It's html. Sometimes I will use `<pre></pre>`
to mark something fenced block is not suitable for.

<pre>
Usage: grep [OPTION] . . .PATTERN [FILE] . . .
</pre>

**Comment by tamlok** [comment]
Already fix it in (1a866fb0e0927f0ab950e95ca8853d869a8bbf1a). Will be carried in next version.

Thanks!
