### ISSUE TITLE
导出PDF图片缩放问题

### ISSUE THREAD

**Issue by 1049451037** [tamlok/vnote#642]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2

Symptoms (表现):

图片长宽与原始图片不一致，手动设置=widthx，显示的大小跟导出PDF看到的大小不一样，所以还得每次重新导出看宽度是否合适，感觉有点麻烦，能否改进一下，多谢！

How to Repro (如何复现):

插入图片，导出PDF。

**Comment by tamlok** [comment]
Hi,

能否具体说一下操作步骤和效果？

- 默认pdf导出还是wkhtml2pdf导出？导出的时候的设置是怎么样？
- 导出后的效果截图？预期效果？
- 是否使用自定义样式？

这些都有助于开发者复现和解决问题，节省时间。

谢谢！

**Comment by 1049451037** [comment]
比如我在笔记里放了一个柱状图：

![image](https://user-images.githubusercontent.com/15194939/53308382-9e84b000-38db-11e9-99f2-2f66d1204e2c.png)

预览效果不错，于是导出PDF：

![image](https://user-images.githubusercontent.com/15194939/53308398-cd028b00-38db-11e9-8d93-09dfb39f16ce.png)

结果，图片被缩放到模糊不清了：

![image](https://user-images.githubusercontent.com/15194939/53308436-38e4f380-38dc-11e9-9874-e445871b8ee5.png)

**Comment by tamlok** [comment]
这是因为PDF没有滚动条，所以如果图片超出页面宽度，会被缩放。你觉得还有其他的解决方案吗？

**Comment by 1049451037** [comment]
能否设置一下if，图片宽度超过页面就缩放，否则不缩放呢？

**Comment by tamlok** [comment]
随手截了一个小图，导出后好像没有被缩放？

![image](https://user-images.githubusercontent.com/5763157/53309749-8c5b3f80-38e4-11e9-9459-96acbc96034f.png)

**Comment by 1049451037** [comment]
额……有没有可能是系统的问题？我是Ubuntu 18.04

**Comment by 1049451037** [comment]
我试了一下，换成wkhtml2pdf就好了

**Comment by miurahr** [comment]
Can we close here?
