### ISSUE TITLE
代码块缺少最后一行

### ISSUE THREAD

**Issue by dasnnj** [tamlok/vnote#643]
OS Version (操作系统): Windows

VNote Version：2.2

Symptoms (表现):
使用代码块语法
```
int a= 0;
int b=0;
```
会少显示第二行int b = 0;
必须在int b = 0;后面再加一个空行才能把第二行显示出来

**Comment by dasnnj** [comment]
我需要关掉这个issue,因为在我的个人电脑上是有这个问题的，可是换了一台电脑就没有这个问题

**Comment by tamlok** [comment]
Hi, 一定是语法问题，能否贴一个能复现这个问题的文件或者完整文本？

**Comment by dasnnj** [comment]
> Hi, 一定是语法问题，能否贴一个能复现这个问题的文件或者完整文本？

嗯感谢回复，我晚上回家会贴一下的，昨天写博客出现的问题，然后今天把代码同步过来用另一台电脑打开却没问题

**Comment by dasnnj** [comment]
渲染器是Marked的时候代码如下
![image](https://user-images.githubusercontent.com/24741477/53340749-eb50a100-3944-11e9-8e04-c5a701cb3417.png)
会出现
![image](https://user-images.githubusercontent.com/24741477/53340790-ce1bd280-3944-11e9-8007-68940c6ef7d2.png)
另外 这种语法只有一个渲染器支持
![image](https://user-images.githubusercontent.com/24741477/53340925-2eab0f80-3945-11e9-94f9-c10b1eb7b04a.png)

**Comment by tamlok** [comment]
首先，这是在一个列表下面的代码块，整个代码块都需要缩进。要测试这个问题，可以把除了代码块外的所有内容删除，应该会渲染正常。关于列表里面嵌套代码块的语法，请搜一下。

两个等号高亮不是标准语法哦，另外，markdown-it是默认的支持的渲染器，其他渲染器在vnote里面都只是尽力支持。

**Comment by dasnnj** [comment]
> 首先，这是在一个列表下面的代码块，整个代码块都需要缩进。要测试这个问题，可以把除了代码块外的所有内容删除，应该会渲染正常。关于列表里面嵌套代码块的语法，请搜一下。
> 
> 两个等号高亮不是标准语法哦，另外，markdown-it是默认的支持的渲染器，其他渲染器在vnote里面都只是尽力支持。

get，后面我换一下渲染器。然后我测试了一下你说的删除出了代码块以外的内容，发现marked渲染器仍然是缺少一行
