### ISSUE TITLE
表格中的元素带有"|"字符时无法正常渲染

### ISSUE THREAD

**Issue by kaakboom** [tamlok/vnote#644]
例子：
|  A  | $P(B|A)$ |
| --- | -------- |
| 0.5 | 0.25     |
应该是parse的时候把P(B|A)中间的"|" 也识别成了表格的分割符

**Comment by Memento1990** [comment]
在特殊字符前加 `\` 进行转义即可, eg:
| $P(B\|A)$ |

**Comment by kaakboom** [comment]
> 
> 
> 在特殊字符前加 `\` 进行转义即可, eg:
> | $P(B|A)$ |

可以了，谢谢
