### ISSUE TITLE
一个问题：新建文件之后再重命名，有时候没法粘贴文字

### ISSUE THREAD

**Issue by amosCc** [tamlok/vnote#646]
OS Version (操作系统): Windows, 

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
新建文件之后再重命名，有时候没法粘贴文字

How to Repro (如何复现):
就是新建文件之后，想再重命名的时候，已经复制了一行文字，但是右键粘贴和快捷键粘贴的时候没法粘贴文字，没有反应，不知道为什么。
然后出现这个问题的时候我退出了软件，再重启软件，还是没有用……

**Comment by tamlok** [comment]
hi，

应该是复制的文字里面包含了文件名非法字符，可以尝试仅仅复制一些简单的字母文字来测试一下。
