### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#647]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现): The Outline is a hierarchical tree of (sub)headers in a note. The small triangles can be used for collapsing or expanding a header section. When e.g. in note 1 only 1 or all the (sub)headers are collapsed, and note 2 is selected, then one goes back to note 1, all the collapsed sections in note 1 are expanded again.
It is possible to keep/freeze the status of an Outline fixed? This applies to sections on a page, some of which might be partly collapsed, others entirely collapsed, others entirely expanded.
If this is not possible right now I would like to request it as a feature.

How to Repro (如何复现):

**Comment by tamlok** [comment]
VNote now does not store the expansion status of the outline. You could try the left/right arrow at the up right corner to constrain the expansion level.

**Comment by DutchPete** [comment]
That goes some way towards what I mean, although those arrows are an across the board measure, i.e. constraining e.g. to expansion level 3 means it is applied to all the notes in the notebook. Also, it does not allow one header to be limited to e.g. expansion level 3 and another header in the same note to e.g. expansion level 5.
Is there an intention to develop this?
A more general question: is VNote still being actively developed?

**Comment by tamlok** [comment]
Hi,

Will consider restoring the expansion status for each note in the future.

After developing VNote for more than 2 years, I am sad to see that there is still one main contributor in development (thanks @miurahr very much and it is a pity that VNote could not catch his eyes earlier), which makes me tired. Another fact is that VNote now is not extensible and needs to be refactored. Hence I am considering developing **VNoteX** based on VNote and temporarily stop adding new features to VNote.

**Comment by kerhbal** [comment]
@tamlok Any ideas about the platform? Still QT or change to electron? And anything decided about opensource/close-source ? Thanks for such handy tool!

**Comment by DutchPete** [comment]
@tamlok : 1st of all I want to thank you for your patience with my many questions.
Secondly I want to thank you for a very good, interesting, very useful Markdown note-taking app/management tool. :+1:  :+1:  :+1: 
When one looks on internet for this kind of app, VNote is not listed, which is a pity - for my use case it is better than Evernote, OneNote, both of which I used, and many well-known others, some of which I used. I really hope VNote will continue to exist, esp. the Linux version. Have you thought about a paid version?

I don't know what refactoring is, but can you give an indication of what VNoteX will be like compared with VNote? Any idea about a timeline?

**Comment by kerhbal** [comment]
@DutchPete Agreed. Also tried Evernote, OneNote before.

**Comment by DutchPete** [comment]
> @DutchPete Agreed. Also tried Evernote, OneNote before.

@kerhbal I also tried a more direct competitor of VNote: QOwnNotes, which is also a Markdown note-taking/management app. I did not like the interface at all, found it confusing, and did not get out of it what I wanted. I tried it twice and twice ended up ditching it, the 2nd time for good. I also found the dev to be somewhat arrogant.

I use Typora too for compiling texts - it is a fantastic markdown editor, but an editor only. Its note management capabilities are rudimentary. I was really happy when I stumbled on to VNote, exactly what I was looking for. Is it perfect? No, but nothing in life is perfect. I sincerely hope Le Tan will manage to keep VNote or its successor going.

In any case, all VN notes are fully portable so whatever happens my notes are safe, not locked into some proprietary format like OneNote.

**Comment by tamlok** [comment]
@kerhbal @DutchPete 

Hi,

Some considerations about VNoteX:

1. Qt 5.12 with Python plugin extensions enabled;
2. Will **not** be open source for now but still free of charge;
3. VNoteX will inherit almost everything from VNote and can read VNote's data;
4. Still available on Linux, Windows, and macOS;
5. Currently there is no a scheduled timeline but I am already working on it.

Thanks!

**Comment by DutchPete** [comment]
@tamlok thanks for that info Le Tan.
Sounds interesting. For now I am going ahead with VNote.
What is the reason VNoteX will not be open source?

**Comment by kerhbal** [comment]
@tamlok Thank you. Looking forward to it.

**Comment by tamlok** [comment]
@DutchPete For such an app, open source seems not to make a difference (an open source library could benefit lots of developers instead).

**Comment by DutchPete** [comment]
@tamlok OK, thanks for your honesty, I understand now.
Out of interest: do you feel that VNote has benefited other developers?
Isn't <i>open source</i> and added marketing advantage?

**Comment by tamlok** [comment]
For the "make no difference" here, I mean it is hard for a CPP and GUI APP project to atract other developers to participate in. So open-sourcing VNoteX seems not so attractive to me. :)

**Comment by DutchPete** [comment]
OK, I understand.I wish you good luck with the project. Let us know via this page if/when VNoteX is operational.
