### ISSUE TITLE
mac下新建笔记打开笔记卡顿，点击部分菜单卡顿

### ISSUE THREAD

**Issue by willtse** [tamlok/vnote#649]
OS Version (操作系统): macOS 10.14.2

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2

Symptoms (表现):
1. 打开应用时，系统会出现10秒-30秒(貌似和上次退出前打开的标签页数目有关，越多时间越长)左右的卡顿（系统除了鼠标什么都操作不了）；
2. 进入应用后，每打开一个笔记也会卡顿5秒-10秒；
3. 使用右键菜单或者`⌥+⌘+N`新建笔记时，输入文件名后点击确定后，在新的笔记的标签页出来后系统也会卡顿5秒-10秒；
4. 点击部分会出现新qt窗口的菜单项也会卡顿3-5秒，如`文件-自定义快捷键`和`编辑-编辑器样式-添加样式`。

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

请更新2.3测试一下？这次构建使用了新的xcode和qt 5.9.7，看能否解决。

**Comment by willtse** [comment]
十分感谢！ 下载安装了`VNote-2.3-x64.dmg`，试了一下，现在感觉比之前好多了，每打开一个笔记只会卡顿1-2秒了。
其实最近两天我尝试自己编译安装了VNote，用的homebrew安装的`qt5.12.1`，阅读模式会出现这里这个错误 #258 #263 ，但是一点都不卡，打开每个笔记都是秒开。
我觉得应该是qt5.9在macOS 10.14 下的问题吧... >_< ，期待等您以后的更新，非常感谢您的工具。

**Comment by tamlok** [comment]
赞！那我改天试试xcode最新版看看，到时候给个链接您，麻烦帮忙测试一下。

**Comment by tamlok** [comment]
现在可以自行用5.12编译了。

**Comment by willtse** [comment]
刚刚自行编译了一下，感觉丝般顺滑！谢谢！

**Comment by tamlok** [comment]
那干脆后面全部上Qt 5.12得了。期待5.12下面的积极反馈。
