### ISSUE TITLE
建议加入windows版本实时编译新版本

### ISSUE THREAD

**Issue by bequt** [tamlok/vnote#65]
建议加入windows版本实时编译新版本

**Comment by tamlok** [comment]
Hi，VNote是有持续构建的版本的，链接是[Bintray](https://bintray.com/tamlok/vnote/vnote/_latestVersion)，不过对国内网速要求可能有点高。只要master分支有更新，这里就会更新。

另外，qq群里也会不定时有测试版本。

谢谢关注！

**Comment by bequt** [comment]
谢谢你的回答，支持您
