### ISSUE TITLE
Relationship note-folder

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#652]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现): when I have a note open, it is not necessarily a note relating to the folder that is highlighted in the tree structure in the pane on the left. Is there a way to easily, quickly establish which folder a note belongs to? Of course, if one reads through the note one can find out, but some notes a long, some may be similar, .... whatever. Reading through the note is not the most efficient way.

How to Repro (如何复现):

**Comment by tamlok** [comment]
Right click on the tab of opened notes and there is a `Locate to folder` option. Or `Ctrl+E D`.

**Comment by DutchPete** [comment]
Got it. Another possibility: hover you mouse over the tab and a green "tool tip" shows the path :smile:
There seem to be many little jewels like that in VNote. I keep discovering them. I am really beginning to like VN more & more, and that is not meant to sweet-talk you !!

**Comment by mtibbi** [comment]
I had the same doubt as DutchPete.
It's fine for me to use the key combination to refresh the left panel, but sometimes I was confused by the mismatched highlights and thought I was editing another document.
As a suggestion for improvement, the highlights in the left panel should be cleared when there is no match to the active note (in focus) in the editor.

**Comment by tamlok** [comment]
@mtibbi Maybe I will add a switch to decide whether let the left panel follow the edit tab.

**Comment by mtibbi** [comment]
**@tamlok**, That would be a better solution.
Thanks for the prompt reply to my comment.

**Comment by DutchPete** [comment]
@tamlok will that switch be added to VNote too or only to VNoteX?

**Comment by tamlok** [comment]
Fixed. Please try latest build [here](https://bintray.com/tamlok/vnote/vnote/2.3#files).

You need to add `sync_note_list_to_current_tab=true` under the `[global]` section of `vnote.ini`. You could file the `vnote.ini` file in `File` menu and `Open Configuration Folder` menu item. Restart VNote to let it work.

**Comment by DutchPete** [comment]
@tamlok I amended the `vnote.ini` file as indicated. but I see no difference.

So, let's say in the left hand pane I click on folder, which is then highlighted. And let's say I click on note 1, which is opened as a new tab in the tab bar.
If, in the tab bar, I subsequently click on note 3 (located in folder Y), folder X remains highlighted in the left hand pane.

The expected behaviour would be for folder Y to be shown AND highlighted in the left hand pane.

BTW, earlier today I download version 2.3 before you made this fix. Could it be that the "old" version 2.3 is not good anymore? **If** that's the case, the "new" version 2.3 should be to renamed to something like 2.3.1 or 2.4 or .... whatever.

**Comment by tamlok** [comment]
Paste you `vnote.ini` please.

**Comment by DutchPete** [comment]
`[global]
allow_user_track=true
attachment_folder=attachments
code_block_css_style=
confirm_images_clean_up=false
css_style=v_pure/v_pure
current_background_color=System
editor_style=
enable_auto_save=false
enable_backup_file=true
enable_image_caption=true
external_image_folder=_v_images
heading_sequence_type=1
highlight_matches_in_page=true
image_folder=images
insert_title_from_note_name=false
keyboard_layout=
minimize_to_system_tray=0
note_list_view_order=1
outline_expanded_level=2
search_dock_checked=true
search_options=5, 2, 7, 0, 4, 
single_click_close_previous_tab=false
split_file_list=false
sync_note_list_to_current_tab=true
theme=v_pure
tools_dock_checked=true
version=2.3

[shortcuts]
ActivateNextTab=Ctrl+Tab`

**Comment by mtibbi** [comment]
**@tamlok**, I tested the win_x64 version and it is working as expected. When you click on any editor tab, the highlights in left panel point to the active document. The only exception is for documents that are not in a notebook, this is the case of flash_page that resides in the configuration folder. In such cases I think it would be better to fade out, or wipe out, the highlights in the left panel.

Thank you for offering such a quick solution to my problem!

**Comment by tamlok** [comment]
@DutchPete I need to test it on Linux. BTW, I think you need to refer to the Markdown Guidance in the help menu for the syntax of a fenced code block.

**Comment by DutchPete** [comment]
```
[global]
allow_user_track=true
attachment_folder=attachments
code_block_css_style=
confirm_images_clean_up=false
css_style=v_pure/v_pure
current_background_color=System
editor_style=
enable_auto_save=false
enable_backup_file=true
enable_image_caption=true
external_image_folder=_v_images
heading_sequence_type=1
highlight_matches_in_page=true
image_folder=images
insert_title_from_note_name=false
keyboard_layout=
minimize_to_system_tray=0
note_list_view_order=1
outline_expanded_level=2
search_dock_checked=true
search_options=5, 2, 7, 0, 4,
single_click_close_previous_tab=false
split_file_list=false
sync_note_list_to_current_tab=true
theme=v_pure
tools_dock_checked=true
version=2.3

[shortcuts]
ActivateNextTab=Ctrl+Tab
```

**Comment by tamlok** [comment]
Tested on Linux and it works as expected.

**Comment by DutchPete** [comment]
@tamlok I am sorry but it does not work at all on Linux Mint, which is based on Ubuntu.
1.You have not made any comment about the code I have added to the `vnote.ini` file, so I assume it is correct. Am I right?
2. I assume we are in agreement about what the expectation is. Am I right?
3. What Linux distro did you test it on?
4. Is there anything else I should do at my end?

**Comment by tamlok** [comment]
Your config seems right. I tested on openSUSE. I don't know what is the potential issue. Just let it be and let's wait for VNoteX.

**Comment by DutchPete** [comment]
openSUSE is quite different from Mint. I agree to leave it at this, since it is not a major issue, and wait for VNoteX. Thanks anyway for trying to resolve it.
