### ISSUE TITLE
图片或表格是否可居中显示？

### ISSUE THREAD

**Issue by cranebeta** [tamlok/vnote#653]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2

编辑或阅读模式下，图片和表格是否可选居中显示？不知道目前是否支持该功能，试了下写html的方式，好像没有效果。

**Comment by tamlok** [comment]
阅读模式下，md菜单里面有一个显示图片标题选项，勾选后会居中显示图片。

可以通过自定义css文件的方式控制样式，具体参考文档进行自定义样式。

编辑模式不支持。

**Comment by cranebeta** [comment]
好的，太感谢了

**Comment by CherryChung** [comment]
3.0版本貌似没有看到这个设置选型哦
