### ISSUE TITLE
Close root folder?

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#654]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现): when I open VNote it shows all the root folders I have created - currently only 2. Is it possible to close the root folder I do not use?

How to Repro (如何复现):

**Comment by tamlok** [comment]
What does "close the root folder" mean?

**Comment by DutchPete** [comment]
From what I understand @kerhbal explained [here](https://github.com/tamlok/vnote/issues/640), there is a notebook with root folders and child folders and notes.

My notebook is called *Vnote*, and inside it I have to folders (i.e. root folders), each of which has child folders and notes.
I used one of the 2 root folders for testing purposes when I discovered *VNote* as a program and was trying out various features and possibilities. Both root folders are is shown in the top panel on the right when I open VNote app, but I do not want to see the test folder. Is there a way to close it, or hide it?

**Comment by tamlok** [comment]
Attach a screenshot to illustrate?

**Comment by DutchPete** [comment]
@tamlok Are you now working night time? Just joking.
Please tell me how I can attach a screenshot to an answer here, I don't see a button for it. My apologies if I seem a bit dumb.

**Comment by tamlok** [comment]
Just drag an image to the input dialog or copy&paste. Github will upload the image.

**Comment by DutchPete** [comment]
Sorry, neither drag & drop nor copy/paste work, so here is a link to [Imgur](https://imgur.com/yShNdrn)

**Comment by tamlok** [comment]
If there are 2 folders in your computer and now you don't need one of them, what you need to do is just simply deleting it. That is the same in VNote's folders.

**Comment by DutchPete** [comment]
I understand that deleting a folder is possible, but I don't want to delete my *Test* folder (yet), I just don't want to see it listed for the time being.
Judging by your reply I guess the answer is that it is not possible to not have it listed. In other words, all root folders I create will always be listed, and delisting them means deleting them. Right?

**Comment by tamlok** [comment]
Yes! Hiding a folder is not so friendly since you may not be aware of this after a while.

**Comment by DutchPete** [comment]
OK, thanks for your patience :smile:
