### ISSUE TITLE
Outline shows backslash "\"

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#660]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现): 
Outline shows backslash "\"

How to Repro (如何复现):
Title:
`# the \<form> Element`
Outline:
the \\\<form> Element

**Comment by tamlok** [comment]
The outline in edit mode just show what it is in editor, no conversion to HTML.

**Comment by seaspeak** [comment]
OK. I'll close this.
