### ISSUE TITLE
阅读模式不能加粗/倾斜带标点符号的句子

### ISSUE THREAD

**Issue by Lisuaki** [tamlok/vnote#662]
OS Version (操作系统): Windows 10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3, 最新版
Symptoms (表现):阅读模式不能加粗/倾斜带标点符号的句子

How to Repro (如何复现):
举个例子↓
想要这样的格式：
**那么鱼呢？**鱼大概就是佛吧。

然后在编辑模式就能正常看到被加粗的效果：
**那么鱼呢？**鱼大概就是佛吧。

然后保存阅读结果就变成星号了
**那么鱼呢？**鱼大概就是佛吧。

然后发现如果不带符号的话像这样：
**那么鱼呢**？鱼大概就是佛吧。

就能正确的显示
强迫症表示写文章的时候比较难受啊，要么不带符号要么只能整段加格式，百度和翻issue也没找到，反馈一下吧(°ー°〃)

哦不对哦，怎么Github的编辑器也是这样，尴尬了

**Comment by kerhbal** [comment]
如图，在123前面加个空格即可，好像这问题以前提到过，应该是markdown-it的bug
![image](https://user-images.githubusercontent.com/11629684/54088301-07841300-4333-11e9-8de9-fd1945095c76.png)
![image](https://user-images.githubusercontent.com/11629684/54088302-0c48c700-4333-11e9-8c31-7c1ad24fcb1e.png)

**Comment by Lisuaki** [comment]
Soga，看到预览能用结果阅读模式不能用就懵了，感谢感谢( •̀ ω •́ )y

**Comment by tamlok** [comment]
可以试试片段来快速
