### ISSUE TITLE
从系统托盘最大化时，窗口排列不正常

### ISSUE THREAD

**Issue by Stivenke** [tamlok/vnote#665]
OS Version (操作系统): Windows x64 17134

(VNote版本): 2.3

Symptoms (表现):
![20190312](https://user-images.githubusercontent.com/23474403/54174311-cfaad600-44c0-11e9-9265-255ae3fba0bb.png)

How to Repro (如何复现):
在勾选系统托盘（文件-->设置-->常规-->系统托盘 [勾选]），最小化窗口（或 X 窗口）后，再单击系统托盘上的 VNote 图标，还原窗口时，就会出现。
此时，再单击窗口最大化按钮两次，就可以恢复正常。

**Comment by tamlok** [comment]
Hi,

显卡驱动问题，请参考[文档](https://tamlok.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#toc_8)，可以尝试在设置中改变opengl的值，然后重启。

**Comment by Stivenke** [comment]
谢谢！
试了一下，将 文件-->设置-->常规-->OpenGL 改成其他值（非默认值），就可以了。
