### ISSUE TITLE
Advertising

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#666]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):Just to let you know I advertised a bit more for VNote. Not because I have an axe to grind but simply because I like the app and I think you deserve it
Here is the link: [Notable](https://github.com/notable/notable/issues/26#issuecomment-471878132)

How to Repro (如何复现):

**Comment by arcturus140** [comment]
Now this is quite a diabolic issue here, #666!

**Comment by LuoshuiTianyi** [comment]
As a Chinese,I think this behavior is not so poliet for the author.Because in our opinions,we shouldn't say 'Another is better than this one'.We think it will show the disrespect.

I think you can advertise it at some public platform,but not under other authors' works.Or this kind of behavior will be called "黑粉" in Chinese.

But I don't know what's your idea.Maybe I'm much sensitive.

How do you think?

**Comment by DutchPete** [comment]
@LuoshuiTianyi the reason I did it is because the other commenter mentioned that for the time being he is using note-taking app X - I cannot remember the name of the app. I, as well as someone else, had had a discussion with the dev about a feature that he refused to see the benefit of, which surprised me.

So, I just mentioned to the other commenter using app X that I discovered VNote and was alsousing Typora, both of which are a competitor of Notable, the app where I posted my comment. But, if I am not mistaken, I did NOT say that VNote or Typora were better than Notable.

Nevertheless, I do not think you are too sensitive and take your point: I will not comment like that again.  I have absolutely no knowledge of the Chinese language so "黑粉" does not mean anything to me, but from the context in your sentence I can guess what is likely to mean. Sorry.

**Comment by kerhbal** [comment]
@DutchPete "黑粉" means "dark fans", which basically are a part of fans that continuing looking for trouble in other competitors repository/socialmedia/circle/public space by starting some conversation about the comparison of full of nonsense. Of course I don't think what you did is any of that, but it's true that there is a little chance someone may think that way.

**Comment by DutchPete** [comment]
@kerhbal thanks for the explanation; I thought it meant some like "dumb jerk". Anyhow, I got my 1st Chinese language lesson ;-))
I shall remove the comment.

**Comment by kerhbal** [comment]
You're welcome. Personally I don't think it's a big deal since it's just a simple conversation about concrete function suggestions.

**Comment by DutchPete** [comment]
I have deleted the somewhat insulting part of my comment, i.e. the bit that references VNote and Typora.
