### ISSUE TITLE
高分屏界面错位问题

### ISSUE THREAD

**Issue by wgjas2** [tamlok/vnote#667]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3, fcfc1ca..

Symptoms (表现):高分屏下有缩放问题：预览模式下定位不准（鼠标单击位置偏移）、界面边缘被裁切，切换成编辑模式会弹回来并且定位恢复，边缘回归，菜单会有工具栏的重影（鼠标滑过后恢复）。

How to Repro (如何复现): 屏幕缩放不为100%就会复现（我的屏幕是4K屏缩放200%）

**Comment by tamlok** [comment]
Hi,

应该是显卡驱动问题。请参考 https://github.com/tamlok/vnote/issues/665 以及文档进行解决。

**Comment by wgjas2** [comment]
谢谢，改成非默认就可以了。

**Comment by wgjas2** [comment]
谢谢，改成非默认就可以了。
