### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#670]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现): a right-click on a note title in the left panel shows *info* in the context. Selecting that shows a tag field in the dialogue box, but it is not possible to put anything in that field. is it possible to tag a note?

How to Repro (如何复现):

**Comment by kerhbal** [comment]
![image](https://user-images.githubusercontent.com/11629684/54388156-7e8f1380-4673-11e9-8460-7ce2ce2a9c69.png)
You can add tags here.

**Comment by DutchPete** [comment]
@kerhbal thank you, once again !!

**Comment by DiamondI** [comment]
> ![image](https://user-images.githubusercontent.com/11629684/54388156-7e8f1380-4673-11e9-8460-7ce2ce2a9c69.png)
> You can add tags here.

![image](https://user-images.githubusercontent.com/18584660/63564432-a32ed600-c597-11e9-9780-afa9e43ba826.png)

The `tag` dialogue box in `info` pane is quite confusing for that it looks like an editable field. I think it's better to make it more like an uneditable field.
