### ISSUE TITLE
能否增加个类似typora实时预览的模式

### ISSUE THREAD

**Issue by wupengchoy** [tamlok/vnote#673]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
markdown编辑不能像typora一样能够实时渲染结果。

How to Repro (如何复现):

能否增加个类似typora实时预览的模式

**Comment by Stivenke** [comment]
恕我多嘴，建议看一下作者写的“为什么需要VNote” https://tamlok.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E4%B8%BA%E4%BB%80%E4%B9%88%E9%9C%80%E8%A6%81VNote.md

**Comment by wupengchoy** [comment]
原来如此，多谢

**Comment by ChungZH** [comment]
所以 close 掉这个 issue 吧。
