### ISSUE TITLE
Preserving links

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#677]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现): Let's say I have 2 note: Note A and Note B, and Note A links to Note B.
Is there a way to preserve that link if I move Note B to another location?

How to Repro (如何复现): move Note B to another folder

**Comment by tamlok** [comment]
Hi,

Since all data in VNote are plain text and you could modify your data outside VNote, so there is no way for VNote to track such things.

VNoteX will try to solve this at least in the case user manages their notes only via VNoteX.

**Comment by DutchPete** [comment]
> Since all data in VNote are plain text and you could modify your data outside VNote, so there is no way for VNote to track such things.
No, not really, because if you move note B you don't necessarily know that note A (and maybe notes D, R, V as well) links to it. You only find out by coincidence if, sometime after the move, you go to note A and see the link no longer works, in which case you can make the amendment, although that could take some time if you need to find B among the many notes you have.

> VNoteX will try to solve this at least in the case user manages their notes only via VNoteX.
OK, that's sounds good :+1:
Another feature that I hope you will preserve in VNoteX is the automatic outline numbering, that is a really useful feature, among many other useful features. I have come to love Vnote, it is a very good app, the concept is good. :+1:
