### ISSUE TITLE
vnote导出的笔记带有generated by vnote字样问题

### ISSUE THREAD

**Issue by wallezhang** [tamlok/vnote#682]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3

Symptoms (表现):
导出的pdf和html文档中，最下会有一行小字：generated by vnote，请问有计划可以去掉吗？

How to Repro (如何复现):
每次导出都可以复现

**Comment by tamlok** [comment]
暂时好像没有开关关掉。如果实在需要，可以查找替换一下源代码，重新编译。或者调用pandoc来进行导出。

**Comment by wallezhang** [comment]
> 暂时好像没有开关关掉。如果实在需要，可以查找替换一下源代码，重新编译。或者调用pandoc来进行导出。

谢谢回答哈，第一次使用，感觉比之前用的其它客户端都要好用，多谢作者
