### ISSUE TITLE
Feature suggestion for VNoteX

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#686]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现): it would be useful to be able to use *anchors*. By an *anchor* I mean a point anywhere on a note page to which another note can link. Markdown allows for linking to a header, but it does not always work or work well. As far as I know it does not work in VNote, or if does it is not easy to use.
One should not have to rely on a header, one should be able to link to a specific point on a note page.

How to Repro (如何复现):

**Comment by LuoshuiTianyi** [comment]
I think VNote will have more functions of Vim,and the “ ` ” mark function in Vim can do this work.So wait for the development of it.

**Comment by tamlok** [comment]
@LuoshuiTianyi Vim mode in VNote now supports the mark of Vim.

**Comment by DutchPete** [comment]
@tamlok I assume @LuoshuiTianyi means VNoteX, whereas you mean VNote. If this statement is correct, please explain to me:
1. How to employ the Vim mode in VNote - I have not found it in the menu
2. How to use the mark of Vim as an *anchor*.

**Comment by LuoshuiTianyi** [comment]
> @LuoshuiTianyi Vim mode in VNote now supports the mark of Vim.

OK,I know now.I haven't ever used it in VNote.

**Comment by tamlok** [comment]
Enable Vim mode via the settings dialog in the Read&Edit tab.

Try read through the shortcuts help in the help menu.

**Comment by LuoshuiTianyi** [comment]
You can open the Vim mode there.

![](http://ww1.sinaimg.cn/large/006FzndGgy1g1gjdmqwnlj30fd06ljru.jpg)

Reading the 'shortcuts help' may can help you to learn how to use this function.You can also read [this passage](https://vim.fandom.com/wiki/Using_marks),I think it's helpful,too.

**Comment by tamlok** [comment]
For your original request, I will consider refining the anchor feature in VNoteX. You still need to set an anchor via html tag if it is not a heading.

**Comment by DutchPete** [comment]
@LuoshuiTianyi thank you so much. I told @tamlok that there are hidden jewels in VNote. Those jewels should be made more explicit on the documentation page.
I am not familiar with Vim, but I will read up on it on the page you linked to. I use *anchors* a lot, so I hope I can use it in VNote. I suppose that if I use them, i.e. create them in Vim mode, I will have to stay in Vim mode permanently. Right?

**Comment by tamlok** [comment]
Mark in Vim mode is not what you are looking for. It is temporary and local to one file.

**Comment by DutchPete** [comment]
> For your original request, I will consider refining the anchor feature in VNoteX. You still need to set an anchor via html tag if it is not a heading.

OK @tamlok many thanks.
