### ISSUE TITLE
[Feature Request] 取消 Insert From Clipboard 弹窗

### ISSUE THREAD

**Issue by laggardkernel** [tamlok/vnote#687]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3

目前Insert From Clipboard非常反人类，弹出后可以使用方向键选择，但是无法Enter回车确认选择。另外，双击选中 `Insert As ...` 还有一定几率闪退。经查看剪贴板，双击时复制了选项文本，从而导致应用闪退？

希望能给出一个直接复制文本近编辑器的方法，给一个开关项。或者是改善一下弹窗的确认方法，能够全部键盘操作，每次都要操作鼠标去确认实在麻烦。

**Comment by tamlok** [comment]
无法回车确认是macos独有的问题，后面会优化一下。Ctrl-Shift-V是粘贴纯文本。

**Comment by tamlok** [comment]
根据Qt的文档，mac下面应该`Command+O`确认。后面会添加回车确认。

![image](https://user-images.githubusercontent.com/5763157/54895017-75fece80-4ef8-11e9-82b1-59458630190b.png)

**Comment by tamlok** [comment]
已经修复，请在这里下载最新构建版： https://bintray.com/tamlok/vnote/vnote/2.3#files

**Comment by laggardkernel** [comment]
用上面地址里面的测试了一下已经没有问题了，非常感谢。
