### ISSUE TITLE
如何修改存储目录(不在c盘)

### ISSUE THREAD

**Issue by baiguantao** [tamlok/vnote#688]
OS Version (操作系统): Windows, Linux, macOS
win10
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.3
Symptoms (表现):

如何修改存储目录(不在c盘)
How to Repro (如何复现):
最近重装系统，c盘的vnote写的文档没了  发现没法设置目录到其他盘符

**Comment by tamlok** [comment]
Hi,

新建笔记本的时候，笔记本根文件夹是可以随意选择的，包括D盘，只要给定一个空的目录即可。

如果希望迁移当前的笔记本，可以把笔记本根文件夹对应的那个目录复制一份到目标路径，然后在VNote里面把原来的笔记本移除（可以选择是否删除磁盘上的文件），然后新建笔记本，根文件夹选择刚才复制的目标路径的那个文件夹，VNote会重新导入该笔记本。因此，也可以把该文件夹放在第三方同步服务中，以实现多个PC之间的同步。

谢谢！

**Comment by baiguantao** [comment]
找了好久，好隐藏的位置啊
我一直是直接新建根文件夹
