### ISSUE TITLE
菜单和编辑器不支持mactype，阅读时没问题

### ISSUE THREAD

**Issue by heartnn** [tamlok/vnote#69]
![new](https://user-images.githubusercontent.com/457514/33924640-f4af95fe-e011-11e7-842f-ab63f75375c5.jpg)
![new2](https://user-images.githubusercontent.com/457514/33924645-f6d425fc-e011-11e7-9959-d2590032008a.jpg)

**Comment by tamlok** [comment]
Hi, 所以图一是有mactype的，图二是没有mactype的吗？

我没有了解过mactype，它应该是一个渲染引擎，不用更改字体文件？所以是同一套字体，支持mactype和不支持mactype的界面会有两个不同的效果？

谢谢支持！

**Comment by heartnn** [comment]
第二张是windows自带的cleartype，但是似乎是我的字体配置出问题了，清空设置系统重新生成css文件后似乎没问题了。
