### ISSUE TITLE
编辑器字号状态无法保存

### ISSUE THREAD

**Issue by wallezhang** [tamlok/vnote#690]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3

Symptoms (表现):
编辑器字号使用command + "+"调整大了之后，再次打开APP，或者关掉当前文档，重新打开，都会恢复到原始的字号大小，这个状态怎么可以保存住呢？

How to Repro (如何复现):

**Comment by tamlok** [comment]
文件菜单，设置里面可以设置。

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/54910083-9b0a3600-4f26-11e9-8681-27145c6ab54a.png)

**Comment by wallezhang** [comment]
> 文件菜单，设置里面可以设置。
> 
> ![image](https://user-images.githubusercontent.com/5763157/54910103-a3fb0780-4f26-11e9-8573-41205855fe45.png)

thanks for reply
