### ISSUE TITLE
Install VNote

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#693]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现): I initially started using the AppImage to get a feel for VNote. As you know, I have grown to love the program and would now like to install it. I have the following questions:
1. if I install VNote I suppose I can continue using the folders I have created by just clicking on *Add Notebook* in the left hand pane. Correct?
2. I suppose it is not possible to carry over my setting from the AppImage to the installed version. Correct?
3. is there a PPA so that I can get automatic notifications of updates? If yes, please point me to it.

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

Configuration locates in user's home directory. It makes no difference for different VNote's executables. There is no PPA for VNote now. I do not have time to maintain that.

Thanks!

**Comment by DutchPete** [comment]
OK, thank you.
