### ISSUE TITLE
请教Vnote在windows 7 64bit编辑的ssl支持如何实现？

### ISSUE THREAD

**Issue by donaldtone** [tamlok/vnote#695]
OS Version (操作系统): Windows7 64bit

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3
Symptoms (表现): 用qt 5.9.7 + vc2015编译成功。不过在windeployqt后，没有openssl相关的文件。Vnote倒是运行正常。
想请教一下，如何设置才能添加ssl支持？直接copy相关文件还是需要把lib编译进去？

How to Repro (如何复现):

**Comment by tamlok** [comment]
直接把openssl的几个dll文件拷贝到exe所在目录即可。你可以把vnote的压缩包下载下来提取。
