### ISSUE TITLE
编辑页面毫无响应

### ISSUE THREAD

**Issue by biubiuboom** [tamlok/vnote#698]
OS Version (操作系统): Windows10 笔记本 高分双屏

VNote Version: 2.3

Symptoms (表现):
新建一个笔记本，编辑完毕进入阅读模式后，再也无法编辑了，在编辑页面毫无响应。
无论用快捷键还是点击编辑图标。

**Comment by biubiuboom** [comment]
如下图:
[http://wx2.sinaimg.cn/large/007erPXFgy1g1lgerrabhg30r90mravn.gif](url)
传不上图,很烦.

**Comment by tamlok** [comment]
Hi,

是显卡驱动引起的opgnGL的问题，请参考 https://github.com/tamlok/vnote/issues/665 进行解决，很简单的。

**Comment by biubiuboom** [comment]
> 
> 
> Hi,
> 
> 是显卡驱动引起的 opgnGL 的问题，请参考 #665 进行解决，很简单的。

搞定了,是双显卡高分屏才会出现的问题吧
蛮普遍的
