### ISSUE TITLE
插入图片功能的建议

### ISSUE THREAD

**Issue by cairy** [tamlok/vnote#7]
1. 多次粘贴图片，每次粘贴后光标不能定位到行尾，而是在`.jp`和`g)`中间，是否是bug，弹出粘贴图片对话框，光标是否可以默认在图片标题输入框，考虑一下？
2. 图片默认是保存在images文件夹中，这个是否能配置呢？因为不同的软件要使用不同的默认文件夹，比如安卓上的*易码*要求图片在assets中才能显示（这个我要两边都反馈）

**Comment by tamlok** [comment]
您好，谢谢使用和反馈！

1. 我尝试了多次粘贴图片，还是不能重现您说的光标错位的问题，能否详细说明一下场景？比如：
    - 哪个平台？Windows，Linux，还是macOS？
    - 粘贴板保存的是图片还是图片链接？比如说是复制了什么？然后如何粘贴？
2. 弹出插入图片对话框后，后面会将光标默认为标题输入框。这里是设计的疏忽，谢谢提出！:)
3. 后面可以考虑自定义图片文件夹，但是有以下几点考虑，如果您有好的建议，欢迎提出，一起讨论。
    - VNote会清理在VNote中插入的图片（即保存在`images`文件夹下的图片）；如果允许自定义图片文件夹，考虑到向后兼容问题，对于原来的`images`文件夹下的图片的处理就不能太武断了；
    - 可自定义文件夹的粒度应该是什么呢？笔记本，文件夹，还是笔记？
    - 是否允许用户后面修改默认文件夹？

关于第3点，现在我初步考虑到的方案是在 **笔记本** 层面支持自定义图片文件夹， **允许修改** ，在用户删除了一些图片链接后VNote清理无用图片时会弹出一个待删除图片列表给 **用户确认** （用户可以选择关闭提醒，完全交由VNote来处理）。

再次感谢！如果有需求，也可以邮件或者Q群进一步交流。

**Comment by cairy** [comment]
感谢回复，我是使用的Windows 10，从系统自带的文件管理器中复制的图片，因为要连续复制粘贴图片，粘贴一张之后我想换到下一行再复制粘贴下一张，复制粘贴第一张的时候光标可以定位到行尾，粘贴第二张后就不行了。
关于图片文件夹想想现在这样挺聪明的，其实我想的很简单，就是一个图片默认文件夹名的配置，这个文件名默认叫`images`，我把它改为`assets`，下次粘贴图片放入就会自动放入`assets`，因为是相对路径，只要之前的`images`目录存在，也不会有任何影响。
再次感谢，软件很好用。

**Comment by tamlok** [comment]
好的，我已经能重现这个问题了，后面会解决！

谢谢使用！

**Comment by tamlok** [comment]
您好！现在新版(7d05f96f947f4ab663303d50b6d80aedf5457d35)已经支持自定义图片目录名字(9bf3f9394fbffaab8fb2688506b309c1cbb0afa0)了，可以全局或针对笔记本；设置以后，仅对新插入的图片生效！

另外，插入图片的那两个问题应该也已经解决了。

谢谢使用。
