### ISSUE TITLE
希望增加 Ctrl + W 关闭标签页的功能

### ISSUE THREAD

**Issue by Mlearn** [tamlok/vnote#701]
OS Version (操作系统): Windows 10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3

Symptoms (表现):

关闭当前标签页快捷键（Ctrl + E, X）不起作用。

Hope (希望):

增加 Ctrl + W 关闭当前标签页的快捷键。同时这个快捷键也与当前所流行的大部分编辑器的多标签页关闭快捷键相一致

**Comment by tamlok** [comment]
Hi,

VNote支持自定义快捷键，在“文件”菜单里面有自定义快捷键的入口。具体可以参考文档。

另外，`Ctrl+W`对于编辑器来说，在Unix环境下一般用于向前删除当前一个单词，这个感觉更常用一点。

**Comment by Mlearn** [comment]
好的，另外，Ctrl + E, X 快捷键是起作用的，我理解成了按住 Ctrl 键不放，然后顺序按 E 和 X 键。应该是 同时按下 Ctrl 和 E，之后全部松开，再按 X 键。

谢谢。

**Comment by tamlok** [comment]
是的，所有`Ctrl+E W`这种类似的都是先按前导键`Ctrl+E`，然后松开，按下一个按键，就是一个序列。VNote里面`Ctrl+E`后面有很多快捷键组合，可以尽量避免和其他快捷键的冲突，具体可以参考帮助菜单。
