### ISSUE TITLE
希望增加打开“笔记信息”窗口的快捷键

### ISSUE THREAD

**Issue by kerhbal** [tamlok/vnote#703]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2

如题，目的是方便重命名笔记。在自定义快捷键文档里似乎没有发现针对这个的快捷键。谢谢！

**Comment by tamlok** [comment]
F2?

**Comment by kerhbal** [comment]
@tamlok F2 需要焦点是在笔记列表且选中一个笔记。能否添加一个更加全局一点的快捷键，比如在编辑模式下焦点在笔记内时能快捷打开笔记信息窗口呢？

**Comment by tamlok** [comment]
Added 93d20015192adeeed9dc46fdd6cdc9a308dbab6a

**Comment by kerhbal** [comment]
@tamlok 刚试了，没问题。谢谢！
