### ISSUE TITLE
图片莫名跑进_v_recycle_bin

### ISSUE THREAD

**Issue by GorryTech** [tamlok/vnote#705]
OS Version (操作系统): Windows, Linux, macOS
linux
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.3
Symptoms (表现):
升级到2.3后，打开原有笔记，发现图片无法显示，搜索了一下，发现跑到_v_recycle_bin里去了。

How to Repro (如何复现):
在阅读模式下，阅读以前的笔记，但图片莫名被删除了。

**Comment by tamlok** [comment]
能稳定复现吗？大概是什么形式的图片（本地相对路径）？

**Comment by TechGorry** [comment]
1、出现了好几次，我把图片从_v_recycle_bin还原回去了，目前没再出现，但是我很确定，我没删过那些图片；
2、是本地相对路径，例如_v_images/20190401062946991_334179602.png；

**Comment by tamlok** [comment]
Hi,

为了保险起见，在文件菜单，打开配置文件夹，找到`vnote.ini`，然后在`global`小节下面添加配置：

https://github.com/tamlok/vnote/blob/8871f56368d14eee9cd639485eed412d0e241554/src/resources/vnote.ini#L136

这样，VNote会向用户确认才删除它认为不再需要的图片。

另外，有一种可能是你在编辑的过程中，一时把一些图片的语法搞乱了，然后VNote识别图片的时候识别不到该图片，于是认为该图片不再被使用，在保存的时候会删除该图片。以后保存的时候，可以留意一下编辑模式下面是否能正确预览图片。

谢谢！

**Comment by TechGorry** [comment]
第二种可能不存在，因为并非在编辑模式下图片被删的。不过我先试试您提到的修改配置的方案，谢谢！

**Comment by loggerhead** [comment]
遇到了同样的问题，不确定怎么复现

**Comment by jackydi** [comment]
我刚刚也遇到了相同的问题，从2.4覆盖到2.5版本之后，图片都跑到回收站里了，不知道怎么回事，还以为是插入标题的原因

**Comment by tamlok** [comment]
@jackydi 大概是什么样的文章，能右键给我整个笔记的内容吗？

**Comment by tamlok** [comment]
可能和开启自动保存有关系。
