### ISSUE TITLE
解析网页效果问题

### ISSUE THREAD

**Issue by chhLab** [tamlok/vnote#706]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3, 
Symptoms (表现):
我把[网页](https://theme-next.org/docs/getting-started)内容复制了，分别粘贴到vnote和[yun writer](https://ivarptr.github.io/yu-writer.site/)解析成markdown，结果发现vnote中没有了图片，样式也跟原网页相差太大，希望vnote能改进一下解析效果，支持一下hexo页面
(图片左侧为yun writer解析效果，右侧为vnote)
![image](https://user-images.githubusercontent.com/48938342/55311787-6a7e4b00-5496-11e9-9544-7340627d3ea8.png)

How to Repro (如何复现):
复制[网页](https://theme-next.org/docs/getting-started)内容，分别粘贴到vnote和[yun writer](https://ivarptr.github.io/yu-writer.site/)

**Comment by tamlok** [comment]
VNote里面默认不解析，请右键菜单，选择“解析为Markdown并粘贴”，VNote还会自动下载图片到本地。

![image](https://user-images.githubusercontent.com/5763157/55312354-e6c55e00-5497-11e9-8e04-afe2913400bd.png)

效果如下：

![image](https://user-images.githubusercontent.com/5763157/55312400-065c8680-5498-11e9-914b-f1af5c8f8c2b.png)

谢谢！

**Comment by chhLab** [comment]
啊，原来是我不会用啊，尴尬啦
