### ISSUE TITLE
How to enable Vim mode 如何启用Vim

### ISSUE THREAD

**Issue by tamlok** [tamlok/vnote#710]
Open the `Settings` dialog under the `File` menu. Choose the `Read/Edit` tab. Now you could enable Vim mode in the `Key mode` option. Remember to restart VNote!
 
![image](https://user-images.githubusercontent.com/5763157/55442145-f354ce00-55df-11e9-894f-710558994994.png)

**Comment by henices** [comment]
You can try to pin this issue to remain always top.

**Comment by YohananDiamond** [comment]
I think that this coudl be on the wiki too... I know it's (probably) on the documentation, but.. maybe putting a FAQ on the wiki could be cool too.

**Comment by 598532284** [comment]
I canceled the menu of bar panel. where
 can I find it agin? thanks
