### ISSUE TITLE
编辑模式下 代码块 中出现 空行，渲染错乱

### ISSUE THREAD

**Issue by dalerkd** [tamlok/vnote#711]
OS Version (操作系统): Windows, Linux, macOS
Win7-64bit
VNote Version (Help - About VNote - Version: )(VNote版本): 2.3

## Symptoms (表现):
编辑模式下： 代码块中出现空行，该**代码块识别**失效(变为紫色)。

## How to Repro (如何复现):
2号区域 由于代码中有一个空行,
导致2号区域 高亮无效。
3号区域 错误高亮
4号区域 高亮也伴随无效

![QQ截图20190403113312](https://user-images.githubusercontent.com/10300911/55451144-4e002100-5604-11e9-8ebb-bd205bd62fdc.png)

**Comment by tamlok** [comment]
Hi,

按照MD基本语法，第一行三个反引号前面一般要空一行，以和前面的元素区分。另外，如果要语法高亮，可以在三个反引号后面加上语言标识。

谢谢！

**Comment by dalerkd** [comment]
感谢回复 
我尝试了您介绍的在MD前增加前导空行. 确定这样可以规避识别错误.

我更趋向于认为这是一个BUG.推测是由于阅读模式和编辑模式引擎不同导致的.
原因是这产生了不一致:
- VNote阅读模式对 代码块 即使 没有空行,依然渲染正确.
- VNote编辑模式对 代码块 没有前置空行的情况,发生错乱.

图二是图一代码在阅读模式下显示正常.
![图一](https://user-images.githubusercontent.com/10300911/55457496-a6431d00-561c-11e9-9ea5-05e8e8137440.png)
![图二](https://user-images.githubusercontent.com/10300911/55457501-aa6f3a80-561c-11e9-9a80-40f9bf5539b8.png)


另一个对比是Typora的渲染也支持了这一情况:在编辑模式下 不要求 额外的空行作为前导,如附图:

或许可以考虑让其更加一致,而不用单独为每个源码添加空行?

![Typora的支持情况](https://user-images.githubusercontent.com/10300911/55457252-01284480-561c-11e9-8cb4-f5b2e6aefe2d.png)

**Comment by tamlok** [comment]
嗯嗯，我仔细想了想，的确是Bug。马上会修复！现在的情况是块元素被行内元素给遮盖了。

**Comment by tamlok** [comment]
2.4已经修复。
