### ISSUE TITLE
在文件夹高亮的时候，输入回车键 enter键，vnote不会有任何反应，能否把回车键设成打开文件夹所在位置？

### ISSUE THREAD

**Issue by HgyHgyHgy** [tamlok/vnote#712]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):
这样就不不必右键点击，再去点击打开文件夹所在位置了

vnote好像无法设置，打开文件夹所在位置的快捷键。

**Comment by tamlok** [comment]
按照约定俗成，回车一般是展开子文件夹。

**Comment by HgyHgyHgy** [comment]
约定俗成，回车也有打开文件夹的时候。

何况，本来vnote中，回车就不能展开子文件夹。只能双击才能展开。

**Comment by Memento1990** [comment]
主键盘的回车可以, 小键盘的回车不可以.
