### ISSUE TITLE
软件布局发生变化

### ISSUE THREAD

**Issue by taotieren** [tamlok/vnote#713]
OS Version (操作系统): Windows10 1809 64位

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):vnote全屏运行后，放到后台切换成别的窗口，过一段时间后再切换回来，软件界面布局会发生变化，再次点击窗口缩放按钮，就有回复正常，100%复现这个问题

How to Repro (如何复现):再次点击窗口缩放按钮。
同时建议增加便签这个功能。

**Comment by tamlok** [comment]
Hi,

参考 https://github.com/tamlok/vnote/issues/665 升级驱动或更改openGL设置。

关于便签，暂时可以考虑使用`Ctrl+Alt+L`灵犀页或者`Ctrl+Alt+I`快速访问。

**Comment by taotieren** [comment]
Thanks！
