### ISSUE TITLE
How to open, how to empty recycle bin

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#716]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现): how can I open the Recycle Bin? how can I empty it?

How to Repro (如何复现):

**Comment by tamlok** [comment]
In the notebook selector's dropdown menu, right click on a specific notebook.

**Comment by DutchPete** [comment]
@tamlok right clicking does not show an option to empty the recycle bin. Remember, I am using the Linux version.

**Comment by tamlok** [comment]
Have you created any notebooks ever?

On openSUSE:

![image](https://user-images.githubusercontent.com/5763157/55599601-126e6f80-5748-11e9-88ea-e07bd69a9818.png)


![image](https://user-images.githubusercontent.com/5763157/55599559-eeab2980-5747-11e9-858f-417cd7ddf3b0.png)

**Comment by DutchPete** [comment]
openSUSE is not a very widely used distro. I am on Mint, which is based on Ubuntu, and between them they are probably the most widely used among Linux users.

Anyway, here is my normal VNote set-up:
![VNote normal status](https://user-images.githubusercontent.com/10794265/55605782-95ea8980-5765-11e9-8ca3-c71c1e13a7c3.png)

When I click on the black dropdown arrow, it just adds a line above it, i.e. between the green VNote and the green tab Notebooks, with the text
*+ Add Notebook*, and my 2 notebooks *Test* and *Geopolitics* remain listed as is, nothing else. It does not show that little context menu as per your 2nd screenshot above.

Unfortunately the program does not allow a screenshot of that situation: as soon as I activate the screenshot app, VNote goes back to its normal lay-out as in the screenshot above.

Thinking about your question "Have you created any notebooks ever?", my 1st reaction is to say "yes, of course, you can see them in my screenshot above. But maybe the are just folders, and not notebooks?
Please clarify, because I am a bit lost here.

**Comment by tamlok** [comment]
Could you right click on one item in the drop down list?

**Comment by DutchPete** [comment]
There is nothing in the dropdown list.

**Comment by tamlok** [comment]
Maybe a screen record could help?

**Comment by DutchPete** [comment]
Sorry for the late reply. I had to step away from my desk.

A screen record would be helpful, but I am ashamed to admit I do not have a program for that installed for the simple reason that I have not had any use for it :blush: 

Having said that, I think it is easier for me to delete the folder *_v_recycle_bin*. I assume the folder will automatically be recreated when I delete a note, right?

BTW, am I right when I say I have created a notebook correctly?

**Comment by tamlok** [comment]
Yeah, you could just delete that folder. You already did create a notebook.

**Comment by DutchPete** [comment]
OK Le Tan, thanks for your help, that's how I will handle it. If ever I have deleted a note and would want to recover it I'll go through that folder's subfolders and find the note manually.

What I do find strange is that this feature is available in openSUSE but not in Mint. perhaps that is also an issue could address in VNoteX.
