### ISSUE TITLE
2.3和2.4版本 notebooks目录树没有了

### ISSUE THREAD

**Issue by uugo** [tamlok/vnote#717]
OS Version (操作系统): macOS 10.14

VNote Version (Help - About VNote - Version: )(VNote版本): 2.4

Symptoms (表现):
左侧的的notebooks目录树没有了，没找到可以显示的地方。

**Comment by tamlok** [comment]
文件菜单，设置，重置布局，然后文件菜单，重启VNote，即可。应该是很久没更新版本了？

**Comment by uugo** [comment]
版本是最新的2.4版，osx 的2.4dmg版本的的“文件”菜单没有“设置”，通过“偏好设置”里的“重置布局”，还是没出来。

**Comment by tamlok** [comment]
有截图吗？试试工具栏有一个扩展的按钮，那个是最大化编辑区的，看是不是这个原因。

**Comment by uugo** [comment]
确实是这个原因，扩展编辑区域按钮，多谢多谢。
