### ISSUE TITLE
What is the default language for fenced code?

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#72]
_vnote_ seems automatically pick up a language for a fecned code which the language is not specified for.

I personally think it should be more reasonable to not highlight anything if the language is not specified by the user. [GitHub does the same thing](https://goo.gl/n2uswY).

**Comment by tamlok** [comment]
When no language is specified, `highlight.js` will try to guess the language. I also think it is better to not highlight it if language is not specified. Will disable the guess later.

Thanks!

**Comment by tamlok** [comment]
Already disable it (fe9d4e46bf1c8bcf8fe1fa4743b35acdda1d596d). Thanks!
