### ISSUE TITLE
[20190407]文件夹删除后无法再次创建：显示已经存在该文件夹

### ISSUE THREAD

**Issue by shuchaoma** [tamlok/vnote#720]
OS Version (操作系统): Windows, Linux, macOS
- Linux
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
- 2.4 & 2.3 都存在
Symptoms (表现):
![image](https://user-images.githubusercontent.com/6086958/55678943-0267b300-5935-11e9-8c85-bf5311e8b078.png)

How to Repro (如何复现):
- 历史上曾经删除过一个文件夹，然后重新创建时出现这类“dialog”。
- 但是在vnote界面已经不显示该文件夹了。

我研究了一下发现_vnote.json还存在这个索引，索性也将该文件中相关条目进行了删除；但是依然存在这个问题。

**Comment by tamlok** [comment]
把对应文件夹和json里面的对应条目删除后再重启vnote试试。一般只要不绕过vnote进行文件操作都不会有这个问题。

**Comment by shuchaoma** [comment]
> 把对应文件夹和json里面的对应条目删除后再重启vnote试试。一般只要不绕过vnote进行文件操作都不会有这个问题。

按照你的操作方式：1）将对应文件夹和_vnote.json对应内容删除后 2）重启vnote。
发现依然说新创建的文件夹存在。

很奇怪。及时有缓存，重启肯定会消失才对呀；

**Comment by shuchaoma** [comment]
补充：
-  我索性将文件夹和_vnote.json加上对应的条目，然后重启了几次；最终解决了这个问题。

以后再也不终端进入vnote目录了~；谢谢~
