### ISSUE TITLE
Auto-numbering

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#721]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3

Symptoms (表现): This is a very useful feature, it really makes a note and its outline much better to read and understand. Nevertheless, VNote actually adds the numbers to the headers and subheaders, thus modifying the notes. The program should not modify my notes.

Perhaps in VNoteX you could make it such that it only renders the numbers in reading mode and in the outline, without those notes actually getting added to the note.

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

VNote tries to make edit mode look like read mode. And if do not add the number in edit mode, your note will look different in other editors.

**Comment by DutchPete** [comment]
That depends on the editor. Typora, for example, does not add the numbers to your note, but it renders them as such both in the note and in the outline.

**Comment by DutchPete** [comment]
I hope you will consider this issue for VNoteX. Maybe it could be made into an option or a toggle.

**Comment by DutchPete** [comment]
This the same as issue #1040, so this issue can be closed. I do hope that in VNoteX either
* the css code as per #1040 will be integrated, or
* if the header sequence is enabled in the settings VNoteX will not add the header numbers physically to the document, as described above.
