### ISSUE TITLE
阅读模式下Linux换行符没显示换行

### ISSUE THREAD

**Issue by princeofdream** [tamlok/vnote#722]
OS Version (操作系统): Windows, Linux, macOS
Windows
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
latest
Symptoms (表现):
编辑模式copy 带linux换行符的文字到vnote，退出编辑模式，转为阅读模式，没显示换行，文字连续一行过去

How to Repro (如何复现):
编辑模式copy 带linux换行符的文字到vnote，退出编辑模式，转为阅读模式，没显示换行，文字连续一行过去

**Comment by tamlok** [comment]
hi，markdown语法默认是末尾带两个空格或者多一个空行表示换行。可以在markdown菜单，markdown-it选项，勾选换行，重启vnote，这样默认自动换行。

**Comment by princeofdream** [comment]
勾选换行并重启了vnote，原来linux换行符还是没生效，还是加两个空格才显示换行

**Comment by tamlok** [comment]
试试文件菜单，重启。

**Comment by princeofdream** [comment]
我以为会有服务在后台跑，进程管理kill掉vnote.ext，失败，整个系统重启，显示还是一样，linux换行符还是被阅读模式忽略了，甚至直接编辑的文件，进入阅读模式还是一样，然后把HTML等其他所有的√去掉，只剩换行，菜单重启，依然显示是一行

**Comment by tamlok** [comment]
把这个文件上传贴出来我这边看一下？或者发我邮箱。

**Comment by princeofdream** [comment]
[NAT.zip](https://github.com/tamlok/vnote/files/3053271/NAT.zip)
是否md文件只支持markdown语法？我试了txt，都得外部打开，如果是这样的话，我就直接close这个issue好了

**Comment by tamlok** [comment]
我这边测试没有问题：

首先确认渲染器是markdown-it:

![image](https://user-images.githubusercontent.com/5763157/55767947-7af17f80-5aad-11e9-992c-ee803ad06f92.png)

然后，确认换行选项被勾选：

![image](https://user-images.githubusercontent.com/5763157/55767965-88a70500-5aad-11e9-8cdb-427ff1e69dea.png)

然后，文件菜单，重启，重启VNote。

另外，建议可以使用行内代码块来包含这些命令行，具体语法参考 https://tamlok.github.io/viki/#!markdown.md#toc_12 ，这样整个文档会显得干净很多。

目前VNote还不支持打开纯文本，后面会添加支持。

**Comment by princeofdream** [comment]
渲染器问题，close，感谢解答

**Comment by YcatZh** [comment]
段末两个空格搞定
