### ISSUE TITLE
希望拓展大纲显示功能

### ISSUE THREAD

**Issue by IElisha** [tamlok/vnote#726]
大纲的显示功能，建议增加快捷键，实现分级显示标题的目的。
比如：
ctrl + 1 ，只显示1级标题，其余层级标题折叠
ctrl + 2 ，只显示1级和2级标题，其余层级标题折叠
ctrl + 3 ，只显示1级和2级以及3级标题，其余层级标题折叠

谢谢！
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

**Comment by tamlok** [comment]
Hi,

![image](https://user-images.githubusercontent.com/5763157/55800413-46f67880-5b06-11e9-8e5e-666ce2c2b4b2.png)

这里的左右箭头可以实现该功能。

**Comment by IElisha** [comment]
谢谢，真的可以！
