### ISSUE TITLE
Internal links within a note

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#727]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3

Symptoms (表现): by an internal link I mean a link to a point somewhere else in the note. Markdown supports this with
`[link text](#header-text)`
which will link to a header, entitled `# Header text` somewhere in the note. It can also link to ## or ### or ..... ###### subheaders.
I have not found this in VNote's markdown guide, so I assume it is not supported. I even tried using the syntax in a note, bu it does not work.
Is this something that can be considered for VNoteX?

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

Move your mouse to the right of a title, a blue `#` will show up. The status line will show the anchor for this title, such as `xxxx#toc_2` and `toc_2` is the right anchor to use.

![image](https://user-images.githubusercontent.com/5763157/55800606-ad7b9680-5b06-11e9-9f87-62656803b10c.png)

**Comment by DutchPete** [comment]
1 other, very important aspect: your syntax works perfectly fine, but when one inserts a new header before the header that is anchored to, then the link does not work anymore. The reason: your syntax uses a header count. So linking to e.g. header 5 (toc_5) will remain linked to the 5th header counted from the top.

With conventional syntax, inserting additional headers makes no difference, the link stays linked to the same header. The reason: conventional syntax uses the header title, so it does not matter whereabouts on the page that header is.

Preserving links while editing a note, or while moving a note (we spoke about that before), is very important to preserve the integrity of the notes and their inter-relationships !!

**Comment by DutchPete** [comment]
Just to close off this issue for anyone who might hit upon this: a much better way do an internal link is to use
`<a name="abcd"></a>` as the anchor point (can be put anywhere), and `[any text](#abcd)` as the link. Works well, no problems.
A couple more advantages of this are that any text can be added to the file, the link still works, and also this can be used in other markdown editors (portability), which the `toc_number` does not.
