### ISSUE TITLE
windows 10 全屏（F11）后微软拼音输入法遮挡

### ISSUE THREAD

**Issue by iIQOverflow** [tamlok/vnote#728]
OS Version (操作系统): Windows 10 Education

VNote Version (Help - About VNote - Version: )(VNote版本): VNote2.4，2019年9月4日安装

Symptoms (表现):
微软拼音输入法遮挡问题，看不到待选汉字，只能看到拼音。

How to Repro (如何复现):
win10系统进入笔记，按F11（进入全屏模式），使用微软自带的拼音输入法只能看到拼音（如pin'yin'shu'ru'fa），但是看不到待选汉字。

**Comment by tamlok** [comment]
这边无法重现，怀疑可能是openGL的问题，尝试一下：

1. 升级显卡驱动；
2. 关闭所有打开的笔记，然后设置对话框，opengl那里选择一些非默认的值，确认；文件菜单，重启vnote，看能否正常。

**Comment by iIQOverflow** [comment]
感谢，修改opengl后重启正常。
