### ISSUE TITLE
窗口 resize 的 bug

### ISSUE THREAD

**Issue by Rictusempra** [tamlok/vnote#73]
![image](https://user-images.githubusercontent.com/16912240/34079627-45ce97d4-e36c-11e7-9b25-02f800cc097d.png)

Environ. 最新64位便携版，Windows 10.16299.125 Pro

STR：
1. 解压之后运行，创建新笔记时点取消
1. 关闭再运行然后最大化（或此时不复现）
1. 关闭再运行

**Comment by tamlok** [comment]
Hi，这种情况一般是显卡驱动的问题，试试更新一下系统或者显卡驱动？之前好几个用户都是更新后就解决了。

谢谢！

**Comment by Rictusempra** [comment]
等等，，显卡驱动？？？？？
然而我并无法更新
（系统跟驱动都是最新。。）
另
![image](https://user-images.githubusercontent.com/16912240/34079758-c76a1f1e-e36e-11e7-9471-c35478cd84e0.png)

**Comment by seaspeak** [comment]
Maybe you can try deleting setting folder "%appdata%\vnote" and try again?

**Comment by Rictusempra** [comment]
> Maybe you can try deleting the setting folder "%appdata%\vnote" and try again?

This helps. Thx.

I'll reopen whenever it re-occurs and never get fixed.
