### ISSUE TITLE
vnote和ahk软件不兼容，不能用ahk软件来做一些自动化的处理

### ISSUE THREAD

**Issue by HgyHgyHgy** [tamlok/vnote#730]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):
vnote似乎和其他软件不一样。不能对ahk (autohotkey)的操作响应。
此外，它也不对一些窗口管理的软件进行响应。譬如不能半屏显示，或者切换到另一个显示器后不会自动调整分辨率。（可以切换到第二个显示器，但分辨率并不会自动调整。）

**Comment by HgyHgyHgy** [comment]
发现原因是默认的opengl的原因，改成非默认的，就能响应了！！
改变了默认opengl后，对窗口管理软件也可以响应了！

为什么不默认就设定可以响应的选项呢？不是偶然看到窗口布局不正常的帖子，都不能发现这个原因！

**Comment by tamlok** [comment]
赞！

之前尝试过改变默认值的，但有用户反映一打开就无响应，所以赶紧设为默认值。

所以只能靠每个用户根据自己的环境设置了。
