### ISSUE TITLE
既然vnote利用了文件夹作为笔记，为什么不进行更充分地利用！譬如给文件夹加tag

### ISSUE THREAD

**Issue by HgyHgyHgy** [tamlok/vnote#731]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):
以及支持新建任意格式文件到该文件夹中。
目前，可以可以显示任意格式的文件。但新建时，需要自己删掉文件，再新建正确的文件。

如果支持在一个预先设定的目录底下拷贝各种格式的空白文件到当前目录并重命名为输入的文件名，那该多好！

以文件夹来存放笔记，有很多好处。可以用其他一些文件搜索软件来查找到所需文件，甚至全文搜索也是很方便。

但也不应该因此就限制了其功能。譬如添加标签。

**Comment by Memento1990** [comment]
右下角不是有标签tag功能吗?

**Comment by HgyHgyHgy** [comment]
早试过了。文件夹加不了的。虽然有tag，那会加到md文件中。
