### ISSUE TITLE
从编辑模式切回阅读模式黑屏

### ISSUE THREAD

**Issue by dmahacker** [tamlok/vnote#734]
OS Version (操作系统): ArchLinux KDE

VNote Version (Help - About VNote - Version: )(VNote版本): aur/vnote 2.4-1

Symptoms (表现):
阅读模式渲染黑屏

How to Repro (如何复现):
首先以阅读模式打开一个文档
然后在渲染区域右键，选择编辑
之后再次右键，从选择保存（或放弃）更改并阅读
此时返回阅读模式，渲染黑屏，如图

![image](https://user-images.githubusercontent.com/8119999/56007750-4d564180-5d0c-11e9-9dda-90f2277b9550.png)

**Comment by tamlok** [comment]
难道又是AUR的Qt有什么更新了然后又break了~~

目前建议使用官方的AppImage包，或者AUR里面的`vnote-bin`包。

**Comment by dmahacker** [comment]
好，我试一下

**Comment by dmahacker** [comment]
> 难道又是AUR的Qt有什么更新了然后又break了~~
> 
> 目前建议使用官方的AppImage包，或者AUR里面的`vnote-bin`包。

aur/vnote-bin的下载地址稍微有点问题，这个包是您在维护吗
aur里的下载地址是:

> https://github.com/tamlok/vnote//releases/download/2.4/VNote-2.4-x86_64.AppImage

实际上现在下载地址应该是

> https://github.com/tamlok/vnote/releases/download/v2.4/VNote-2.4-x86_64.AppImage

(少了个v)

source这一行改成这样就好了
![image](https://user-images.githubusercontent.com/8119999/56008324-7b3c8580-5d0e-11e9-9749-75c1eb903b39.png)

然后就是我装好vnote-bin还是有一样的问题
之后我又测试了一下直接下载appimage来使用也是同样的现象
我觉得可能是我系统的qt出了啥问题...我一会儿装个虚拟机测试一下

**Comment by tamlok** [comment]
不是我维护的，这个问题是因为之前发布2.4的时候写少了一个v。

appimage应该不会出现这种情况。或许重启一下系统？

**Comment by dmahacker** [comment]
> 不是我维护的，这个问题是因为之前发布2.4的时候写少了一个v。
> 
> appimage应该不会出现这种情况。或许重启一下系统？

找到了解决办法..如果有同样问题的使用KDE的朋友可以尝试这个方法解决
打开系统设置->显示和监控->混成器，将渲染后端改成XRender（之前我是OpenGL），如图
![image](https://user-images.githubusercontent.com/8119999/56009556-c0fb4d00-5d12-11e9-9930-af668029d2e2.png)
之后重启VNote即可
