### ISSUE TITLE
arch linux PKGBUILD 文件的下载地址有点问题

### ISSUE THREAD

**Issue by haoweiah** [tamlok/vnote#736]
OS Version (操作系统): arch Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.4

Symptoms (表现):==> ==> ERROR: Failure while downloading https://github.com/tamlok/vnote//releases/download/2.4/VNote-2.4-x86_64.AppImage
    Aborting...

How to Repro (如何复现):makepkg -sic

**Comment by tamlok** [comment]
这个能给包维护着说一下更新一下吗？

**Comment by haoweiah** [comment]
说了，应该已经更新了
