### ISSUE TITLE
Add some syntax highlights in edit mode?

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#74]
I'm not sure if this is consistent with vnote design philosophy. But editing a long black-and-white file is really dull.

Adding a little bit of colors won't confuse users, since current possible colorful places only reside in fenced blocks. I don't actually think this through, just an idea for discussion.

![image](https://user-images.githubusercontent.com/8821870/34083914-ef65e6bc-e3b2-11e7-95a6-e0d7c416578a.png)

**Comment by tamlok** [comment]
Where does this screenshot come from? VNote?

Here is the edit interface of VNote on my desktop:

![image](https://user-images.githubusercontent.com/5763157/34106528-83587ca6-e433-11e7-86ad-7e245852381d.png)

**Comment by seaspeak** [comment]
It's from vim's torte theme.

Just now I realized that all things are colored. 

My monitor is the primary source of problem. It doesn't show light purple, light green, and other light colors very well.

I also made a mistake on syntax. I don't insert a blank line before the start of a list. The following code won't get highlighted. But it is interpreted as a list in read mode.
```
list example:
- one
- two
- three
```

**Comment by tamlok** [comment]
You could custom the style to your taste. It is very easy. Download this [mdhl file](https://github.com/tamlok/vnote/blob/master/src/resources/themes/v_pure/v_pure.mdhl) and drop it in your VNote's configuration folder's subfolder `styles`. VNote will detect `css` and `mdhl` files here.

**Comment by seaspeak** [comment]
Thanks for the tip, which I need much.

Please also have a look at the inconsistent interpretations of a list in read and edit mode.

Now I close the issue.

**Comment by seaspeak** [comment]
In v_moonlight.mdhl, do I have `selected-word-foreground` , `searched-word-foreground` ... options? Dark themes especially need these attributes.

I try to rename the theme folder and files under the folder (e.g. v_pure to v_mytheme). I can see it under vnote|file|themes, but unable to enable it.

**Comment by tamlok** [comment]
You could change the `editor-selection` element. A full reference for the stylesheet could be found [here](http://hasseg.org/peg-markdown-highlight/docs/stylesheet_syntax.html).

**Comment by seaspeak** [comment]
I'm sorry I didn't describe my problem well. I mean "[VNote] Style for searched word highlight" under `editor`.

Highlights and normal texts are often light colors in dark themes, so they are often indistinguishable from each other. 

![image](https://user-images.githubusercontent.com/8821870/34185477-81b60246-e560-11e7-9a32-b17fb125b7bd.png)

**Comment by tamlok** [comment]
Check these configs (especially `searched-word-background`) in MDHL file:

```
# [VNote] Style for trailing space
trailing-space: 636d81
# [VNote] Style for line number
line-number-background: 2c313a
line-number-foreground: 5c6370
# [VNote] Style for selected word highlight
selected-word-background: 454bb2
# [VNote] Style for searched word highlight
searched-word-background: 424956
# [VNote] Style for searched word under cursor highlight
searched-word-cursor-background: 596173
# [VNote] Style for incremental searched word highlight
incremental-searched-word-background: 596173
# [VNote] Style for color column in fenced code block
color-column-background: c9302c
color-column-foreground: eeeeee
# [VNote} Style for preview image line
preview-image-line-foreground: 6f5799
```

**Comment by tamlok** [comment]
Oh, I got what you mean! I will add foreground options later. They are not supported yet.
