### ISSUE TITLE
Just a thank you :-))

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#740]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3
Symptoms (表现): I just completed manually transferring 10 MB of notes from another note-taking/management program to VNote ! I am impressed with VNote, enjoy using it and feel I am now really the owner of my notes since they are in a platform-independent format. It is a good program that deserves  to be better know among people who are interested in this kind of program - something to bear in mind for VNoteX.

I have opened a number of issues, mostly with questions about how to do this or that. I hope I have not caused too much inconvenience, while I have also tried to make a useful contribution with some suggestions. I am looking forward to VNoteX - is there any way to keep aware of its release?

How to Repro (如何复现):

**Comment by tamlok** [comment]
Just "Watch" this repo, you will be noticed then. Thanks!

**Comment by DutchPete** [comment]
OK, thanks, and thanks for an excellent program !
