### ISSUE TITLE
怎样把文件夹底下的所有子目录一下子展开？有没有快捷方式？

### ISSUE THREAD

**Issue by HgyHgyHgy** [tamlok/vnote#742]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):
需要不断点击展开，才能看到所有内容，不方便

**Comment by tamlok** [comment]
在某一个文件夹上面选中，`*`，即可。

**Comment by HgyHgyHgy** [comment]
我试了一下，按*号，是关闭vnote的程序，并不会展开文件夹。
对于最新版来说，也是一样的结果。win10.
检查了一下快捷键设置，也没看到*号。*号的输入，也是正常的。

**Comment by tamlok** [comment]
你是在笔记本里面按，还是浏览器面板？

**Comment by HgyHgyHgy** [comment]
在笔记本里按。
按+,-号等等，都有效果。
如果目录已展开，按\*号，没反应。
若目录未展开，即vnote闪退。

**Comment by HgyHgyHgy** [comment]
按主键盘shift+8对应的\*，没问题。数字键盘的*,才会闪退。

**Comment by tamlok** [comment]
好吧~我的键盘没有小键盘~后面修复一下。

**Comment by Memento1990** [comment]
win10 下按小键盘上的 `*` 是没有问题的~
