### ISSUE TITLE
[bug] Linux 2.4 版本 Latex 支持异常

### ISSUE THREAD

**Issue by kmahyyg** [tamlok/vnote#749]
OS Version (操作系统): Arch Linux

VNote Version (Help - About VNote - Version: )

```
VNote
版本: 2.4
作者: Le Tan (tamlok)
```

Symptoms (表现): 使用 MathJax 和 Markdown-it， Latex 无法正确渲染 <del>且保存后重启会丢失 Latex 内容</del> 。仅开启了 MathJAX 扩展。

How to Repro (如何复现):  行内输入 `$\alpha_{1}$` 在 MathJAX 官方 demo 可以正常预览，在 vnote 下阅读模式会是原 Latex 字符串。

![image](https://user-images.githubusercontent.com/16604643/56331105-82a3d900-61bd-11e9-89bb-19d624c39ce3.png)

而且在渲染失败后狂吃 CPU。

![image](https://user-images.githubusercontent.com/16604643/56331152-bda60c80-61bd-11e9-8139-e7fd319bcd9d.png)

**Comment by kmahyyg** [comment]
使用的是 Arch Linux CN 源的 Git Build，对应 Commit 为  master .

**Comment by tamlok** [comment]
Windows下面没有问题，可以尝试：

1. 在单独的一个新文件里面仅写上`$\alpha_{1}$`进行测试；
2. 使用官方的AppImage尝试；

谢谢！

**Comment by tamlok** [comment]
So what is the cause? @kmahyyg

**Comment by kmahyyg** [comment]
CPU 占用正常，但是渲染依然异常。

另外：考虑中国大陆的网络问题，建议更改 MathJax 的 JS 地址为 jsdelivr CDN.

![image](https://user-images.githubusercontent.com/16604643/56338548-091be300-61dd-11e9-9566-c636de7e45f9.png)


急着写东西，暂时迁移到 StackEdit.

**Comment by kmahyyg** [comment]
日志文件没有显示有程序本身的问题造成的异常。

发个牢骚： 另，想知道作为一个 Qt 应用为什么体积那么大？我乍一看还以为是 Electron 应用。 Desktop PWA 已经被 Chrome 支持的今天，一个单纯的笔记应用或许可以考虑被 PWA 代替了。

**Comment by tamlok** [comment]
1. 尝试一个简单的公式看看？比如`$a - b$`；
2. 渲染引擎里面，记得选择`Markdown-it`；
3. 有没有可能是网络问题呢？在设置对话框里面可以设置MathJax的地址；
4. 体积大是因为嵌套了一个QWebEngineProcess来浏览网页和执行JS；

谢谢！

**Comment by kmahyyg** [comment]
1. 渲染正常，猜测存在 escape 或 JS 渲染问题
2. 已确认过选择的是 markdown-it
3. 不是网络问题，尝试过自行修改 JS CDN，对我需要渲染的 Latex 无效。

BTW，在从命令行尝试通过 `proxychains vnote` 方法（原理：劫持网络 lib）强行调用代理启动后出现了 coredump，看起来是 QtWebEngine 对这个代理方法兼容有问题。

4. 非常感谢解答。

**Comment by kmahyyg** [comment]
Any update?

**Comment by tamlok** [comment]
这边Linux下面还是暂时无法重现哦。

**Comment by kmahyyg** [comment]
Worked with the latest vnote-git build in archlinuxcn repo.
