### ISSUE TITLE
Delete a tag

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#753]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3.

Symptoms (表现): if I have assigned a tag to 10 different notes, is there a way to "centrally" delete that tag, i.e. with 1 action, or do I have to open each of the 10 notes individually and delete the tag there?

How to Repro (如何复现):

**Comment by tamlok** [comment]
For now, I am afraid so.

**Comment by DutchPete** [comment]
OK. If you do't add it to VNote anymore (:sob: ), then that's another feature request for VNoteX .
