### ISSUE TITLE
文档是否可以本地查看

### ISSUE THREAD

**Issue by Skypekey** [tamlok/vnote#755]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
文档只能在线观看，是否可以下载到本地。

How to Repro (如何复现):

**Comment by Skypekey** [comment]
另外笔记本工具栏是否可以拖放到右边，习惯于左边大纲。如果大纲和笔记本工具栏都在左边，用起来很不习惯，所以想问问可不可以调整

**Comment by tamlok** [comment]
文档是这个仓库的gh-pages分支，你把它下载下来即可，然后在vnote里面新建笔记本，根文件夹选择下载下来的json文件对应的文件夹，就可以在vnote里面打开。

导航栏暂时改不了，后面会优化。
