### ISSUE TITLE
There is no support for Right-to-Left (RTL) languages

### ISSUE THREAD

**Issue by tri-go** [tamlok/vnote#759]
When writing text in an RTL lanugage (for example, Hebrew, Arabic, etc.), writing **should** start from the **right** of the page and continue to the **left**. Most text editors support 

In *Vnote*, When a line begins with Hebrew characters (For example), the line is still aligned to the **left** instead of the **right**.
(I tested this on **Linux** with the latest **Vnote appimage version (2.4)**)

I'm attaching two pictures to show how the text renders correctly in *Kate (text editor)* and how it renders in *Vnote*. I'm also attaching the .md file that I used for testing. It will show several situations: 
1. Starting a line with Hebrew characters vs. Latin characters. 
2. Mixing Latin text and then Hebrew text vs. first mixing Hebrew text and then Latin text. 
3. Starting a line with symbols and then Hebrew/Latin characters

This is how things work (correctly) in Kate (Latin text is aligned to the **left** while Hebrew text is aligned to the **right**):
![RTL-test-in-Kate-normal](https://user-images.githubusercontent.com/49899269/56567115-e747a500-65bc-11e9-8e39-9f05bf4489a6.png)

This is how Vnote shows the same text (everything is aligned to the **left** of the page):
![RTL-test-in-Vnote](https://user-images.githubusercontent.com/49899269/56567186-080ffa80-65bd-11e9-9771-7f0d21bfed08.png)

For more information about Right-to-Left language systems: https://en.wikipedia.org/wiki/Right-to-left
And for more information about Bi-directional text (mixing RTL languages with Left-to-Right languages): https://en.wikipedia.org/wiki/Bi-directional_text

This is the .md file that I used in my testing. Github doesn't allow uploading of .md files, so I just chaged the suffix to .txt instead of .md. You can download it and change it back to .md.
[A_note_about_right-to-left_support.txt](https://github.com/tamlok/vnote/files/3106664/A_note_about_right-to-left_support.txt)

Is there a way to fix this issue?
The wikipedia article about [Right-to-left#Computing_support](https://en.wikipedia.org/wiki/Right-to-left#Computing_support) says: "Right-to-left, top-to-bottom text is supported in common consumer software. Often this support must be explicitly enabled."
Maybe it just needs to be enabled somehow..

Thank you

**Comment by tamlok** [comment]
It is supported now.  Please get the latest build https://bintray.com/tamlok/vnote/vnote/2.4#files to try it out.

BTW, Vim mode does not support RTL. And Visual Code Studio and Vim does not support RTL, either.

**Comment by tri-go** [comment]
I checked it with the latest build. Now RTL **works** in the _Edit mode_. It still **doesn't work** in the _Read mode_.
In the _read mode_, all the lines (even RTL lines) are still aligned to the **left** instead of the **right**.
Here is a screenshot to show this (_green_ - works as expected, _red_ - not working as expected):
![Edit mode vs Read mode](https://user-images.githubusercontent.com/49899269/56818995-8a185180-6851-11e9-92e6-a4b83c50159a.png)

Could this also be fixed?
(Thank you very much for fixing the RTL issue in the edit mode)

**Comment by tamlok** [comment]
In read mode, VNote uses Markdown-it to render MD to HTML. It seems that there is no support for RTL in markdown. You could try [demo](https://markdown-it.github.io/) here. Or if you could find any Markdown editor could handle RTL correctly, please tell me. For now, I don't think I could solve this.

**Comment by tri-go** [comment]
As you suggested, I've posted on this issue in _markdown-it_'s github. The author of markdown-it, @puzrin, [says](https://github.com/markdown-it/markdown-it/issues/554#issuecomment-487310550): 

> If you are sure, bug is related to this package, you are expected to provide smallest possible code sample, not text and screenshots. **You could ask vNotes authors to post those**. But i'm sure, parser don't touch any unicode direction marks. https://github.com/markdown-it/markdown-it/issues/554#issuecomment-487310550

So since you're Vnote's author, could you, please, help me in solving this issue and provide @puzrin with a code sample that shows how this bug is related to _markdown-it_?

Thank you

**Comment by tamlok** [comment]
I gave you their official demo https://markdown-it.github.io/ . You could show them how it looks when writing RTL language in the demo. I think that should be enough. BTW, you could ask them whether you need to write extra markup to denote the direction of the text manually.

**Comment by tamlok** [comment]
May be you need to denote the RTL direction explicitlyl like:

```
<div dir="rtl">
שלום בעולם  
<br>
ہیلو دنیا  
</div>
```

If all your contents are RTL within one note, you could add this line to your note (you could use Snippet utils in VNote to input this line in one single shortcut):

```html
<style> body { direction: rtl; } </style>
```

References:

- https://stackoverflow.com/questions/2258028/rtl-in-markdown
- https://talk.commonmark.org/t/explicit-rtl-indication-in-pure-markdown/286/2
- https://github.com/dear-github/dear-github/issues/147

**Comment by ahangarha** [comment]
You must add `dir="auto"` in all `<p>` or possibly `<div>` tags while rendering MD into HTML. This is called bidi and will solve the issue.

There is no need to add support for RTL in MD
