### ISSUE TITLE
Full Notebook Search

### ISSUE THREAD

**Issue by stakaz** [tamlok/vnote#76]
Hello!  Could you consider adding a search option for the whole notebook (search in each file)?

VNote looks really great and promising. Thanks for this great app.

**Comment by tamlok** [comment]
Hi, we have a plan to implement the search within notebook. It is on the road.

Thanks for your attention!

**Comment by stakaz** [comment]
Great to hear. Do you have a time plan or something like that?

**Comment by tamlok** [comment]
This feature has been requested at the very beginning of VNote, so it is at a high priority now. May be implemented within the next two versions.

**Comment by tamlok** [comment]
Added in 1.13! :)
