### ISSUE TITLE
win10经常无响应

### ISSUE THREAD

**Issue by littleheary** [tamlok/vnote#762]
打开软件经常无响应，100%发生。打开一小会儿就会无响应，无法操作任何笔记和文件夹。用不了呀！

**Comment by tamlok** [comment]
和另一个issue一样，更新一下显卡驱动，或者使用集成显卡，或者设置一下vnote里面opengl的值。具体搜一下已关闭issue里面opengl。

**Comment by tamlok** [comment]
https://github.com/tamlok/vnote/issues/665
