### ISSUE TITLE
vnote的右键菜单并非每一个项目后面都有快捷字母的选择，而且快捷字母，也不是唯一的。能不能都添加一个快捷字母，并让字母唯一？

### ISSUE THREAD

**Issue by HgyHgyHgy** [tamlok/vnote#763]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):
这样，就可以方便用ahk来简化操作了！不然发生一系列{down}...{enter},脚本可能会变得不够稳定。
目前，只能鼠标复制路径后，再启动ahk。

**Comment by tamlok** [comment]
哪个不唯一？不唯一的估计就是写代码写乱了。

具体哪些想加的都可以提出来。谢谢！

**Comment by HgyHgyHgy** [comment]
右键点击md文件，就有两个o的快捷键了。按一下o,是阅读模式，按第二下，是才是打开文件位置。

希望加一下，复制文件路径的快捷键，或者快捷字母。由于必须右键点击才能选定文件，添加快捷字母才能实际操作。

**Comment by tamlok** [comment]
ok！后面改进一下，谢谢！

**Comment by HgyHgyHgy** [comment]
新建文件时，能不能添加一个开关，决定“新建文件后，是否自动打开文件”。
新建文件，自动打开文件是很方便。
可是我新建一个打不开的文件，它也自动打开，就每次都要关闭它。
不过，这个需求可能比较小众。但这个确实无法从外部改变它的行为。
我新建一个打不开的文件后，然后用ahk来更新它，让它变成正确的文件。

**Comment by tamlok** [comment]
已经修复了，同时如果是非md或HTML文件，都不会再新建的时候自动打开。

可以下载最新构建版或者等下一个版本。

谢谢反馈！

**Comment by HgyHgyHgy** [comment]
2.4版本，还是会自动打开。最新构建版在什么地方下载？是说下载源码编译？用什么工具，如何编译？

**Comment by tamlok** [comment]
认真看一下主页，有个downloads的图标。

**Comment by HgyHgyHgy** [comment]
原来是只更新了32位的，没更新64位的。
32位确实不会自动打开了。是否64位应该也没什么影响。

**Comment by tamlok** [comment]
64位的现在应该构建完了。
