### ISSUE TITLE
目前新建任意文件格式的最好的方法

### ISSUE THREAD

**Issue by HgyHgyHgy** [tamlok/vnote#765]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):
首先装个superF4，方便在启动阶段就强行结束软件。
用vnote新建文件，输入相应的后缀名。
vnote会自动打开该文件。
用superF4的快捷键强行关闭打开的软件。
然后右键复制文件路径，用ahk自动更新文件为正确的文件格式，并自动打开。

注意千万不要按错，在未保存的界面按了强行关闭的快捷键，未保存的内容就会消失了。

最好是能够做到全自动的，可是，新建文件时，一定会自动打开文件。你就不得不把打开软件关闭。自动强行关闭，可能会出错，丢失未保存内容。

**Comment by Memento1990** [comment]
😢 我觉得这样不如在上面那个`浏览器`页签里查看来的方便, 工具的本质是为了让自己的工作, 写作, 管理方便, 这样弄的话反而有些本末倒置了.

**Comment by HgyHgyHgy** [comment]
新建一个excell文件或opj文件用于处理数据或者作图，还是十分有必要的。如果放在其他地方，或者用浏览器页新建，还是多了许多额外步骤。

**Comment by HgyHgyHgy** [comment]
最新版，新建文件不自动打开了。可以用ahk来新建任意格式文件。方便了许多。
#NoEnv
#IfWinActive,ahk_class Qt5QWindowIcon
F5::
send,^c
sleep,100
start_pos:=InStr(clipboard,"[")
end_pos:=InStr(clipboard,"]")
folder_path:=SubStr(clipboard, start_pos+2, end_pos-start_pos-3)
StringReplace, folder_path, folder_path, /, \, All
InputBox, Filename, 输入文件名, 文件名 , 640, 480
clipboard=%folder_path%\%Filename%
clipwait
send,``
send,^a
sendinput,%Filename%
send,{Enter}
FileRecycle, %clipboard%
SplitPath, clipboard, name, dir, ext, name_no_ext, drive
sleep,300
FileCopy, F:\模板\1.%ext%, %Clipboard%
sleep,300
Run,%clipboard%

return

**Comment by HgyHgyHgy** [comment]
`是新建文件的快捷键，更换为实际设置的快捷键，就能用。模板文件中，要提前新建，1.xlsx等等模板文件。
