### ISSUE TITLE
Tag support

### ISSUE THREAD

**Issue by stakaz** [tamlok/vnote#77]
A nice and handy feature would be tag support for the notes. This could be realized in a markdown matter (and with full notebook support) without the need for a database. E. g. with an @tag or better something like #tag (as @something can be used for citations and references in markdown pandoc later).

**Comment by tamlok** [comment]
VNote has a plan to support the tags of notes via the configuration files. In my opinion, adding tags via configuration files is better than adding some notations within the note.

1. Tags are used to manage notes and do not belong to the content of a note.
2. Notations of tags in the note is not a standard (or basic) Markdown grammar, which makes the notes less portable or compatible.

What do you think of this?

Thanks!

**Comment by stakaz** [comment]
Regardless of the implementation it would be a very handy feature. I personally like the idea that everything is stored in the note md file by you are right, that saving tags into config files is a cleaner way. Unless one uses something like yaml header in the markdown (not sure, whether it was only pandoc or markdown in general).

**Comment by tamlok** [comment]
Supported!

**Comment by kamalmost** [comment]
how to add tags to notes?

**Comment by tamlok** [comment]
@kamalmost Hi, open a note and you could add tag at the right bottom corner, within the status bar.
