### ISSUE TITLE
有没有可能将笔记编辑区域单独做成一个项目

### ISSUE THREAD

**Issue by zyzz19951230** [tamlok/vnote#771]
非常好的一个开源项目。抱歉并非反馈问题，而是向您咨询一些问题。
最近在用qt开发一个开源的pdf阅读器项目，想法是将markdown编辑器和pdf阅读器融合到一块去，实现边看书边做笔记的功能，目前pdf阅读器部分已经实现，markdown部分尝试了web向的editor.md以及QMarkdownTextEdit组件，可以实现功能但效果都不尽如人意，然后看到您这个项目，发现markdown编辑器效果非常好，但由于代码比较多，一时之间不知道如何将编辑器部分单独提取出来，不知道能不能将编辑器部分做成一个单独的、可以复用组件(库)，以便其他开发者可以比较方便的进行二次开发。

**Comment by tamlok** [comment]
Hi，

目前由于时间问题，放在VNote上的精力不是很多，所以估计没有时间进行抽取了。你可以自己尝试一下。

谢谢！
