### ISSUE TITLE
After copy a link path the editor window becomes black

### ISSUE THREAD

**Issue by stakaz** [tamlok/vnote#78]
Hello this happens to me on the current git version:
After I copy a link (text or image) the editor window becomes black and I have to close all opened files (in this split) to get a normal view back again.

I have compiled with QT 5.10 on an actual arch linux system.

**Comment by tamlok** [comment]
Copy link and image in read mode? I develop VNote in Manjaro with 5.9.3, and haven't tested 5.10 yet. Could you try 5.9.3? You could download Qt from its website, and it could be installed into a folder, not affecting your system.

**Comment by tamlok** [comment]
Does it happen once we copy the link? I will try to repo it.

**Comment by stakaz** [comment]
I have looked into the problem a little bit deeper. It happens in read (preview) mode and it does not depend on the action, just click right and then left and the preview becomes black. You have to close and reopen the file to get the preview back.

**Comment by tamlok** [comment]
Do not need to copy the link? Just right clicking anywhere in the read mode to popup the context menu, and then left clicking other places to hide the menu will trigger a black window?

**Comment by stakaz** [comment]
Yes, exactly... Black only in the editor area (where the document is placed).

**Comment by tamlok** [comment]
Still can not reproduce it. I suggest that you could download Qt5.9 to compile it. 5.9 the LTS version. If the issue still exists, I think it may be caused by the openGL or display card driver. VNote use `QtWebEngineView` to render the HTML. It has some special requirements to the driver.
