### ISSUE TITLE
[Questions] pandoc 合并的 markdown 文本内容出现反斜杠 `\`

### ISSUE THREAD

**Issue by livingworld** [tamlok/vnote#782]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.4

Symptoms (表现): VNote 非常棒的一点就是不仅能全局检索多文件的本文内容，还能将文件以多文件或单文件合并的形式导出，这样汇总包含相关关键词的文本或卡片素材进行写作就非常便捷了。不过我有个问题，就是使用整合的 pandoc 工具导出的 markdown 格式文件会出现一些反斜杠的现象，问题出现在 markdown 格式源文件中包含类似于 [ 、] _ > < 这类字符文件中，导出的 markdown 格式相应符号位置前就会出现反斜杠 `\`。

How to Repro (如何复现): 问题出在 pandoc 导出命令么，是否可以通过 pandoc 命令的来自定义处理此类问题？

**Comment by tamlok** [comment]
将md格式导出为md格式？这个不需要pandoc吧？

如果是用pandoc来导出，那就是pandoc的问题，你可以先在命令行直接调用pandoc尝试解决。你列出的那些都是特殊字符，一般在md里面是需要转义的。

**Comment by livingworld** [comment]
对，用 pandoc 合并导出文件。

**Comment by tamlok** [comment]
合并多个md为一个md的话，你不如写个小脚本直接将多个文件合并，然后设置vnote调用你的脚本即可。

应该是pandoc的设置问题，你可以先在命令行里面调试好pandoc的参数再在vnote里面测试。

**Comment by tamlok** [comment]
而且，pandoc是进行格式转换的，md转md，估计是通过纯文本转md进行的，所以pandoc加上反斜杠转义感觉也是正确的做法。因为人家本来不是这样使用的。

**Comment by livingworld** [comment]
@tamlok 好的。主要是合并用关键词搜索出来的多个 markdown 文件为单个文件文件，就是将小推车里面的文件合并导出，这个还是非常好用的。
