### ISSUE TITLE
软件启动总是打开“欢迎页面”，设置没用

### ISSUE THREAD

**Issue by yousifun** [tamlok/vnote#783]
OS Version (操作系统): Windows 10 1809

VNote Version (Help - About VNote - Version: )(VNote版本): 2.4

Symptoms (表现):
软件启动总是打开“欢迎页面”，设置没用，重装删除配置文件也没有用。
![20190509092943.png](https://i.loli.net/2019/05/09/5cd382a56f17a.png)

How to Repro (如何复现):
另外一台电脑正常，不会出现这情况。笔记本不知道怎么回事抽风，无论怎么设置都是会打开“欢迎页面”。

**Comment by tamlok** [comment]
估计今天是一年第64天的倍数，所以每次启动总会打开欢迎界面。后面改一下逻辑。

**Comment by Memento1990** [comment]
🤔 还有这个隐藏逻辑~特意去尝试了一下, 确实如此, O(∩_∩)O哈哈~一般vnote启动后就放在那里了, 不怎么经常关闭启动的.

**Comment by tamlok** [comment]
主要是很多用户刚安装完后基本不会看就关闭，所以后面再显示一下，希望减少一些重复零碎的issue。

后面改为一天最多只显示一次吧。

**Comment by tamlok** [comment]
已经修复了 https://github.com/tamlok/vnote/commit/56715bc9a5c8377e9234eb8d2e06ed377b179b32

后面之后在该天的第一次打开才会显示。
