### ISSUE TITLE
VNote 2.4

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#789]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.4

Symptoms (表现): If I have a note open, and want to open another one, it replaces the one that is already open. How can I get the 2nd note to open in a new tab?

Also, I want to change the "Activate next tab" shortcut from Ctrl+Tab to Ctrl+PageDown. I tried to modify it to Ctrl+PgDn, but thata does not work. Please advise.

How to Repro (如何复现):

**Comment by tamlok** [comment]
Select this option in Settings:

![image](https://user-images.githubusercontent.com/5763157/57564663-037f7a80-73e2-11e9-8767-19c9a68d0102.png)

Try `Ctrl+PgDown` instead? Reference https://doc.qt.io/archives/qt-4.8/qkeysequence.html

**Comment by DutchPete** [comment]
Regarding the settings: I had that setting already, but it is not what my question is about.
I have noticed in version 2.4 that when I click on a note in the left pane, it opens that note in a tab in the central pane - let's call it note1.
When I next click on another note, let's call it note2, in the left pane, the tab with note1 is closed and replaced by a tab with note2 that is opened.

In the previous versions, 2.2 and 2.3, it was possible to have note2 open in a new tab **next to** the tab with note1. This does not seem to be possible in version 2.4 anymore, and that would be a big drawback.
But maybe it is still possible: please show me what I need to do.

**Comment by tamlok** [comment]
Then you need to de-select that option in the Settings. Or double-click to open a note.

**Comment by DutchPete** [comment]
OK, thank you.
