### ISSUE TITLE
搜索展示TODO 的功能

### ISSUE THREAD

**Issue by spesun** [tamlok/vnote#793]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):  

How to Repro (如何复现):
是否有过滤出来待办事项的功能

**Comment by tamlok** [comment]
搜索支持正则表达式的，所以可以考虑搜索`^\[x?\]`这样的？

**Comment by spesun** [comment]
也是一个解决的办法，谢谢
