### ISSUE TITLE
文件夹误删问题

### ISSUE THREAD

**Issue by josonle** [tamlok/vnote#798]
Linux操作系统，Vnote版本2.5版本。今天在使用时想移除“笔记本”下的一个文件夹，但是删除功能怎么是把文件完全删除啊？回收站中都没有踪影？这个逻辑是不是有什么问题啊，不应该是删除功能只是把vnote.json中的记录移除吗，怎么把磁盘中的文件删掉啊，希望能改进这一点。
还有就是误删的文件能恢复吗？看提示说是有笔记的回收站不知道这个在哪里。

**Comment by tamlok** [comment]
这个不算误删吧？删除一个文件夹的时候，就是提示删除，而非移除。界面也有警告提示。

![image](https://user-images.githubusercontent.com/5763157/57916973-7d25d580-78c6-11e9-8673-aa1278d68fe6.png)

每个笔记本都有一个回收站，删除的文件都可以在里面找回来。在笔记本下拉选择列表里面，右键菜单，打开回收站即可。或者直接去到笔记本根文件夹下面的`v_recycle_bin`文件夹下面按日期找。

**Comment by josonle** [comment]
> 这个不算误删吧？删除一个文件夹的时候，就是提示删除，而非移除。界面也有警告提示。
> 
> ![image](https://user-images.githubusercontent.com/5763157/57916973-7d25d580-78c6-11e9-8673-aa1278d68fe6.png)
> 
> 每个笔记本都有一个回收站，删除的文件都可以在里面找回来。在笔记本下拉选择列表里面，右键菜单，打开回收站即可。或者直接去到笔记本根文件夹下面的`v_recycle_bin`文件夹下面按日期找。

感谢啊，找到了，以后会多注意的。
