### ISSUE TITLE
希望能支持插入图片的管道命令以及脚注功能

### ISSUE THREAD

**Issue by swanv** [tamlok/vnote#8]
使用 马克飞象 的时候发现它有一个非常好的功能， 插入图片时可以这样` ![@描述 | left | 300x0 ](example.jpg)` 这样图片的下方会出现图片描述文字，left 表示靠左，图片的宽度会被设置为300px (x0应该表示保持缩放比)。这样实现了 图片和文字混排，而不是图片占用整个一行。

现阶段 VNote 插入的图片如果过宽，不会自动缩放，会撑大到整个界面之外。如果能实现上述功能，那么就很完美了。

**Comment by tamlok** [comment]
这个应该是马克飞象的扩展语法，不是标准的Markdown语法。后面会考虑一下兼容性和扩展的折中。

另外， 新版目前支持编辑模式时限制预览图片的宽度，您可以试用一下。

谢谢使用！

**Comment by swanv** [comment]
好的，可能我使用的是 1.3 版没有更新

**Comment by tamlok** [comment]
您好！为了兼容性，VNote目前暂时不会引入过多的扩展语法。针对您提出的问题，目前已经实现的解决方案是：

1. 阅读模式(a154e568de035f3f529868f28308f59285767de0)和编辑模式下均支持自动限制图片的宽度。
2. 居中显示图片，并在图片下方显示图片描述文字作为标题(5bb692bcc56117dfc1376e0f291c51a065909125)。

谢谢使用！

**Comment by tamlok** [comment]
目前打算使用插件[markdown-it footnote](https://github.com/markdown-it/markdown-it-footnote)来实现脚注功能，但该插件目前有问题，已提issue。
