### ISSUE TITLE
关闭某个编辑窗口时闪退

### ISSUE THREAD

**Issue by AaronKir** [tamlok/vnote#80]
我使用的系统是win7。我打开的编辑窗口太多了想关闭一些，但是一点关闭就闪退，重启时编辑窗口并未被关闭。

**Comment by tamlok** [comment]
Hi，能稳定地重现这个问题吗？被关闭的窗口是编辑模式还是阅读模式？VNote的配置文件夹下有一个`vnote.log`文件，后面遇到崩溃的时候，方便的话可以把这个文件发送到我邮箱，我看看有没有啥错误信息。配置文件夹可以在文件菜单里面打开。

谢谢反馈！

**Comment by AaronKir** [comment]
我试了很多次，无论是编辑模式或是阅读模式，关闭某个编辑窗口VNote都会闪退。有时候可以成功关闭1~2个，但继续再关闭的话还是会闪退，而且重启之后那些成功关闭的编辑窗口又恢复打开了。

**Comment by tamlok** [comment]
可以提供一下log吗？我这边复现不了。
