### ISSUE TITLE
小推车是做什么用的？

### ISSUE THREAD

**Issue by xvusrmqj** [tamlok/vnote#815]
看了一遍文档，也没有小推车 的内容，不知道这个是做什么用的？

**Comment by tamlok** [comment]
任意文件都可以添加到小推车里面，然后最后统一处理，比如导出小推车里面的所有文件。笔记列表里面右键菜单，添加到小推车。

就是类似于购物车，然后订单结算。

**Comment by xvusrmqj** [comment]
小推车的功能感觉很棒啊。那小推车的内容能支持同步吗？我在vnote.json文件中没有看到关于小推车的内容。是不是说它不能同步到另一台电脑？

**Comment by tamlok** [comment]
这个是临时的，没有持久化。后面会考虑保存起来。
