### ISSUE TITLE
是否可以考虑一下关联.md文件？

### ISSUE THREAD

**Issue by bequt** [tamlok/vnote#82]
是否可以考虑一下关联```.md```文件？方便直接打开```.md```文件

**Comment by tamlok** [comment]
Hi, 在Win下能可以设置md文件的默认打开程序是`VNote.exe`，或者直接将文件拖放到VNote的编辑区域。在Linux下也可以设置md文件的打开方式是VNote。

因为时间有限，所以该功能就交由操作系统来提供了，VNote暂时不提供设置选项。

谢谢支持！
