### ISSUE TITLE
回收站找起来太费劲，还原操作必须手工？

### ISSUE THREAD

**Issue by roro4ever** [tamlok/vnote#822]
OS Version (操作系统): Windows 10 

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
今天想恢复前几天删除的一片笔记，仿佛记得哪里看到过回收站，但就是死活找不到。  
看了几个issue，tamlock说在笔记本下拉菜单上右键（下拉按钮上点右键？这个操作有点儿新鲜呢），读了N遍没理解到啥意思。
  
自己瞎试，发现是在选择笔记本的下拉菜单的项目上，点右键就会出现该笔记本的回收站。  
这个操作太SAO了吧。何不就在当前选中的笔记本名字上右键呢，那样多直观。

之后发现，在任一打开的笔记的标签头上右键，也能打开回收站。

而且两种操作都会打开资源管理器 [notebookName]\_v_recycle_bin。  
按照自然的操作习惯，我以为的两者有区别：
+ 在笔记本名称上右键就进入_v_recycle_bin，
+ 在某个笔记的标签头上右键，就进入它所在笔记文件夹的回收站子目录 [notebookName]\_v_recycle_bin\noteFolderName\_v_recycle_bin

观察了下，目前回收站是按删除日期建子目录，并没有按笔记文件夹分，自然就无法实现这种效果。  
   
当然，用户可能直接删除了某个笔记文件夹而非笔记，所以按日期分会更简单。

---
不过，这个回收站，需要用户手动移动笔记到原目录吗？  
我没找到其他操作方式，从点击回收站就打开资源管理器来看，似乎只能手工搬移。  
但是我搬移之后，即使“重新加载”，在原笔记文件夹下也无法看到我删除的笔记，这。。。
最终，是在历史中双击打开找回的笔记的。

以后，在文件管理上，VNOTE可能还需要再完善完善就很好了。

VNOTE我每天都在用，是比较成功的一个笔记软件，谢谢作者的付出，我也经常推荐给周围的朋友，我已经很多年不做编程了，天天看小说，呵呵，所以帮不上什么忙。  
VNOTE目前已经有了很多用户，不着急，慢慢维护，慢慢发展，最终肯定会在在笔记软件这个细分领域拥有一批忠实用户的。

**Comment by tamlok** [comment]
刚开始，VNote删除的文件是不会放到系统的回收站的，这个跨平台实现比较困难，因此导致有些用户误删了整个D盘（因为新建笔记本的时候把D盘选为根目录，然后删除的时候没有看提示）。因此，VNote为每个笔记本提供了一个回收站的功能，所有删除都是把文件移动到回收站里面。因为VNote元数据是基于松散的文本结构，还原什么的比较复杂，因此就都按删除日期放到一个文件夹里面。

后面感觉可以增加一层废纸篓文件夹，可以移动笔记到废纸篓，废纸篓就是一个正常的文件夹，这样用户可以在vnote里面浏览并把笔记移动回其他正常的文件夹。

谢谢！
