### ISSUE TITLE
舰长模式的J,K 与用户希望的、最自然的激活方式不同

### ISSUE THREAD

**Issue by roro4ever** [tamlok/vnote#830]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
舰长模式下，Ctrl + E，按下JK后，所激活的标签页与用户希望激活的标签页不同。
用户希望的、最自然的方式是： 
+ 按下J，激活当前标签页的左侧标签页
+ 按下K，激活当前标签页的右侧标签页

这也是VIMIUM一直使用的方式。

作者有同感吗？呵呵。

**Comment by tamlok** [comment]
我觉得我们应该和vim看齐，而不是vimium😂j是向下，k是向上，所以j是下一个，k是上一个，于是就这样实现了。

**Comment by roro4ever** [comment]
VIM没有JK切换标签页，只有:tabp :tabn，但显然很不方便，很多VIMER是在vimrc中加了东西来切换的，因此vimium也是根据自己的习惯定制了这个快捷键。
使用习惯没法说谁好谁坏，以后可以通过做一个选项让用户来决定。
Github 好像不能投票哈，从没用过投票功能。

**Comment by tamlok** [comment]
vnote支持自定义快捷键的，看一下官方文档吧。

**Comment by tamlok** [comment]
在文件菜单下面有一个自定义快捷键。
