### ISSUE TITLE
双击笔记会打开两条相同的笔记，修改笔记会导致笔记内容清空

### ISSUE THREAD

**Issue by iaotin** [tamlok/vnote#834]
OS Version (操作系统): Windows 10 专业版 1809

VNote Version (Help - About VNote - Version: )(VNote版本): 2.5

Symptoms (表现):
快速双击左侧笔记，有时候会打开两条相同的笔记，修改笔记并保存，然后关闭所有笔记，再打开会导致笔记内容清空

How to Repro (如何复现):
当一条笔记较大时（在我的 issue 中是一万字左右），由于载入的时间大于鼠标双击的间隔，会出现打开了两条相同的笔记。
对两条笔记做冲突的修改，然后分别保存，关闭后再次打开，所有内容消失。

编辑模式为交换文件，另外打开了坚果云同步。此外没有其他的文件操作。

**Comment by iaotin** [comment]
出现了两次了，因为会打开很多条笔记同时编辑，不会注意到有两条是相同的一条。两次都幸好通过文件历史找回来了。
之后试验了一系列笔记编辑情况，终于能够复现这个小问题。
希望作者能够加入双击打开笔记的开关，非常感谢。

**Comment by tamlok** [comment]
Hi,

在默认编辑模式打开时能复现该问题。

已经修复(https://github.com/tamlok/vnote/commit/e0ba7210f36e37df8ee20e9e6684d5da622642d7)。

欢迎下载最新构建版本测试(https://bintray.com/tamlok/vnote/vnote/2.6#files)

Thanks
