### ISSUE TITLE
智能表格功能会删除某些字符串

### ISSUE THREAD

**Issue by jackydi** [tamlok/vnote#837]
OS Version (操作系统): Windows10
VNote Version (Help - About VNote - Version: )(VNote版本): 2.5

Symptoms (表现):

开启智能表格功能时，会删除某些字符串

How to Repro (如何复现):

1. 编辑模式下，打开智能表格功能，复制一个带%2C的字符串到表格单元格中，%2会被自动替换为一些空格。

2. 或者，关闭智能表格功能时，把带有%2C字符的字符串复制到表格单元格中，然后打开智能表格功能，也会被自动替换。

其他智能表格的问题在标题： #832 中也详细说明了，希望有时间能修复。

**Comment by tamlok** [comment]
Hi,

已经修复！ https://github.com/tamlok/vnote/commit/09df438f2e9103c81b69ad7b5160c5338b8a4fda

谢谢！
