### ISSUE TITLE
阅读模式使用快捷键跳转标题，在某些地方会失效

### ISSUE THREAD

**Issue by agentzheng** [tamlok/vnote#84]
![default](https://user-images.githubusercontent.com/22427645/34465240-760021d2-eee0-11e7-8ee8-0ee517d3e964.png)
![default](https://user-images.githubusercontent.com/22427645/34465307-73014ec4-eee1-11e7-92d2-3d697746429d.png)

从文档底部连续向上跳转标题，在图中这个两个时候（举个例子），[[ 无法向上跳转，即使先]]到下一个标题，再次[[ 回到原位置时还是会失效

win 64 portable 1.11  快捷键参考示例文件

**Comment by tamlok** [comment]
Hi, 请确认一下输入焦点在编辑区域再试一下？即确保上下箭头能够移动阅读模式里面那个滚动条的情况下，再试试？

谢谢反馈！

**Comment by agentzheng** [comment]
确认了，使用方向键是可以移动的，但是[[ 就不行，使用 ]]从文档上部往下暂未遇到类似问题 @tamlok

**Comment by tamlok** [comment]
请问`[[`是在任意情况下都不可以吗？另外，其他比如`[}`, `[]`这类的有没有问题呢？另外，您有进行过自定义快捷键设置吗？

谢谢！

**Comment by agentzheng** [comment]
@tamlok 你好，我在issue中已经说过了，[[只在特定地方不可以，图片中的两个地方是我举的例子，经过我刚才又测试了一下，问题可以在别的文档中复现.但是暂时未发现出现的位置有什么规律。然后经过你的提醒，我发现 []在上面两幅图的位置也失效了，][ ,[{ 和 ]} 还是可以正常使用，我没有对VNote进行过自定义快捷键。

**Comment by tamlok** [comment]
已经修复了(9e5f3abb4bbbe00eee4612c0a0ce352f50e8ba03)，会在下一个版本带上，或者下载最新构建版本。

非常感谢反馈！ :)

**Comment by agentzheng** [comment]
@tamlok 支持，很棒的软件，准备从typora转过来

**Comment by tamlok** [comment]
已经发布1.11.1，请下载尝试是否已经解决问题。
