### ISSUE TITLE
保存好的内容，重新打开VNote之后就消失部分

### ISSUE THREAD

**Issue by Chen-gjy** [tamlok/vnote#840]
OS Version (操作系统):  Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.5

Symptoms (表现):
已经保存好的内容，重新打开VNote之后就消失部分了。
ps：我个人的vnote经常有十几个标签页

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

能稳定复现吗？是否开启了自动保存功能？

我暂时没遇到过这种情况。

谢谢！

**Comment by laggardkernel** [comment]
遇到和你差不多的情况：
- 平时开6、7个标签
- 有些文件内容没有保存上
- 有些文件内容变为空白

目前推测是app退出时，`.vswp`变动没有合并回原文件，之后swap文件还被删除了……

**Comment by tamlok** [comment]
https://github.com/tamlok/vnote/issues/850

已经修复
