### ISSUE TITLE
VNote的Latex公式支持问题

### ISSUE THREAD

**Issue by 7sasuke7l** [tamlok/vnote#841]
Windows 10家庭中文版
VNote 2.6 X64 采用的渲染器时MarkDown-it，扩展是MathJax
问题：LaTex中的行外公式，VNote可以实施预览，比如我输入

 $\dfrac{4t-4t^3}{1-4t^2+t^4}=-\dfrac{3t-t^3}{1-3t^2}$

就会显示对应的公式，且代码变为绿色，但这行公式我其实是想单独一行居中，应该时两边时$$$$，但我改为

 $$\dfrac{4t-4t^3}{1-4t^2+t^4}=-\dfrac{3t-t^3}{1-3t^2}$$

此时就代码并没有高亮变绿色，仍然是黑色，公式也不会显示。

这里图片用图床吧，本人不是程序员，仅仅是数学系学生，所以对github不是很了解
[https://s2.ax1x.com/2019/06/11/Vgp9rq.png](url)

**Comment by tamlok** [comment]
$$那一行前面和后面都加一行空行，应该就没问题了。目前这个块元素需要和前后的行内元素分隔开来。

**Comment by 7sasuke7l** [comment]
> $$那一行前面和后面都加一行空行，应该就没问题了。目前这个块元素需要和前后的行内元素分隔开来。

非常赞，完美解决，多谢了
