### ISSUE TITLE
Folder out of place

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#842]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3

Symptoms (表现): I have 1 root folder, with a number of subfolders that I use to collect my various notes in. In addition, I have a folder with attachments and a folder with images. The files in the *attachments* folder and in the *images* folder are only linked to from within the subfolders.

The *attachments* folder mysteriously appeared among the subfolders when I opened VNote today. I want to get this folder out, i.e. not in the list among the subfolders when VN is open. I tried right-clicking, then *Delete*, but that would mean deleting the folder permanently, which I don't want, of course.

Please advise how to proceed.

How to Repro (如何复现):

**Comment by tamlok** [comment]
You could open the `_vnote.json` file within that folder, and remove the attachment folder entry:

It may look like this:

```json
{
    "created_time": "",
    "files": [
        {
            "attachment_folder": "",
            "attachments": [
            ],
            "created_time": "2017-12-28T04:54:12Z",
            "modified_time": "2018-12-10T09:37:03Z",
            "name": "notes.md",
            "tags": [
            ]
        }
    ],
    "sub_directories": [
        {
            "name": "Your Attachment Folder Name"
        },
        {
            "name": "Ideas"
        }
    ],
    "version": "1"
}
```

You need to remove:

```json
 {
            "name": "Your Attachment Folder Name"
 },
```

**Comment by DutchPete** [comment]
Thank you, that worked fine.
