### ISSUE TITLE
VNote 2.6 cannot run on Linux Mint 18.3

### ISSUE THREAD

**Issue by jluliuchao** [tamlok/vnote#848]
OS Version (操作系统): Linux Mint 18.3

VNote Version (Help - About VNote - Version: )(VNote版本): 2.6

Symptoms (表现):corruption

How to Repro (如何复现):Open a note in VNote,and then touch CTRL+T a few times,and VNote will abort.

The log file is attached.[VNote.log](https://github.com/tamlok/vnote/files/3288640/VNote.log)

**Comment by tamlok** [comment]
I think it is similar issue as https://github.com/tamlok/vnote/issues/417 caused by display card driver according to the following lines:

```
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x4a4bbc)[0x7f4f44640bbc]
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x4a4da7)[0x7f4f44640da7]
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x4a4f61)[0x7f4f44640f61]
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x4a5069)[0x7f4f44641069]
/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x35267c)[0x7f4f444ee67c]
```

**Comment by jluliuchao** [comment]
@tamlok Thanks,this problem is solved after I install the NVIDIA driver.
