### ISSUE TITLE
希望能在阅读模式加入光标

### ISSUE THREAD

**Issue by agentzheng** [tamlok/vnote#85]
虽然说编辑模式很强大了，但是我们最终还是要看一下在阅读模式下到底是长什么样，但是每次我ctrl+t 保存并进入阅读模式想要预览一下，然而当我按下ctrl+w想要编辑的时候，我基本无法预测到光标的位置（这个体验很差。。。），光标不在我原来从编辑模式进入阅读模式的位置了，我可能还需要各种移动光标再回到原位，并不方便。
我的一点小想法就是在阅读模式也加入光标，鼠标和键盘可以移动光标，当ctrl+w的时候直接从那里就可以开始编辑。同时在ctrl+t的时候保留原来编辑模式光标的位置。谢谢。
![default](https://user-images.githubusercontent.com/22427645/34465970-897df2ec-eeff-11e7-8b73-c87af9c57a92.png)
![default](https://user-images.githubusercontent.com/22427645/34466026-8d802854-ef01-11e7-8006-3f6292cade1c.png)

**Comment by tamlok** [comment]
hi，阅读模式暂时无法添加光标。目前vnote是通过标题来进行阅读和编辑模式的定位。可以进行如下优化：切换为编辑模式时，如果编辑模式已经在该标题下，则不再移动光标。这样对于临时切换到阅读模式预览效果应该是没有问题了。其实vnote之前是计划加一个lens的功能，即预览光标所在的附近几行。

**Comment by agentzheng** [comment]
@tamlok 支持

**Comment by tamlok** [comment]
已经在1.11.1中修复了。后面如果还有问题，可以重新打开该issue。 谢谢反馈！
