### ISSUE TITLE
文件内容变为空白，为何保存失效？

### ISSUE THREAD

**Issue by laggardkernel** [tamlok/vnote#850]
**更正**：此bug由于同一文件打开两份导致

OS Version (操作系统): macOS

VNote Version: 2.6, Qt 5.9.7

Symptoms (表现):

昨天关闭Vnote，今天打开时发现多个文件变为空白。大多为最近编辑过的文件。以`network.md` 文件为例，根据Dropbox历史，`network.md`上次保存时间为11号，实际上编辑过程中我是有`Cmd+S`保存的，最新变动时间应该为13号或者14号。在这个时间段内，`_vnote.json`是有被Dropbox更新的。这说名至少不是Dropbox的锅。

为什么实际`.md`文件在保存后没有更新，那我`Cmd+S`到底保存到哪里去了呢？

**结论**

忙活了半天，终于小心翼翼恢复完毕。问题在于`Cmd+Q`退出时，`.vswp`文件没有合并。自己尝试了几次，保存后，只关闭标签不关闭app，可以观测到对应`.vswp`合并回去了。但是在打开标签的情况下`Cmd+Q`就会触发这个bug，`.vswp`没有合并，同时原文件大小变为0。触发几率 100%，关闭swap file可解。

**Comment by laggardkernel** [comment]
更新：在网页版Dropbox一番查找后，发现删除文件类表中有同名`.vswp`文件存在。

请问：`.vswp`文件是不是中间保存的文件。目前VNote保存机制时暂时保存在`.vswp`文件内，退出app时合并变动到源文件？

**Comment by tamlok** [comment]
Hi,

谢谢帮忙调试！`cmd+q`是macOS特有的强加的快捷键，可能会引起一些副作用。想确认一下：

1. 如果`cmd+q`之前把文件都保存好，然后再`cmd+q`，会发生文件丢失吗？
2. 如果正常关闭程序（`x`按钮），会发生文件丢失吗？
3. VNote的逻辑是：如果没有保存，则把修改先保存到swp文件，如果按保存，那么就会写入原文件，关闭的时候会把swp文件删除。现在一个原因可能是`cmd+q`之后，系统在vnote要保存原文件的时候就把vnote强杀了，所以留了一个空白文件。

我会尽快确认并修复。

谢谢！

**Comment by laggardkernel** [comment]
今天再测试发现这个问题触发还需要其他条件。以下是正确的触发步骤，
1. 开启swap，重启vnote
2. 选择带有图片的笔记，**双击**笔记（貌似打开文件由双击改为了单击，此时错误地打开了2份一样的笔记）
3. 关闭一份重复打开的笔记
4. 修改另一份打开的笔记，`Cmd+S`保存，退出。

这个时候会弹出一个提示框，告知你有无效的图片（其实图片依然有效，仍然在笔记中被引用）。由于图片实际还在被使用，我自然选了取消删除，然后就会触发笔记原文件`.md`变为0的bug。有一定几率`.vswp`没有被删除，再次打开时提示恢复文件，但如何触发这种情况没做深入研究。

1. 会；
2. `Cmd+q`和点击关闭`x`按钮表现行为没有区别；
3. 空白文件行为应该和我上面步骤中双击打开一份文件2次有关；

**Comment by laggardkernel** [comment]
关于单击打开笔记。经过确认，在`Settings -> Note Management -> Notes`下有`Single click to open a note in current tab`选框。虽然我并没有勾选它，但现在却变为了单击打开笔记。VNote版本为 2.6.

**Comment by tamlok** [comment]
谢谢！那应该是和之前用户报告的问题一样，双击快速的话可以把一个文件同时打开两个，从而导致保存失败。这个问题应该已经修复了的，你可以尝试一下下载最新构建版本：https://bintray.com/tamlok/vnote/vnote/2.6#files

另外，这个版本用的是Qt 5.12了，听说cpu会降下来，也麻烦帮忙留意一下。另外，可以的话，可以帮忙测试一下这个版本的公式原地预览是否正常工作。

谢谢！

**Comment by laggardkernel** [comment]
抱歉，一开始没注意到双击打开2份是个bug。搜索了一下，的确有人已经反馈了这个bug #834。我还以为是app改动了默认打开行为，由于我双击相当于两次单击，所以一个文件打开了两次……

上面链接中的版本已经没有了一个文件打开2次的问题。

CPU降下来是什么，能够详细讲一下吗？

原地预览应该不是`Cmd+T`预览吧。因为我没有用过这个功能，从字面上推测是指在编辑模式下渲染公式，类似于编辑模式下在图片链接下渲染图片。Markdown开启MathJax扩展，`Cmd+T`切换预览显示公式没有问题，但是在编辑状态下并没有渲染为公式。

**Comment by tamlok** [comment]
之前在mac上面是cpu占用有时候比较严重。

所以用了新版本后还有文件被清空的情况吗？

原地预览就是在编辑模式下面预览公式，不是`cmd+t`，那估计还是有点问题，后面我看一下。

**Comment by laggardkernel** [comment]
CPU的问题没有注意过，所以不大好对比。

新版本没有出现文件被清空问题，这个问题已经解决了。
