### ISSUE TITLE
全屏的时候菜单栏不可用

### ISSUE THREAD

**Issue by yehaifeng** [tamlok/vnote#852]
OS Version (操作系统): Windows,

VNote Version (Help - About VNote - Version: )(VNote版本): 2.6
Symptoms (表现):
<F11>的时候菜单栏不可用，是否可修复一下，谢谢。

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi，

请参考置顶issue更新一下显卡驱动或者设置一下opengl，谢谢！或直接搜索关闭的issue:全屏。

**Comment by yehaifeng** [comment]
谢谢！
添加环境变量 QT_OPENGL = angle解决。 #226
