### ISSUE TITLE
Strange GUI behaviors on Win (Win上异常的图形界面行为)

### ISSUE THREAD

**Issue by tamlok** [tamlok/vnote#853]
VNote requires openGL and it may not work well on Windows by default.

Strange behaviors include:

- Interface freezes and does not response (especially in read mode);
- Widgets are out of order after maximizing and restoring the main window;
- No cursor in edit mode;
- Menus are not clickable in full screen mode.

There are several ways to solve this issue:

- Try to assign an integrated display card to VNote is available;
- Try to update the driver of display card;
- Specify openGL option to use by doing either of these:
    - Declare a system environment variable named `QT_OPENGL` and set its value to one of `desktop`, or `angle`, or `software`;
    - In `Settings` dialog of VNote, select one of the openGL option and apply.

Restart of VNote is needed and it is recommended to close all the notes before trying to specify openGL option.

**Comment by charles-sun0v0** [comment]
遇到同样的问题，指定显卡驱动为集显没有用，但是设置opengl为SoftwareOpenGL有用

**Comment by sunshine-zkf** [comment]
遇到软件无法缩小后，在VNote的设置对话框里面，指定一个openGL的值，重启VNote后，VNote刚进入就闪退了，删除软件重新安装也无法进入。

**Comment by tamlok** [comment]
@sunshine-zkf 是VNote 2.0吧？去到`c:\users\xxx\AppData\Roaming\VNote`下面，打开`session.ini`，把里面的`[last_opened_files]`整个小节删掉。如果不懂操作，可以直接删除`session.ini`，后面需要重新导入以前的笔记本。

**Comment by sunshine-zkf** [comment]
> @sunshine-zkf 是VNote 2.0吧？去到`c:\users\xxx\AppData\Roaming\VNote`下面，打开`session.ini`，把里面的`[last_opened_files]`整个小节删掉。如果不懂操作，可以直接删除`session.ini`，后面需要重新导入以前的笔记本。

非常感谢博主如此快的回复，按你的方法可以进入笔记了，但是设置OpenGL值后，重启依然未解决全屏不能缩小的问题。

**Comment by tamlok** [comment]
@sunshine-zkf 尝试新的值前先不要打开笔记，然后多试几个值，每个都试一下。

**Comment by westfly** [comment]
```
声明一个名为QT_OPENGL的环境变量，其值为desktop 
```
好使

**Comment by Bruise-Lee** [comment]
![Image](https://github.com/user-attachments/assets/fe28156a-4877-41d1-ba03-fdfdcc8fc77b)puml返回的乱码了，放到测试上没有错，什么情况
