### ISSUE TITLE
自定义快捷键, 实现「ctrl+,」==「$$」

### ISSUE THREAD

**Issue by zhuoshuai** [tamlok/vnote#859]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.6
Symptoms (表现):
> 能不能自定义快捷键, 实现类似于 ` 「ctrl+;」==「``」且光标自动移动至中央`的功能, 使得`「ctrl+,」==「$$」,且光标自动移动至中央`

**Comment by tamlok** [comment]
hi，这个暂时没有快捷键，可以考虑使用片段功能，并分配快捷键，具体参考官方文档。

效果：假如分配快捷键f，那么可以通过｀ctrl-e s f｀来实现插入公式。

**Comment by zhuoshuai** [comment]
1. 代码片段插入的方式有点大材小用了，在写文章中若是频繁的插入行内公式，使用`ctrl-e s f` 不太方便。
2. 能不能在配置文件`vnote.ini`中留个自定义`符号`+`快捷键`的选项，类似`「ctrl+;」==「``」`？

**Comment by tamlok** [comment]
这个目前暂时没有，后面会添加。

**Comment by zhuoshuai** [comment]
现在暂时在Win10 下，通过`AutoHotkey`实现vnote窗口下快捷键「ctrl+,」==「$$」及「ctrl+/」==「$$$$」；
脚本代码如下：
```
#ifWinActive, ahk_class Qt5QWindowIcon
;「ctrl+,」==「$$」，「ctrl+/」==「$$$$」

;;;;;;;;;;;;;「ctrl+,」==「$$」
^,::  ;ctrl+,
	SendInput $$
	
	Send {Left}
Return
;;;;;;;;;;;;;「ctrl+/」==「$$$$」
^/::  ;ctrl+/
	SendInput $$$$
	
	Send {Left}
	Send {Left}
Return
#ifWinActive
```
