### ISSUE TITLE
强烈建议增加一个新建同级目录的快捷键

### ISSUE THREAD

**Issue by HgyHgyHgy** [tamlok/vnote#861]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
虽然用ahk也可以部分地实现这个功能，但在子目录已打开的情况下不能做到。
可以先按“向左”，在子目录未展开的情况下，它会进入上一目录，然后发出新建目录的命令，就能新建同级目录。
但在子目录已展开的情况下，它会把目录变成未展开！
ahk无从判断目录是否已展开，“向左”数量无法确定。只能先把目录收缩，后再发出新建同级目录命令。

How to Repro (如何复现):
望，增加一个新建同级目录快捷键。对于用文件夹来记录信息的操作影响很大。

或者取消“向左”收缩目录的功能，这个向左会收缩目录的功能不太直观，也阻碍了用ahk新建同级目录的方法。收缩目录本来已可用减号来进行。

**Comment by tamlok** [comment]
后面加一个菜单项吧。

**Comment by HgyHgyHgy** [comment]
取消“向左”收缩目录的功能, 或者增加返回上一级目录的快捷键，会更简单。能够定制新建同级目录的快捷键，是最好的。

**Comment by tamlok** [comment]
Fixed in v2.7.
