### ISSUE TITLE
本地 PlantUML JAR 使用 sh -c 似乎应该用引号将后续参数包裹传递

### ISSUE THREAD

**Issue by zzndb** [tamlok/vnote#864]
OS Version (操作系统): openSUSE Tumbleweed

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7

Symptoms (表现):

设置-Markdown-PlantUML JAR 测试失败 部分截图如下

![image](https://user-images.githubusercontent.com/20870493/59962624-93086500-951a-11e9-9fab-e5794717e7f8.png)
---

将 `/bin/sh -c` 后续参数用引号（单/双）包裹正常

如测试
```
sh -c ls -al
sh -c 'ls -al'
```
的不同效果

**Comment by tamlok** [comment]
Uh~~~ 应该已经修复了。
