### ISSUE TITLE
v2.7 阅读模式在 macOS 中失效

### ISSUE THREAD

**Issue by laggardkernel** [tamlok/vnote#866]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7

Symptoms (表现):

切换到阅读模式无显示，一片空白。换到旧版 v2.6 50fbbdb7c218e130318d9c3497b1bdf91c62f3c8 无此问题。

**Comment by laggardkernel** [comment]
我手头还有一个 v2.6 1046d1，此版本阅读模式也无效。

**Comment by tamlok** [comment]
应该是qt的版本引起的，会紧急修复。

**Comment by tamlok** [comment]
Hi,

应该是Qt版本变更引起的，应该已经修复了，帮忙下载最新构建版本测试一下：https://bintray.com/tamlok/vnote/vnote/2.7#files ？

谢谢！

**Comment by laggardkernel** [comment]
据测试此问题已修复。
