### ISSUE TITLE
Copy Button

### ISSUE THREAD

**Issue by Warning-Forever** [tamlok/vnote#867]
OS Version: Windows 7 x64
VNote Version: 2.7

It's about the new feature Copy Button: "Add copy button to copy code block in read mode"
But what if I don't need that button? Is there a setting to remove it?
Thanks.

**Comment by tamlok** [comment]
Currently there is no config for this. If you could compile it yourself, you could easily disable this by adding a return at the front of the function addCopyButtonxxxx in markdown_template.js.

**Comment by tamlok** [comment]
Already fixed now. I added a config to control it. You could download the latest build https://bintray.com/tamlok/vnote/vnote/2.7#files and have a try.

https://github.com/tamlok/vnote/blob/151481cfcaab469e7bbde7d732cbab88389092fe/src/resources/vnote.ini#L424

Thanks!

**Comment by Warning-Forever** [comment]
It works. Thank you very much.
