### ISSUE TITLE
VNote-2.7-x64 无法启动

### ISSUE THREAD

**Issue by July-X** [tamlok/vnote#869]
OS Version (操作系统): Windows, Linux, macOS
macOs:10.14.5
VNote Version (Help - About VNote - Version: )(VNote版本): VNote-2.7-x64.dmg

Symptoms (表现):
安装后无法启动

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

应该是Qt版本变更引起的，应该已经修复了，帮忙下载最新构建版本测试一下：https://bintray.com/tamlok/vnote/vnote/2.7#files ？

谢谢！

**Comment by amosCc** [comment]
我下载这个了，但打开之后没法预览

**Comment by tamlok** [comment]
是一个小时前下载的吗？这里的文件是最新构建的，我一个小时前有新的修复，所以你需要重新下载一个测试。

**Comment by July-X** [comment]
> 是一个小时前下载的吗？这里的文件是最新构建的，我一个小时前有新的修复，所以你需要重新下载一个测试。

可以关闭issue了，重启Mac即可。
