### ISSUE TITLE
v_simple主题无法在编辑模式加粗加大显示分级标题

### ISSUE THREAD

**Issue by zhaoruiyang98** [tamlok/vnote#870]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7

Symptoms (表现):在编辑模式下无法像v_pure那样加粗加大显示分级标题(## 内容)

**Comment by tamlok** [comment]
@LuoshuiTianyi (the author)

**Comment by LuoshuiTianyi** [comment]
我专门改掉的 emm，如果接受不了的话我就改回去吧

2019-06-24 17:56 GMT+08:00, Le Tan <notifications@github.com>:

**Comment by zhaoruiyang98** [comment]
> 我专门改掉的 emm，如果接受不了的话我就改回去吧 2019-06-24 17:56 GMT+08:00, Le Tan <notifications@github.com>:
> […](#)
> @LuoshuiTianyi (the author) -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#870 (comment)](https://github.com/tamlok/vnote/issues/870#issuecomment-504943076)

= =|| 我是觉得渲染一下分级标题在编辑的时候挺方便的，也比较符合vnote编辑模式的原地预览特性

**Comment by LuoshuiTianyi** [comment]
行

2019-06-24 18:46 GMT+08:00, zhaoruiyang98 <notifications@github.com>:

**Comment by LuoshuiTianyi** [comment]
嗯。。。等会，我不是很会用 Git

我输入 git push origin dev 的时侯显示了：src refspec dev does not match any

请问如何解决？

Siyu Cao <csycaosiyu@gmail.com> 于2019年6月24日周一 下午6:46写道：

**Comment by LuoshuiTianyi** [comment]
还是说我应该先 Fork 给我自己，然后提交 pr ？

Siyu Cao <csycaosiyu@gmail.com> 于2019年6月24日周一 下午6:55写道：

**Comment by zhaoruiyang98** [comment]
> 还是说我应该先 Fork 给我自己，然后提交 pr ？ Siyu Cao <csycaosiyu@gmail.com> 于2019年6月24日周一 下午6:55写道：
> […](#)
> 嗯。。。等会，我不是很会用 Git 我输入 git push origin dev 的时侯显示了：src refspec dev does not match any 请问如何解决？ Siyu Cao ***@***.***> 于2019年6月24日周一 下午6:46写道： > 行 > > 2019-06-24 18:46 GMT+08:00, zhaoruiyang98 ***@***.***>: > > Closed #870. > > > > -- > > You are receiving this because you were mentioned. > > Reply to this email directly or view it on GitHub: > > [#870 (comment)](https://github.com/tamlok/vnote/issues/870#event-2433842302) >

对，应该是先fork的

**Comment by tamlok** [comment]
@LuoshuiTianyi 如果要修改的话，最好这两天提pr哦，我打算发布一个2.7.1，紧急修复一下之前的问题。

**Comment by LuoshuiTianyi** [comment]
已经提交了

2019-06-24 20:57 GMT+08:00, Le Tan <notifications@github.com>:

**Comment by LuoshuiTianyi** [comment]
只不过不是用 pr

Siyu Cao <csycaosiyu@gmail.com> 于2019年6月24日周一 下午9:29写道：

**Comment by tamlok** [comment]
这里没显示有pr啊

**Comment by LuoshuiTianyi** [comment]
哦豁，我之前忘了点击 pr 了

Le Tan <notifications@github.com> 于2019年6月24日周一 下午9:30写道：
