### ISSUE TITLE
VNote move taskBar

### ISSUE THREAD

**Issue by hqwx2018** [tamlok/vnote#873]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7

Symptoms (表现):
打开VNote，拖动到任务栏底部，无法再拖动上来。

How to Repro (如何复现):

**Comment by tamlok** [comment]
这个应该是win操作系统的问题，并非vnote特定？你可以任务栏尝试右键菜单把vnote最大化，然后文件菜单，设置，重置布局，重启vnote，应该就好了。

**Comment by hqwx2018** [comment]
是的 企业微信也有这样的问题，这个无法修复吗

**Comment by tamlok** [comment]
这个应该是操作系统的问题呀！微软应该禁止窗口拖动到任务栏一以下。应用程序估计么啥办法，也不应该是应用程序负责的范围。

**Comment by hqwx2018** [comment]
好的 谢谢
