### ISSUE TITLE
question: how to clear highlight

### ISSUE THREAD

**Issue by linusboyle** [tamlok/vnote#877]
Hello, the `:nohl` command is not implemented yet. what should I do to clear the search result highlight in vim mode?

**Comment by tamlok** [comment]
According to the [shortcuts help](https://github.com/tamlok/vnote/blob/master/src/resources/docs/shortcuts_en.md), you could use `<space><space>` to clear highlight.

**Comment by linusboyle** [comment]
> According to the [shortcuts help](https://github.com/tamlok/vnote/blob/master/src/resources/docs/shortcuts_en.md), you could use `<space><space>` to clear highlight.

That's it, thank you
