### ISSUE TITLE
windows 10下，样式错乱

### ISSUE THREAD

**Issue by foreveryang321** [tamlok/vnote#88]
![tim 20180107154000](https://user-images.githubusercontent.com/5868190/34647606-431a3dd0-f3c1-11e7-9f29-7947f3555f6a.png)

**Comment by tamlok** [comment]
Hi, 请更新一下操作系统或者显卡驱动再试试？很多用户都遇到过这种情况，我之前是通过更新显卡驱动解决了。

谢谢支持！

**Comment by foreveryang321** [comment]
好的，谢谢

**Comment by foreveryang321** [comment]
更新最新显卡驱动后正常了

**Comment by tamlok** [comment]
期待使用反馈！ :)
