### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by cossonleo** [tamlok/vnote#885]
OS Version (操作系统): Linux/archlinux

QT： 5.13

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.1 appimage

Symptoms (表现): 无法启动
![image](https://user-images.githubusercontent.com/20379044/60483843-c9d43d00-9cc9-11e9-89cc-476d8e16e41a.png)

How to Repro (如何复现):

**Comment by tamlok** [comment]
通过`vnote-bin`来安装VNote吧，在Qt 5.13下没有测试过。Qt的版本升级经常会造成不兼容的问题的。

**Comment by cossonleo** [comment]
已经解决了，谢谢大佬
