### ISSUE TITLE
windows10下样式显示异常，如何找问题？

### ISSUE THREAD

**Issue by disheno** [tamlok/vnote#888]
OS Version (操作系统): Windows, Linux, macOS
windows10 ，预览版，驱动是最新的
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
窗体控件大小异常，该怎么找问题？

How to Repro (如何复现):
![微信截图_20190704004739](https://user-images.githubusercontent.com/19802097/60609960-5cbdc600-9df5-11e9-9ebf-fdd1de5a6348.png)
![微信截图_20190704004944](https://user-images.githubusercontent.com/19802097/60610109-b1f9d780-9df5-11e9-8537-038f7e6cda59.png)

**Comment by tamlok** [comment]
看置顶第三个issue，opengl的问题

**Comment by disheno** [comment]
> 看置顶第三个issue，opengl的问题

试了的，还是没有解决，切换过3种opengl方式

**Comment by tamlok** [comment]
重启vnote了吗？文件菜单，配置文件夹，把themes文件夹删掉，重启vnote，再试试？

**Comment by disheno** [comment]
> 重启vnote了吗？文件菜单，配置文件夹，把themes文件夹删掉，重启vnote，再试试？

![image](https://user-images.githubusercontent.com/19802097/60758352-e1545280-a048-11e9-889e-cbdc324b832e.png)
大大，试了一下，依然没有解决，工具栏图标特别小

电脑配置是放大200%的，
![image](https://user-images.githubusercontent.com/19802097/60758453-5c1d6d80-a049-11e9-92c1-dc72679bac0a.png)

**Comment by tamlok** [comment]
你这个是自己编译的吗？

**Comment by disheno** [comment]
> 你这个是自己编译的吗？

不是的,是下载release里的:VNote_win_X64_portable_2.7.1.zip

**Comment by tamlok** [comment]
那就不太清楚了，这边无法复现。你可以用快捷键替代工具栏。

**Comment by disheno** [comment]
> 那就不太清楚了，这边无法复现。你可以用快捷键替代工具栏。

有什么办法可以找出问题吗,工具栏控件跟其他控件不一样吗

**Comment by tamlok** [comment]
暂时不知道什么问题。你看其实工具栏里面也有两个按钮大小是正常的。

**Comment by disheno** [comment]
> 暂时不知道什么问题。你看其实工具栏里面也有两个按钮大小是正常的。

![image](https://user-images.githubusercontent.com/19802097/60770524-2e4e2c80-a10e-11e9-9740-c30aa639080f.png)
**我直接在设置中将工具栏按钮大小设置为15了,可以使用,看起来是工具栏按钮没跟着系统设置同样的放大200%**
