### ISSUE TITLE
[feature suggestion]文件管理

### ISSUE THREAD

**Issue by grothen** [tamlok/vnote#890]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

觉得非常奇怪，文件管理器里面为什么不支持所有的后缀，至少给这样的选项吧

**Comment by tamlok** [comment]
什么意思呢？具体截图说明？

**Comment by grothen** [comment]
[image: image.png]
我想在这里能显示所有类型的文件，可以设置一个开关来控制是否能显示，因为经常会有链接本地文件的操作

**Comment by tamlok** [comment]
没看到图片，还是不懂您的意思。vnote里面对文件类型是没有限制的。

**Comment by grothen** [comment]
不好意思，图片可能有点问题，我知道可以链接任意格式的文件，但是我希望能在左下角的笔记框里面显示出来

**Comment by tamlok** [comment]
那个是需要你编辑json文件把笔记加到索引里面，任意格式都可以。

另外，你可以使用左侧第三个tab浏览器功能来浏览任意文件，无需索引。

**Comment by HgyHgyHgy** [comment]
还不如增加一键导入该文件夹所有文件的右键菜单或快捷键。

或者可是设置是否显示所有文件，即使包括没索引的文件，也就不必为未索引的文件新建索引。

其实多数情况下，自己导入也不麻烦，但如果是参考文献，那就麻烦了。参考文献会不断增加，你很难记住那个添加了，哪个没添加。
你只好打开那个目录去打开参考文献，不能在vnote中直接打开参考文献。
至于转到那个浏览器界面，那要几步操作，还不如直接打开目录后再打开文献。

**Comment by grothen** [comment]
![image](https://user-images.githubusercontent.com/3252576/60753823-ebeff700-a00a-11e9-8495-77214e76fd44.png)
这个文件夹里有一个123.m的文件但是没有显示出来

**Comment by tamlok** [comment]
这是笔记本，是有索引文件索引的，并不会显示任意文件，你得手动修改索引文件或者在文件菜单里面导入外部文件。

如果要显示任意文件，可以使用第三个tab的浏览器功能：

![image](https://user-images.githubusercontent.com/5763157/60755236-6f1b4800-a01f-11e9-83d8-fcced9a410fc.png)

**Comment by grothen** [comment]
明白了，多谢
