### ISSUE TITLE
建议复制excel表格内容后，增加“以md语法表格插入”的功能

### ISSUE THREAD

**Issue by meteorfall** [tamlok/vnote#891]
OS Version (操作系统): Windows, 

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.1

Suggestion :
建议对excel表格的内容复制后，再粘贴时增加“以MD语法表格形式插入”，可以将excel数据表格自动转化成符合md语法的表格，也利于后续的直接编辑数据

**Comment by tamlok** [comment]
编辑器右键菜单：

![image](https://user-images.githubusercontent.com/5763157/60750135-a9acc280-9fd6-11e9-80e5-4b90d388f1b0.png)

**Comment by meteorfall** [comment]
原来如此～～～感谢大神！
原来直接用ctrl+V,看粘贴选项里面没有，还以为没这功能。大神原来早想到了～～～
