### ISSUE TITLE
Sort notebooks alphabetically

### ISSUE THREAD

**Issue by mkpaz** [tamlok/vnote#892]
Would you be so kind to implement this feature. For now notebooks sorted in order they were created.

Update:
Ahh, I've found. It can be changed in **session.ini** manually. But anyway..

**Comment by tamlok** [comment]
It is not intended to have too many notebooks in VNote, so there is no GUI way to sort notebooks. You could just order them in `session.ini` manually. Will add it in the future.

**Comment by tamlok** [comment]
VNote 2.8 now supports sorting notebooks in the context menu of the notebook selector list.
