### ISSUE TITLE
建议: 希望标题可以添加关联文件

### ISSUE THREAD

**Issue by plus-zhang** [tamlok/vnote#896]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.1

~~Symptoms (表现):~~

~~How to Repro (如何复现):~~

目前可以通过对标题或文字添加*目标文件的绝对路径*来链接, 不过一旦**目标文件移动**以后, 就需要再次关联, 不知是否可以添加一种更加先进方便文件链接方式, 无视文件的移动

**Comment by AdrianaWarlock** [comment]
onenote之类都是直接创建副本。这种方式很占空间。
可以添加相对路径.. 但是移动的话肯定找不到。
