### ISSUE TITLE
European bank account?

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#897]
I know the answer will probably be NO, but one never knows: do you have a European bank account number?

**Comment by tamlok** [comment]
No, there is only one Paypal account. Thank you for your kindness. Considering the service fee, I would not encourage you to donate too much! :) Just keep using VNote and spread words about it! :)

**Comment by DutchPete** [comment]
I don't like PayPal and don't use it. Thanks for your tip about the service fee.
As for spread the word, once again I mentioned VNote [here](https://www.ghacks.net/2019/07/10/zim-is-a-free-open-source-text-editor-with-wiki-like-features/) - see the very 1st comment in the thread ;-)
