### ISSUE TITLE
release目前地址无法下载

### ISSUE THREAD

**Issue by helloworldgnu** [tamlok/vnote#90]
相关版本下载，放到网盘上吧。由于众所周知的国内的原因，现在的下载链接，尝试下载很多次都无法下载

**Comment by tamlok** [comment]
Hi，首页放有百度云盘的下载地址，里面包含有最新稳定版，可以尝试一下。http://pan.baidu.com/s/1jI5HROq

谢谢支持！

**Comment by helloworldgnu** [comment]
嗯，亲测好用，比较了几款md工具，VNote是比较理想的。感谢奉献的优化作品。
