### ISSUE TITLE
希望能有搜索所有笔记的功能

### ISSUE THREAD

**Issue by lrxcmwy** [tamlok/vnote#906]
希望能够提供一个全局搜索的功能，因为我是有重度的写笔记需求，有的时候遇到问题，想从笔记里翻出答案需要花费很多额外的时间，因此希望能有这个功能，以达到能搜索所有笔记的效果，作者么么哒

**Comment by tamlok** [comment]
这种基本功能早就实现了。具体功能请参考官方文档。

- 编辑菜单里面有个高级查找功能;
- ctrl-e c 快捷键能打开全局搜索功能;
- 通用入口能提供全文搜索功能。

**Comment by lrxcmwy** [comment]
谢谢>,< 是我刚用不久，没有发现这个功能


在2019年7月19日 09:26，Le Tan<notifications@github.com> 写道：

这种基本功能早就实现了。具体功能请参考官方文档。

编辑菜单里面有个高级查找功能;
ctrl-e c 快捷键能打开全局搜索功能;
通用入口能提供全文搜索功能。
