### ISSUE TITLE
Texts are garbled in editing mode

### ISSUE THREAD

**Issue by mgoldchild** [tamlok/vnote#908]
I’m running Manjaro Gnome 3 on a Lenovo Thinkpad x1 carbon 6gen. All had been working fine until I updated my packages. But now I got text garbled in editiong mode.  In preview mode, texts are correctly rendered. Even if i changed my font which was installed in my PC, the behavior did not change. And i have already tried to re-install vnote from AUR (vnote-bin).

OS Version (操作系统): Manjaro Linux

more detail.

```
[mike@mike-pc ~/Apps/paper][18:33:15] (master)[H][X][I][%][λ]> inxi -Fxz
System:    Host: mike-pc Kernel: 4.19.59-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.1.0 Desktop: Gnome 3.32.2 
           Distro: Manjaro Linux 
Machine:   Type: Laptop System: LENOVO product: 20KHCTO1WW v: ThinkPad X1 Carbon 6th serial: <filter> 
           Mobo: LENOVO model: 20KHCTO1WW v: SDK0J40709 WIN serial: <filter> UEFI: LENOVO v: N23ET59W (1.34 ) 
           date: 11/08/2018 
Battery:   ID-1: BAT0 charge: 49.4 Wh condition: 55.9/57.0 Wh (98%) model: LGC 01AV494 status: Discharging 
CPU:       Topology: Quad Core model: Intel Core i5-8350U bits: 64 type: MT MCP arch: Kaby Lake rev: A 
           L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 30344 
           Speed: 800 I’d appreciate any suggestions on how to un-garble the text so I could read the error message or any other suggestions for getting my application to work well.
MHz min/max: 400/3600 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 5: 800 6: 800 
           7: 800 8: 800 
Graphics:  Device-1: Intel UHD Graphics 620 vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0 
           Display: x11 server: X.org 1.20.5 driver: i915 resolution: <xdpyinfo missing> 
           OpenGL: renderer: Mesa DRI Intel UHD Graphics 620 (Kabylake GT2) v: 4.5 Mesa 19.1.2 
           direct render: Yes 
Audio:     Device-1: Intel Sunrise Point-LP HD Audio vendor: Lenovo driver: snd_hda_intel v: kernel 
           bus ID: 00:1f.3 
           Sound Server: ALSA v: k4.19.59-1-MANJARO 
Network:   Device-1: Intel Ethernet I219-LM vendor: Lenovo driver: e1000e v: 3.2.6-k port: efa0 bus ID: 00:1f.6 
           IF: enp0s31f6 state: down mac: <filter> 
           Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi v: kernel port: efa0 bus ID: 02:00.0 
           IF: wlp2s0 state: up mac: <filter> 
Drives:    Local Storage: total: 476.94 GiB used: 80.44 GiB (16.9%) 
           ID-1: /dev/nvme0n1 model: LENSE30512GMSP34MEAT3TA size: 476.94 GiB 
Partition: ID-1: / size: 468.16 GiB used: 80.44 GiB (17.2%) fs: ext4 dev: /dev/nvme0n1p2 
Sensors:   System Temperatures: cpu: 41.5 C mobo: N/A 
           Fan Speeds (RPM): cpu: 0 
Info:      Processes: 308 Uptime: 7h 15m Memory: 15.42 GiB used: 2.90 GiB (18.8%) Init: systemd Compilers: 
           gcc: 9.1.0 Shell: zsh v: 5.7.1 inxi: 3.0.34 
```

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.1

Symptoms (表现):Text garbled in editing mode.

How to Repro (如何复现):
This Japanese letter (`ぐ`) does not-rendered in editing mode. 
I think it can reproduce on Manjaro Gnome 3 latest.

![Screenshot from 2019-07-23 18-44-12](https://user-images.githubusercontent.com/8959761/61712738-f4c62400-ad91-11e9-80a0-7bc845edcf49.png)

**Comment by tamlok** [comment]
Hi,

I think it is caused by the font used by editor.

Try specifying a font which could display Japanese correctly via the Settings:

![image](https://user-images.githubusercontent.com/5763157/61713221-9e091c00-ad8a-11e9-8d83-6d12db4a00b0.png)

Or you could modify the `*.mdhl` file of your chosen theme in configuration folder. More details could be found [here](https://tamlok.github.io/vnote/en_us/#!docs/Users/Themes%20and%20Styles.md).

**Comment by mgoldchild** [comment]
@tamlok Thank you for your advice. I just now tried to enable custom font in settings and applied Japanese font. However it was not working well on my environment (still letters look like a tofu LOL). So I'll find another workaround coz this problem is not only Vnote but also I got this kind of similar problem on some few another applications like Google Chrome, Goldendict. Thank you as always!

**Comment by mgoldchild** [comment]
@tamlok I fully fixed this problem by updating my system font to `noto-fonts-cjk (Noto Sans CJK JP Regular)` by using Gnome Tweak. Not only Vnote but also Chrorm and Goldendict are fixed. This problem was caused by recent patch of Noto font according to the site. Thank you very much. :bowing_man: 

FYI: https://forum.manjaro.org/t/manjaro-settings-managers-chinese-text-cant-display-normally/95967
