### ISSUE TITLE
编辑修改的时候  页面是空白的

### ISSUE THREAD

**Issue by StevenSun121** [tamlok/vnote#91]
![demo](https://user-images.githubusercontent.com/15046999/34659095-e3971432-f46f-11e7-8c43-f69f50d4fd3c.gif)

**Comment by tamlok** [comment]
hi，请问具体是什么情况？VNote是没有两边实时预览的哦。

**Comment by StevenSun121** [comment]
![image](https://user-images.githubusercontent.com/15046999/34659155-91a6eb06-f470-11e7-84b0-52811bea28c1.png)
@tamlok

**Comment by tamlok** [comment]
谢谢反馈！目前还是第一次看到这种情况。是每个笔记都这样子吗？重启VNote也还是有这个问题？

建议尝试更新一下操作系统或者显卡驱动试试。如果问题还是存在，方便的话，可以在出现这个问题的时候在文件菜单里打开VNote的配置文件夹，然后把vnote.log发到我的邮箱tamlokveer@gmail.com。

谢谢！

**Comment by StevenSun121** [comment]
我是今天第一次下载并开始使用的 , 新建的markdown文件编辑没有问题 , 保存后再次编辑就出现显示不正常的问题了 , 尝试过重启VNote , 没有效果
至于您说的操作系统和显卡驱动的问题 , 我稍后试一下
配置文件我先把目前的文件发您 , 清空后 , 再操作一次 再发您

**Comment by tamlok** [comment]
Hi,

貌似找到解决办法了，应该是opengl的毛病。试试加一个系统环境变量QT_OPENGL，值为angle

如果angle不行，再试试software

每次设置完环境变量后，记得重启vnote。

谢谢！
