### ISSUE TITLE
对Markdown中图片进行缩放后，使用pandoc导出docx时没有图片

### ISSUE THREAD

**Issue by marryton007** [tamlok/vnote#916]
OS Version (操作系统): Windows, Linux, macOS
Windows 10 家庭版
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.7.1
Symptoms (表现):
在markdown中插入图片时，进行缩放，使用pandoc导出成docx格式时没有图片

pandoc 命令：
pandoc  -o "%1" "%0"

![image](https://user-images.githubusercontent.com/2311328/62337227-66c30980-b506-11e9-86f3-e84542151a43.png)

错误信息：
>>> 导出到 D:/Documents/vnote_exports 。
>>> 正在导出笔记 D:/Documents/vnote_notebooks/vnotebook/mfc/mfc.md 。
>>> pandoc  -o "D:\Documents\vnote_exports\mfc_001.docx" "D:\Documents\vnote_notebooks\vnotebook\mfc\mfc.md"
>>> [WARNING] Could not fetch resource '_v_images/20190801184444965_11984.jpg%20=432x': PandocResourceNotFound "_v_images/20190801184444965_11984.jpg =432x"
[WARNING] Could not fetch resource '_v_images/20190801183848444_11215.png%20=780x': PandocResourceNotFound "_v_images/20190801183848444_11215.png =780x"
[WARNING] Could not fetch resource '_v_images/20190801183903659_7703.png%20=780x': PandocResourceNotFound "_v_images/20190801183903659_7703.png =780x"

>>> 笔记 D:/Documents/vnote_notebooks/vnotebook/mfc/mfc.md 导出为 D:/Documents/vnote_exports/mfc_001.docx 。
>>> 导出了 1 个笔记。

How to Repro (如何复现):

**Comment by marryton007** [comment]
找了个临时解决办法：
先导出成Html格式， 再用pandoc转成docx格式，这样可行。其中有个小问题，插入的图片必须是png格式才可显示，jpg格式的图片在docx文件中没有显示出来。

**Comment by tamlok** [comment]
源格式那里选择html即可，图片缩放语法可能pandoc不支持，所以得由vnote转。

**Comment by marryton007** [comment]
thanks tamlok, 源格式设为html后，还是出现了问题

![image](https://user-images.githubusercontent.com/2311328/62442761-7a32d680-b78b-11e9-80ef-c2a867b53446.png)

>>> 导出到 D:/Documents/vnote_exports 。
>>> 正在导出笔记 D:/Documents/vnote_notebooks/vnotebook/mfc/mfc.md 。
>>> pandoc --resource-path=.:"Z:/TEMP/VNote-wvf4kH" --css="file:\\\C:\Users\marryton007\AppData\Roaming\vnote\themes\v_pure\v_pure.css" --css="file:\\\C:\Users\marryton007\AppData\Roaming\vnote\themes\v_pure\v_pure_codeblock.css" -s -o "D:\Documents\vnote_exports\mfc.docx" "Z:\TEMP\VNote-wvf4kH\vnote_tmp.html"
>>> [WARNING] Could not fetch resource './vnote_tmp_files/20190802092739729_22504.png': PandocResourceNotFound "./vnote_tmp_files/20190802092739729_22504.png"
[WARNING] Could not fetch resource './vnote_tmp_files/20190802105318030_13078.png': PandocResourceNotFound "./vnote_tmp_files/20190802105318030_13078.png"
[WARNING] Could not fetch resource './vnote_tmp_files/20190802105334531_29287.png': PandocResourceNotFound "./vnote_tmp_files/20190802105334531_29287.png"
[WARNING] Could not fetch resource './vnote_tmp_files/20190804100242147_13325.png': PandocResourceNotFound "./vnote_tmp_files/20190804100242147_13325.png"
[WARNING] Could not fetch resource './vnote_tmp_files/20190804100335845_22770.png': PandocResourceNotFound "./vnote_tmp_files/20190804100335845_22770.png"
[WARNING] Could not fetch resource './vnote_tmp_files/20190801183848444_11215.png': PandocResourceNotFound "./vnote_tmp_files/20190801183848444_11215.png"
[WARNING] Could not fetch resource './vnote_tmp_files/20190801183903659_7703.png': PandocResourceNotFound "./vnote_tmp_files/20190801183903659_7703.png"

>>> 笔记 D:/Documents/vnote_notebooks/vnotebook/mfc/mfc.md 导出为 D:/Documents/vnote_exports/mfc.docx 。
>>> 导出了 1 个笔记。

**Comment by tamlok** [comment]
From Pandoc's [doc](https://pandoc.org/MANUAL.html):

> --resource-path=SEARCHPATH
List of paths to search for images and other resources. The paths should be separated by : on Linux, UNIX, and macOS systems, and by ; on Windows. If --resource-path is not specified, the default resource path is the working directory. Note that, if --resource-path is specified, the working directory must be explicitly listed or it will not be searched. For example: --resource-path=.:test will search the working directory and the test subdirectory, in that order.

So you need to change the command to:

```
pandoc --resource-path=.;"%3" --css="%2" --css="%4" -s -o "%1" "%0"
```

**Comment by marryton007** [comment]
thanks tamlok, it works now.  I think this issue could be closed.  thanks again.
