### ISSUE TITLE
Markdown-It 方式下多个标记语法的渲染无法实现

### ISSUE THREAD

**Issue by aybthebest** [tamlok/vnote#918]
OS Version (操作系统):  macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7

Symptoms (表现):
主要包括下划线，++++，====，：，Typographic等

How to Repro (如何复现):
md-id给的Demo：https://markdown-it.github.io

**Comment by tamlok** [comment]
这些是通过插件实现的扩展语法吧？目前暂时还不支持自定义加载md-it插件，后面会支持。

**Comment by aybthebest** [comment]
明白了，这些功能确实是通过插件实现的。谢谢回复！
