### ISSUE TITLE
[需求]在 “通用入口”和“搜索窗口” 中搜索笔记里的关键词后可以点击跳转到关键词所在行

### ISSUE THREAD

**Issue by 7Harold-Zhang** [tamlok/vnote#919]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): v2.7.1 c152c46

Symptoms (表现):
在 “通用入口”和“搜索窗口” 中搜索到关键词后只能跳转到第一个关键词的位置，可否添加一个点击跳转到指定行的功能，现在搜索完了只能跳转到第一个关键词。
比如下面的搜索结果，可以双击跳转到那一行并高亮显示的功能。

![图片](https://user-images.githubusercontent.com/51531094/62369536-80923a00-b562-11e9-9618-756b1a4a0d92.png)
可以这样会方便一些，当然现在用“查找和替换”来将就一下也可以。

另外：Vnote真的很不错，基本满足了我的所有要求，十分感谢。

**Comment by tamlok** [comment]
这个细节还没有时间实现，后面会完善。目前，你可以在设置杂项里面把搜索后高亮匹配项目勾选（这样在通用模式中会以编辑模式打开结果），这时候会高亮第一个匹配项，然后按`ctrl+8`和`ctrl+9`可以跳转前后一个匹配项！

**Comment by 7Harold-Zhang** [comment]
> 
> 
> 这个细节还没有时间实现，后面会完善。目前，你可以在设置杂项里面把搜索后高亮匹配项目勾选（这样在通用模式中会以编辑模式打开结果），这时候会高亮第一个匹配项，然后按`ctrl+8`和`ctrl+9`可以跳转前后一个匹配项！

谢谢，在结果较少的情况下这样也可以。我需要关掉这个issues吗？
