### ISSUE TITLE
如何自定义模板

### ISSUE THREAD

**Issue by gk4030** [tamlok/vnote#92]
如何自定义模板，以模板创建笔记

**Comment by tamlok** [comment]
Hi，新建笔记的时候，在选择模板那一行末尾有一个文件夹图标，点击后打开模板文件夹，把对应的md文件扔进里面就可以了。

谢谢！

**Comment by DerekTso** [comment]
自定义模板里面设置如下

`%d%%MMM% %yyyy%`

可是它显示出来的是

> 13四月 2018

如何只显示英语格式的, 而不跟locale呢? 比如

> 13Apr 2018

**Comment by tamlok** [comment]
@DerekTso Hi, 这个是根据系统的locale来显示的，所以如果是中文的locale，那就是中文的语言习惯了。可以考虑使用纯数字或把系统的语言换成中文。

**Comment by tamlok** [comment]
@DerekTso 之前这方面没怎么留意，我后面看看能不能根据语言来显示。谢谢！
