### ISSUE TITLE
【bug report】导出为PDF时代码块上方出现复制按钮（v2.7.2)

### ISSUE THREAD

**Issue by Creling** [tamlok/vnote#920]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

Symptoms (表现):

![image](https://user-images.githubusercontent.com/43109504/62369575-a0c1f900-b562-11e9-9b00-4c478f20a6d6.png)

How to Repro (如何复现):
以默认配置导出为pdf即可复现

![image](https://user-images.githubusercontent.com/43109504/62369774-4d9c7600-b563-11e9-8cdd-e9e5d6e2c600.png)

**Comment by tamlok** [comment]
Hi,

文件菜单，打开配置文件夹，把resources文件夹删除，然后重启VNote，应该就可以了。这个是css样式没有更新导致的。

**Comment by Creling** [comment]
解决

感谢您的帮助
