### ISSUE TITLE
模板的使用

### ISSUE THREAD

**Issue by menghuu** [tamlok/vnote#922]
OS Version (操作系统): `macOS`

VNote Version (Help - About VNote - Version: )(VNote版本): `2.7.1`

Symptoms (表现):
模板怎么使用, 文档中关于这个的太少了, 有哪些 magic word?

还有%no%为啥是标题.. 不应该是%title%吗,或者%name%, %no%是什么的缩写?

How to Repro (如何复现):

无

**Comment by tamlok** [comment]
新建笔记的时候可以选择模板，在模板选择框右侧有个文件夹图标，点击就能打开模板文件夹，把你的md模板文件放在这里，vnote就能识别模板。

新建笔记的时候，输入%help%即显示所有幻词。

以上信息都可以在官方文档中找到详细说明和例子:

https://tamlok.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E5%B9%BB%E8%AF%8D.md

https://tamlok.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E6%A8%A1%E6%9D%BF.md

**Comment by menghuu** [comment]
额, 之前只看到了第一个链接,第二个没看到
