### ISSUE TITLE
不能显示笔记内容

### ISSUE THREAD

**Issue by bryceyang** [tamlok/vnote#934]
OS Version (操作系统): Windows, Linux, macOS
macOS
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
VNote-2.7.2-x64.dmg
Symptoms (表现):
不能显示笔记内容。具体表现：
1. 可以看到md文件列表，点击之后能够在右下部底栏看到所在行数，百分比等信息；但是就是毫无内容显示，跟默认打开界面一模一样；
2. 右键md文件以编辑模式打开，只能看到右下部底栏文件信息变动，UI其他位置无任何变化。
<img width="1680" alt="Screenshot 2019-08-16 17 31 28" src="https://user-images.githubusercontent.com/9302617/63158407-c31c4200-c04b-11e9-8c93-7f4c3132b1f6.png">

How to Repro (如何复现):
直接下载最新release安装就是这样。

**Comment by tamlok** [comment]
我这边复现不了，您可以试一下重启系统。也可以打开一个笔记后在帮助菜单查看log，看看有什么错误信息。

2.7正常吗？

**Comment by bryceyang** [comment]
将所有相关文件删除之后重新安装问题解决。可能是我很久以前安装过一次vnote残余的配置文件影响了此次安装。
一个软件如果你费了劲儿没有用上，反而会想方法用上，真有意思。

**Comment by tamlok** [comment]
哦哦，现在才看到你的图片，这个是因为编辑区域被缩小到0宽度了，拖拉一下或者重置布局即可。之前有一个版本的升级改动了界面，会导致这个问题。
