### ISSUE TITLE
正文字体太小

### ISSUE THREAD

**Issue by bryceyang** [tamlok/vnote#938]
OS Version (操作系统): Windows, Linux, macOS
macOS 10.14.6
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
v 2.7.2
Symptoms (表现):
**表现**： 在mbp15上，正文字体过小，每次都需要按cmd+ 放大才行，每次手动放大之后，新建笔记字体仍然是默认最小的状态。
**希望**：请问有没有设置项可以记住我放大的比例，然后自动运用到所有的新建笔记上。
或者本身设置里有没有能调默认正文大小的地方，我只看到了有调节字体的选项。

How to Repro (如何复现):

**Comment by tamlok** [comment]
设置-阅读/编辑-自定义缩放
