### ISSUE TITLE
Read mode ignores themes

### ISSUE THREAD

**Issue by netcrns** [tamlok/vnote#939]
OS Version:
Windows 10

VNote Version:
2.7.2

Symptoms:
Read mode ignores themes, making the read-area appear with a bright background.
Everything works as expected in edit mode.

How to Repro:
1. Change to a dark theme (e.g. v_detorte & v_moonlight).
2. Create a note and open it in read mode. Toggle between the modes with ctrl+t to really make your eyes burn during a late night.

**Comment by tamlok** [comment]
Besides the default CSS style of a theme, VNote allows user to specify another CSS style separately. Check if it is in this case:

![image](https://user-images.githubusercontent.com/5763157/63402145-c5e0b380-c40c-11e9-9625-3968a0f5e25c.png)

If it is not, try reset VNote like this:

1. Open configuration folder in `File` menu;
2. Delete folder `themes`;
3. In the `Settings` dialog, click the `Reset Layout` button;
4. Click `Restart` in the `File` menu and check if it works now.

**Comment by netcrns** [comment]
Your steps unfortunately did not fix my issue. I appreciate your help nonetheless!
It seems I was just too bloody tired (and maybe a tad too drunk) to see this drop-down menu:
![VNote_2019-08-21_13-56-46](https://user-images.githubusercontent.com/34162313/63430018-e106ef80-c41b-11e9-8c95-96f747b853af.png)
After selecting "System" from that menu and restarting Vnote, I got what I'd hoped for.
I apologise for my premature action of posting this issue. I should've figured this out myself.

**Comment by tamlok** [comment]
You tried the wrong menu! rendering style, not rendering background.
