### ISSUE TITLE
windows10下行号像素被截断部分

### ISSUE THREAD

**Issue by MaiTestarossa** [tamlok/vnote#94]
![image](https://user-images.githubusercontent.com/20226906/34823260-b39a5d56-f704-11e7-961c-533d771f8e97.png)

如图，下方左边是激活行的效果，目测被截断了1行像素，下方右边是非激活状态，被截断了更多。

windows10系统，同时装过很多中日字体，想不到更多其他有效信息了。

**Comment by tamlok** [comment]
谢谢反馈！想不到居然还有出现这样的效果！我看一下代码，看怎么能避免。

再次感谢详细的评测和反馈！希望继续关注VNote的进步！

**Comment by tamlok** [comment]
Hi，应该已经修复了(45526cc0a822fd9c9c557337c3a0aa3741e8f01c)。

可以[这里](https://ci.appveyor.com/api/buildjobs/o95nbbcrreuxedpg/artifacts/build%2Fdistrib%2FVNote_win_X64.exe)下载最新构建版本，重命名后直接覆盖EXE。

谢谢反馈和建议！
