### ISSUE TITLE
请问如何取消阅读模式下代码框左上角的复制按钮

### ISSUE THREAD

**Issue by pysense** [tamlok/vnote#944]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.1

Symptoms (表现):
阅读模式下代码块左上角默认添加了复制按钮，因为我在导出为 html 后封装到为 chm 格式，貌似 chm 不支持执行 javascript，并且平时也用不上这个功能，考虑取消掉。

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

参考以下两个issue，可以添加选项将其禁用：

https://github.com/tamlok/vnote/issues/920

https://github.com/tamlok/vnote/issues/867

**Comment by pysense** [comment]
感谢，解决了。

先删除 resources 目录后，修改 vnote.ini 文件再启动 VNote 即可。

```
[web]
enable_code_block_copy_button=false
```
