### ISSUE TITLE
图片插入可以加入gif支持

### ISSUE THREAD

**Issue by ArchyXiao** [tamlok/vnote#946]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
整理算法笔记经常用到动图，用于展现数据结构变化过程，希望尽快考虑支持gif展示~

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi，

阅读模式是支持Gif的吧？目前编辑模式还不支持。

**Comment by tamlok** [comment]
希望能在issue中详细说明一下问题。不然我也爱莫能助，还浪费大家的时间。

**Comment by ArchyXiao** [comment]
哦哦，阅读模式是可以正常展示gif的，已经够用了
