### ISSUE TITLE
Question about Unicode

### ISSUE THREAD

**Issue by DutchPete** [tamlok/vnote#948]
OS Version (操作系统): Linux Mint 19.2 XFCE

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

Symptoms (表现): VNote does not seem to support Unicode, is that correct? If not, is there a way to activate it?

How to Repro (如何复现):

**Comment by tamlok** [comment]
How do you tell whether VNote supports Unicode or not? What is your scenario and the unexpected behavior of VNote?

Thanks!

**Comment by DutchPete** [comment]
Funny you ask the question: you should know if VNote supports Unicode, should you not?
Anyway, if e.g. I type <kbd>CTRL</kbd> + <kbd>U</kbd> + 2714, then <kbd>Enter</kbd>, I would expect there to appear a tick/check mark, but nothing happens. Therefore my conclusion is that VNote does not support Unicode. Or maybe it only supports certain characters only.

Either way, can you tell me what the status is?

**Comment by tamlok** [comment]
`Ctrl+U 2714`, I think, is just one input method provided by a specific editor.

VNote does not provide such way to input Unicode, but it does support displaying Unicode. You could simply copy Unicode emoji into VNote.

**Comment by DutchPete** [comment]
What do you mean by:

> You could simply copy Unicode emoji into VNote.

If I insert `:smile:`, VNote will not display a smile emoji.
There are 2 unicodes for a smiling face: U+263A and U+FE0F.
The U refers to the combination <kbd>CTRL</kbd>+<kbd>U</kbd>, but in VNote that combination does not work. And just copy/pasting e.g. U+263A does not render a smiley.
So, how does it work in VNote? Please show me with an example.

**Comment by tamlok** [comment]
1. Just copy and paste like this: 😋🤗
2. Enable the emoji plugin of markdown-it in the markdown menu, and you could insert `:smile:` and it will be rendered as a smile face in read mode. Check out [this](https://github.com/markdown-it/markdown-it-emoji/blob/master/dist/markdown-it-emoji.js).

**Comment by DutchPete** [comment]
AH, OK, the emoji plugin is what I need. Thanks, it works fine.
Is there a way to have the emojis rendered in color?

**Comment by tamlok** [comment]
It is a matter of font you choose in editor.

**Comment by DutchPete** [comment]
I understand. I have not seen a place where I can choose the font, or is that choice done by you, baked into the code and unchangeable?

**Comment by tamlok** [comment]
Why not take a look at the Settings dialog or search the docs? :)

**Comment by DutchPete** [comment]
I apologise, I had not noticed it in the Settings, mea culpa.
I set the font to Noto Color Emoji, which is *the* font for color emojis - I have only ever seen this one mentioned on the internet for color emojis- but unfortunately VNote still does not render emojis in color. I looked through the Documentation, specifically the section on Themes and Styles, and although customisability is impressive (kudos for that !), I still did not see a way to get the emojis to be turned to color.

Anyhow, maybe I am asking too much, or my questions are too basic - I admit I should have picked up the setting in the Settings dialogue - so I won't bug you any longer with this.

**Comment by DutchPete** [comment]
Last question on this subject: is there a chance that eventually one will be able to type Unicode in VNote, ie. <kbd>CTRL</kbd>+<kbd>U</kbd>+`code`, or will it always have to be copy/pasted?

**Comment by tamlok** [comment]
I do not know how to display it in color, either. Just don't mind this small issue.

Will consider supporting inputting Unicode in VNoteX.

**Comment by DutchPete** [comment]
OK, thank you @tamlok.
