### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by IIInsomnia** [tamlok/vnote#95]
* 加入表格插入，类似 `Typora`
* 更改字体等
* 采用 electron

**Comment by tamlok** [comment]
Hi,

- 目前VNote对表格编辑还没有任何优化。后面会参考各种编辑器，专门进行优化。
- 字体是支持自定义的，需要在样式文件里面指定。目前自定义主题或样式有点麻烦，下一个版本会添加一些对应的功能来方便用户更改。VNote是高度可定制的，不过由于时间关系，所以很多配置都没有通过GUI界面暴露给用户，但是可以通过修改配置文件来进行自定义。
- Qt相对于Electron有99%的优势！C++的速度是Electron等使用JS脚本语言无法赶上的。您可以尝试一下在CMD Markdown等编辑器里面切换多个文件，和在VNote里面切换多个文件，速度不是一个级别上的。所以，Electron除了颜值高之外，对于Qt基本没啥优势。不过，最重要的原因还是，更改技术方案成本太高了，也不太现实。 :)

谢谢关注！

**Comment by amitbha** [comment]
支持QT

**Comment by helloworldgnu** [comment]
支持QT
