### ISSUE TITLE
能预览带`\`路径的图片,阅读模式却没用

### ISSUE THREAD

**Issue by trdmm** [tamlok/vnote#953]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

Symptoms (表现):

我的Typora插入的图片路径是`\`,VNote是`/`,这没问题
但是在编辑模式下图片能预览带`\`路径的图片,阅读模式却没用

另外,设置里面的笔记管理下
![批注 2019-08-30 003534.jpg](https://i.loli.net/2019/08/30/Y6UrqKZJgHapl3u.jpg)
这个外部文件的自定义图片文件夹是干嘛的?

**Comment by tamlok** [comment]
hi，

- 下次提这种问题的时候，最好能把文本贴一下，不然只能靠猜;
- 要我猜的话，应该是路径里面有空格，url规定空格需要用`20%`替代;
- 其实复制图片然后直接在编辑器里面粘贴(ctrlv)即可，vnote会帮你处理所有事情;
- vnote除了作为笔记软件，也可以作为一个编辑器编辑非笔记本内的其他md文件，称为外部文件;这里是定义编辑外部文件时，图片放哪里。

**Comment by trdmm** [comment]
> hi，
> 
> * 下次提这种问题的时候，最好能把文本贴一下，不然只能靠猜;
> * 要我猜的话，应该是路径里面有空格，url规定空格需要用`20%`替代;
> * 其实复制图片然后直接在编辑器里面粘贴(ctrlv)即可，vnote会帮你处理所有事情;
> * vnote除了作为笔记软件，也可以作为一个编辑器编辑非笔记本内的其他md文件，称为外部文件;这里是定义编辑外部文件时，图片放哪里。

这是预览模式,正反斜杠都可以
![1.jpg](https://i.loli.net/2019/08/30/SHgtu36jeIMycOW.jpg)
阅读模式的话`\`就不显示了.
![2.jpg](https://i.loli.net/2019/08/30/MYvKrG7VD5ulPmf.jpg)
编辑模式可以的话,阅读模式应该也可以的吧 :D
> 不过不影响使用,嘻嘻

**Comment by trdmm** [comment]
> hi，
> 
> * 下次提这种问题的时候，最好能把文本贴一下，不然只能靠猜;
> * 要我猜的话，应该是路径里面有空格，url规定空格需要用`20%`替代;
> * 其实复制图片然后直接在编辑器里面粘贴(ctrlv)即可，vnote会帮你处理所有事情;
> * vnote除了作为笔记软件，也可以作为一个编辑器编辑非笔记本内的其他md文件，称为外部文件;这里是定义编辑外部文件时，图片放哪里。

这是预览模式,正反斜杠都可以
![1.jpg](https://i.loli.net/2019/08/30/SHgtu36jeIMycOW.jpg)
阅读模式的话`\`就不显示了.
![2.jpg](https://i.loli.net/2019/08/30/MYvKrG7VD5ulPmf.jpg)
编辑模式可以的话,阅读模式应该也可以的吧 :D
> 不过不影响使用,嘻嘻

**Comment by tamlok** [comment]
URL还是应该使用`/`的，编辑模式和阅读模式一般会尽量一致。
