### ISSUE TITLE
macos无法打开vnote，系统版本10.13.6

### ISSUE THREAD

**Issue by daniellauyu** [tamlok/vnote#956]
OS Version (操作系统):  macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):brew cask install vnote
Updating Homebrew...
^C
==> Satisfying dependencies
==> Downloading https://github.com/tamlok/vnote/releases/download/v2.7.2/VNote-2.7.2-x64.dmg
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/70038437/c681cc
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'vnote'.
==> Installing Cask vnote
==> Moving App 'VNote.app' to '/Applications/VNote.app'.
🍺  vnote was successfully installed!
brew安装成功，打不开；
通过release下载macos版本也打不开。

How to Repro (如何复现):

**Comment by tamlok** [comment]
重启一下操作系统再试试？

**Comment by daniellauyu** [comment]
😂重启系统好了，大佬回复好快，感谢
