### ISSUE TITLE
快捷键帮助及自定义快捷键的“默认的配置可能是这样子的：”内容不一致

### ISSUE THREAD

**Issue by erwim** [tamlok/vnote#958]
OS Version (操作系统): Windows10
VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2
Symptoms (表现):
快捷键帮助及自定义快捷键的“默认的配置可能是这样子的：”内容不一致，最明显就是EditNote=Ctrl+W，这条。
How to Repro (如何复现):
如上所示。

小疑问：是否根目录复制vnote.ini就可以同步设置了？因为感觉每次复制过去，vnote启动后又会新建出好几个目录。因为习惯vscode、sublime之类的插件，可以git同步设置等。

目前vnote我个人的用法是整理笔记，比onenote之类的方便，但是复杂的表格、富文本还是onenote。对于markdown初学者，个人认为vnote展现的方式比typora、vscode友好，至少让人知道markdown如何一步步实现。

**Comment by tamlok** [comment]
Hi,

因为代码总是在更新，所以文档可能延迟，这里只是给出一个例子，所以说是`可能`。最新的可以参考这里： https://github.com/tamlok/vnote/blob/master/src/resources/vnote.ini  后面会更新一下。

一般同步`vnote.ini`就可以了，自动生成的目录都是EXE里面释放出来的。

**Comment by erwim** [comment]
> 
> 
> Hi,
> 
> 因为代码总是在更新，所以文档可能延迟，这里只是给出一个例子，所以说是`可能`。最新的可以参考这里： https://github.com/tamlok/vnote/blob/master/src/resources/vnote.ini 后面会更新一下。
> 
> 一般同步`vnote.ini`就可以了，自动生成的目录都是EXE里面释放出来的。

片段什么还是另外文件夹，建议能否今后版本或者2.0以后，有设置导出、备份。

%help%，列表只会出现0.3秒不到，新建笔记或者片段。
