### ISSUE TITLE
Linux上无法输入中文

### ISSUE THREAD

**Issue by trzhong** [tamlok/vnote#962]
OS Version (操作系统): Linux Mint 19.2 xfce

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2 AppImage

Symptoms (表现):

无论是对话框还是编辑窗口，Ctrl+Space/Ctrl+Shift/Shift均无法切换为中文输入法（我使用的是Fcitx中州韵），切换到其他应用（例如Terminal切换正常），因此无法输入中文。中文显示是正常的，粘贴中文到编辑窗口是正常的，预览也是正常的。

此外，明明在设置中取消了系统托盘，但是系统托盘中仍然看到VNote图标并可以操作。

How to Repro (如何复现):

按上面操作应该可以重现吧。。。

**Comment by tamlok** [comment]
Hi,

是官网下载的AppImage吗？`fcitx-diagnose`显示qt5的支持正常吗？这个应该是fcitx和qt的恩怨，和vnote无关。

https://github.com/tamlok/vnote/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+fcitx

设置里面的系统托盘是指关闭VNote后是否驻留在系统托盘，VNote总是会在系统托盘有个小图标。鼠标停留在选项上面，应该有详细的解释。

谢谢！

**Comment by trzhong** [comment]
> Hi,
> 
> 是官网下载的AppImage吗？`fcitx-diagnose`显示qt5的支持正常吗？这个应该是fcitx和qt的恩怨，和vnote无关。
> 
> https://github.com/tamlok/vnote/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+fcitx
> 
> 设置里面的系统托盘是指关闭VNote后是否驻留在系统托盘，VNote总是会在系统托盘有个小图标。鼠标停留在选项上面，应该有详细的解释。
> 
> 谢谢！

嗯，是在官网下载的。哦，如果是指关闭之后是否驻留那就没有问题了。输入法我再看看qt5是啥回事吧。

**Comment by trzhong** [comment]
原来系统带的是qt4，所以装了qt5、fcitx-fontend-qt5，现在终于可以输入中文了。
