### ISSUE TITLE
绘制sequence功能失效

### ISSUE THREAD

**Issue by joechenrh** [tamlok/vnote#969]
OS Version (操作系统): Windows,

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2
Symptoms (表现):

绘制sequence功能无法使用

How to Repro (如何复现):

![image](https://user-images.githubusercontent.com/18008525/64859776-b9432a00-d65d-11e9-9902-94fd71f10c27.png)

![image](https://user-images.githubusercontent.com/18008525/64859804-d677f880-d65d-11e9-8705-e310c5283d80.png)

**Comment by tamlok** [comment]
puml需要配置，在设置对话框里面。

**Comment by joechenrh** [comment]
谢谢！找到了，看了下 `mermaid` 的文档，其实也有对应功能。
