### ISSUE TITLE
Graphviz mac下配置问题

### ISSUE THREAD

**Issue by zldark** [tamlok/vnote#973]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
输入Graphviz路径后，测试不成功。
![image](https://user-images.githubusercontent.com/31798535/65036474-16045480-d97e-11e9-9fb5-5e11719b0c33.png)
![image](https://user-images.githubusercontent.com/31798535/65036488-1f8dbc80-d97e-11e9-90de-476f0a91543b.png)
这个我应该怎么处理呢？
路径我填的是：/usr/local/Cellar/graphviz/2.40.1/bin/dot
How to Repro (如何复现):

**Comment by zldark** [comment]
Command: /usr/local/Cellar/graphviz/2.40.1/bin/dot -Tsvg
ExitCode: 0
Output: <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">


<svg width="106pt" height="116pt"
 viewBox="0.00 0.00 105.83 116.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 112)">
<title>G</title>
<polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-112 101.8271,-112 101.8271,4 -4,4"/>

<g id="node1" class="node">
<title>VNote</title>
<ellipse fill="none" stroke="#000000" cx="48.9136" cy="-90" rx="33.8683" ry="18"/>
<text text-anchor="middle" x="48.9136" y="-85.8" font-family="Times,serif" font-size="14.00" fill="#000000">VNote</text>
</g>

<g id="node2" class="node">
<title>Markdown</title>
<ellipse fill="none" stroke="#000000" cx="48.9136" cy="-18" rx="48.8273" ry="18"/>
<text text-anchor="middle" x="48.9136" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Markdown</text>
</g>

<g id="edge1" class="edge">
<title>VNote&#45;&gt;Markdown</title>
<path fill="none" stroke="#000000" d="M48.9136,-71.8314C48.9136,-64.131 48.9136,-54.9743 48.9136,-46.4166"/>
<polygon fill="#000000" stroke="#000000" points="52.4137,-46.4132 48.9136,-36.4133 45.4137,-46.4133 52.4137,-46.4132"/>
</g>
</g>
</svg>

Error:

**Comment by zldark** [comment]
```

Command: /usr/local/Cellar/graphviz/2.40.1/bin/dot -Tsvg
ExitCode: 0
Output: <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.40.1 (20161225.0304)
 -->
<!-- Title: G Pages: 1 -->
<svg width="106pt" height="116pt"
 viewBox="0.00 0.00 105.83 116.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 112)">
<title>G</title>
<polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-112 101.8271,-112 101.8271,4 -4,4"/>
<!-- VNote -->
<g id="node1" class="node">
<title>VNote</title>
<ellipse fill="none" stroke="#000000" cx="48.9136" cy="-90" rx="33.8683" ry="18"/>
<text text-anchor="middle" x="48.9136" y="-85.8" font-family="Times,serif" font-size="14.00" fill="#000000">VNote</text>
</g>
<!-- Markdown -->
<g id="node2" class="node">
<title>Markdown</title>
<ellipse fill="none" stroke="#000000" cx="48.9136" cy="-18" rx="48.8273" ry="18"/>
<text text-anchor="middle" x="48.9136" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Markdown</text>
</g>
<!-- VNote&#45;&gt;Markdown -->
<g id="edge1" class="edge">
<title>VNote&#45;&gt;Markdown</title>
<path fill="none" stroke="#000000" d="M48.9136,-71.8314C48.9136,-64.131 48.9136,-54.9743 48.9136,-46.4166"/>
<polygon fill="#000000" stroke="#000000" points="52.4137,-46.4132 48.9136,-36.4133 45.4137,-46.4133 52.4137,-46.4132"/>
</g>
</g>
</svg>

Error: 
```

**Comment by tamlok** [comment]
上面不是写着测试成功了吗？

**Comment by zldark** [comment]
但是实际似乎没有渲染
![image](https://user-images.githubusercontent.com/31798535/65037196-ba3acb00-d97f-11e9-9714-8a62935fa39c.png)

![image](https://user-images.githubusercontent.com/31798535/65037232-c9217d80-d97f-11e9-9534-5ec2acb9f443.png)

**Comment by tamlok** [comment]
换一个简单的图试试？帮助菜单里面查看log看看有没有什么信息。

**Comment by zldark** [comment]
嗷嗷，重启了下，突然又可以啦。
谢谢啦！
