### ISSUE TITLE
图片大小调整的小问题

### ISSUE THREAD

**Issue by pluscao** [tamlok/vnote#976]
如果不删除图片大小参数，直接设置没有问题，
但是删除图片大小数值，再填入新值图片就会被删除

![8](https://user-images.githubusercontent.com/23414002/65130613-5f14e100-da30-11e9-8a46-8c32ef7fbf7c.gif)

**Comment by tamlok** [comment]
应该是自动保存把图片给误删了。使用交换文件，关闭自动保存，即可。
