### ISSUE TITLE
编辑模式下为粗体，显示模式下就不是粗体了

### ISSUE THREAD

**Issue by jackydi** [tamlok/vnote#996]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7

Symptoms (表现):
看下面两张图？在typora中显示是正常的。
![image](https://user-images.githubusercontent.com/50565266/66556925-a439b800-eb83-11e9-9a8c-5c1acac199cc.png)
![image](https://user-images.githubusercontent.com/50565266/66556977-be739600-eb83-11e9-82b4-4558f3c313d1.png)

How to Repro (如何复现):

**Comment by tamlok** [comment]
接口前面添加一个空格看看？markdown-it对于中文的有些处理会有点问题。

**Comment by jackydi** [comment]
> 接口前面添加一个空格看看？markdown-it对于中文的有些处理会有点问题。

后面添加一个空格确实好了。
